### ISSUE TITLE
[BUG]There was some error accessing the binary "keka7z"

### ISSUE THREAD

**Issue by LoveJessyChen** [aonez/Keka#1002]
### Configuration
- Keka version: 1.2.50
- macOS version: 12.1 (21C52)

### Describe the bug
When create a zip or 7z,it will appear:
There was some error accessing the binary "keka7z"

### To Reproduce
1. Go to 'Right Menu'
2. Click on 'Using "KeKa Compressed"'
3. See error

**Comment by aonez** [comment]
@LoveJessyChen you’ve downloaded Keka from the web? If so, try this:
https://github.com/aonez/Keka/wiki/Quarantine-(p7zip-error)

**Comment by LoveJessyChen** [comment]
Ok,I will try this method！

**Comment by aonez** [comment]
Please let me know if that works for you 😊

**Comment by LoveJessyChen** [comment]
Ok, I do it and it works well.

**Comment by aonez** [comment]
Happy to hear that @LoveJessyChen :)

Dupe of #208
