### ISSUE TITLE
RAR extraction failed

### ISSUE THREAD

**Issue by kyr0x** [aonez/Keka#1005]
My first time using this site, not sure if this is a bug but hopefully you can help eitherway!
<img width="408" alt="Keka 2022-01-05 13-30-37" src="https://user-images.githubusercontent.com/54468377/148217958-08cbc05b-d307-4a06-9e27-f16200d45451.png">

**Comment by aonez** [comment]
Can you click in the ⚠️ icon and copy/paste the error message?

Since it's a parted RAR archive, do you have all part together in the same folder?

**Comment by kyr0x** [comment]
It says "comment is too long", how can I send it to you? 

I downloaded the .rar from a website, so I am not aware of the "other parts", could that be the issue, that I am missing parts?

**Comment by aonez** [comment]
Just try to extract it again, when the error occurs click on the ⚠️ symbol and on the "copy" button,
then simply paste it here in a new comment.

<img width="601" alt="Screenshot 2022-01-05 at 14 26 00" src="https://user-images.githubusercontent.com/480163/148225076-f3d8b264-1bdd-482b-911f-35fee53d4f85.png">

The file is `...part1.rar`, that usually means there're `...part2.rar`, `...part3.rar` and so on. If you only downloaded part 1 you're probably missing some parts.

**Comment by kyr0x** [comment]
Oh okey, first of all the error message exceeded the maximum characters allowed, that is why I could not paste it here.

I will download the 2 other parts and come back to you. So when I have downloaded all three parts, do I have to combine them somehow? Or do I just click one of them?

**Comment by aonez** [comment]
> Oh okey, first of all the error message exceeded the maximum characters allowed, that is why I could not paste it here.

Ah! You could also click on "Save", and drop the save `Keka.log` to a new comment here.

> Or do I just click one of them?

You just need to open one of them :)

**Comment by kyr0x** [comment]
Got it to work when I downloaded all files, thanks!
