### ISSUE TITLE
Extraction of file failed, giving me Error code 2 using "p7zip"

### ISSUE THREAD

**Issue by mabr787** [aonez/Keka#1006]
I'm trying to extract a file and it keeps giving me the same error

**Comment by aonez** [comment]
Can you copy and paste here the error shown:

![](https://user-images.githubusercontent.com/480163/148225076-f3d8b264-1bdd-482b-911f-35fee53d4f85.png)

**Comment by mabr787** [comment]
OS: Version 12.1 (Build 21C52)
Keka: v1.2.50-r4808 (WEB) (Sandboxed) (en)
Format detected: RAR Legacy
Binary used: kekaunrar
Arguments: (
    x,
    "-idcd",
    "-kb",
    "-x*/__MACOSX",
    "-y",
    "/Users/miguelbarreto/Downloads/Test-King-Testing-Engine.exe",
    "/Users/miguelbarreto/Downloads/Test-King-Testing-Engine.kextraction/Operation/"
)

/Users/miguelbarreto/Downloads/Test-King-Testing-Engine.exe is not RAR archive

No files to extract

OS: Version 12.1 (Build 21C52)
Keka: v1.2.50-r4808 (WEB) (Sandboxed) (en)
Format detected: RAR Legacy
Binary used: keka7z
Arguments: (
    x,
    "/Users/miguelbarreto/Downloads/Test-King-Testing-Engine.exe",
    "-o/Users/miguelbarreto/Downloads/Test-King-Testing-Engine.kextraction/Operation",
    "-aou",
    "-xr!__MACOSX"
)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,12 CPUs x64)
Modified by aONe for Keka

Scanning the drive for archives:
  0M Scan /Users/miguelbarreto/Downloads/

1 file, 3682342 bytes (3597 KiB)

Extracting archive: /Users/miguelbarreto/Downloads/Test-King-Testing-Engine.exe
  0% Open

ERROR: /Users/miguelbarreto/Downloads/Test-King-Testing-Engine.exe
Can not open the file as archive


 82%

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

Error code 2

**Comment by aonez** [comment]
Is it possible that you share the file or the link to download it? It probably can't be extracted (not all EXE files can be) or was broken during download/upload.

**Comment by mabr787** [comment]
I have tried to download it again because I thought it was broken but it was still saying the same. 

It doesn't let me upload it here.

**Comment by aonez** [comment]
Can you share the download link? Here or at info@keka.io.
