### ISSUE TITLE
Broken icon designer Dribbble link in the About Keka window

### ISSUE THREAD

**Issue by leiweimu** [aonez/Keka#1009]
### Configuration
- Keka version: 1.2.51 (4869)
- macOS version: 11.6.2 (20G314)

### Describe the bug
The link to the icon designer Jonathan Coutiño's Dribbble profile does not seem to work. 
The current URL https://ralts00.dribbble.com/ leads to a 404 error from Dribble. 
It appears that the correct link is https://www.dribbble.com/ralts00

### To Reproduce
1. Go to 'Keta' then 'About Keka'
2. Click on 'Dribbble' after Jonathan Coutiño text
3. See 404 error on the page opened

**Comment by gingerbeardman** [comment]
Nice spot!

Dribbble really should redirect those old links.

**Comment by aonez** [comment]
Thanks @leiweimu! I'm sure @ ralts00 thanks you too 😛
Changed it right away for the next Keka revision, @ralts00 deserves this 🔝

@gingerbeardman probably maintaining (and creating) subdomains is not worth it and they removed this option...

**Comment by gingerbeardman** [comment]
I was told the old link was to a portfolio that has since been removed. 

New link is to user profile.

**Comment by aonez** [comment]
So it is a user based choice? Or they removed the portfolio?

**Comment by ralts00** [comment]
The link changed because I stopped paying for the dribbble portfolio.
thanks for the change 🥰
