### ISSUE TITLE
[Fatal Error] Error while extracting

### ISSUE THREAD

**Issue by kyr0x** [aonez/Keka#1010]
OS: Version 12.1 (Build 21C52)
Keka: v1.2.50-r4808 (WEB) (Sandboxed) (en-GB)
Format detected: 7Z
Binary used: keka7z
Arguments: (
    x,
    "/Users/Viktor/Downloads/XLN.Audio.Addictive.Keys.Complete.v1.4.3-macOS.7z.001",
    "-o/Users/Viktor/Downloads/XLN.Audio.Addictive.Keys.Complete.v1.4.3-macOS.7z.kextraction/Operation",
    "-aou",
    "-xr!__MACOSX"
)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs LE)
Modified by aONe for Keka

Scanning the drive for archives:
  0M Scan /Users/Viktor/Downloads/

1 file, 734003200 bytes (700 MiB)

Extracting archive: /Users/Viktor/Downloads/XLN.Audio.Addictive.Keys.Complete.v1.4.3-macOS.7z.001
  0% 1 Open

ERROR: /Users/Viktor/Downloads/XLN.Audio.Addictive.Keys.Complete.v1.4.3-macOS.7z.001
XLN.Audio.Addictive.Keys.Complete.v1.4.3-macOS.7z
Open ERROR: Can not open the file as [7z
Error code 2

**Comment by aonez** [comment]
Same issue as #1005? Do you have all the parts?

**Comment by kyr0x** [comment]
Oh right, so I would need 001 to 006 in this case? 

I thought I didn't need them all because case there was not a "part1" in the name. 

I will update when I have downloaded all of them!

**Comment by aonez** [comment]
I guess it was that 😊 7Z uses that numbering scheme for parted files.

have a nice one!
