### ISSUE TITLE
Move files to bin in Google Drive sync folder [BUG]

### ISSUE THREAD

**Issue by ivan-huelves** [aonez/Keka#1014]
- Keka version: 1.2.51 (4869)
- macOS version: 10.14.6 (18G87)
- google drive version: 54.0.3.0 (Intel)

Keka doesn't move automatically the compressed file to the bin when it is in a Google Drive Sync Folder. I read that something similar happened to icloud folders.

Thanks!

**Comment by aonez** [comment]
Can you [enable a debug session in Keka](https://github.com/aonez/Keka/wiki/Report-an-issue), reproduce the issue and attach here the log?

**Comment by ivan-huelves** [comment]
Sorry, I gave access to external devices and it's works as charm. Thanks!

**Comment by aonez** [comment]
Nice!!
