### ISSUE TITLE
[BUG] Compression very slow, Zip barely uses any resources and the compression fails after drive fills up (resulted file becomes over 2x bigger than the source 210 GB folder before failing)

### ISSUE THREAD

**Issue by Piipperi** [aonez/Keka#1020]
### Configuration
- Keka version: 1.2.51 (4869)
- macOS version: 12.1 (21C52)

### Describe the bug
Compressing a ~210 GB Final Cut Pro library to a zip/7z is taking very long, with an estimation of a day or two before completion. 7z just takes very long with the computer going full tilt, but compressing using Zip uses barely any resources (SSD not getting read from faster than 30 MB/s, and Keka using only around 80% of my 8 threaded CPU). Both compression methods start to create a file that's larger than the original folder itself, I tried to Zip on my NAS with 500 GB of free space, and the drive was disconnected after it was close to filling up, with the resulting file showing it being over 400 GB! Similar behavior happening with 7z compression too. Both have been done on the default settings (normal - exclude Mac resource forks checked)

[Zip.log](https://github.com/aonez/Keka/files/7920966/Zip.log)
[7z.log](https://github.com/aonez/Keka/files/7922606/7z.log)

### Expected behavior
A zip or 7z file that wouldn't be bigger than the source

**Comment by aonez** [comment]
Can you check if this build fixes the issue for you: [Keka-1.2.52.r4877](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.2.52.r4877.7z)

If it still fails. check executing this command in the Terminal and restarting Keka:

```sh
defaults write com.aone.keka Use7zz -bool false
```

**Comment by Piipperi** [comment]
> Can you check if this build fixes the issue for you: [Keka-1.2.52.r4877](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.2.52.r4877.7z)
> 
> If it still fails. check executing this command in the Terminal and restarting Keka:
> 
> ```shell
> defaults write com.aone.keka Use7zz -bool false
> ```

It appears that with the new build it does compress properly both as a 7z and a zip.
