### ISSUE TITLE
[REQ] extracting unknown formats (was: support for tar file with .spk extension)

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#1022]
### Is your feature request related to a problem? Please describe

Tried to extract a .spk Synology package file, which is a known archive file format but unknown to Keka as it uses a different file extension.

### Describe the solution you'd like

Keka should know how to extract it, or be able to guess.

### Describe alternatives you've considered

The Unarchiver, which already knows how to handle .spk files.

### Additional context

Maybe `file` command can be used to inspect the contents of a file and be able to guess if it's of a supported type? The worst outcome is that the file still cannot be expanded, the best outcome is that the file is expanded when no explicit support!

For example, SPK is in fact a simple TAR file with a different file extension.

```
$ file synokernel-cdrom_broadwell-6.2.3_1.0-1.spk
synokernel-cdrom_broadwell-6.2.3_1.0-1.spk: POSIX tar archive (GNU)
```

Of course, explicit support is needed to add Keka to the context menu (open with) for a particular file type. Would it help to take a look at all the file extensions supported by The Unarchiver?

**Comment by aonez** [comment]
Can you share a sample file? Keka already has format detection that detects various types or TAR packages, I’m not sure why is not detecting that one.

**Comment by aonez** [comment]
Already found some :)

**Comment by aonez** [comment]
I've downloaded one random from here https://archive.synology.com/download/Package and they don't seem to be TAR packages. Can you share one?

**Comment by gingerbeardman** [comment]
Try https://github.com/publicarray/spksrc/releases/download/sonarr-3.0.5.1144/nzbdrone_x64-6.1_20210329-19.spk

**Comment by gingerbeardman** [comment]
Indeed Keka does exract this, not sure what i did wrong/different earlier.

So I guess it would always be nice to add more file extensions so Keka shows up on the Open With... menu.

**Comment by aonez** [comment]
> So I guess it would always be nice to add more file extensions so Keka shows up on the Open With... menu.

Sure! I'll add this one to the supported list.

Seems that newer SPK archives are compressed in another way. For example:

- https://global.download.synology.com/download/Package/spk/Contacts/1.0.0-0243/Contacts-x86_64-1.0.0-0243.spk
- https://global.download.synology.com/download/Package/spk/Contacts/1.0.2-10389/Contacts-x86_64-1.0.2-10389.spk

The newer 1.0.2 is no more a TAR.

**Comment by aonez** [comment]
Got curious, here some info: https://help.synology.com/developer-guide/toolkit/pack_stage.html

**Comment by aonez** [comment]
1.2.53 up handling spk by default :)
