### ISSUE TITLE
Can't disable sound when unzipping

### ISSUE THREAD

**Issue by iamdannywyatt** [aonez/Keka#1023]
Even though I have the notifications for Keka set to OFF and the macOS sound effects also set to OFF, every time I unzip a file I get this sound effect. Since I'm a producer and I have big speakers in the studio, sometimes having that sound on the speakers becomes a bit annoying (and scary sometimes). Any way to fix this?
Thanks! :)

- Keka version: 1.2.50 (4808)
- macOS version: 10.15.7

![Screen Shot 2022-01-24 at 10 11 10 PM](https://user-images.githubusercontent.com/96640778/150874253-d249d287-4862-4326-8f06-f3d71d9b6019.png)
![Screen Shot 2022-01-24 at 10 11 58 PM](https://user-images.githubusercontent.com/96640778/150874259-e7d43cd3-63d9-45e1-867a-e71d846b9f16.png)

**Comment by aonez** [comment]
Check the Keka preferences, you can disable the sound for compression and extraction.

**Comment by iamdannywyatt** [comment]
> Check the Keka preferences, you can disable the sound for compression and extraction.

Yes, I was about to write that I found it. I didn't see that option. Thanks for replying :)
