### ISSUE TITLE
Just purchased Keka from the app store & zip archiving is not available

### ISSUE THREAD

**Issue by acpodz** [aonez/Keka#1042]
### Configuration
- Keka version: 1.2.52 (4882)
- macOS version: 12.1

### Describe the bug
On selecting ZIP, there is no file drop area

### To Reproduce
1. Open a new window
2. Select ZIP

### Expected behavior
A file drop area to be displayed in the "new window" as described in the App Store. Note: I paid for the app and am not using any free trial version

**Comment by aonez** [comment]
Take a look at the documentation:

https://github.com/aonez/Keka/wiki/Compressing-with-Keka

Let me know if you need any additional help :)

**Comment by acpodz** [comment]
I was expecting a visible drop area and din't realise that the entire window was the drop area. Works really well. Many thanks!
