### ISSUE TITLE
[BUG] "Send to Keka" sometimes leaves window open 

### ISSUE THREAD

**Issue by Stooovie** [aonez/Keka#1045]
### Configuration
- Keka version: 1.2.52
- macOS version: 12.2

### Describe the bug
Upon extracting or archiving, the default window sometimes (**not always!**) opens and stays open after finishing

### To Reproduce
1.) Select an item to archive or extract
2) go to Services-Send to Keka (or press ctrl-shift-k)

### Expected behavior
Selected item is compressed or extracted, and any Keka windows close

### Screenshots
This window opens and stays open.
![Screenshot 2022-02-13 at 16 02 15](https://user-images.githubusercontent.com/10572373/153759305-78702826-691e-471c-a951-8d38006a2c84.jpg)

### Additional context
I think this started happening with Monterey. I don't remember this being a problem before. Completely removing the app with AppCleaner (i.e. preference and support files too) and reinstalling didn't fix the issue, nor did unchecking/rechecking Close Keka when no windows is open. **Does not happen every time.** It **_does_** happen on newly created user account.

**Comment by aonez** [comment]
@Stooovie I've tried reproducing you issue without like. Spammed the service like 50 times and never saw the advanced window.

Can you send an screencast reproducing the issue? Maybe the timing of it give a little more input. Also let me know if you have any third party app that handles other app windows.

**Comment by aonez** [comment]
For example I was thinking about a third party app like Afloat https://github.com/aonez/Keka/issues/38, although this behavior was fixed back in 2018.

**Comment by Stooovie** [comment]
Hi,[ here's a video](https://www.youtube.com/watch?v=kgFHF7hsF4U) where it happens in 2 out of 10 attempts (I'm canceling the archiving for expedience but that makes no difference in the behavior). It's me pressing ctrl-shift-k ("Send to Keka"). I do have 3rd-party apps that handle other app windows such as Rectangle but this is the same on a completely new user account where none of those apps are running. It also happens when I kill the Rectangle process. I have also checked keyboard shortcuts but ctrl+shift combination is very distinct and I haven't found anything that might interfere.

**Comment by aonez** [comment]
@Stooovie sadly I wasn't able to reproduce this. Not sure what can be the issue here. I'll make a build with additional logging, maybe that way we can get more information, but I'm pretty sure there's something else there that is activating Keka twice thus showing the window.

**Comment by POEG1726** [comment]
Same thing happened to me

**Comment by aonez** [comment]
Dupe #1512
