### ISSUE TITLE
[BUG] Perte des TAG après décompression 

### ISSUE THREAD

**Issue by Robert83210** [aonez/Keka#1046]
- Keka version: [1.2.52] (4882)
- macOS version: [ 10.17.7 (19H1713)

1) Attribution d’un Tag de couleur à un fichier (img, ou  txt, ou jpg  etc…) 

2) création d’une archive Zip par Drag and Drop sur l’icône de Keka

3) Ouverture du fichier zippé 	
             • soit via Utilitaire d’archives Apple
             • soit via Keka 

4) décompression normale du fichier nippé 
     mais **perte du Tag**

[Probleme Perte de TAG avec Keka.pdf](https://github.com/aonez/Keka/files/8055967/Probleme.Perte.de.TAG.avec.Keka.pdf)

**Comment by gingerbeardman** [comment]
<img width="349" alt="Screen shot 2022-02-13 at 16 15 51" src="https://user-images.githubusercontent.com/49612/153762208-0206bc92-9028-45b1-9aec-08c706c4fa07.png">

décocher la case "Exclure les fichiers spéciaux Mac"

**Comment by aonez** [comment]
@Robert83210 this is currently not supported in Keka using the ZIP or 7Z format. Use TAR, BZIP2, GZ, ZSTD or any other format instead.

**Comment by Robert83210** [comment]
Bonjour Gingerbeardman et merci pour la réponse
J'ai décoché "Exclude Mac resource forks" et même redemarrer le Mac mais
après ouverture du nouveau fichier compressé le pb persiste car le Tag a disparu

**Comment by gingerbeardman** [comment]
ceci n'est actuellement pas supporté dans Keka en utilisant le format ZIP ou 7Z. Utilisez TAR, BZIP2, GZ, ZSTD ou tout autre format à la place.

Ou utilisez l'utilitaire d'archivage de macOS, désolé.

**Comment by gingerbeardman** [comment]
The above is a request for support for tags and encryption in ZIP or 7Z.

**Comment by Robert83210** [comment]
Oui effectivement, c'est ainsi que j'aurai du formuler ma demande Désolé

**Comment by aonez** [comment]
Closing this one as a dupe of #90. Thanks to both of you :)
