### ISSUE TITLE
Password doesn't work when compressing with 7ZIP

### ISSUE THREAD

**Issue by diegoborgh** [aonez/Keka#1050]
I need to able to queue folder compression, so I thought the best solution is Keka for this.
On Compression settings I have default format "7ZIP", default method "No Compression".

I copied paste the password, and also pasted the same password on extraction to test and it fails every single time.

Tried multiple times with multiple sources, manually typing password, copy/paste, it seems there is a bug.

Using 1.2.52 version on Mac M1

**Comment by diegoborgh** [comment]
I understand now it needs to be opened with Keka

**Comment by aonez** [comment]
This was #477. Have a nice one @diegoborgh!
