### ISSUE TITLE
Add zip files to 7z file

### ISSUE THREAD

**Issue by djs71a** [aonez/Keka#107]
Is it possible to create a 7zip file that contains a set of zip files? When I drag zip files to Keka, it extracts them instead of creating one 7zip file.

**Comment by aonez** [comment]
Sure! You can set Keka to “Always compress” or just drop the files to the bottom zone of the advanced window, where the secondary option (in this case compression) will be:
https://github.com/aonez/Keka/wiki/Compressing-with-Keka#how-to-compress-some-files

I’ll add a little explanation on the wiki about this secondary option.

**Comment by djs71a** [comment]
Thanks! I didn't notice the secondary option when I was using the app earlier. Works perfect.
