### ISSUE TITLE
How do I add a file to an existing keka zip?

### ISSUE THREAD

**Issue by Gewurztraminer** [aonez/Keka#1072]
How do I add a file to an existing keka zip?

**Comment by aonez** [comment]
This is currently no possible with Keka.

**Comment by scratch-er** [comment]
Unpack it, copy the file to add into the directory, than re-pack.
And I think it's time for Keka to add more feathures rather than focus on only simplicity.

**Comment by mbirth** [comment]
Duplicate of #231
