### ISSUE TITLE
[REQ] Support `pzstd` to parallelize the zstd compression and decompression

### ISSUE THREAD

**Issue by pan93412** [aonez/Keka#1075]
### Is your feature request related to a problem? Please describe

[`pzstd` is the official parallized `zstd`.](https://github.com/facebook/zstd/tree/dev/contrib/pzstd) It can speed up the zstd compression for about 48%, and decompression for ~64%:

    $ time pzstd -o test.pzstd 2022.2.24.tar
    2022.2.24.tar        : 95.50%   (7609145344 => 7266750007 bytes, test.pzstd)
    
    ________________________________________________________
    Executed in   10.06 secs    fish           external
       usr time   19.47 secs    0.08 millis   19.47 secs
       sys time   10.82 secs    1.86 millis   10.82 secs

    $ time zstd -o test.zstd 2022.2.24.tar
    2022.2.24.tar        : 95.49%   (  7.09 GiB =>   6.77 GiB, test.zstd)
    
    ________________________________________________________
    Executed in   14.92 secs    fish           external
       usr time   11.58 secs    0.07 millis   11.58 secs
       sys time    7.12 secs    1.28 millis    7.12 secs

    $ mv test.pzstd test.zst
    $ time pzstd -d test.zst
    test.zst            : 7609145344 bytes
    
    ________________________________________________________
    Executed in    9.57 secs    fish           external
       usr time    6.47 secs    0.09 millis    6.47 secs
       sys time    9.68 secs    1.50 millis    9.68 secs

    $ rm -rf test
    $ time zstd -d test.zst
    test.zst            : 7609145344 bytes
    
    ________________________________________________________
    Executed in   15.79 secs    fish           external
       usr time    5.62 secs    0.09 millis    5.62 secs
       sys time    7.15 secs    1.51 millis    7.15 secs

However, [the compression ratio of `pzstd` is usually higher than `zstd`.](https://github.com/facebook/zstd/issues/517)

### Describe the solution you'd like

Users can choose either `pzstd` or `zstd` for compression and decompression.

### Describe alternatives you've considered

Use `pzstd` when parallized compression/depression enabled; otherwise, use `zstd`.

### Additional context

None.

**Comment by aonez** [comment]
@pan93412 the current implementation of `ZSTD` (included in Keka) already supports and uses multi threaded operations. You just need to compile ZSTD with `DZSTD_MULTITHREAD`.

Does not work as expected for you?

**Comment by pan93412** [comment]
> @pan93412 the current implementation of `ZSTD` (included in Keka) already supports and uses multi threaded operations. You just need to compile ZSTD with `DZSTD_MULTITHREAD`.
> 
> Does not work as expected for you?

Seems work. Thanks!
