### ISSUE TITLE
Rehuse extraction password in batch operations

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#108]
As pointed by arnage74 via mail, can be interesting to rehuse the extraction password if needed when dropping multiple compressed files at one.

**Comment by baszero** [comment]
By when is this feature available in the regular version?

**Comment by aonez** [comment]
@baszero no timeline yet, there're still a few thing to develop in the [1.2.0](https://github.com/aonez/Keka/milestone/7) version.

**Comment by baszero** [comment]
Understand, but it's quite annoying to enter 100 times the same password
(my clients do password protect all zips).
