### ISSUE TITLE
keka  decompression failed. error code 2

### ISSUE THREAD

**Issue by juyeonKang** [aonez/Keka#1086]
i can't figure out what's the problem is.  could you help me please?
(( when i try to decompress the same file on Windows 10(not mac), it worked well. ))

### Bug Report
OS: Version 12.3.1(Build 21E258) (x86_64)
Keka: v1.2.53-r4962 (WEB) (Sandboxed) (ko)
Format detected: Unknown
Binary used: keka7zz
Arguments: (
    x,
    "/Users/a1/Downloads/otp.com_apache.zip",
    "-o/Users/a1/Downloads/otp.com_apache.kextraction/Operation",
    "-snld",
    "-aou",
    "-xr!__MACOSX",
    "-bsp1"
)

7-Zip (z) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26 : Modified by aone for Keka
 64-bit locale=en_US.UTF-8 Threads:12

Scanning the drive for archives:
  0M Scan /Users/a1/Downloads/
1 file, 379519 bytes (371 KiB)

Extracting archive: /Users/a1/Downloads/otp.com_apache.zip
  0%
ERROR: /Users/a1/Downloads/otp.com_apache.zip
/Users/a1/Downloads/otp.com_apache.zip
Open ERROR: Cannot open the file as [zip] archive

ERRORS:
Is not archive

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

Error code 2

**Comment by aonez** [comment]
Seems that the file is not a valid ZIP. Can you share it? If you need you
can send it or a link to it at ***@***.***
