### ISSUE TITLE
[REQ] Allow selection of E or P cores on Apple Silicon via QoS

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#1087]
### Is your feature request related to a problem? Please describe

On Apple Silicon Macs, apps can run on either Efficiency or Performance cores.

Apps can assign themselves and their processes to either type of core via QoS.

https://eclecticlight.co/2022/01/07/how-macos-controls-performance-qos-on-intel-and-m1-processors/

### Describe the solution you'd like

- Option in Keka to select E or P cores only when running on Apple Silicon.

### Describe alternatives you've considered

- Cormorant 
  https://eclecticlight.co/2020/12/11/cormorant-now-supports-drag-and-drop-and-can-run-ten-times-faster/

**Comment by aonez** [comment]
Thanks @gingerbeardman. Always interesting to read eclecticlight. Since lately I'm working hard with Swift I've tried a lot of [`qos`](https://developer.apple.com/documentation/dispatch/dispatchqos/qosclass) on iOS.

Keka is using all the available cores right now (E and P). Using just one of those will result in slower tasks (specially using the E ones). What will be the benefit for you? Or what idea do you have in mind?

**Comment by aonez** [comment]
Correction, just checked that compression and extraction of  Archive in Keka is done using only the performance cores.

**Comment by gingerbeardman** [comment]
It would be great to be able to specify only E cores for power saving. I don't mind it taking longer when battery is more important.

**Comment by aonez** [comment]
This is the same operation on top running only on efficiency cores and on bottom on all cores. Obviously this is a big file and with the slowest option of 7Z. For smaller files and faster options the difference will not be that big.

<img width="516" alt="Screenshot 2022-04-28 at 14 42 41" src="https://user-images.githubusercontent.com/480163/165754448-debab064-c43e-493b-8aba-e13785aa043b.png">

**Comment by gingerbeardman** [comment]
Is the difference less stark when using Apple Archive?

**Comment by aonez** [comment]
Indeed, the same operation takes 4 seconds on performance and 26 seconds on efficiency. Still amazed with this format.

**Comment by gingerbeardman** [comment]
Excellent, my M1 MBP is yet to arrive. But I'm ready for it!!!

**Comment by aonez** [comment]
Still not sure about this. Same test as above (AAR 2.68 file), CPU history and energy impact.

Anyway, here a test version that runs tasks in background priority (efficiency cores on M1). No toggle, just compare it to the regular Keka version: [Keka-QoS-9](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-QoS-9.7z)

## Efficiency

![eficiency](https://user-images.githubusercontent.com/480163/165902846-f0750c99-467b-4928-a40f-88b0bd0af0c1.png)
<img width="454" alt="eficiency_hist" src="https://user-images.githubusercontent.com/480163/165902855-8dc7fa47-4e16-44a9-a1e2-95faf4961aa2.png">

## Performance

![performance](https://user-images.githubusercontent.com/480163/165902871-c8a370d3-ffc2-4d68-98cb-ee2699eb2005.png)
<img width="454" alt="performance_hist" src="https://user-images.githubusercontent.com/480163/165902875-dfba4a8e-66ea-4833-bad5-dde759b0bbfe.png">

**Comment by gingerbeardman** [comment]
https://twitter.com/howardnoakley/status/1520073629861560325

> They’re doing it right, but Energy Impact is junk: at QoS 9, the E cores will be limited to less than 1 GHz, but the Energy Impact graph isn’t aware of that. In general Activity Monitor etc. don’t monitor core frequency yet.

**Comment by aonez** [comment]
@gingerbeardman when are you receiving your M1 equipped Mac?

**Comment by gingerbeardman** [comment]
This month. It was delayed 5–7 weeks and already 3 weeks have passed.

**Comment by aonez** [comment]
Already did a test build: [Keka-v1.3.0-dev.r4979](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.3.0-dev.r4979.7z)

![Screenshot 2022-05-04 at 15 42 32](https://user-images.githubusercontent.com/480163/166693930-7dcf69c9-66f9-4cba-a611-2ca546a60b28.png)

I've just sold my M1 MacBook Air (just 8GB or RAM wasn't enough) so I'll be unable to test this again for a while.

**Comment by gingerbeardman** [comment]
My MBP will have 16GB, fingers crossed that's enough for my usage. Should be!

**Comment by gingerbeardman** [comment]
My M1 laptop has arrived, let me know what you want me to test.

**Comment by aonez** [comment]
@gingerbeardman I wanted to check just that all options worked as expected. Just use it as you will and let me know if you find anything strange.

Loving your M1 already? I'm missing my Air a lot 🥹

**Comment by gingerbeardman** [comment]
Been using it for the last week. 

The M1 Pro MBP is good, though I use it with an external display keyboard and mouse so the main difference I am noticing is SPEED! M1 2 to 3 times faster than my Intel Mac mini. Feels more than that!

**Comment by aonez** [comment]
> M1 Pro is 2 to 3 times faster than my Intel Mac mini. Feels more than that!

yup! I’m yet again using a 2018 Mac mini and even if it has 32GB of RAM compared to the Air’s 8GB the M1 felt a lot faster. Also the integrated Intel graphics are awful in 4K resolutions.

**Comment by aonez** [comment]
Going to push this one in the next release. I was waiting for more upgrades for a 1.3 release, but the iOS version is taking so much time right now and this feature is very handy.

**Comment by aonez** [comment]
I'm just wishing for Apple to release M2 MacBook Pro's already...
