### ISSUE TITLE
[BUG] 오류코드1 'unar' 사용중이라고 뜹니다.

### ISSUE THREAD

**Issue by youyoungpark** [aonez/Keka#1090]
OS: 버전 12.2.1(빌드 21D62) (x86_64)
Keka: v1.2.52-r4882 (WEB) (Sandboxed) (ko)
Format detected: ZIP
Binary used: kekaunar
Arguments: (
    "-q",
    "-r",
    "-D",
    "-K",
    "-nq",
    "-o",
    "/Users/youyoung/Downloads/0207 \U110b\U1175\U1107\U1175\U11be\U1102\U1161 \U110c\U1169\U110c\U1175\U11ab\U110b\U116e \U1111\U116e\U11af.kextraction/Operation",
    "/Users/youyoung/Downloads/0207 \U110b\U1175\U1107\U1175\U11be\U1102\U1161 \U110c\U1169\U110c\U1175\U11ab\U110b\U116e \U1111\U116e\U11af.zip"
)
Archive parsing failed! (Data is corrupted.)

Error code 1

자주 이렇게 뜨는데 뭐가 문제일까요? 파일 전체 압축이 실패하는게 아니라 반정도만 실패합니다..

**Comment by aonez** [comment]
-- 구글 번역기로 번역

파일 헤더가 손상된 것 같습니다. 공개 파일인 경우 링크를 공유하여 다운로드하고 테스트하십시오.

---

Seems that the file header is corrupted. If it's a public file please share the link to download and test it.
