### ISSUE TITLE
ZIP is including other folders as well (parents) [BUG]

### ISSUE THREAD

**Issue by iamdannywyatt** [aonez/Keka#1097]
I just noticed that when I expand ZIP files, it's including other folders, for example, let's say that the folder I want to compress is folder 5. So the structure is this

Folder 1 > Folder 2 > Folder 3 > Folder 4 > Folder 5

When I compress and then expand, instead of showing me just folder 5, it's including folder 1 through folder 5.

Any idea why this is happening? This doesn't happen when using the default archive engine by Apple.

**Comment by aonez** [comment]
Hi @iamdannywyatt,

I'm unable to reproduce the issue. Can you create an screencast reproducing the issue?

https://user-images.githubusercontent.com/480163/167643789-9c6d01ba-059f-4574-b88c-da2abaf171bb.mov

Also, do you have any special setting in the Compression Preferences of Keka?

<img width="791" alt="Screenshot 2022-05-10 at 15 40 00" src="https://user-images.githubusercontent.com/480163/167642275-a83e37c2-e1bb-4025-8ecc-8cc71487ad76.png">
