### ISSUE TITLE
[REQ] Add the feature of broswering the content of archieves and extract only some of the archieved files

### ISSUE THREAD

**Issue by scratch-er** [aonez/Keka#1102]
Most archievers on Linux have the feature of broswering the content of archieves and extract only some of the archieved files, if supported by the format of the archieve. However, Keka can only unpack the whole archieve. It can be bothering in cases where you only want to extract some of the files from a huge archieve.

Instead of unpacking directly, could you show a tree view of the content of the archieve and allow the user to unpack only some of the files?

But, is this feature necessary for mac users? I've noticed that most archivers on mac do not have the feature of browsing archive files, and finder (and keka) will unpack an archieve even without prompting when opening it. I'm a heavy linux user and l'm used to browsing an archieve file before unpacking it. I'm not sure wether mac users are used to directly unpacking the whole archieve.

Or, make unpacking directly the default behavior, and add an option to broswer the archieve for those who need this feature.

**Comment by aonez** [comment]
https://github.com/aonez/Keka/issues/100
