### ISSUE TITLE
[REQ] Add an option to show the password while entering it before archiving

### ISSUE THREAD

**Issue by navinthomas** [aonez/Keka#1104]
### Is your feature request related to a problem? Please describe

Keka has a 'Repeat' password field, but there is no option to temporarily view the password that you have entered. Sometimes, passwords can be very long and complicated. So, providing a temporary visual confirmation, that the password used to secure the archive is what the user desired, might be a good idea.

<img width="448" alt="image" src="https://user-images.githubusercontent.com/34918736/168462466-bc9375b1-ab41-4727-8b7b-8bb15992760a.png">

### Describe the solution you'd like

Add a 'Show password' checkbox like in the example below.

<img width="448" alt="image" src="https://www.eduhk.hk/ocio/webdoc/images/faq/image/7zip_pwd03.png">

The checkbox can be added in the screen shown in the first screenshot.

### Describe alternatives you've considered

There is no alternative that I think of for this scenario.

### Additional context

When typing long, complicated passwords with uppercase and lowercase characters, I find that I make the exact same mistake multiple times while typing the password quickly. Therefore, having just a repeat password field will not make it foolproof enough for people like me.

How 7-zip implements this feature:
![image](https://user-images.githubusercontent.com/34918736/168462890-b041ef92-8f08-4fa5-8947-769283f7cc2b.png)

**Comment by aonez** [comment]
Thanks for the feedback @navinthomas! Will follow this issue here:
https://github.com/aonez/Keka/issues/659

**Comment by navinthomas** [comment]
Thanks. Can't believe I missed the original feature request while searching if it was already asked for.
