### ISSUE TITLE
„Cannot open the file as archive error code: 2“ what to do?

### ISSUE THREAD

**Issue by Quallenknoedel** [aonez/Keka#1123]
Hey,
Keka says „cannot open the file as archive // error code 2“ when I tried to unpack a movie. I renamed all four parts of the movie into "part1" "part2" etc. and hope, it didn't make any thing worse. Any help will be appreciated!

========
OS: Version 12.4 (Build 21F79) (arm64)
Keka: v1.2.54-r4983 (WEB) (Sandboxed) (de)
Format detected: RAR Legacy
Binary used: kekaunrar
Arguments: (
x,
"-idcd",
"-kb",
"-x*/__MACOSX",
"-y",
"/Users/(my user name)/Downloads/Old/part1.rar",
"/Users/(my user name)/Downloads/Old/part1.kextraction/Operation/"
)

/Users/(my user name)/Downloads/Old/part1.rar is not RAR archive
No files to extract

OS: Version 12.4 (Build 21F79) (arm64)
Keka: v1.2.54-r4983 (WEB) (Sandboxed) (de)
Format detected: RAR Legacy
Binary used: keka7zz
Arguments: (
x,
"/Users/(my user name)/Downloads/Old/part1.rar",
"-o/Users/(my user name)/Downloads/Old/part1.kextraction/Operation",
"-snld",
"-aou",
"-xr!__MACOSX",
"-bsp1"
)

7-Zip (z) 21.07 (arm64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26 : Modified by aone for Keka
64-bit arm_v:8 locale=en_US.UTF-8 Threads:8, ASM

Scanning the drive for archives:
0M Scan /Users/(my user name)/Downloads/Old/
1 file, 2097152000 bytes (2000 MiB)

Extracting archive: /Users/(my user name)/Downloads/Old/part1.rar
0% Open 0%
Can't open as archive: 1
Files: 0
Size: 0
Compressed: 0

ERROR: /Users/(my user name)/Downloads/Old/part1.rar
Cannot open the file as archive

Error code 2

**Comment by aonez** [comment]
Hi @Quallenknoedel. The file you're trying to extract is detected as a RAR 4.0, so the parts should look like:

1. file.rar
2. file.r01
3. file.r02
...
4. file.rXX

**Comment by aonez** [comment]
If you downloaded the files please share the link so I can test. You can also send it to info@keka.io

**Comment by gingerbeardman** [comment]
From terminal you can do `file part1.rar` to confirm the type of the contents of the file.

**Comment by aonez** [comment]
> From terminal you can do `file part1.rar` to confirm the type of the contents of the file.

Actually this was the right answer. The files are not RAR at all.

**Comment by aonez** [comment]
I've fixed an step in RAR volumes check to be sure to detect the actual file format. With these files with the code fixed Keka will report `Unknown` as the detected format.

**Comment by UnixCro** [comment]
Keka is bullshit. It maliciously alters the iCons of zip and other archival shipments so you can't
