### ISSUE TITLE
[BUG] apple menu default language overidden by localised Keka ver instead of remaining as EN- system installed

### ISSUE THREAD

**Issue by seitsme** [aonez/Keka#1136]
### Configuration
- Keka version: [e.g. 1.2.55]
- macOS version: [e.g. 10.13.6]

### Describe the bug
i think i found a bug not sure what is causing that.
i have many languages installed in keyboard menu but my OSX is EN.

i close keka which is in EL via terminal command for testing.
i go top left to the apple mac icon.
i click it and i see choices. ie.. about this mac.

now i run keka in EL always
i go top left to the apple mac icon again.
i click it and i see choices in EL not in EN which where my
default.

Thats a bit strange. I am not sure if keka does this when i switch to EL from EN,
via terminal and the problem is that it does not leave the main OSX language, for the apple menu as is.
It seems it switches to the language of the apple menu only, for a reason or looks apple bug.

Unless the apple menu changes language by the sparkle project framework and i may have to go back there to bring back EN instead ?

The apple menu i guess is finder related. not sure why this is overiding the default user language installed by the system.

With keka open when i switch to another app like mozilla and go to the apple menu it shows EN language=ok.
When i go back to keka and go back to the apple menu it reverses to EL (GR) instead of EN.

![ss-](https://user-images.githubusercontent.com/35772956/177046824-b08608bc-6c64-4b8e-a6c2-41c83f78480f.jpg)

what shoud be looking is like below
![ss- 2](https://user-images.githubusercontent.com/35772956/177047512-5e0ac3c8-fd47-4935-8ab7-29b13166f852.jpg)

**Comment by aonez** [comment]
This is the way macOS works. You can check for example with TextEdit.

```sh
/System/Applications/TextEdit.app/Contents/MacOS/TextEdit -AppleLanguages "(de)"
```
