### ISSUE TITLE
[BUG]  update related bug #1134 

### ISSUE THREAD

**Issue by seitsme** [aonez/Keka#1137]
### Configuration
    Keka version: [e.g. 1.2.55]
    macOS version: [e.g. 10.13.6]

### Describe the bug
I run the EL keka for testing and today i went and clicked on check updates.

i got the error you see in the screenshot.

I see that the error is in English though and cannot find it in localisation.
not sure if i have to go to sparkle and do some edits there as well.

![ss- 1](https://user-images.githubusercontent.com/35772956/177047241-d1860e71-43e8-4784-86e0-2d1a732bc7e9.jpg)

**Comment by aonez** [comment]
This is again from Sparkle. All update strings are inside the Sparkle framework. This line is in fact missing in the Greek Sparkle.strings but is present in the Base as well as in other translations:

https://github.com/sparkle-project/Sparkle/blob/c1bf68f91f5c37ba5b3ac5028e34ceb5d444de12/Sparkle/Base.lproj/Sparkle.strings#L13-L14

```
/* No comment provided by engineer. */
"%1$@ can’t be updated if it’s running from the location it was downloaded to." = "%1$@ can’t be updated if it’s running from the location it was downloaded to.";
```
