### ISSUE TITLE
[BUG] Window can't be un-minimised when "minimise windows into application icon" is on

### ISSUE THREAD

**Issue by Scorbo** [aonez/Keka#1138]
### Configuration
- Keka version: 1.2.55 (5009)
- macOS version: 12.4 (21F79)

### Describe the bug
When a window of Keka is minimised, it cannot be revealed again if the MacOS setting "minimise windows into application icon" is on. 
It can only be revealed when right-clicking the dock icon and choosing the name of the window.

### To Reproduce
1. Turn on "minimise windows into application icon" in MacOS dock and menu bar preferences
2. Minimise a Keka window
3. Try to go back to the window (click the dock icon, command-tab, etc)

### Expected behavior
The window would be revealed again, like other applications.

https://user-images.githubusercontent.com/91365006/178664340-abaacbc3-1d8f-40c8-850a-041d4b2d4ad7.mp4

**Comment by aonez** [comment]
Nice one. Replicated it, let's see if that has a fix.

**Comment by aonez** [comment]
Note this option is not very stable, having any application with multiple windows minimized will only deminiaturize the active window. This happens with any application.

**Comment by aonez** [comment]
This build should have this fixed: https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.56.r5018.7z
