### ISSUE TITLE
[BUG] ignored setting "Extraction: Always extract in a subfolder"

### ISSUE THREAD

**Issue by jrappen** [aonez/Keka#1139]
### Configuration

- Keka version: `1.2.55 (5009)`
- macOS version: `macOS Monterey 12.4 (21F79)`

### Describe the bug

Using Keka with the **default options** will unpack a zip with the contents:

```text
subdir
    file1.1
    file1.2
file1
```

named `whatever.zip` as:

```text
whatever
    subdir
        file1.1
        file1.2
    file1
whatever.zip
```

### To Reproduce

Download Keka from App Store. Use default settings.

### Expected behavior

```text
subdir
    file1.1
    file1.2
file1
whatever.zip
```

Settings should be applied.

### Screenshots

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/8577450/178723454-beabb672-24b1-47ac-be2e-0ea734a34b5a.png">

**Comment by aonez** [comment]
That option _always_ forces the creation of a subfolder but does mean it will not create it when needed. This is tracked here: https://github.com/aonez/Keka/issues/72
