### ISSUE TITLE
Keka opens to German webpage by default when setting as default uncompressor

### ISSUE THREAD

**Issue by jslawler** [aonez/Keka#1154]
1. Download Keka from macOS App Store
2. Open Keka
3. Set Keka as the default uncompressor
4. Prompt to install KekaDefaultApp
5. Tap "Learn More"
6. Keka opens http://www.keka.io/defaultapp/, but defaults to German website, rather then (in my case) English

<img width="1436" alt="Screen Shot 2022-08-14 at 7 33 55 am" src="https://user-images.githubusercontent.com/95468948/184511468-f6339283-6205-4121-8eab-0caa746a73b9.png">

**Comment by aonez** [comment]
Thanks for the tip! This is very weird, indeed it stopped worked while checking the issue...

**Comment by aonez** [comment]
Fixed! Thanks again @jslawler
