### ISSUE TITLE
Is it feasible to allow building for older OS and PPC arch from sources?

### ISSUE THREAD

**Issue by barracuda156** [aonez/Keka#1158]
I wanted to update Keka in Macports. Currently we got an ancient version there: https://github.com/macports/macports-ports/blob/master/archivers/keka/Portfile

But we want to support older systems. Versions of Keka for 10.5 and 10.6 are archaic, and also 10.6 is Intel-only, so does not work on 10.6 PPC or Rosetta.

Is there any way to build it from sources for older OS and hopefully for PPC too? We have all build tools, latest GCC and Cmake etc. For graphics, Qt5 is broken, sadly, but Qt4 and GTK3 work (possibly GTK4 will be fixed soon).

**Comment by aonez** [comment]
Sorry not possible, each deprecation has its technical reasons and requirements.

**Comment by barracuda156** [comment]
> Sorry not possible, each deprecation has its technical reasons and requirements.

@aonez Just in case, maybe it is possible to build it without GUI? AFAIK all command-line archivers build fine for PPC, including latest ones. (GUI, understandably, may be completely broken for older systems due to changes in frameworks and Xcode xibs.)
