### ISSUE TITLE
[REQ]shortcut to create a folder the same name as archive

### ISSUE THREAD

**Issue by MRKsas** [aonez/Keka#1169]
I want to know if there is a easier way to create a folder the same name as archive, even if the archive contains only one file.

As for now, I need to tick "ALWAYS EXTRACT IN A SUBFOLDER" in preference each time I use this function.

I think there should be a shortcut in Keka interface

**Comment by aonez** [comment]
How are you calling the extraction? The "Always extract in a subfolder" option is permanent, so should be always used if you enabled it once.
