### ISSUE TITLE
[BUG] Issue extracting ZIP file

### ISSUE THREAD

**Issue by sdc1-clickclack** [aonez/Keka#1176]
### Configuration
- Keka version: [e.g. 1.1.24 (3421)]
- macOS version: [e.g. 10.14.6 (18G2022)]

### Describe the bug
Hello. I am not a developer or a student, nor am I especially tech-savvy, although neither am I a beginner.
I have recently been encountering a problem with the most current versions of Keka when I try to extract the contents of a .ZIP archive. I specify a destination folder/directory, but then I get an error message saying that the operation failed for ErrorDomain Code 1. For several years, I have been using Keka to extract the contents of .ZIP and other compressed archives without any problem, but this issue started recently. I will attach a log file below from one .ZIP archive that I tried to expand as a test. One possibility occurs to me: Is it possible that I cannot use Keka to expand archives while logged into my standard user account on my MacBook Pro instead of being logged into my admin account?  I cannot recall whether I downloaded the most recent versions of Keka while logged into one of my accounts instead of the other, as this was never a problem before. Actually, I think that I have encountered this same issue when I tried expanding archives while logged in as either user.

### To Reproduce
1. I have Keka set as the default app for extracting compressed archive files.
2. I double-click on a .ZIP archive.
3. When Keka asks me to do so, I specify the destination folder to which the contents of the archive should be extracted, and to which I have full access privileges.
4. I see an error message saying the operation failed. I am attaching the log file of one such test immediately below.

[Keka.log](https://github.com/aonez/Keka/files/9905625/Keka.log)

### Expected behavior
The contents of the .ZIP archive (usually either a folder or else an app and one or two simple text docs) should be extracted from the archive into the destination folder I have specified.

**Comment by gingerbeardman** [comment]
What is the exact error message that Keka shows when it fails?

You could try this: https://github.com/aonez/Keka/wiki/Error-accessing-the-binary

And check disk access permissions: https://github.com/aonez/Keka/wiki/Sandbox

**Comment by aonez** [comment]
Seems Keka has some issue executing the processes. Can you try removing
Keka and Installing it again? Does it also fail with a 7Z file?

**Comment by sdc1-clickclack** [comment]
> What is the exact error message that Keka shows when it fails?
Thank you for responding. Here is the error message:
<img width="516" alt="Keka-fail-error" src="https://user-images.githubusercontent.com/117127963/199314651-e3ec1b42-a360-4a64-a86a-f3dc41877d53.png">



> You could try this: https://github.com/aonez/Keka/wiki/Error-accessing-the-binary
> And check disk access permissions: https://github.com/aonez/Keka/wiki/Sandbox
Thanks for the suggestions. RE: the quarantine problem, I tried running the Terminal command to remove the quarantine flag, but got a very lengthy series of failure messages pertaining to permissions. I was logged into my standard user account, but will try performing the same operation while logged into my admin account. 
RE: the Sandbox aspect, I checked the File Access panel and saw that Keka already had access to my Downloads folder, and also to a folder belonging to my admin user account, where I store the most recent compressed archive files I have downloaded for various applications. I did enable access to my Home folder, as well, but that seems to have made no difference as I still encountered the same operation failure error — and that was after I had deleted and then reinstalled Keka, as suggested by aonez.

**Comment by aonez** [comment]
Also try restarting your Mac. This is macOS denying Keka access to its own
binaries. Usually restarting + reinstalling Keka fixes the issue.

**Comment by sdc1-clickclack** [comment]
> Seems Keka has some issue executing the processes. Can you try removing Keka and Installing it again? Does it also fail with a 7Z file?
> […](#)

Thank you so much for your response. I tried deleting and reinstalling Keka, and also used my admin account to grant Read & Write access to my standard user account for Keka, but I still encounter the same error when I attempt to use Keka to extract the contents of a .ZIP archive.
As for your last question, I do not know if I have any "7Z" archives with which to test Keka.
One thing I did learn, however, is that when I am logged into my admin account, I do NOT get the error when I use Keka to extract the contents of the very same .ZIP archive that yielded the error when I tested it from y non-admin account. That must be significant, but I do not know what changes I might need to make or where I need to make them. (I keep having the nagging suspicion that some painfully obvious mistake or oversight could be the reason for my having this problem, but I do not recall that it ever happened before the past few weeks.)

**Comment by sdc1-clickclack** [comment]
> Also try restarting your Mac. This is macOS denying Keka access to its own binaries. Usually restarting + reinstalling Keka fixes the issue.
> […](#)

I restarted my Mac and then once again deleted and reinstalled Keka, once more ensuring that both my admin and standard user accounts have Read & Write access to the Keka app. I got the same error.
I logged into my admin account and tried using Terminal to remove the quarantine flag from Keka, but got another very lengthy series of failure messages pertaining to permissions for lots and lots of resources/components within the Keka app.

I suppose I might have to content myself with the fact that I can always log into my admin account temporarily in order to extract the contents of problematic archive files. The only other test that I can think of would consist of my deleting the current version of Keka, installing an older version from a few months ago, and trying to extract the contents of the same  .ZIP archive while logged into my non-admin account — but perhaps it may not be worth the bother. I would prefer to figure out why this problem is happening so that it could be resolved, but I recognize that it is not _crucial_ that I do so.

**Comment by sdc1-clickclack** [comment]
Just in case there is still any interest in trying to determine why I am getting this error, here is an update: 
I tried extracting the contents of a couple of different .ZIP archives than the most recent ones for which I saw the failure message — and there was **no error message;** the archives were expanded without delay or any other issues.

The recently downloaded .ZIP archives for which Keka could not extract the contents are both Mac utility apps that I downloaded from Howard Oakley's excellent [EclecticLight Company](https://eclecticlight.co/downloads/) website. I can only presume there must be _something_ different about the .ZIP archives he creates for his apps when compared with .ZIP archives that I have downloaded from other people/websites, although I do not know what this difference might be.

**Comment by aonez** [comment]
So it's working for some ZIP files and not for others? A newly created ZIP file, booth created with Keka and macOS, do extract correctly?

**Comment by sdc1-clickclack** [comment]
> So it's working for some ZIP files and not for others? A newly created ZIP file, booth created with Keka and macOS, do extract correctly?

Sorry for the delay in my response; I was out running errands. YES, it seems that Keka has no trouble extracting some other .ZIP archives, but I get that "Extraction of (...) failed" error for the .ZIP archives containing utility apps that I downloaded from Howard Oakley's website. I quickly created a brand-new .ZIP archive using first MacOS and then Keka itself, and Keka extracted their contents without any problem. I have not tried running more extensive tests with a lot of .ZIP archives, either old or recent, so I do not know whether any other .ZIP archives might trigger the same error message. I presume there is something unusual about the .ZIP archives I downloaded from Howard's website over the past few months, but have no idea what that difference might be.

**Comment by sdc1-clickclack** [comment]
HANG ON, hold everything...!!! This is VERY odd, but I shut down my Mac last night and did not turn it on again until this afternoon, and I just tried extracting the two .ZIP archives I downloaded most recently from Howard Oakley's website AND THEY BOTH EXTRACTED WITHOUT THE FAILURE ERROR.
I **am officially baffled as to why the problem is no longer afflicting these same .ZIP archives.**

I did save the error log generated yesterday when Keka failed to open the .ZIP file for a utility app named Silent Knight. If you want, I can upload a copy of it here (after obscuring my user account name for that folder/directory).

**Comment by aonez** [comment]
Sure upload the log, I’m sure it will be macOS sandbox again denying Keka
access to the binaries.

Glad it works now, this issue happened a few times over the years, usually
restarting (shutdown in this case?) and/or reinstalling Keka fixes this
since macOS’s sandbox system stops blocking Keka’s binaries. Odd indeed.

**Comment by sdc1-clickclack** [comment]
> Sure upload the log, I’m sure it will be macOS sandbox again denying Keka access to the binaries. (...snip...)

Okay, here is a .PNG image showing the log file for that error, but with the name changed for my admin account.

<img width="713" alt="Keka-failure-log_anon" src="https://user-images.githubusercontent.com/117127963/199626444-eebb8423-697b-4c8e-bd1c-24b7d8e4a618.png">

I'm puzzled as to why shutting down seemingly resolved the problem after deleting & re-installing Keka AND restarting my Mac both failed to do so. So many mysteries, so few clues..... unless gremlins are an actual factor.

**Comment by gingerbeardman** [comment]
> AND THEY BOTH EXTRACTED WITHOUT THE FAILURE ERROR.

But did the extract with Keka or the macOS system archive utility?

**Comment by sdc1-clickclack** [comment]
> > AND THEY BOTH EXTRACTED WITHOUT THE FAILURE ERROR.
> 
> But did the extract with Keka or the macOS system archive utility?

Sorry for not being more clear, but yes, they both extracted with Keka. I just now tried once again extracting one of the two .ZIP archives that yielded the failure error before, and Keka extracted its contents immediately without any issues.

**Comment by sdc1-clickclack** [comment]
Sorry, I am still new here and not familiar with standard protocol, but it did just occur to me that I should close this issue as I am the one who opened it, and it appears the problem was temporary and not an issue for others. Thanks again for the responses and helpful suggestions — and for continuing to update Keka and keep it available.

**Comment by aonez** [comment]
Hopefully you don't have this problem ever again 😁
