### ISSUE TITLE
Tasks window size issue in macOS Ventura

### ISSUE THREAD

**Issue by mooneyed** [aonez/Keka#1178]
Once, during the creation of many archives, I accidentally clicked on the green button of the process window, as a result of which, the window expanded to full screen. When I pressed this button again, the window shrank into a minimal view. And now it is impossible to return this window to its normal appearance, the arrows on the sides of the window do not work when hovering over the mouse. You can only open half of the text window of the first compression process. I think that only reinstalling the application will help here.

![IsHtkyH](https://user-images.githubusercontent.com/480163/201473996-525cb743-59f1-482d-8ea1-44887e35e59c.png)

![6LAmdSb](https://user-images.githubusercontent.com/480163/201473955-5ccded9b-11a6-4468-8034-8f8ccaa6da35.png)

**Comment by aonez** [comment]
Are you using macOS Ventura? If so, please try this build:

https://d.keka.io/test/Keka-v1.2.58.r5072

Please let me know if this fixes the issue.

**Comment by mooneyed** [comment]
> Are you using macOS Ventura? If so, please try this build:
> 
Yes
> https://d.keka.io/test/Keka-v1.2.58.r5072
> 
> Please let me know if this fixes the issue.

Now it works correctly.
