### ISSUE TITLE
please publish public EdDSA signing key

### ISSUE THREAD

**Issue by michaelowenfinoa** [aonez/Keka#1185]
I would like to be able to cryptographically verify the authenticity of Keka. I observe there is a text file with each release that has checksum information and a EdDSA signature. However I am unable to locate the public key used to generate the EdDSA signature.

Could you please direct me to the public EdDSA that is used to create the EdDSA signatures in these text files?

Ideally this public key would not be hard to find, and should be linked to in the README and/or release page, or on the keka.io site. Perhaps I am just missing it, but I do not see it anywhere.

Thanks

**Comment by aonez** [comment]
Sure. It'll be best to sign the app bundle or the DMG?

**Comment by michaelowenfinoa** [comment]
Cool - for me the DMG, but I could imagine some may also like to have the .zip signed.

**Comment by aonez** [comment]
In fact the ZIP is also signed since it's also used to the update process (when there's no delta available).

Already added it to the package script, the next revision DMG will be also EdDSA signed.

**Comment by aonez** [comment]
This was published starting with 1.2.59 😊
