### ISSUE TITLE
解压提取失败

### ISSUE THREAD

**Issue by intobest** [aonez/Keka#1187]
version:  1.2.58 (5074)
macOS Big Sur 11.7.1

when I decompress rar files, it will be error。
Prompt me：
There was some error accessing the binary "7zz"
Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"

**Comment by aonez** [comment]
Usually shutting down the Mac and reinstalling Keka fixes this issue. Let me know if that helps.

**Comment by intobest** [comment]
@aonez Thank you ！ Your reply helped me。

**Comment by Tetonne** [comment]
not solve here (delete app with a deleter reboot, then re install any idea advise?

**Comment by aonez** [comment]
Please @Tetonne open another issue providing more information about your issue
