### ISSUE TITLE
Keka does not .zip in background?

### ISSUE THREAD

**Issue by 86536243wedqwe** [aonez/Keka#119]
Hey there,

I have a problem with Keka 1.0.12. on macOS that it either is painfully slow or does not continue to .zip in background when I have other tasks open and in foreground (like the browser right now). The problem is persistent whether I am on battery or on wall charge and it has nothing to do with my power settings for all I know.

Can it be that it is not using all the potential CPU power to run its tasks? Generally it is much much slower than the OS inbuild archiver.

All the best.

**Comment by aonez** [comment]
Keka works in background the same as in foreground. Maybe there's something involving the app nap? You can check if Keka has this option within the "Get Info" panel.

**Comment by aonez** [comment]
Also within the "Activity Monitor" you can check if Keka is in a "nap" state:

<img width="680" alt="activitymonitor_appnapactive_2x" src="https://developer.apple.com/library/content/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/Art/activitymonitor_appnapactive_2x.png">

More info here: https://developer.apple.com/library/content/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/AppNap.html

**Comment by 86536243wedqwe** [comment]
It has nothing to do with app nap. And while in Activity Monitor I noticed that Keka does not use a lot of CPU power - barely 5% per extracting job in the queue. While extracting multiple archives, around 50% of overall CPU is still idle.

Can I allocate more processing power to Keka to speed up archiving and unarchiving?

**Comment by aonez** [comment]
There's no restriction in the CPU usage, so I'm not sure what's the problem here.

What system are we talking here? Mac model?

**Comment by byfy** [comment]
I also encountered the same problem,so must switch to keka regularly.
System：OSX 10.13.2 
Thanks

**Comment by aonez** [comment]
@byfy your machine is also a MacBook?

**Comment by byfy** [comment]
@aonez Yes~,MacBook Pro (Retina, 15-inch, Mid 2015)  High Sierra 10.13.2

**Comment by aonez** [comment]
Could you try this build: http://download.kekaosx.com/test/Keka-1.0.12-bgslowdown.7z
I've added an activity indication to the system, so it should respect in any case the operation.

Is there any specifics to the extraction/compression? Like source type of files or origin/destination disk?

**Comment by byfy** [comment]
operation: extraction
file size: 90GB(single file
source file format: .json
origin and destination disk: local disk

Thanks~

**Comment by TheDeathOfAffect** [comment]
I'm experiencing the same problem. 30GB file says it needs 20min for .7z'ing, running in background the timer does not run. After 20min it says 3min elapsed. More or less the time the app was running in foreground. WTF?

Operation: .7z (non solid)
File size: 30GB project folder
Origin and destination disk: SSD via USB-C

**Comment by aonez** [comment]
I've replicated now this issue. It's only the timer that is not reliable when Keka enters on Nap mode, thus giving a bad estimation.

The operation (extraction/compression) does not stop/pause at any moment.

**Comment by aonez** [comment]
> Could you try this build: http://download.kekaosx.com/test/Keka-1.0.12-bgslowdown.7z

@TheDeathOfAffect, @byfy did you tried that build? This build should not enter in Nap mode, therefore the timer should run fine.

**Comment by aonez** [comment]
Fixed in 1.0.14
