### ISSUE TITLE
[BUG] AAR, created by Keka UI, can't be tested by 7zz and Unar

### ISSUE THREAD

**Issue by kkovaletp** [aonez/Keka#1190]
### Configuration
- Keka version: 1.2.58 (5074)
- macOS version: 12.6.1 (21G217)

### Describe the bug
[Keka_2022-12-03-225731722.log](https://github.com/aonez/Keka/files/10147392/Keka_2022-12-03-225731722.log)
Attach a log file reproducing the issue: https://github.com/aonez/Keka/wiki/Report-an-issue

I created AAR by Keka UI, then tried to unpack it by Keka UI - successfully.
But when I tried to test it in the shell by the next commands, both failed with the next output:
```
$> /Applications/Keka.app/Contents/MacOS/Keka --ignore-file-access --cli 7zz t ./selenide-allure-junit-master.aar
7-Zip (z) 22.00 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-06-15 : Modified by aone for Keka
 64-bit locale=en_US.UTF-8 Threads:12

Scanning the drive for archives:
1 file, 6855 bytes (7 KiB)

Testing archive: /Users/<>/Desktop/selenide-allure-junit-master.aar
ERROR: /Users/<>/Desktop/selenide-allure-junit-master.aar
Cannot open the file as archive


Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
```
```
$> /Applications/Keka.app/Contents/MacOS/Keka --ignore-file-access --cli unar -o - ./selenide-allure-junit-master.aar > /dev/null
Couldn't recognize the archive format.
```
In the same way, downloaded AAR from the Internet is tested successfully.
When I executed the `file -b --mime-type <file>` against both files, I see that AAR from Internet has ZIP format, while created by Keka is octet-stream

### To Reproduce

See the Description

### Expected behavior

I expect that at least one of the (7zz, Unar) modules is able to test created by the Keka UI AAR archive. At the same time, I expect that the created by Keka UI AAR has the correct format according to AAR specs and is compatible with native consumers

### Screenshots
![Screenshot 03 12 2022 в 22 13 24](https://user-images.githubusercontent.com/32730812/205462377-18fc2154-cb7e-4a96-a0a9-4da93f1a3c23.png)

### Additional context
[selenide-allure-junit-master.aar.zip](https://github.com/aonez/Keka/files/10147395/selenide-allure-junit-master.aar.zip)

**Comment by gingerbeardman** [comment]
AAR is an Apple proprietary format.

Use `aa` (previously `yaa`) command to work with it.

In terminal do `man aa` to find out more.

**Comment by kkovaletp** [comment]
> Use `aa` (previously `yaa` on some older macOS versions) command to work with it.
> In Terminal do `man aa` to find out more.

Thanks a lot for pointing me to this standard tool!
I've checked and see that actually Keka creates correct AAR archive and the downloaded one from the Internet is not actually AAR.

In this case, as there is no Keka module to support the AAR format and both 7zz and unar failed to parse it, does it mean that Keka UI uses the `aa` to do the job?

**Comment by gingerbeardman** [comment]
yes, Keka uses `aa` do work with such archives.

Can you share a link to selenide-allure-junit-master.aar? the filename implies that it is a downloaded GitHub repo, but why would it have the aar ending? Usually it would be a zip.

What is the output of `file selenide-allure-junit-master.aar` in Terminal?

**Comment by kkovaletp** [comment]
> Yes, Keka uses `aa` do work with such archives.

Great, thanks for the confirmation!

> Can you share a link to `selenide-allure-junit-master.aar`? the filename implies that it is a downloaded GitHub repo, but why would it have the `.aar` ending? Usually it would be a `.zip`.

This file is attached to this ticket: [https://github.com/aonez/Keka/files/10147395/selenide-allure-junit-master.aar.zip](https://github.com/aonez/Keka/files/10147395/selenide-allure-junit-master.aar.zip)
Yes, it is a repo and I've created AAR archive from it by Keka just as an example of AAR processing.

> What is the output of `file selenide-allure-junit-master.aar` in Terminal?

```
$> file ./selenide-allure-junit-master.aar
./selenide-allure-junit-master.aar: data

$> file -b --mime-type ./selenide-allure-junit-master.aar
application/octet-stream
```

Anyway, I see that there is no issue here and my misunderstanding was caused by the absence of AAR format processing by `aa` tool. Now I've added this case to my [test-archive](https://github.com/aonez/Keka/discussions/1189) script and everything works fine.
Feel free to provide your feedback in that thread)

**Comment by gingerbeardman** [comment]
Great!

I misunderstood something that you had downloaded an AAR file.

**Comment by kkovaletp** [comment]
With this, I'm closing this issue
