### ISSUE TITLE
[BUG] From report alert

### ISSUE THREAD

**Issue by vlape** [aonez/Keka#1192]
Your comments here

Error when attempting to compress with ZSTD
Version 1.2.58 (5074)

Error while getting the tasks list (quitting 0):

*** -[NSArray initWithArray:range:copyItems:]: range {0, 2} extends beyond bounds [0 .. 0]

**Comment by aonez** [comment]
Thanks for the feedback @vlape!

I'm closing this one in favor of https://github.com/aonez/Keka/issues/1153
