### ISSUE TITLE
[BUG] keka no longer serves as default app in MacOS x 13.1, it is just me or anyone else facing the same issue?

### ISSUE THREAD

**Issue by MRKsas** [aonez/Keka#1196]

**Comment by aonez** [comment]
Did you fixed it or should I check this?

**Comment by MRKsas** [comment]
> Did you fixed it or should I check this?

no. The bug remains.

**Comment by aonez** [comment]
It is working for me. Are you receiving any error message?

![Screenshot 2022-12-14 at 22 41 40](https://user-images.githubusercontent.com/480163/207721279-8dabfc58-6c0b-44ae-97af-b71b8e638443.png)

**Comment by MRKsas** [comment]
I have set up keka as default in the setting, and the "get info" page of any zip files also shows "open with keka", but it is actually Archive Utility doing the job.

**Comment by aonez** [comment]
Just to be sure, are you taking about extracting or compressing files?
If you right click on any of those file and got to “Open with…” what does it say?

some screenshot or a screencast (video) reproducing the issue will be very helpful.

**Comment by aonez** [comment]
Reopen with the information requested if you still have the issue.

**Comment by MRKsas** [comment]
Uploading Screen Recording 2022-12-15 at 4.44.31 PM.mp4…

**Comment by MRKsas** [comment]
https://user-images.githubusercontent.com/115054265/207814694-1a2adc80-7359-41f3-b472-9da8b14aad8a.mp4
