### ISSUE TITLE
[BUG] Keka unable to extract 7z file it creates by itself

### ISSUE THREAD

**Issue by mr-moon** [aonez/Keka#1198]
### Configuration
- Keka version: 1.2.55 (5009)
- macOS version: 12.6 (16" intel 2019)

### Describe the bug
Unable to extract 7z file, created with Keka itself.
[Keka_2022-12-26-122044630.log](https://github.com/aonez/Keka/files/10303027/Keka_2022-12-26-122044630.log)

### To Reproduce
1. Open keka
2. Choose 7z and max compression
3. Type in password "Test12345!"
4. Confirm password: "Test12345!"
5. Check "encrypt filenames"
6. Add a single file
7. Now try extracting created 7z file. It will always fail as if you were typing wrong password.

### Expected behavior
Normally extract 7z it creates

**Comment by aonez** [comment]
Please check you're really using Keka to extract the files. Check: https://github.com/aonez/Keka/issues/477

**Comment by mr-moon** [comment]
Indeed. Thank you and sorry.
