### ISSUE TITLE
Cannot open with windows (7zip/winzip) password protected archive keka (macos)

### ISSUE THREAD

**Issue by 4kokoano** [aonez/Keka#1199]
Hello
im unable to open a password protected archive created with keka (7z or zip) on windows system with 7zip or winzip or windows sel exctractor: it says password is wrong

its working with a password protected file created with 7zip (windows system) and opened with keka or finder

using terminal command zip -e  , resulting in having blank password and archived is not protected ( again in windows system , working fine in macos bigsur)

pc1 : macos bigsur jap 
pc2 : windows 7

help would be much appreciate

Thanks

**Comment by aonez** [comment]
Can you share the file and/or the password used for the compression?

Here or send it to info@keka.io

**Comment by 4kokoano** [comment]
it worked once then tried with other archive and failed to open cause bad password (same password , mp3 or pdf or jpg)
[Desert.jpg.zip](https://github.com/aonez/Keka/files/10327000/Desert.jpg.zip)
password : Dnb88#Y6Gvap24&

**Comment by aonez** [comment]
No issues on my end. Maybe you're mistyping some of the symbols on Windows? For example on my end, using a Virtual Machine the keys I have to press are different.

![640](https://user-images.githubusercontent.com/480163/210138264-20adb229-7090-4fe7-8b17-fb8112b45ac8.gif)
