### ISSUE TITLE
Unpacking zip, encoding corrupts filenames

### ISSUE THREAD

**Issue by tkisme** [aonez/Keka#12]
It's happening to names of files and folders within zip archives (scrambled when looking or unzipping them), and to the content in some Text files, other files seems to fare better even though their names are gibberish.

**Comment by tkisme** [comment]
https://github.com/kjerk/sjisunzip

**Comment by tkisme** [comment]
no offence, Entropy do it well.

**Comment by aonez** [comment]
thanks for the tip, will look at it

**Comment by aonez** [comment]
can you share a file to test?

**Comment by tkisme** [comment]
[Battle.net-Setup-CN.zip](https://github.com/aonez/Keka/files/712802/Battle.net-Setup-CN.zip)

**Comment by maz-1** [comment]
Maybe use p7zip-natspec or unzip-iconv for encoding autodetection?
https://aur.archlinux.org/packages/p7zip-natspec/
https://aur.archlinux.org/packages/unzip-iconv

**Comment by aonez** [comment]
Just deleted one of you comments because it contained a file with adult images.

For the battle-net issue, here is the right issue that already contains a test file: https://github.com/aonez/Keka/issues/2

For the zip encoding, [here](https://github.com/aonez/Keka/files/723633/test.zip) an all ages test file, found https://sourceforge.net/p/sevenzip/discussion/45797/thread/5af7bde0.

Just note that the bundled macOS compression utility also fails to extract it with the correct encoding.

**Comment by aonez** [comment]
Just for test I've opened **Unicode test.zip** file, that you can find inside the test file posted before and Entropy did not extracted the files with the Chinese encoding, omitted them. Also the adult file you've posted before got unusable with Entropy, no images nor text file when extracted.

**Comment by aonez** [comment]
[Here](https://github.com/aonez/Keka/files/724775/biografiko.zip) another test file. This one is encoded in Greek DOS (737 codepage). This one was found [here](https://sourceforge.net/p/p7zip/bugs/151/).

**Comment by aonez** [comment]
Some useful info here: https://sourceforge.net/p/p7zip/discussion/383044/thread/3d213124

No quick fix though.

**Comment by tkisme** [comment]
maybe add iconv is enough?Can't wait to test.

**Comment by tkisme** [comment]
![image](https://cloud.githubusercontent.com/assets/5886048/22229992/264c0f3e-e216-11e6-95b9-56068b93e46a.png)
from The Unarchiver

**Comment by maz-1** [comment]
Official support could take some time, but as I have pasted above, there is already third-party patches to add encoding autodetection support to unzip and p7zip :-)

**Comment by tkisme** [comment]
I think keka is the replacement of the default 'Archive Utility.app'.Use different application to handle different archives is just annoying.
So I think this is the necessary functions.

**Comment by maz-1** [comment]
I can't get the point. Keka is behaving similar to built-in archive utility (double click and decompress), I did not see anything annoying
Anyway, I tried to build latest p7zip with natspec patch and replaced Keka.app/Contents/Resources/keka7z, still no luck. The patch needs to be fixed for p7zip 16.02.

**Comment by tkisme** [comment]
I think the system built-in 'Archive Utility.app' is useless,that's my point.Keka is just perfect.

**Comment by aonez** [comment]
@maz-1 , what natspec library you've used to compile p7zip? Can you share those files?

**Comment by maz-1** [comment]
Here is the natspec patch for p7zip 15.14.1 
https://aur.archlinux.org/cgit/aur.git/tree/natspec.patch?h=p7zip-natspec
line 31 doesnt apply on p7zip 16.02, need a fix.
Here is the natspec library
https://sourceforge.net/projects/natspec/

@tkisme
Whatever. Why not stop arguring and start finding a solution to the problem?

**Comment by aonez** [comment]
@maz-1 I've already downloaded both the patch and the library files, and fixed the patch. But I'm unable to link p7zip to the natspec library. How you did it?

**Comment by maz-1** [comment]
I made a homebrew formula to build natspec : https://gist.github.com/maz-1/2c797fa2ccf5aa815017676bbb884a73
Download natspec.rb and run "brew install natspec.rb" should install the library.
And then patch p7zip with this(Modified a little to link to natspec) : https://gist.github.com/maz-1/f8e0bce8516e11337a758314c07ca423

But the encoding detection is still borken (15.02 has the same problem):
`/Users/ling/Downloads/p7zip_15.14.1/bin/7z  x /Users/ling/Downloads/test/Unicode\ test.zip

7-Zip [64] 15.14 : Copyright (c) 1999-2015 Igor Pavlov : 2015-12-31
p7zip Version 15.14.1 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 8458 bytes (9 KiB)

Extracting archive: /Users/ling/Downloads/test/Unicode test.zip
Broken encoding: '(null)' (to) or 'CP936' (from) or UCS2. May be you forget setlocale in main or gconv-modules is missed?
: Invalid argument
…
Broken encoding: '(null)' (to) or 'CP936' (from) or UCS2. May be you forget setlocale in main or gconv-modules is missed?
: Invalid argument
--
Path = /Users/ling/Downloads/test/Unicode test.zip
Type = zip
Physical Size = 8458

  0%Broken encoding: '(null)' (to) or 'CP936' (from) or UCS2. May be you forget setlocale in main or gconv-modules is missed?
: Invalid argument
…
Broken encoding: '(null)' (to) or 'CP936' (from) or UCS2. May be you forget setlocale in main or gconv-modules is missed?
: No such file or directory
Everything is Ok

Folders: 7
Files: 30
Size:       132
Compressed: 8458
`

**Comment by aonez** [comment]
Another file that gets broken, Russian content shared by Колобок via mail: [IIS.zip](https://github.com/aonez/Keka/files/825620/IIS.zip)

**Comment by InfinityMe** [comment]
IIS.zip was probably created by the built-in Windows archiver, I now checked, unpacked and re-packed the files, then unpacked, the encoding went bad.
WinRar on Windows at the same time works with such an archive correctly.
![2017-03-09 22 49 09](https://cloud.githubusercontent.com/assets/1360926/23767807/00744cfe-051b-11e7-88e7-2a736190d318.png)
![2017-03-09 22 48 29](https://cloud.githubusercontent.com/assets/1360926/23767810/04bb3322-051b-11e7-8fa6-c442c323e4e7.png)

**Comment by aonez** [comment]
Should check https://github.com/ethereon/p7zip-hybrid encoding changes

**Comment by aonez** [comment]
This one should be fixed in 1.1.6!!!

**Comment by ffffwh** [comment]
I am doing a research whether I could replace 'The Unarchiver' with this great App.

The only concern seems to be zip file name encoding. IMHO, auto encoding detection does not work 100%, so manual selection should be provided as a last resort.

With no offence, is it implemented?

**Comment by aonez** [comment]
It was implemented in 1.1.6 @ffffwh. Inspired in The Unarchiver way, so will be very (maybe too much) familiar. You can test the feature with the example file found in the comment https://github.com/aonez/Keka/issues/12#issuecomment-274597094.
