### ISSUE TITLE
[BUG] Issue with passwords.

### ISSUE THREAD

**Issue by vladimir-chistyakoff** [aonez/Keka#1215]
### Configuration
- Keka version: 1.2.60
- macOS version: 13.2 (22D49)

### Describe the bug
When unzipping a 7 zip archive created in other programs and on other operating systems with a Cyrillic password (for example, ПАРОЛЬ), the password is not accepted. It is possible to create an archive in Keka with a Cyrillic password, but it is no longer possible to unzip it in Windows.

### To Reproduce
1. Try to unzip the attached archive (7zip archive in zip archive)
2. Type or copy password (without quotes): "ПАРОЛЬ"

In any other OS (for example Windows) Unzip is done.

### Expected behavior
Unzip
[TEST_ARCHIVE.zip](https://github.com/aonez/Keka/files/10686231/TEST_ARCHIVE.zip)

**Comment by aonez** [comment]
It does work for me.

![Screenshot 2023-02-08 at 19 30 16](https://user-images.githubusercontent.com/480163/217620077-5da6d1b5-d45d-425b-9e9c-1bce5ed3126a.png)

![Screenshot 2023-02-08 at 19 32 51](https://user-images.githubusercontent.com/480163/217620646-f90477a9-a814-46ab-a843-cae234e4c76c.png)


Be sure to click on "Show password" to be sure you're properly introducing the password on the Windows environment.

![Screenshot 2023-02-08 at 19 30 44](https://user-images.githubusercontent.com/480163/217620282-bb9659dd-7280-42ee-9840-b97d80151e19.png)

**Comment by vladimir-chistyakoff** [comment]
I'm sorry that I explained the procedure incorrectly. Try to unzip the password-protected archive using Keka.

**Comment by aonez** [comment]
You are most probably extracting it with the macOS default extraction tool. If you drop the file to Keka, does not extract it? It works properly on my end.

**Comment by AKikhaev** [comment]
It also cant unpack 7z password protected archive created in keka with the same password :(

**Comment by aonez** [comment]
@AKikhaev again you're most probably not using Keka to extract that file, but the macOS bundled extraction tool. Be sure to use Keka, drop the file to the Keka icon or window.

Take a look at: https://github.com/aonez/Keka/issues/477
