### ISSUE TITLE
Wrong link in Wiki

### ISSUE THREAD

**Issue by markgeary** [aonez/Keka#1228]
### Configuration
- Keka version: [e.g. 1.1.24 (3421)]
- macOS version: [e.g. 10.14.6 (18G2022)]

### Describe the bug
https://github.com/aonez/Keka/wiki/ has the incorrect link for "Use it from the Terminal"
It should be [...]/Terminal-support rather than [...]/Terminal-client.

Is this the right way to report this? I'm new to github.

**Comment by aonez** [comment]
Sure thanks!

Fixed it already https://github.com/aonez/Keka/wiki/Home/e2e736c92e7f4d577b11d1a654eef623a622dcef
