### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sonograme** [aonez/Keka#1229]
Dear Aonez,

There seems to be quite a lot of issues trying to open files I have downloaded.
I encountered error before using the Unarchiver, most probably because the compressed file was done on Windows.

Due to very good review, I decided to buy your app and I can't open any files.
Do you have any solutions for me ?

Below are the following error texts :

OS: Version 10.15.7 (assemblage 19H15) (x86_64)
Keka: v1.2.61-r5114 (MAS) (Sandboxed) (fr)
Format detected: Unknown
Binary used: keka7zz
Arguments: (
    x,
    "/Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00443.zip",
    "-o/Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00443.kextraction/Operation",
    "-snld",
    "-aou",
    "-xr!__MACOSX",
    "-bsp1"
)

7-Zip (z) 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15 : Modified by aone for Keka
 64-bit locale=en_US.UTF-8 Threads:16

Scanning the drive for archives:
  0M Scan /Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/
1 file, 101154816 bytes (97 MiB)

Extracting archive: /Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00443.zip
  8% Open  8%
ERROR: /Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00443.zip
/Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00443.zip
Open ERROR: Cannot open the file as [zip] archive

ERRORS:
Is not archive

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

Error code 2

Or this one 

OS: Version 10.15.7 (assemblage 19H15) (x86_64)
Keka: v1.2.61-r5114 (MAS) (Sandboxed) (fr)
Format detected: RAR Legacy
Binary used: kekaunrar
Arguments: (
    x,
    "-idcd",
    "-kb",
    "-x*/__MACOSX",
    "-y",
    "/Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00781.rar",
    "/Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00781.kextraction/Operation/"
)

Extracting from /Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00781.rar

Creating    /Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00781.kextraction/Operation/Somewhere I Belong Multitrack  OK

Extracting  /Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00781.kextraction/Operation/Somewhere I Belong Multitrack/01 - Kick Drum.mp3     
5%6%
17%18%

Somewhere I Belong Multitrack/01 - Kick Drum.mp3 - checksum error

Corrupt header is found

OS: Version 10.15.7 (assemblage 19H15) (x86_64)
Keka: v1.2.61-r5114 (MAS) (Sandboxed) (fr)
Format detected: RAR Legacy
Binary used: keka7zz
Arguments: (
    x,
    "/Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00781.rar",
    "-o/Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00781.kextraction/Operation",
    "-snld",
    "-aou",
    "-xr!__MACOSX",
    "-bsp1"
)

7-Zip (z) 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15 : Modified by aone for Keka
 64-bit locale=en_US.UTF-8 Threads:16

Scanning the drive for archives:
  0M Scan /Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/
1 file, 22904832 bytes (22 MiB)

Extracting archive: /Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00781.rar

WARNINGS:
There are data after the end of archive

--
Path = /Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00781.rar
Type = Rar
ERRORS:
Headers Error
WARNINGS:
There are data after the end of archive
Physical Size = 7455468
Tail Size = 15449364
Solid = -
Blocks = 1
Multivolume = -
Volumes = 1

  0%

ERRORS:
Headers Error

ERROR: Data Error : Somewhere I Belong Multitrack/01 - Kick Drum.mp3

Archives with Errors: 1

Warnings: 1

Open Errors: 1

Sub items Errors: 1

Error code 2

Or this one : 

OS: Version 10.15.7 (assemblage 19H15) (x86_64)
Keka: v1.2.61-r5114 (MAS) (Sandboxed) (fr)
Format detected: Unknown
Binary used: keka7zz
Arguments: (
    x,
    "/Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00784.7z",
    "-o/Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00784.kextraction/Operation",
    "-snld",
    "-aou",
    "-xr!__MACOSX",
    "-bsp1"
)

7-Zip (z) 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15 : Modified by aone for Keka
 64-bit locale=en_US.UTF-8 Threads:16

Scanning the drive for archives:
  0M Scan /Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/
1 file, 67108864 bytes (64 MiB)

Extracting archive: /Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00784.7z
 12% Open 12%
ERROR: /Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00784.7z
/Users/nicolassuffit/Desktop/Remixpacks Collection Vol. 02/stems/00784.7z
Open ERROR: Cannot open the file as [7z] archive

ERRORS:
Is not archive

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

Error code 2

**Comment by aonez** [comment]
Hi @sonograme 

Seeing those logs I think the downloads are corrupt or invalid.

Can you share any of this files URL so I can download and test it?

**Comment by sonograme** [comment]
Hello,

Thanks for the reply, here is the download

magnet:?xt=urn:btih:45a805dbd78b8dec796a0a127c4b4d2466ddbb9a

**Comment by aonez** [comment]
@sonograme no peers on the magnet. Will wait a while.

**Comment by aonez** [comment]
Just checked `00784.7z` and extracted properly. Probably the download got corrupted in your side.

I don't know what client are you using for downloads, [Transmission](https://transmissionbt.com) has a "[Verify Local Data](https://forum.transmissionbt.com/viewtopic.php?t=13372)" feature, that will be helpful.
