### ISSUE TITLE
[BUG] Trace/BPT trap: 5

### ISSUE THREAD

**Issue by Debuggernaut** [aonez/Keka#1230]
### Configuration
- Keka version: latest (here on Github and from the app store)
- macOS version: 13.2, 22D49

### Describe the bug
When I try to use the command line Keka tools, they immediately error out like so:

$ /Applications/Keka.app/Contents/MacOS/keka7z 
Trace/BPT trap: 5

### Additional context
tried running xattr already FWIW.  UI seems to work fine.

Experienced the same issue on 1.2.56, 1.2.53, 1.2.14 downloaded from Github.  No repro on 1.1.30

$ sudo xattr -c /Applications/Keka.app/Contents/MacOS/Keka

[keka7z-2023-03-17-184156.ips.zip](https://github.com/aonez/Keka/files/11007255/keka7z-2023-03-17-184156.ips.zip)

**Comment by aonez** [comment]
Take a look at the wiki: https://github.com/aonez/Keka/wiki/Terminal-support

Since version 1.2.11 you can’t use the binaries directly since they are sandboxed, you should call the through Keka:

`/Applications/Keka.app/Contents/MacOS/Keka --cli keka7z`

**Comment by Debuggernaut** [comment]
Thanks!
