### ISSUE TITLE
[BUG] Unable to extract file including NFC character from Finder after Ventura 13.3 Update

### ISSUE THREAD

**Issue by hw0603** [aonez/Keka#1233]
### Configuration
- Keka version: 1.2.61 (5114)
- macOS version: 13.3(22E252)

### Describe the bug
If the file name contains NFC characters, you cannot extract them by double-clicking them in the Finder.

### To Reproduce
1. Double click file on Finder

### Expected behavior
Archive file must be extracted to current dir

### Screenshots
None

### Additional context
You can rename the file to remove NFC characters, or execute the Keka window, and then drag and drop the file to the window to extract it normally.

**Comment by hw0603** [comment]
I've upgraded from 13.2.1 to 13.3, and I found Keka was already set to default app.
I've also re-set the default app settings in Keka setting, but it's no good.

If I drop the file to Keka, it will be extracted normally. At first, I thought NFC characters were simply a problem, but after compressing a folder containing the Korean file name in Windows 11 ARM (parallels), I named the compressed file in Korean, but there was no problem decompressing it with Keka.

I have a sample of files that cause problems with decompression, but the contents in the files are not suitable for sharing in public places such as Github. Is there any other way I can share this file privately?

**Comment by aonez** [comment]
Just send it to ***@***.***

**Comment by aonez** [comment]
Sorry it went to spam, just saw the file. Testing right away.

**Comment by aonez** [comment]
Just extracted the shared file both with Keka and Ventura's bundled extractor with no issues.

> I have a sample of files that cause problems with decompression, but the contents in the files are not suitable for sharing in public places such as Github. Is there any other way I can share this file privately?

What was the issue? Can you share an screencast reproducing it?

**Comment by hw0603** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/31981462/229343127-b488cf5b-d9fc-4d84-882e-944a781bf3f0.png">
  
Pic 1, when I opened `05주차.zip` from Finder
<img width="912" alt="스크린샷 2023-04-02 오후 6 03 43" src="https://user-images.githubusercontent.com/31981462/229343262-fe0419f2-87ba-4bec-9a15-d5f779d9b97b.png">
  
Pic 2, when I renamed same file to `05.zip` and opened it same way.
  
Under normal circumstances, a dialog box asking which path to extract the file should be displayed regardless of the file name. 

I haven't found the exact reason why this phenomenon occurs yet. I'm just guessing it's an "NFC<->NFD issue" because the symptom has been resolved after removing Korean from the file name.

As I told you in the mail, the file was not compressed by me. I tried to decompress the issue using Bandizip, ALzip, Windows Explorer default zip folder on Windows and then using Keka in MacOS, but the issue has not yet been reproduced.

I'm testing in various situations, and I'll share it again if I get additional information or find a way to reproduce the problem.

**Comment by aonez** [comment]
> after compressing a folder containing the Korean file name in Windows 11 ARM (parallels), I named the compressed file in Korean

All those you did in Windows 11, right? With the bundled compression tool (contextual menu) or a third party compression tool? Maybe this has something to do with composition and decomposition of characters.

Also how did you sent the file to the host macOS, using the Parallels Additions (copy/paste or drag/drop) or using a shared folder?

Maybe I can reproduce the issue with all that steps. Anyhow, if you ever reproduce it again maybe you can catch the specific steps to do it.

Thanks for all the feedback @hw0603

**Comment by hw0603** [comment]
@aonez I found this was not the issue of Keka. It was something with Ventura 13.3 Update. ([Link](https://discussions.apple.com/thread/254748658))
  
Workaround:
> Select the file in Finder that you cannot open, press Enter to enter edit mode, and then immediately press Enter again to exit edit mode. Will this open the file? In some cases, you may need to do the same with the full path of the file.
The purpose of this sequence of operations is to convert NFC characters to NFD (editing a file name in Finder converts it to NFD). Apparently, Ventura 13.3 does not equate the filename passed as NFC with the NFD and loses sight of it when the application is launched with the open command or a double-click from Finder.

I'll close this issue since it's a bug of MacOS itself.

**Comment by aonez** [comment]
macOS Ventura really is a bag of bugs... hopefully they release a more stable 14.0 in the summer.
