### ISSUE TITLE
Multiple compress/extract action - run iterative / parallel switch

### ISSUE THREAD

**Issue by iangrey** [aonez/Keka#124]
*ACT*
- invoke 8 7zip/best compressions (drag 8 folders into keka, set up to "archive as single files")

*OBS*
- all run in parallel, taking more than 1 hour to complete

*ACT*
- run the 8 compressions manually

*OBS*
- finish in 30 minutes

*EXP*
- queue should be faster, not slower than waiting and manually starting new tasks

=> I'd love to have a switch for parallel/iterative compression/extraction, or some kind of WIP-limit (no more than X parallel operations)

**Comment by aonez** [comment]
I'm sure this will fit you #21, will be one of the firsts things to do after 1.1.0 is released.
