### ISSUE TITLE
Password issue

### ISSUE THREAD

**Issue by docmandave** [aonez/Keka#125]
I really like the Keka interface, but the version I just downloaded from the Apple store has a fatal flaw ... When I drag and drop a file (e.g. Excel document) and create a zip archive with a password, when you double click on the archive, it asks for the password and ANY text you type in will open the archive and give the error message: "Extraction of (zip name) failed. Error code 2 using "p7zip"
Fatal error   

I'm new to Github so apologies if this is posted in the wrong place...

**Comment by aonez** [comment]
The extracted file does actually has content in it? Or it's just an empty fileName.extension file?

**Comment by aonez** [comment]
> I'm new to Github so apologies if this is posted in the wrong place...

Right place! Thanks for taking the time 👍

**Comment by docmandave** [comment]
Yes, the file has content in it. Can I send you a video screencast showing the process?

**Comment by aonez** [comment]
Sure. Or if you can send and example file would be even better.

**Comment by docmandave** [comment]
Ok an update... I ran the process again and Keka produces a file when you input a bad password (with the same name as the original) BUT that file is empty and won't open... So that's good. Just a little confusing. Seems more logical to return 'wrong password' and not create any file. 

Here's a screencast: https://www.dropbox.com/s/qd2vdskmrbkq9g9/KEKA%20PW.mov?dl=0

**Comment by aonez** [comment]
Thanks @docmandave! So that makes more sense... The thing is that Keka extracts what it can, in the case of not having the correct password, it will extract all the structure (folders and filenames). It was asked before, and in a way you're right. But sometimes this blank structure might help...

I can add a preference for this, since most users would not need this structure. In fact I'll add it #126 👍

**Comment by docmandave** [comment]
Thanks @aonez I appreciate the fast replies! 

Personally, if a zip is password protected, I would not want anyone without a password to see any of the info contained within, even the file names, so I would suggest returning nothing as the default output but that's me, the sender talking
