### ISSUE TITLE
How to use Keka as the default decompression tool while keeping the default icon for mac archives

### ISSUE THREAD

**Issue by TinyuZhao** [aonez/Keka#1254]
Keka as the default unzip tool for Mac will change the icons of all the zip packages, all kinds of colors, but I still like the icons of the original Mac zip packages, please tell me how to restore them.

<img width="922" alt="image" src="https://user-images.githubusercontent.com/44396641/235715501-25d4d3aa-c86b-42ec-af6a-a826e144233a.png">

**Comment by Tinyu-Zhao** [comment]
> You should revert the default app to the `Archive Utility` for this to happen.
> 
> 
> 
> 1. Right click/cmd+click on the file to be changed (gz, tar, etc)
> 
> 2. Get Info
> 
> 3. Set `Archive Utility` on the "Open With" section
> 
> 4. Click on "Change All..."
> 
> <img width="377" alt="Screenshot 2023-05-02 at 18 36 05" src="https://user-images.githubusercontent.com/480163/235729263-b033615a-c8d9-43cb-97e5-72832c84bd55.png">
> 
> 

Thanks for your help!
One more question, why do I use the helper to set all the decompression points to Keka, but when I "right-click on the folder and click on the compressed file" I still use the default compression tool, and when I check the compressed file type, I find that the default opening method is to use Keka. .
What should I do to make the default compression method also use Keka?

**Comment by aonez** [comment]
If you mean the default "Compress "..." option in the contextual menu, this one is hardcoded into Finder and can't be used by Keka.

You can use the Keka services or the Finder Extension options, that will appear at the bottom of the contextual menu:

<img width="602" alt="Screenshot 2023-05-02 at 18 52 46" src="https://user-images.githubusercontent.com/480163/235732758-60956e11-cfca-4f98-be62-9f85ff004947.png">

**Comment by Tinyu-Zhao** [comment]
Thank you for your help!
