### ISSUE TITLE
Unsupported MSI executable file

### ISSUE THREAD

**Issue by biolocoo** [aonez/Keka#1255]
### Configuration
OS: Version 12.6.1 (Build 21G217) (arm64)
Keka: v1.2.62-beta.1-r5123 (WEB) (Sandboxed) (en)

Im trying to unzip a .msi file in my Macbook. It seems in every tutorial I read that I should just use Keka but this error continue to appear. I already re download the file 5 times, re download Keka 2 and reset the computer. 

ERROR code 2 
Format detected: Windows MSI
Binary used: keka7zz
Arguments: (
    x,
    "/Users/bioloco_/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Add-Ins.localized/M6-191111-122824.msi",
    "-o/Users/bioloco_/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Add-Ins.localized/M6-191111-122824.kextraction/Operation",
    "-snld",
    "-aou",
    "-xr!__MACOSX",
    "-bsp1"
)

7-Zip (z) 22.01 (arm64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15 : Modified by aone for Keka
 64-bit arm_v:8 locale=en_US.UTF-8 Threads:8, ASM

Scanning the drive for archives:
  0M Scan /Users/bioloco_/Library/Group  . t.localized/Add-Ins.localized/

1 file, 2074112 bytes (2026 KiB)

Extracting archive: /Users/bioloco_/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Add-Ins.localized/M6-191111-122824.msi
  0%
ERROR: /Users/bioloco_/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Add-Ins.localized/M6-191111-122824.msi
Icon._DFD16BE99BC7619651171A.exe
Open ERROR: Cannot open the file as [PE] archive

**Comment by aonez** [comment]
This one is an unsupported MSI executable file.
