### ISSUE TITLE
Another odd LZH from Atari ST

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#1257]
Another odd LZH, from Atari ST

http://discmaster.textfiles.com/file/11869/www.umich.edu.archive.2014.03.zip/www.umich.edu/~archive/atari/Games/Puzzle/nanjin11.lzh

_Originally posted by @gingerbeardman in https://github.com/aonez/Keka/issues/84#issuecomment-1533513040_

**Comment by aonez** [comment]
@gingerbeardman just was taking a look at this file. It has some kind of _Germanish_ wording before an unusual LZH signature.

I'm not sure if this is a variant of the format or just a corrupt one. Do you have any other example from the same site/provider?

**Comment by aonez** [comment]
<img width="557" alt="Screenshot 2023-05-04 at 16 11 06" src="https://user-images.githubusercontent.com/480163/236233500-ec24d25c-5ba9-4885-9b98-585e65f2cb9e.png">

This is what I can parse right now (not extract), removing the extra header info and fixing the LZH signature. But looking at it I can see there should be more contents.

**Comment by gingerbeardman** [comment]
If you browse using DiscMaster you'll see that it was able to parse the whole archive and it's all navigable and human readable,  so it seems to be complete.

Here's a link to a different copy of the same LZH (hash matches):
<http://discmaster.textfiles.com/browse/6694/CCE_PD.iso/pc/1000/CCE_1077.ZIP/CCE_1077/NANJIN11.LZH>

**Comment by gingerbeardman** [comment]
I don't have a working Atari ST setup with LHA/LZH decompressors... but:

Some research:

using `brew install lha` FAIL
```
$ lha x nanjin11.lzh
LHa: Error: Unknown level header (level 46)
```

using `brew install lhasa` GOOD
```
$ lha x nanjin11.lzh
nanjing/nanjing.app	- Melted   :  ooooooooooooooo
nanjing/doku/nanjing.doc	- Melted   :  oooo
nanjing/doku/nanjing.txt	- Melted   :  oooo
nanjing/guide/nanjing.hyp	- Melted   :  oo
nanjing/guide/nanjing.ref	- Melted   :  o
nanjing/nanjing.upl	- Melted   :  o
```

MacLHA on Macintosh System 7.5 complained but was able to extract it all.

![Screen shot 2023-05-04 at 17 42 59](https://user-images.githubusercontent.com/49612/236270355-e7b317ee-9e66-4fc1-b130-db30ef173674.png)

![Screen shot 2023-05-04 at 17 41 52](https://user-images.githubusercontent.com/49612/236270348-4fd13b87-24a6-4157-af8e-37acc1be7bce.png)

**Comment by gingerbeardman** [comment]
> I'm not sure if this is a variant of the format or just a corrupt one. Do you have any other example from the same site/provider?

Other fails from this folder: http://discmaster.textfiles.com/file/11869/www.umich.edu.archive.2014.03.zip/www.umich.edu/~archive/atari/Games/Puzzle/

![Screen shot 2023-05-04 at 18 00 43](https://user-images.githubusercontent.com/49612/236274528-f80bbe32-a21a-4b30-8b75-1d168a79a52e.png)

**Comment by aonez** [comment]
Ok my bad, I was overlooking the extra header info. It actually is a comment, starting with `-com-` ending with a NULL byte and followed by the proper signature `-lh5-`:

```
-com-Nanjing 1.1, 12.12.1994, Shareware eingeschrnkt, ein PiaG-Spiel
Bei Nanjing mssen 72 Steine, die sich durch Motiv und/oder Farbe
unterscheiden, auf ein 12 mal 8 Felder groes Spielfeld plaziert
werden. GEM-Spiel, lauffhig als Accessory oder Programm.
Neu: 4-Steine-Regel gelockert, weniger Einschrnkungen)*-lh5-
```

Just removing the comment helps:
[nanjin11_nocomment.lzh.zip](https://github.com/aonez/Keka/files/11399762/nanjin11_nocomment.lzh.zip)

I'll check all the comment specifications (if I found them) to fix it properly.

**Comment by gingerbeardman** [comment]
Cool! Thanks.

Interestingly, the other fails are all -lh1- with no comment that I can see.

**Comment by aonez** [comment]
> Interestingly, the other fails are all -lh1- with no comment that I can see.

Will check those, probably are older since the compression method 1 was used instead of the 5.

**Comment by aonez** [comment]
Also implemented the detection and proper parsing of the commented file in the build above.
