### ISSUE TITLE
[BUG] RAR extraction issue probably caused by quarantine

### ISSUE THREAD

**Issue by delfireinoso** [aonez/Keka#1258]
### Configuration
- Keka version: [1.2.62-beta.1 (5123)]
- macOS version: [13.3.1 (a) (22E772610a)]

### Describe the bug
Keka is unable to uncompress some RAR files

it's impossible to generat a log on uncompressing

### To Reproduce
in the finder open the context menu open with 'keka' 

### Expected behavior
some rar files are not uncompressed at all

**Comment by aonez** [comment]
Do the same files fail with the current stable version 1.2.61? If so, ca you provide a file that replicates the issue? A link to download it will also work. You can also sends it to info@keka.io.

**Comment by delfireinoso** [comment]
As soon as I’m near the computer you’ll have it It s a .rar type of files It happens with all current versionsUnarchiver fails too, but I’ve managed to uncompressed them Perhaps it’s not a bug but a new file type Delfí ReinosoEl 4 maig 2023, a les 23:34, aONe ***@***.***> va escriure:﻿
Do the same files fail with the current stable version 1.2.61? If so, ca you provide a file that replicates the issue? A link to download it will also work. You can also sends it to ***@***.***

**Comment by delfireinoso** [comment]
I’ve made some tests

The problem it’s possibly mine.


I’ve bought a new Mac mini. Some rar files are not open with KEKA on the Mac disk, but the same files are open on any external APFS disc

The files are actually open on the main disc if I edit the name, anything is valid, one dot or one space

So perhaps is something on a new installation of Ventura on a new Mac, but is annoying

**Comment by aonez** [comment]
What error does Keka report?

**Comment by delfireinoso** [comment]
Nothing The app doesn’t close leaves a compression window to seeAnd the finder icon of the file it’s closed I’ll send you with wetransfer one of such filesIt’s not a hoax I have CleanMyMac running and doesn’t detect it as malware Delfí ReinosoEl 5 maig 2023, a les 15:07, aONe ***@***.***> va escriure:﻿
What error does Keka report?

**Comment by aonez** [comment]
Si tens més info ja diràs :)
