### ISSUE TITLE
[BUG] Cant unpack .rar archive and stuck

### ISSUE THREAD

**Issue by Drovosek01** [aonez/Keka#1277]
### Configuration
- Keka version: 1.3.0 (5194)
- macOS version: 13.4.1 M1

### Describe the bug
Just download and run Keka app then drag and drop ~700 MB .rar archive into Keka window and Keka stuck. I wait 10 minutes then force quit Keka.

### To Reproduce
1. Open Keka app
2. Drag and drop  .rar file that below
3. Wait
4. Keka will not respond

### Expected behavior
I expect that Keka without problem unpack

### Screenshots
-

### Additional context
File CSoft SPDS GraphiCS 2023 v23.0.3744.rar - https://www.dropbox.com/s/d0rgnekvcjv3x4n/CSoft%20SPDS%20GraphiCS%202023%20v23.0.3744.rar?dl=0

**Comment by Drovosek01** [comment]
Same problem for this .rar file - https://cloud.mail.ru/public/mmHq/BygPbycbG

**Comment by aonez** [comment]
Looking in to it

**Comment by aonez** [comment]
This only affects RAR extraction but goes into an infinite bucle (that's the reason you need to Force Quit). It never starts the RAR extraction.

Already fixed: https://github.com/aonez/Keka/releases/tag/v1.3.1
