### ISSUE TITLE
Keka RAR Extract is 20% Slower than The Unarchiver

### ISSUE THREAD

**Issue by greensquarter** [aonez/Keka#1280]
### Configuration
- Keka version: [1.3.1]
- macOS version: [13.4.1]

### Describe the bug
Extracting a RAR file is taking 20% longer compared to The Unarchiver

### To Reproduce
1. Extract RAR file
2. Wait for extraction to complete

### Additional context
Apple M2 chip.

**Comment by aonez** [comment]
Running Keka v1.3.1 no macOS Ventura 13.4.1, M2.

In my tests with a 7.47GB sample RAR containing `iOS_17_beta_2_Simulator_Runtime.dmg`:

- `Keka` extracted it in `25 seconds`.
- `The Unarchiver` extracted it in `1 minute and 32 seconds`.

![Keka-TU-RAR](https://github.com/aonez/Keka/assets/480163/0e6e2cb0-9130-4028-9c8f-28c758d90cbd)

So in my tests **Keka takes 1/4 of the time** that The Unarchiver takes.

Can you provide a sample or a test case that reproduces your statement?

**Comment by aonez** [comment]
Please reopen if you have a way to replicate this.
