### ISSUE TITLE
[BUG] DMG compression integrity verification fails

### ISSUE THREAD

**Issue by Piipperi** [aonez/Keka#1282]
### Configuration
- Keka version: 1.3.1 (5197)
- macOS version: 13.4.1 (22F82)

### Describe the bug
DMG compression integrity verification fails with the following errors:

ERROR: Unsupported Method : 0.ddm
ERROR: Unsupported Method : 1.Apple_partition_map

ERROR: Unsupported Method : 2.hfs

[Keka_2023-07-04-194343394.log](https://github.com/aonez/Keka/files/11951235/Keka_2023-07-04-194343394.log)

### To Reproduce
1. Choose DMG for the file format.
2. Set format to "ULMO (LZMA)" and check the "Verify compression integrity" option.
3. Drag a folder into the window to start the compression.
4. After the compression is complete, it fails with the integrity verification.

### Expected behavior
I'd expect it to not fail unless the file actually didn't pass the verification.

**Comment by aonez** [comment]
Indeed, also `UDRW` fails. Thanks a lot for the tip, will look into it.

**Comment by aonez** [comment]
Aso password protected DMG fail 🫠

**Comment by aonez** [comment]
Fixed in this build: https://d.keka.io/test/Keka-v1.3.2.r5203

The final release will be in a few days. Thanks again for the feedback @Piipperi.

**Comment by aonez** [comment]
Just released it, one more time thanks a lot for the feedback @Piipperi 👍🏼
