### ISSUE TITLE
[BUG] Password protecting folders is not working

### ISSUE THREAD

**Issue by jodriscoll** [aonez/Keka#1284]
### Configuration
- Keka version: 1.3.1
- macOS version: 13.4

### Describe the bug
I've set the password to something generic `testing123` and repeated it (green checkmark), then compressed it (ex: 7z) and when I attempt to extract the folder, it constantly asks for the password (although I've typed it correctly).

### To Reproduce
1. Open Keka, enter the password (and repeat it)
2. Drag+Drop the folder into Keka
3. Compress the file
4. Attempt to open the compressed file generated by Keka

### Expected behavior
I should enter the password that I entered, and it should extract the files accordingly and NOT continue to prompt me.

### Additional context
The "Encrypt filenames" and "Solid archive" are auto-selected in Keka. Also, "Exclude Mac resource forks" is the only thing selected below the "Method" group box within Keka. I also have "Slow" chosen for the most compression, with "7z" being the compression file type of choice. This was the sole purpose I purchased the software, and it doesn't appear to work (unless I'm a knucklehead!).

**Comment by aonez** [comment]
Probably #477.

Please check you're opening the compressed file with Keka since macOS Ventura tends to ignore the default extraction app and tries to open the files with its bundled extraction tool and it does not support AES256 (thus asks for the password again).

To be sure you're opening the file with Keka drop it to its window/icon or do a right click - Open With - Keka.

Let me know if that's not the case and it's something else.

**Comment by jodriscoll** [comment]
To confirm, are you saying that for colleagues/friends to open this file, they must also purchase+own Keka?

I was not expecting that to be a requirement if so.

**Comment by jodriscoll** [comment]
Okay.

So, if I choose "ZIP" (instead of "7Z"), I see the AES-256 encryption checkbox (within the "Method" group box) that is currently unchecked. If I then enter the "Password" and compress the file in question, the password appears to work when a user attempts to extract it.

However, if I choose "7Z" (instead of "ZIP"), I do not see the AES-256 encryption option, and the password I entered isn't working (with the default macOS extraction) unless I use Keka to extract it.

Is this the correct summary?
- If you're not using Keka to extract a 7Z-password-protected file, the default macOS extraction tool fails to validate the password chosen within Keka (unless you use Keka to extract it) during compression.
- If you password-protect a ZIP with Keka (without selecting AES-256), the password entered validates with the default macOS extraction tool and doesn't require Keka.

**Comment by aonez** [comment]
Indeed. Apple only supports AES128 in 7Z, which is less secure. Also uses the legacy ZIP encryption.

As stated any other third-party app (The Unarchiver for example) supports AES256.

**Comment by aonez** [comment]
I might try to implement AES128 if needed, even if AES256 is recommended.

**Comment by jodriscoll** [comment]
Thanks for the clarification. I'll close this now.
