### ISSUE TITLE
Inconsistent archive identifiers

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#129]
Currently all archive formats in prefs are capitalised and inconsistent in whether they describe the format or show the file extension when compared to the icons.

I think the identifiers in the app should reflect those in the icons: all uppercase. 

Or vice versa, given that file extensions are always lowercase, but then the icons would need reworking. The problem with lowercase is that lz is easily distinguishable as LZ (it could be capital i, z).

Currently:
![screen shot 2018-01-25 at 11 12 20](https://user-images.githubusercontent.com/49612/35385575-a3b85412-01c0-11e8-9592-b0db0c21ac21.png)

Proposed, echoing the icons:
7Z
ZIP
TAR
GZ
BZ2
XZ
LZ
DMG
ISO

using: Keka 1.1.0-beta.5

**Comment by aonez** [comment]
Uppercase coming on next release 👍
