### ISSUE TITLE
Legal support for the project

### ISSUE THREAD

**Issue by RichardoC** [aonez/Keka#13]
Have the legal issues been resolved? If so can the source code be added to this github repo?

Thanks

**Comment by aonez** [comment]
Still no legal support for this project. Anyone willing to help will be welcome.

**Comment by magicgoose** [comment]
the link in readme http://trac.kekaosx.com/ticket/14 is dead.
so, what's the trouble?

**Comment by RichardoC** [comment]
@magicgoose What's the issue?

**Comment by magicgoose** [comment]
Yeah, that's what I'm trying to say too

**Comment by philipp-r** [comment]
It do not think that the Free Software Foundation will be able to help since they only publish the license text.
You should probably contact the developers and Apple and send them a cease and desist letter. Maybe you can claim for damages. best is to contact a lawyer for copyright law or maybe a legal clinic where you can get free legal service. 

You could also submit a dispute here which should be easier and faster: <https://www.apple.com/legal/internet-services/itunes/appstorenotices/>

**Comment by magicgoose** [comment]
btw, if you decide to send some letters, etc, remember to save the texts you write, because you might want to reuse them in future when some other _bad person_ repeats the crime.

**Comment by magicgoose** [comment]
>It do not think that the Free Software Foundation will be able to help since they only publish the license text.

this is not true, they did involve into resolving GPL violation issues in the past and it's trivial to find on the Internet.

**Comment by philipp-r** [comment]
@magicgoose  Okay, found this. They can offer assistance 🙈
> This means that only the copyright holders are empowered to act against violations. The FSF acts on all GPL violations reported on FSF copyrighted code, and we offer assistance to any other copyright holder who wishes to do the same.
<https://www.gnu.org/licenses/gpl-violation.en.html>


But since Keka uses p7zip, unrar and some other open source software I suppose you are required to publish the source code to not infringe their copyrights. 😉

**Comment by magicgoose** [comment]
open source doesn't imply GPL though.
p7zip is LGPLv2, so it just requires that user may replace it with different version manually or something like that.
but unrar https://en.wikipedia.org/wiki/Unrar looks like GPL 😉

**Comment by xverges** [comment]
As far as I see,
1. Keka was GPL software. Thus, everyone was entitled to copy it as long as it remained GPL
2. Someone copied it and placed it on the app store, without respecting the GPL terms
3. Keka has been proprietary software for the last 6 years, listing itself as GPL on sourceforge

In my opinion,  the last point does not put you in a better position to deal with point 2 or to have your work properly credited, or to increase your user base.

**Comment by magicgoose** [comment]
@aonez I think it's the right time to come out and answer to all the uncomfortable questions, or admit that Keka is officially proprietary now (in which case I will stop using it)

**Comment by d235j** [comment]
@aonez are there any plans to release Keka as open source? It looks like it uses GPL code and therefore cannot be proprietary, regardless of what others do with the source code.

**Comment by aonez** [comment]
Nothing has changed since 2011 on this matter. No source will be available until this can be handled properly, I don't want to repeat that situation ever again. Sorry for the inconvenience.

**Comment by magicgoose** [comment]
@aonez What have you tried so far?

**Comment by gingerbeardman** [comment]
Hi

I used to work at Apple and would often file requests for takedowns of "lazy clone apps" where open source had been recompiled with a different name and was being sold. It was just par for the course.

I can put you in touch with a legal guy who owes me a favour though i'm not sure what outcome you are trying to achieve.

Get in touch privately if you have any thoughts.

**Comment by davidhealey** [comment]
Isn't Keka violating the GNU GPL by including GNU GPL code but not releasing its own source code?

**Comment by gingerbeardman** [comment]
Are you asking a question to which you already know the answer?

**Comment by aonez** [comment]
> 3\. Keka has been proprietary software for the last 6 years, listing itself as GPL on sourceforge

@xverges The sourceforge page is not maintained for a long time now. You have there 0.X source.

@davidhealey this was asked before, you can redistribute GPL binaries if their source code is available. All source code of the binaries used in Keka are available.

There're no plans for opening the source code anymore.
