### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JuanCab** [aonez/Keka#1308]
### Configuration
- Keka version: 1.3.2 (5208)
- macOS version: 13.5

### Describe the bug
Even through I have ZIP set up in the preferences to exclude MacOS resource forks, a '__MACOSX' file is created upon uncompression of the zip file produced on a linux system

### To Reproduce
1. Select folder to be compressed via contextual menu (Keka > Compress here)
2. Transfer ZIP file produced to Linux server via SSH
3. Issue unzip command, find __MACOSX folder created at same level as parent folder.

### Expected behavior
I had expected this __MACOSX folder to not be created since I had selected to exclude MacOS resource forks (is it not part of that HFS file structure).  If this is NOT a bug, that is fine, I just assumed this was the desired behavior.  If not, can an option to exclude it be added?

**Comment by JuanCab** [comment]
Wierd, now I can't seem to reproduce it.  It might have been a foul up on my part, using some other compressor, but I followed my own steps with the same files and can't reproduce.  If it happens again I will try to capture the actual files triggering the problem.

**Comment by aonez** [comment]
No problem at all. Most probably you used the macOS default compression option that does include that folder.

Anything else don’t hesitate to ask.
