### ISSUE TITLE
[BUG]The compressed file in 7z format cannot be decompressed after setting a password

### ISSUE THREAD

**Issue by zhaiduting** [aonez/Keka#1309]
### Configuration
- Keka 版本 1.3.2 (5208)
- macOS 13.5 (22G74) Apple M2 Pro

### Describe the bug
压缩成 zip 格式的文件设置密码时没有问题，可以正常解压。但是压缩成 7z 格式时却不能设置密码，因为设置密码后无法解压缩，即使密码正确也解压不了。我今天刚刚花了38元购买的 Mac App 就发现了这个问题，不开心

**Comment by zhaiduting** [comment]
There is no problem when setting a password for a file compressed into zip format, and it can be decompressed normally. However, you cannot set a password when compressing into 7z format, because you cannot decompress after setting the password, even if the password is correct, you cannot decompress. I just found this problem in the Mac App I bought for 38 yuan today, not happy

**Comment by aonez** [comment]
Please be sure you’re opening the file with Keka and not the default macOS extraction tool since it does not support AES256 encryption:

https://github.com/aonez/Keka/issues/477

Keka (as many other third party tools) use that advanced and open encryption standard.

**Comment by aonez** [comment]
Please let me know if that solves the issue for you and sorry for any inconveniences.

**Comment by zhaiduting** [comment]
> Please be sure you’re opening the file with Keka and not the default macOS extraction tool since it does not support AES256 encryption:
> 
> #477
> 
> Keka (as many other third party tools) use that advanced and open encryption standard.

Thanks a lot for your pointers, I now know why. It turned out that when I double-clicked the 7z file, the Mac used the system’s built-in decompression tool to open it. When I changed it to keka to open it, I could indeed decompress it successfully.

**Comment by aonez** [comment]
Thanks @zhaiduting. Also note that macOS Ventura and newer tend to ignore if you set Keka as the default handler for ZIP files, so in the future this may happen for you again.
