### ISSUE TITLE
[BUG] Update from 1.3.2 to 1.3.3 fails due to signing issue

### ISSUE THREAD

**Issue by pro-sumer** [aonez/Keka#1313]
### Configuration
- Keka version: 1.3.2 to 1.3.3
- macOS version: macOS Ventura 13.5.1

### Describe the bug

Update error:
```
The update is improperly signed and could not be validated. Please try again later or contact the app developer.
```

### To Reproduce
1. Open Keka 1.3.2
2. Select "Check for updates"

### Expected behavior
Keka 1.3.2 updates to 1.3.3, without issues.

### Screenshots
![keka](https://github.com/aonez/Keka/assets/44335102/27ce9bea-a939-4101-9039-20d0b3fb7ef2)

### Additional context
* Same/similar error when updating via [MacUpdater](https://www.corecode.io/macupdater/)
* Manual install of 1.3.3 [DMG](https://github.com/aonez/Keka/releases/download/v1.3.3/Keka-1.3.3.dmg) from [GitHub Releases page](https://github.com/aonez/Keka/releases) works fine

**Comment by aonez** [comment]
I've just checked and worked on my end. Will do some more tests and republish if needed.

**Comment by aonez** [comment]
Thanks a lot for the feedback @pro-sumer.

I've now reproduced the issue but when updating with no delta (from 1.2.61 or earlier). Could you please verify again if it fails for you when updating from 1.3.2?

**Comment by aonez** [comment]
Turns out the ZIP package was corrupt. Uploaded it again and tested it works. Thanks again for the tip.
