### ISSUE TITLE
[BUG] integrity check fails with wrong filename if create archive with divide and custoname options

### ISSUE THREAD

**Issue by nakayama900** [aonez/Keka#1319]
### Configuration
- Keka version: 1.3.3 (5230)
- macOS version: 13.4.1 (c) (22F770820d)

### Describe the bug

check integrity with wrong filename when using division and custom name.

for example, when 'basename.7z.001' created, keka checks 'basename.001' and fail to check

### To Reproduce

1. Go to '設定'(Config)
2. Click on '圧縮'(archive)
3. Change '保存先の場所'(Save path) to '常に確認'(check always)
4. Compress to 7z with division
5. See error

[Keka.log](https://github.com/aonez/Keka/files/12481508/Keka.log)

### Expected behavior

check correct filename, and no error

### Additional context

I also used option as solid compress, don't include resource folk, trash original file and compress rate: low

**Comment by aonez** [comment]
This was in fact already fixed in this build: [Keka-v1.3.5.r5257](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.3.5.r5257.7z)

**Comment by aonez** [comment]
@nakayama900 Keka 1.3.5 public release is now live. Thanks again for the feedback 🫶
