### ISSUE TITLE
Finder Extension not showing in iCloud folders

### ISSUE THREAD

**Issue by Kamik423** [aonez/Keka#1327]
### Configuration
- Keka version: 1.3.3 (5230)
- macOS version: 14.0 Beta (23A5337a)

### Describe the bug

In macOS Sonoma the Keka options only show up in the *Services* submenu for Finder right clicks.

**Comment by Kamik423** [comment]
So apparently this just happens in iCloud Drive, not however in *~/Library*. Here is a log, although I doubt it'll be useful

```
2023-09-11 18:43:19.529 Dev mode enabled
2023-09-11 18:43:19.530 READER: Dev reader mode enabled
2023-09-11 18:43:19.530 NOTIFICATION: Dev notifications mode enabled
2023-09-11 18:43:19.531 Running on OS X/macOS version 14.0 (Build 23A5337a) (arm64)
2023-09-11 18:43:19.531 Running sandboxed Keka (WEB) version 1.3.3 (5230)
2023-09-11 18:43:19.532 Used localization: en
```

**Comment by aonez** [comment]
Sorry for the inconvenience @Kamik423.

This is a limitation on how the Finder Extensions work. Currently Apple only allows one extension running at a path, and it is a first arrives rule. Since the iCloud folder has an Apple's Finder Extension and it is loaded on boot or login, third party extensions can't be loaded there.

Maybe Apple will remove this limitation in the future but that is unlikely at the moment.

The development of Actions instead of the Finder Extension in Keka might come in the future and may be a workaround for this issue, but this is a yet unknown path right now.

**Comment by Kamik423** [comment]
But in other places I can have multiple Finder Extensions running at the same time. Also is this a new issue in Sonoma?

**Comment by aonez** [comment]
> But in other places I can have multiple Finder Extensions running at the same time

This is new behaviour for me. Can you attach an screenshot showing multiple extensions appearing/running in a folder?

> Also is this a new issue in Sonoma?

Not new to Sonoma. Been having issue with that since the introduction of the Finder Extensions in 2020.

**Comment by Kamik423** [comment]
<img width="859" alt="Screenshot 2023-09-11 at 19 06 59" src="https://github.com/aonez/Keka/assets/16278233/8023bb7b-9eee-4926-aae1-8dc76248f416">

*Compress with Keka* is obviously Keka, *New File* is my own Finder Extension.

**Comment by Kamik423** [comment]
I had two more apps with Finder extensions that I had turned off. It can go to at least four apparently ¯\\\_(ツ)\_/¯

**Comment by aonez** [comment]
That's new for me. I your extension set as a `FinderSync`?

Anyway I understand yours is also not showing in iCloud?

**Comment by Kamik423** [comment]
No extension is working in iCloud Drive for me. Yes it is an `FIFinderSync`. For me `override func menu(for menuKind: FIMenuKind) -> NSMenu?` is just not being called inside iCloud Drive. I had hoped, that you would have found a solution. Keka is an app I use daily and all my data is in iCloud Drive.

**Comment by aonez** [comment]
Sadly I did not found any solution really, and did extensive tests and tries. Also had issues running concurrently with other extensions #898 #913.

I know they're not the same, but you can still use the Services.

**Comment by nicfab** [comment]
I have the same issue.
Please let us know if there is a solution. Otherwise, I will choose another app.

**Comment by aonez** [comment]
@nicfab next version will have the menu in the Finder toolbar so can be used on places where the contextual menu if not possible. Coming next Tuesday.

<img width="979" alt="Screenshot 2023-10-06 at 19 06 58" src="https://github.com/aonez/Keka/assets/480163/a10a09c0-58da-4394-83d4-e5ef2aabc410">

**Comment by nicfab** [comment]
Thank you very much. 
I'll wait for it.

**Comment by Kamik423** [comment]
As stated above, I have the same issue in my app, so I burned one of my Technical Support Incidents (TSI) for this year and I got this response:

> Hi,
> 
> SO, let me start by providing some background and context.  TheFinderSynce extension point was never intended to provide a generalmechanism for extending the Finder.  It was specifically designed tohelp cloud storage application (for example, "Dropbox") provide a betteroverall user experience when interacting with "their" content... andbasically ONLY that.
> 
> Indeed, the general behavior you're describing here:
> 
> "Now this functionality is broken. It only shows up on paths like <working path> but not in anything <other paths that fail>"
> 
> ...has basically ALWAYS been true, though the details of exactly which paths fail vary between systems.  For example, the "Applications" directory didn't work correctly after we divided the system partition in macOS 10.15 and I believe that's still true today.
> 
> More broadly, the Finder Sync extension point was designed around the assumption that any given directory would only have a single backing extension, which means nested extensions have never really worked correctly.  Typically the "closest"/more specific extension ended up taking "ownership" (which is why "broad" users didn't break more things), but the system has never been particularly reliable or robust.
> 
> That leads to here: "... not in anything in iCloud Drive like my desktop or documents directories."
> 
> To be honest, I wouldn't have expected that to ever work.  iCloud Drive should have been the owning extension point, which should have superseded yours.  I'm not sure why your particular configuration worked in the past, but that general answer here is that I would not expect the one FinderSync extension to work "inside" a directory controlled by another cloud storage provider, particularly as the system moves away from Finder Sync extensions in favor of Replicated File Providers.
> 
> I'm afraid the only recommendation I can offer here is to file an enhancement request asking for the system to introduce a new extension point that provides the kind of broad support it sounds like you're looking for:
> 
> http://feedbackassistant.apple.com
> 
> -(Name redacted for GitHub)
> 
> ____________
> (Name redacted for GitHub)
> DTS Engineer, CoreOS/Hardware

I will still pursue this some further, but I don't think that much will come of it.

**Comment by aonez** [comment]
@Kamik423 indeed, that was the purpose of those extensions since the beginning. That's why I was surprised you had more than one working.

Maybe they'll change the behaviour in the future or actions will be our best bet. I'm already using actions on iOS and work flawlessly.

**Comment by aonez** [comment]
Keka 1.3.5 just released.
