### ISSUE TITLE
[BUG] Error code 1 using when unpacking 7z archive 23.01

### ISSUE THREAD

**Issue by Drovosek01** [aonez/Keka#1337]
### Configuration
- Keka version: 1.3.4
- macOS version: macOS Monterey 12.6.8 Intel

### Describe the bug
I made .7z archive using 7-zip application v23.01 on Windows 10.
When I try unpack this archive on macOS - I got error
When I try unpack it on Windows 10 using 7-zip it open and unpack without problems.

Here link to archive - https://mega.nz/file/tmcC3ABJ#a6Cpr-Y7CrwQP_5iGMdrNjIO-ntc2D2sHyC04fN2O4c

**Comment by aonez** [comment]
Can you try with the earlier version 1.3.3:

https://github.com/aonez/Keka/releases/tag/v1.3.3

**Comment by Drovosek01** [comment]
> Can you try with the earlier version 1.3.3:
> 
> https://github.com/aonez/Keka/releases/tag/v1.3.3

I tried now and archive unpacked without problems o_0

Thank you for tip but it look strange

**Comment by aonez** [comment]
I'm on the move right now so can't test, but most probably is the new codec in 7Z 23.01 that compresses Windows ARM64 binaries. I've implemented that version on 1.3.3 but has a big and reverted to 22.01 o. 1.3.4.

**Comment by aonez** [comment]
This is fixed in 1.3.5, to be released next Tuesday 10th. Thanks again @Drovosek01!

**Comment by aonez** [comment]
Keka 1.3.5 public release containing this fix is now live. @Drovosek01 thanks again for the feedback :)
