### ISSUE TITLE
"unknown error" error code 1 using kekatar unarchiving .tar.gz

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#134]
[the .tar.gz files are here](http://www.rendezvo.us/snesmini/)

![screen shot 2018-02-05 at 00 39 18](https://user-images.githubusercontent.com/49612/35784264-7ef36fb8-0a0d-11e8-940e-4112fb301164.png)

**Comment by aonez** [comment]
They get extracted, but there's some problem creating "dev/console". It seems like a malformed alias...

**Comment by aonez** [comment]
I've tried with other extractors and all get an error or create an empty dev/console file. Maybe I can enhance the error message to show the specific information about the error.

**Comment by gingerbeardman** [comment]
I extracted them fine without errors using The Unarchiver.

**Comment by aonez** [comment]
The Unarchiver dismisses the warning and just creates an empty file for dev/console. The result is the same but you don't know that dev/console is not what probably was before getting packed.

**Comment by gingerbeardman** [comment]
Indeed, I spotted that after commenting.

`/dev/console` should be non-empty

`crw-------    1 root     root        5,   1 Jan  1 10:29 console`

**Comment by aonez** [comment]
My guess it was another alias 👍

**Comment by gingerbeardman** [comment]
interestingly I also cannot get directory listing over FTP of that location

thanks!
