### ISSUE TITLE
Always/Never create a root folder on extraction

### ISSUE THREAD

**Issue by digitall-it** [aonez/Keka#135]
Ability to mimic Winrar, Winzip, The Unarchiver's ability to decompress a set of files to a folder named like archive, for example
```
./a.zip => ./a/
./b.zip => ./b/
./c.zip => ./c/
```

To do notes:

- [x] Add behaviour to always create a root folder named like the archive (**fixed in v1.2.0**)
- [ ] Add behaviour to never create a root folder
- [ ] Add dropdown in Preferences to choose from "Always/Automatic/Never" create the root folder
- [x] Use this option in the context menu items (**fixed in v1.2.0**)

**Comment by aonez** [comment]
Currently if the compressed file contains two or more elements, the extraction is automatically created in a folder named with the archive filename. Is not that what you're asking for?

**Comment by digitall-it** [comment]
First, allow me to thank you for the wonderful software.
Second, the behaviour is unpredictable, because a.zip may contain two folders, b.zip may contain only one, and so on. The single folder may be named like another folder that already exists, like "contents".

A feature proposal is to implement a dropdown in the preferences where the logic can be chosen:
1. Always create a subfolder
2. Create a subfolder if the compressed file contains two or more elements (current behaviour)
3. Create a subfolder except in the case the compressed file contains a single element called like the zip file (for example. a.zip contains a folder called a)
4. Never create subfolders


Sometimes I download hundreds of files and discover that either some information about the original structure is lost or duplicated.

A. Case the information is lost:
theme_red.zip contains an element of type folder called public_html, which contains files
theme_blue.zip contains an element called public_html, which contains files

I want the structure to be theme_red/public_html/* and theme_blue/public_html/*. Otherwise I will not know which is which.

B. Case the information is duplicated:
fish.zip contains an element called of type folder called fish, which contains files
bird.zip contains an element called of type folder called bird, which contains files

I want the structure to be fish/* and bird/*. I find instead fish/fish/* and bird/bird/*.

I currently use The Unarchiver, but Keka works where the former stops, to prevent case A from happening. I manually deduplicate all B cases (sometimes it takes days if I got thousands of nested folders).

**Comment by aonez** [comment]
Thanks interesting, thanks for the time taken.

I would reduce the options to:

1. Always
2. Automatic, current behaviour
3. Never

And give the ability to customize context menu items that use any of those. The later option will be harder to implement, so maybe I'll do this enhancement in two times, adding first 1 and 2, and then in a separate version the 3 option.

**Comment by aonez** [comment]
I've implemented the main topic in #333. Will come in the next beta release of the 1.2.0 version.

The other option to never create a folder will come in the future :)

**Comment by digitall-it** [comment]
That’s nice! Thank you! That’s the only thing that prevented me to use Keka as the main decompressor.

**Comment by aonez** [comment]
![Screenshot 2020-06-08 at 11 51 09](https://user-images.githubusercontent.com/480163/84016993-61341c80-a97e-11ea-8024-bce810270bb4.png)

**Comment by aonez** [comment]
I'm closing this one in favor of #72, since "Never create intermediate folders" is the only option missing. Thanks again @digitall-it!
