### ISSUE TITLE
[BUG] Un-sandboxing Keka break work Keka

### ISSUE THREAD

**Issue by Drovosek01** [aonez/Keka#1355]
### Configuration
- Keka version: 1.3.5 (5269)
- macOS version: 12.7 (21G816) Intel

### Describe the bug
Recently I noticed that when unpacking 7z archives using Keka (archives were also created using Keka) all unpacked files have a quarantine flag.
Here is a links to discuss this situation:
https://github.com/aonez/Keka/issues/544
https://github.com/aonez/Keka/issues/405

I executed the command as it is written here so that Keka does not work in the sandbox and so that the quarantine flag is not added
https://github.com/aonez/Keka/wiki/Rar-compression#un-sandbox-keka
`codesign --force --deep --sign - /Applications/Keka.app`

Now when I try to create or unpack any archive, I get error 4.
```
Error code 4 using "7zz"
Attempt to modify an archive previously locked
```

How can I prevent of adding a `com.apple.quarantine` attribute when Keka is running?

**Comment by Drovosek01** [comment]
This is my mistake.
I executed command `sudo codesign -f -d -s - /Applications/Keka.app` and thought it was the same as command `sudo codesign --force --deep --sign - /Applications/Keka.app` just with shortened arguments for quick writing.

After executing the `sudo codesign --force --deep --sign - /Applications/Keka.app` command, everything works without problems and the quarantine attributes are not added.
Thanks again for the cool archiver!

**Comment by aonez** [comment]
Glad to hear that @Drovosek01!
