### ISSUE TITLE
[REQ] Don't keep icon in recent Dock items

### ISSUE THREAD

**Issue by mreid-tt** [aonez/Keka#1360]
### Is your feature request related to a problem? Please describe
When I launch Keka the icon appears in the dock but when I quit the app, the app remains in the recent apps section.

### Describe the solution you'd like
I would like to have the app behave similar to the built-in Archive Utility which shows only when running but disappears when quit.

### Describe alternatives you've considered
An alternative is to just not appear in the Dock at all like those apps which appear as a menu app.

### Additional context
I realise that this is a mostly cosmetic issue but would appreciate if it can be looked into.

**Comment by aonez** [comment]
Thanks for your feedback @mreid-tt. I have some questions first:

1. In my tests, the Archive Utility does run as a normal app and leaves an icon in the recent apps. Do you mean when compressing using the Finder contextual menu?
<img width="317" alt="Screenshot 2023-11-09 at 11 58 11" src="https://github.com/aonez/Keka/assets/480163/2712ed38-8116-4d15-8aa7-5a55c2139852">

2. Do you usually launch Keka to do some compressions using the advanced window or do you use Keka with the Finder Extension, to directly compress or extract files, not using the advanced window?

Thanks again for the feedback. I'm already testing this behaviour, I remember trying this in the past and finding some caveats .

**Comment by mreid-tt** [comment]
Hi @aonez, thanks for getting back to me. I'm attaching a video below showing the differing icon behaviour between Archie Utility and Keka which may help...


https://github.com/aonez/Keka/assets/943378/e89539bf-1f05-4496-825a-4ee9cb863e1a

I'm running macOS Sonoma 14.1.1 on an iMac 24-inch, M1, 2021.

**Comment by aonez** [comment]
I see. It seems the Dock only retains applications that are in the main `/Applications/` folder. If you move Keka to the Applications folder of your user `/Users/YOURUSER/Applications/` or any other folder the icon is not retained in the Dock. The Archive Utility is very deep in the file system that's why it is not retained.

So as a workaround you can move it elsewhere. Anyway I'll test the behaviour of launching it without an icon (as a customizable option).

**Comment by aonez** [comment]
This is a quick test build that only shows the icon in the Dock if you open Keka with no action, so it will not show the icon if you operate like in your video: https://d.keka.io/test/Keka-v1.4.0-dev.r5296

**Comment by mreid-tt** [comment]
> This is a quick test build that only shows the icon in the Dock if you open Keka with no action, so it will not show the icon if you operate like in your video: https://d.keka.io/test/Keka-v1.4.0-dev.r5296

Thanks for this. You are correct that it shows no icon at all. See video below. I'm not sure this would be something that most folks would like though as some feedback is nice.

https://github.com/aonez/Keka/assets/943378/fb14fe5e-089f-4ee4-afa8-091839a6937c

**Comment by aonez** [comment]
I'll definitely implement this as an opt-in option in the Preferences, not the default. Will play nice with #1331.

**Comment by mreid-tt** [comment]
Hmm, I guess there is no way to treat it like a utility that only shows the icon while it is running and disappears afterwards? Alternately, could there be some other feedback like a menubar icon or something to show it's doing something? No feedback may be a bit unnerving.

Also did you note in my video the extracted file was placed in the next new icon position on my desktop rather than right next to the archive like what Archive Utility does? This may be another way to get the user's attention that something has happended.

**Comment by aonez** [comment]
> only shows the icon while it is running and disappears afterwards

Tried it. If it appears once (and its in the Applications folder) it stays even if its no more used.

> Also did you note in my video the extracted file was placed in the next new icon position on my desktop rather than right next to the archive like what Archive Utility does? This may be another way to get the user's attention that something has happended.

Tried this years ago with no success. Sandboxing makes it harder to accomplish.

I think this is a good first implementation (adding the customization in the Preferences).

**Comment by aonez** [comment]
This build has the proper options in `Preferences` - `Appearance`:

https://d.keka.io/test/Keka-v1.4.0-dev.r5301

**Comment by mreid-tt** [comment]
Nice, is there a proposed release schedule of when I may see an update in the App Store?

**Comment by aonez** [comment]
@mreid-tt that version was already released. Sorry for the late reply.
