### ISSUE TITLE
Can not uninstall

### ISSUE THREAD

**Issue by pkdesign** [aonez/Keka#1363]
I uninstalled via your terminal instructions. Then I used Find Any File and HoudahSpot to find anything with "keka" and deleted it. I then rebuilt my Launch Services database.

Why can I still right click on an archive and use "Open with Keka" to decompress a file? I can even set Keka preferences.

![Screenshot 2023-11-16 at 7 17 15 PM](https://github.com/aonez/Keka/assets/20543110/55b2845b-57ed-4c3d-855c-9c6f9aaf689f)

macOS 13.6.1

**Comment by aonez** [comment]
Hi,

This is strange. I understand you already emptied your Trash, but anyway I'm pointing it. You can also search for "Keka" in the Finder and see if it finds the application, or you can even use the Terminal:

```sh
mdfind kMDItemCFBundleIdentifier = "com.aone.keka"
mdfind kMDItemCFBundleIdentifier = "com.aone.Keka-iOS"
```

Note I'm also using "com.aone.Keka-iOS" in case you've installed the iOS version.

If you can give some feedback about why it doesn't fit your needs that would be very welcome. 🙌🏼

Salut!

**Comment by pkdesign** [comment]
I think I may have found the issue. It was finding another instance of Keka on another separate drive. When I deleted it from the other drive, it no longer appears if I right click on a compressed file.

I've been trying to pare down my drive of any non essential utilities. Keka has worked just fine for me, and I may reinstall at some point, but for my needs the builtin archive utility work just fine.
