### ISSUE TITLE
[BUG]: KekaExternalHelper does not even open

### ISSUE THREAD

**Issue by adrian-fro** [aonez/Keka#1371]
### Configuration
- Keka version: 1.1.3
- macOS version: 11.6.8
- intel MacBookPro produced in 2019 (latest before the M1 chips)

### Describe the bug
unable to open KekaExternalHelper downloaded from your website (see screenshot)

### To Reproduce
double-click in Finder on the freshly unzipped application

### Expected behavior
well …

### Screenshots
see attached

### Additional context
Please let me know when the problem will have been solved.

**Comment by aonez** [comment]
I don’t see the screenshot.

**Comment by adrian-fro** [comment]
Thank you for your swift answer.

Here is the screenshot:



Of course, the Helper is in the Applications folder.

Thank you,
Adrian
