### ISSUE TITLE
Error code 1 and unknown error while extracting split 7z files

### ISSUE THREAD

**Issue by prodtired** [aonez/Keka#1372]
### Configuration
- Keka version: 1.3.6 (5281)
- macOS version: 10.13.6 (17G14042)

### Describe the bug
I have a 7z split in 5 parts (file.dmg.7z.001, file.dmg.7z.002... file.dmg.7z.005), 
Attach a log file reproducing the issue: [Keka_2023-12-05-203737368.log](https://github.com/aonez/Keka/files/13572141/Keka_2023-12-05-203737368.log)
### To Reproduce

Right Click on 1st 7z file
Select open with Keka
Unzip dialogue begins
See error

**Comment by aonez** [comment]
The log is incomplete. Please open first Keka, activate the debug mode and
then extract the files. Let’s see what that log says.

**Comment by prodtired** [comment]
oh sorry, here  it is.

[Keka_2023-12-05-230408338.log](https://github.com/aonez/Keka/files/13573444/Keka_2023-12-05-230408338.log)

**Comment by aonez** [comment]
Seems that the files might be corrupted. If those were downloaded, try
downloading then again. Also you can check the size, maybe only one part is
corrupted.

**Comment by prodtired** [comment]
okay, thank you!
