### ISSUE TITLE
Metadata fonts not preserved in/out

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#138]
Metadata fonts are not preserved when compressed in 7z and Zip, or when extracted.

**Comment by aonez** [comment]
Most probably this will be fixed in #90.

**Comment by unamundan** [comment]
The Unarchiver — 3.11.4 (116) from my tests — is the only Mac utility I’ve found that can successfully decompress Zipped or 7z’d archives containing Type 1 fonts and custom icons. Even Apple’s own Archive Utility 10.10 fails at properly safeguarding LWFN / SFNT / FOND file creator and file types through the CODEC pipe. Keka, Entropy, WinZip, and others equally fail this test. While all other compression util apps report unzipped / de-7z’d files as generic zero-byte waste, The Unarchiver is somehow sniffing out the truth, icons, and resources properly. Thanks for a wonderful, simple app that puts the power of industrial-strength 7z compression in our hands, aonez!

**Comment by aonez** [comment]
@unamundan thanks for the feedback! Maybe you can share some fonts and icons to test?

**Comment by unamundan** [comment]
Here ya go, [aonez](https://github.com/aonez) — A handful of noncommercial Type 1 fonts circa 1992. They are, indeed, properly ID’d by the macOS 10.12 Finder prior to compressing ...

![image](https://user-images.githubusercontent.com/37463152/37573939-da219402-2aea-11e8-850a-903a5ac8d135.png)

... and are previewable via Quick Look in the Finder ...

![image](https://user-images.githubusercontent.com/37463152/37573966-1a30f056-2aeb-11e8-8bba-3da31ac140d1.png)

A Finder-generated Zip archive is attached with the fonts inside. Oddly, today, Archive Utility 10.10 can ID these particular fonts AFTER decompression. It couldn’t yesterday. But it was different, random fonts. Keka decompresses these to zero-sized ghost files.

Hope that helps.

[We’re_Healthy_-_We_Promise.zip](https://github.com/aonez/Keka/files/1823416/We.re_Healthy_-_We_Promise.zip)

**Comment by unamundan** [comment]
Here ya go, @aonez —

Attached is a handful of copyright-free Type 1 fonts from circa 1992. (You’re gonna wanna wear mold-resistant protective gear handling these things.) They are, indeed, properly ID’d by the macOS 10.12 Finder prior to compressing ...

![image](https://user-images.githubusercontent.com/37463152/37576001-fa3f3412-2af7-11e8-96ae-c81eb1a8b41c.png)

... and are previewable via Quick Look in the Finder ...

![image](https://user-images.githubusercontent.com/37463152/37576009-074e746a-2af8-11e8-9747-e28fe6dd65a8.png)

A macOS 10.12 Archive Utility 10.10-generated Zip archive is attached with the fonts inside. Oddly, today, Archive Utility 10.10 can ID these particular fonts AFTER decompression. It couldn’t yesterday. But those _were_ different, random fonts. Keka unsuccessfully decompresses these to zero-size ghost files. THe Unarchiver successfully de=archives.

Hope that helps.

![image](https://user-images.githubusercontent.com/37463152/37576085-7e439780-2af8-11e8-9f67-2f79de3da47b.png)

[We’re_Healthy_-_We_Promise.zip](https://github.com/aonez/Keka/files/1823587/We.re_Healthy_-_We_Promise.zip)

**Comment by aonez** [comment]
Cosing this one on favor of #90. The reason is the same.Thanks for the sample @unamundan!

**Comment by aonez** [comment]
@unamundan just letting you know that next release 1.1.6 will properly extract those files :)
