### ISSUE TITLE
[BUG] Keka doesn't reduce archive's final dimension

### ISSUE THREAD

**Issue by iColas7** [aonez/Keka#1380]
### Configuration
- Keka version: 1.3.3
- macOS version: 14.1.2

### Describe the bug
From the app downloaded from the site, I don't have the option to compress the size of the files I want to put in an archive. For example, if I want to use the 7z format, but also zip, it doesn't change anything if I choose "None" or "Slow" as the compression method: the final file size will always be the same

### To Reproduce
1. Select in Keka zip format
2. Select Slow method
3. See the results

### Expected behavior
I would expect the size of the final archive, if I choose "Slow" as the compression method, to be smaller than when you select "None"

**Comment by aonez** [comment]
What kind of files are you compressing?

**Comment by iColas7** [comment]
.mov files

**Comment by aonez** [comment]
Video files are usually already compressed unless they’re raw. That’s why you don’t get much difference compressing them.

**Comment by iColas7** [comment]
OMG, thank you and sorry for the mistake!

**Comment by aonez** [comment]
Glad to help 🤩
