### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by superlativo77** [aonez/Keka#1381]
### Configuration
- Keka version: [e.g. 1.3.6 (5281)]
- macOS version: [Monterey 12.7.2]

### Describe the bug
When I use zip compression on splits they are named like:
filename.zip.zip.001
filename.zip.zip.002

Is it normal or necessary to double zip word? 

I would expect more something like this:
filename.zip.001
filename.zip.002

Thanks in advance.

**Comment by aonez** [comment]
Thanks for the feedback @superlativo77. It seems this only happens when the destination has no previous file access.

Can you confirm if you create two splits in the same destination the second one does not have the issue?

**Comment by aonez** [comment]
Already found the issue and fixed it for the next revision. Thanks again @superlativo77.

**Comment by superlativo77** [comment]
Thank you very much for your quick response and solution.

Happy New Year @aonez
