### ISSUE TITLE
[REQ] Allow "sharing to" Keka iOS

### ISSUE THREAD

**Issue by voltagex** [aonez/Keka#1384]
### Is your feature request related to a problem? Please describe
If I select a file in the iOS Files app and hit Share, Keka doesn't appear as an option
### Describe the solution you'd like
It'd be good to be able to quickly compress a file by sharing it to Keka (yes I know it's built in now, but Keka has more options).

### Describe alternatives you've considered
Opening Keka and compressing the file through that UI

**Comment by aonez** [comment]
Don’t those options appear for you?

![IMG_8974](https://github.com/aonez/Keka/assets/480163/4326d986-5a27-4f8b-9bb3-336c64d3b9dd)

**Comment by voltagex** [comment]
Well that's embarrassing - I didn't scroll down far enough!

The Keka icon doesn't appear on the top line if the file is not an archive though, which I guess makes sense.

Sorry about this and thanks for the pointer!
