### ISSUE TITLE
[REQ] List archive content

### ISSUE THREAD

**Issue by brunetton** [aonez/Keka#1392]
Hi

I needed to verify the an archive structure (folders and files) and I needed a way to list the files and folders included in the archive.

I'd like to have an option to list an archive "internal" files; something like:

![image](https://github.com/aonez/Keka/assets/86322/7c5d5b2f-a956-41bf-9021-af97f92e5145)
 (screenshot I just made from Linux basic [Ark](https://apps.kde.org/fr/ark/) archiver)

**Comment by gingerbeardman** [comment]
Dupe #100 (coming soon)

**Comment by aonez** [comment]
While the new macOS version is under development, if you have an Apple Silicon Mac you can use the iOS version for this:

https://ios.keka.io
