### ISSUE TITLE
Damaged .rar file

### ISSUE THREAD

**Issue by felipep4p** [aonez/Keka#1393]
### Configuration
- Keka version: [e.g. 1.1.24 (3421)]
- macOS version: [e.g. 10.14.6 (18G2022)]

### Describe the bug:

Keka.io Damaged my .rar file

Yesterday, I wanted to unzip an extremely important file, and seeing that the official macOS unzip didn't work, I decided to install Keka.io. When I downloaded it automatically my files changed and as a result I could no longer open them, I got a verification error. I decided to test those same files on a windows device and the same files that Keka.io changed did not work on windows either. 
I need a quick answer as to what I can do, I did not install this program to have damage to my files. Any help is greatly appreciated.

### Screenshots
<img width="542" alt="Captura de pantalla 2024-02-08 a la(s) 23 31 05" src="https://github.com/aonez/Keka/assets/159504003/3a0d18ee-877d-4d8a-b3c1-dea05a95ad5a">
<img width="542" alt="Captura de pantalla 2024-02-08 a la(s) 23 31 05" src="https://github.com/aonez/Keka/assets/159504003/cfcfba95-4912-41f9-8d6a-1ae215ead729">

**Comment by felipep4p** [comment]
if you have any solution, please send me that information at p4p.felipe@gmail.com

**Comment by aonez** [comment]
Hola Felipe. Keka does not modify at all the files it opens. Where did you downloaded Keka from?

Please click in the warning⚠️ icon when you see the error message to get a more extended error information, then paste that here. Feels to me that this “RAR” file is not a valid RAR since it’s not being extracted with unRar but unar. Let’s see that extender error info.

**Comment by felipep4p** [comment]
Hi, thank you for answering me.

this is the error message:

OS: Versión 14.1.2 (Compilación 23B92) (arm64)
Keka: v1.3.7-r5302 (WEB) (Sandboxed) (es)
Format detected: Unknown
Binary used: keka7zz
Arguments: (
    x,
    "/Users/felipealvarez/Desktop/Felipe/VlC/D.rar",
    "-snld",
    "-aou",
    "-xr!__MACOSX",
    "-bsp1"
)

7-Zip (z) 23.01 (arm64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20 : Modified by aone for Keka
 64-bit arm_v:8 locale=en_US.UTF-8 Threads:8 OPEN_MAX:2560, ASM

Scanning the drive for archives:
  0M Scan /Users/felipealvarez/Desktop/Felipe/VlC/
1 file, 825229312 bytes (787 MiB)

Extracting archive: /Users/felipealvarez/Desktop/Felipe/VlC/D.rar
  1% Open
  1%
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

ERROR: /Users/felipealvarez/Desktop/Felipe/VlC/D.rar
Cannot open the file as archive


OS: Versión 14.1.2 (Compilación 23B92) (arm64)
Keka: v1.3.7-r5302 (WEB) (Sandboxed) (es)
Format detected: Unknown
Binary used: kekaunar
Arguments: (
    "-q",
    "-r",
    "-D",
    "-K",
    "-nq",
    "-o",
    "/Users/felipealvarez/Desktop/Felipe/VlC/D.kextraction/Operation",
    "/Users/felipealvarez/Desktop/Felipe/VlC/D.rar"
)
Couldn't recognize the archive format.

Error code 1

---------------------------

I hope you can help me.

**Comment by gingerbeardman** [comment]
It seems to not be a RAR file.

**Comment by aonez** [comment]
Like @gingerbeardman said. If you downloaded those files, try to download them again.

**Comment by felipep4p** [comment]
So, I don't understand what's going on, because I made that file with pretty important things.
the history of this file was:

I created that file in windows with winrar program, I put the file in flash memory and I save it. Then (1 year later) I wanted to open that file (on Macos) and I couldn't open with the official macOS unzip, so I decided to search in YouTube and I found Keka.io. I download it, and when that happen the file changed their icon for Keka.io files, and when I opened, Keka told me it can't open the file. At that moment I thought: "it just a bug, I'll try on my windows device. So I did that, and I couldn't open it either.

that was the whole story.

Now, as you said, maybe Keka.io wasn't at fault, but I really want to know how I could open that file. Please, do you help me with that?

**Comment by aonez** [comment]
Maybe you failed to copy it properly to the flash memory (cache issues). You could try the repair option using WinRAR on Windows.
