### ISSUE TITLE
New task handler stops on password error

### ISSUE THREAD

**Issue by digitall-it** [aonez/Keka#140]
If you ask Keka 1.0.13 (1790) to decompress a list of files, but the first one has a password that the user doesn't know, it doesn't continue to the next element. Instead, the Keka window closes, like if there weren't other files in queue to decompress.

**Comment by aonez** [comment]
As a workaround you can [force the old queue](https://github.com/aonez/Keka/wiki/Hidden-configuration#general), but this should be fixed in a future release.

I'll check how to fix it and depending on the result will come in a 1.0.14 or 1.1.0 version.

Thanks for the tip!

**Comment by aonez** [comment]
Fixed in beta 6! I'll enhance the queue system more in the future anyway.
