### ISSUE TITLE
[BUG] Keka does not clean up .kextraction when password dialog cancelled via regular close button

### ISSUE THREAD

**Issue by mejofi** [aonez/Keka#1409]
### Configuration
- Keka version: 1.4.0-dev (5349)
- macOS version: 14.3.1 (23D60)

### Describe the bug
When extracting a password-protected 7Z archive, Keka pops up a password dialog for then user. If the user closes this with the regular window close button, the temporary `.kextraction` package folder is left behind. This does not happen if the 'x' button is clicked.

### To Reproduce
Double-click a password-protected archive. Instead of entering the password, click the red window close button.

### Expected behavior
The `.kextraction` package folder should be cleaned up regardless of which button is clicked.

### Screenshots
![keka-close-password-dialog-bug-20240305-1250](https://github.com/aonez/Keka/assets/91268/ced45ada-5dd0-4cf2-8697-9389fb6951fc)

**Comment by aonez** [comment]
I'm unable to reproduce this one. Is there any other specifics to your test?

**Comment by mejofi** [comment]
This is on a case-sensitive filesystem again, perhaps that has something to do with it?

**Comment by aonez** [comment]
Makes no change in my tests. I've tried with small and large files and various formats.

Does it also happen if you have the Keka window opened? If so, please "Create a debug session", if not enable "Enable debug information" and "Save debug information". In any of those cases, reproduce the issue and share the log.

**Comment by aonez** [comment]
By the way the version in the screenshot probably is v1.3.7, versions 1.4.0 have the new "eye" icon near the stop button.

<img width="516" alt="Screenshot 2024-03-05 at 15 53 22" src="https://github.com/aonez/Keka/assets/480163/d2a5f8c2-2758-45ca-bffe-8d03344173fe">

**Comment by mejofi** [comment]
Huh, yeah, apparently it got mixed up, removed MAS version for now to avoid further confusion. This seems to be resolved in the current dev/beta build (1.4.0-dev (5355))

Thanks! 🙂

**Comment by aonez** [comment]
I can't reproduce this on v1.3.7 neither. Just ping me back if your reproduce it again. Thanks @mejofi.
