### ISSUE TITLE
Error 1 - Operation not permitted

### ISSUE THREAD

**Issue by rmbrown410** [aonez/Keka#141]
I'm prompted with an error while trying to extract zip archives that I compress with a password. 

"Unable to expand '*.zip' into 'destination'.
(Error 1 - Operation not permitted.)"

That's when the correct password configured is entered and this occurs in both Windows and macOS.

**Comment by aonez** [comment]
Can you share one of those files?

**Comment by rmbrown410** [comment]
No, but the error appears to be specific to those video files. I tried to replicate the problem using some test files of various sizes without any luck. Sorry for wasting your time.

**Comment by aonez** [comment]
Closing this one. Let me know if it needs to be reopened.
