### ISSUE TITLE
BUG: beta 6 just opens prefs when i try to expand an associated RAR file

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#143]
BUG: beta 6 just opens prefs when i try to expand an associated RAR file

video: https://transfer.sh/ghTMK/keka.mov

**Comment by aonez** [comment]
Thanks @gingerbeardman! Fixing this one ASAP.

Only affects RAR format (and probably all using UnrarKit) as you pointed later on the title.

**Comment by aonez** [comment]
Already fixed it but I'll hold since I'm also fixing an issue with the progress bar in Mac OS X 10.9 and 10.10. Hopefully today.

**Comment by aonez** [comment]
Fixed in https://github.com/aonez/Keka/releases/tag/v1.1.0-beta.7 :)
