### ISSUE TITLE
Add a new setting that always prompts the user for a password when compressing

### ISSUE THREAD

**Issue by geigel** [aonez/Keka#1432]
I almost always want to use a password when compressing files, but often the password is different depending on what person I'm sending the compressed file to. I also almost always select files in Finder and then use the right-click menu to "Compress using Keka". When I do this, it uses the default settings I've set up in Keka and I don't have an opportunity to enter a password.

I'd like to have the following two (2) things added to Keka:

1. A new setting that says "Always ask for a password when compressing?" which would show a very simple dialog to the user to enter a password (and confirm it) whenever the user has selected the menu item from the right-click menu. This setting would work even if the user has chosen their global default password—the dialog window could have a button saying "Use your default password" or a form to enter the one-time different password.

2. A new right-click menu item that says "Compress with password using Keka" that would offer the same type of dialog window described above in suggestion number 1 but this menu item would offer the dialog to the user even if their "Always ask for a password..." setting wasn't turned on.

I've considered writing my own Automator quick action script to achieve what I wanted, but I think these would be easy updates within the app which is otherwise very nicely done.

**Comment by gingerbeardman** [comment]
It's a different password every time? Or the same one?

**Comment by aonez** [comment]
Thanks a lot for the feedback @geigel. Same as #1162 and a step of #26, will come eventually.

**Comment by aonez** [comment]
This will come in the next version 1.4.0.
