### ISSUE TITLE
"Preview" mode (suggestion for a feature)

### ISSUE THREAD

**Issue by MaxPower85** [aonez/Keka#144]
I just had an idea... what if there was a button in the toolbar to turn on the "preview" mode... Keka could still function how it does by default and the interface could mostly look the same (just with the addition of a "preview" button in the toolbar), but if the "preview" button was clicked it could switch to "preview" mode and allow you to drag files one by one into Keka's window, the list of files (similar to Finder's "list" view) could appear in Keka's window (under the toolbar) and when you are finished you can just choose to save it as a new archive (the save button could maybe appear at the bottom of the window or the user could just go to File > Save, so there wouldn't be too many buttons in the toolbar).

Also, if you dragged an archive while Keka was in "preview" mode, it could show a list of files inside of that archive... you don't have to make it very fancy right away... initially, just showing icons for folders and filenames without icons would be fine (and later it could be improved)... and you don't have to add options to edit the archive right away... you could just have an option to convert the archive to another format (without having to first uncompress it to disk)... for example, when you drag a ZIP archive to Keka's window in "preview" mode, the drop-down menu that shows the format could automatically change to ZIP (to indicate that it's a ZIP archive) and if you wanted to convert it to 7-ZIP, you just click the drop-down menu and select 7z and then you save it... that would be useful... and additional features could be added later.

**Comment by aonez** [comment]
Thanks for your time @MaxPower85!

The first part of the list will be handled here #54 and the "preview" of the file contents will be handled here #100. About the conversion I don't see the benefits right now, but will take that into consideration after implementing #100.

No sure when they'll be implemented, but for sure #54 will come first and #100 later, maybe with not much delay between.

I'm closing this one as a duplicate 👍
