### ISSUE TITLE
[BUG] No context menu in finder

### ISSUE THREAD

**Issue by kw-sudo** [aonez/Keka#1449]
### Configuration
- Keka version: [1.3.8]
- macOS version: [14.5]

### Describe the bug
since update to version macOS 14.5 there're no entries in finder's context menu

### Screenshots

![keka](https://github.com/aonez/Keka/assets/104136223/e89cc626-f5be-489d-8a76-589300a81f3d)

### Additional context
I've tried both versions, homepage download and macOS app store. Re-installing got no changes. Also, Keka is set to default app.

Regards,
Oliver

**Comment by aonez** [comment]
Hi @master-kw,

I suppose you have the extension enabled in the Keka Preferences (and in the System Preferences) and the folder you're trying in the list. Note iCloud usually fails to show the extension.

<img width="791" alt="Screenshot 2024-05-15 at 20 44 31" src="https://github.com/aonez/Keka/assets/480163/8b95e00d-88fe-429d-887f-1268ed433d09">

**Comment by aonez** [comment]
Glad a reboot worked in this case 🙌
