### ISSUE TITLE
Use tar + p7zip for multithreaded xz tarball

### ISSUE THREAD

**Issue by MaxPower85** [aonez/Keka#145]
Since .txz is the same thing as archiving to TAR and then compressing to XZ format, but the **tar** binary doesn't seem to take advantage of multithreading when compressing to XZ, I think that you shouldn't use the **tar** binary to compress to XZ, only to archive files to TAR and then pipe the output to **7z** binary to do the compression. It works really well, it's much faster and the .txz file that you get can be uncompressed by **tar** that's included with macOS if needed (BTW... avoid compressing a single file to XZ without archiving it as TAR, since it doesn't even preserve the original file name that way and **tar** binary that's included with macOS will not accept to uncompress it).

An example (using the version of **tar** included with macOS... I discovered that **kekatar** that the latest beta is using corrupts the file when you try to pipe the output to **keka7z**... I'll submit a separate bug report for that)...

Just put some large files in a folder named **folder1** in your working directory, mount the latest Beta DMG and try this:
`tar -cf - folder1 | /Volumes/Keka/Keka.app/Contents/Resources/keka7z a -si -txz folder1.txz`

That's much faster than using this:
`tar -cJf folder1.txz folder1`

**Comment by aonez** [comment]
Already had the idea to use xz and pxz, but might try p7zip first.

**Comment by MaxPower85** [comment]
Well, .xz and .7z formats are similar, and 7z seems to be pretty well optimized for compressing to .xz format… 

I did some testing comparing 7z, xz and pixz, how fast they compress a file that was about 730 MB at level 9 (xz also has another level called “extreme”) and how much was the file compressed…

7z seemed to have performed somewhat better than xz or pixz…

It was using 10 threads by default during compression… xz was using 5 (even when told to use 10)… pixz was also using 5 (even when told to use 10)… 

Also, 7z seemed somewhat faster and the file was compressed to 314.3MB… xz and pixz at level 9 compressed it to 314.4MB even though they needed somewhat more time… xz has one more level that it calls “extreme” (that one needed somewhat more time than the “normal” level 9) and it managed to compress the file to 314.2MB.

7z used these settings
7z a -mx=9 -txz

xz used these settings (BTW, if you don’t tell it how many threads to use, it will use just 1 by default)
xz -9 -T10

pixz was using these
pixz -9 -p 10

xz with the “extreme” settings
xz -9 -T10 -e

So… for .xz it seems to me like you should use 7z for all levels it has, but if you want, you can add the “xz extreme” level after 9th 7z level and use xz just with “extreme” settings, since that seems to compressed the file slightly more (but it was the slowest).

But use 7z only for 7z and and XZ compression… 7z seems pretty well optimized for it’s own format and XZ which is similar, but it seems that you can get better performance for other formats with some other utilities... I'll write separately about that in more detail as I do more testing.

**Comment by aonez** [comment]
Thanks a lot for the testing @MaxPower85!

**Comment by aonez** [comment]
In 1.2.0 builds XZ with multithread support is used for tarballs :)

**Comment by MaxPower85** [comment]
Reopening this one...

Looking at the Activity Monitor, kekaxz seems to be used if you have "Always tarbal..." checked in the Preferences instead of the 7z... and for some reason, kekaxz seems to just run with 2 threads and no more than 100% CPU, which would be a single core.

I can't test the kekaxz in the Terminal if it's sandboxed and refuses commands...

But I tested the xz binary from homebrew with 
`tar -cf - 1.psd | /usr/local/Cellar/xz/5.2.5/bin/xz -9 -T8 > 1.psd.tar.xz`
and that uses more than just two threads and more than just 100% CPU (one core) if -T8 is specified... if it is omitted, then it just seems to use a single thread and 100% CPU

But I would suggest just excluding xz from Keka and using 7z for it, as I suggested before

This works fine, even if the number of threads isn't specified and it seems to use more CPU % than xz uses, so it would just compress faster
`tar -cf - 1.psd -C | 7z a -si -txz -mx=9 1.psd.tar.xz`

And to uncompress it, just use this
`7z e -so 1.psd.tar.xz | tar -x -`
