### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Aftertouchaudio** [aonez/Keka#1459]
### Configuration
- Keka version: [1.3.8 (5320)]
- macOS version: [14.4.1 (23E224)]

### Describe the bug
When compressing folders I get an error saying "verification of "file name" failed", the text below says The Compressed Data Seems To Be Invalid. 
Attach a log file reproducing the issue: https://github.com/aonez/Keka/wiki/Report-an-issue

### To Reproduce
Steps to reproduce the behavior: Any time I compress a file where I have "exclude Mac Resource Forks and Verify Compression Integrity selected. All files I try to compress has this problem. 

### Expected behavior
I did not want the compression to have errors? 

### Screenshots
![Screenshot 2024-05-30 at 10 49 11 AM](https://github.com/aonez/Keka/assets/171279154/4837da49-27b5-4358-a5de-1e1a62469521)
![Screenshot 2024-05-30 at 10 49 12 AM](https://github.com/aonez/Keka/assets/171279154/aaec3b72-04b2-4c28-af8f-69d838fea0b0)

**Comment by aonez** [comment]
Does it happen in any folder? For example a folder in the desktop?

**Comment by aonez** [comment]
Closing in favor of #1318
