### ISSUE TITLE
[BUG] Keka 1.4.0 not compatible with macOS Ventura

### ISSUE THREAD

**Issue by hamsterfactor** [aonez/Keka#1473]
### Configuration
- Keka version: 1.4.0
- macOS version: 13.6.7

### Describe the bug
KekaFinderIntegration crashes.
[KekaFinderIntegration-2024-06-22-161748.txt](https://github.com/user-attachments/files/15937133/KekaFinderIntegration-2024-06-22-161748.txt)

### To Reproduce
1. Go to Finder
2. Click on a DMG, etc.
3. See error

### Expected behavior
Nothing. I expect to use Keka via a right-click.

### Screenshots
<img width="260" alt="Screenshot 2024-06-22 at 16 17 54" src="https://github.com/aonez/Keka/assets/173556077/fe0b6420-c117-4102-b074-4f75943fd7d1">

### Additional context
When launching the Keka application, none of the menus work.

**Comment by aonez** [comment]
Thanks a lot for the crash report, already investigating it.

**Comment by aonez** [comment]
This needs to be fixed in an update. Meanwhile you can disable "Show encrypt with default password items" in the Keka Finder Extension Preferences. Sorry for the trouble.

**Comment by aonez** [comment]
Here a fixed build, you can use it while v1.4.1 is publicly released:

https://d.keka.io/test/Keka-v1.4.1.r5438

Thanks again @hamsterfactor!

**Comment by hamsterfactor** [comment]
Hey... I removed Keka 1.4.0 with AppCleaner, rebooted and launched your 1.4.1. I don't see crashes in the Finder at the moment, but the Finder menus, including the Apple menu still won't work/display. Regards, On Jun 22, 2024, at 9:19 PM, aONe ***@***.***> wrote: Here a fixed build, you can use it while v1.4.1 is publicly released: https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.4.1.r5438.7z Thanks again @hamsterfactor ! — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you were mentioned. Message ID: ***@***.***>

**Comment by aonez** [comment]
@hamsterfactor be sure to put Keka on the Applications folder, macOS is sometimes picky enabling the those extensions. Anyway the official update is scheduled for tomorrow so you can use that one instead.

**Comment by aonez** [comment]
Please reopen if you still have this issue with version 1.4.2. Thanks again!
