### ISSUE TITLE
[iOS] Type in password with Chinese characters using Chinese IME

### ISSUE THREAD

**Issue by Kosette** [aonez/Keka#1477]
### Configuration
- Keka version: 1.4.1 iOS
- iOS 17.5.1

### Describe the bug
When decompressing a 7z self-extracting file, you cannot switch to a Chinese keyboard, but you can copy and paste Chinese passwords to decompress correctly.

### To Reproduce
create a encrypted file using Chinese chracters as password, decompress with Keka. No Chinese IME found in keyboard list.

### Expected behavior
Allow to switch to Chinese keyboard to type in Chinese characters

### Additional Contents
Not sure if it is a system feature or what.

**Comment by aonez** [comment]
Using those characters is not recommended if you want the best compatibility with all systems and applications.

That said you can use them in some formats if you wish. While the standard password field of iOS does not enable it, you can enable the option to show the password and use any keyboard you wish:


![Simulator Screenshot - iPhone 12 mini - 2024-06-25 at 17 53 45](https://github.com/aonez/Keka/assets/480163/c55e414f-1a37-47d5-8dd1-a01b07c3dfcd)

**Comment by aonez** [comment]
I'll implement the show password option in all the password inputs so any keyboard can be used. Will leave this ticket open until then.

<a href="https://github.com/aonez/Keka/assets/480163/14a92309-4413-4ab8-850d-b64bc247ebfb"><img width="50%" src="https://github.com/aonez/Keka/assets/480163/14a92309-4413-4ab8-850d-b64bc247ebfb" align="left" /></a>
