### ISSUE TITLE
[BUG] Keka: Error when trying to zip a file

### ISSUE THREAD

**Issue by Nico1945** [aonez/Keka#1479]
Hello everyone
I just bought Keka (the zipping file) and I am already facing a bug -> Any file I am trying to zip leads to a bug (see attached PNG file). The log is also attached (".log" file).
Thank you for your support.
Nicolas
![Keka - Compression Issue](https://github.com/aonez/Keka/assets/98637854/444e655f-2693-4a00-9ce7-d79552ea62da)
[Keka_2024-06-27-194014913.log](https://github.com/user-attachments/files/16012302/Keka_2024-06-27-194014913.log)

**Comment by aonez** [comment]
Hi @Nico1945,

First of all sorry for the inconvenience. This was a bug that lived for a few hours in version 1.4.1 and was fixed in 1.4.2. Please update your version and let me know if you still have any issue with it.

**Comment by aonez** [comment]
Note this is a duplicate of #1476. Sadly Apple took long to review the update (almos 24 hours) and the bug spread was higher than it should have been.

**Comment by Nico1945** [comment]
Thank you for your quick reply.
I installed V1.4.2 and try to zip a file -> It worked. 
The topic is now closed.
Thanks again.
Nicolas

**Comment by aonez** [comment]
Thanks for your compression and feedback @Nico1945! Have a nice one :)
