### ISSUE TITLE
[BUG] Getting the small pop up settings pane every time I compress

### ISSUE THREAD

**Issue by drakeyboy** [aonez/Keka#1485]
### Configuration
- Keka version: [e.g. 1.4.2
- macOS version: 13.6

### Describe the bug
I'm getting the small pop up settings pane every time I compress. This has been happening since the last issue started..
[BUG] Error when compressing ZIP file on version 1.4.1 #1476

### To Reproduce
Right click file
Services
Compress Using Keka
Settings
<img width="513" alt="Screenshot 2024-07-03 at 09 12 12" src="https://github.com/aonez/Keka/assets/173789250/80218332-a19b-4ef2-b26d-8447cfd2ae0a">
 pane pops up and has to be closed every time

### Expected behavior
Zip is created without the pan appearing

**Comment by aonez** [comment]
This is an issue that happens from time to time without way to replicate it.
https://github.com/aonez/Keka/issues/1045

Can you try:

1. Open Keka normally
2. Quit Keka
3. Do your right click operation

Also let me know if only happens with compression or it does happen to with extraction. You can also try Finder Extensions, that are more advanced than Services (although not available everywhere):

<img width="791" alt="Screenshot 2024-07-03 at 10 20 40" src="https://github.com/aonez/Keka/assets/480163/902a1d50-7456-480b-9045-268dcaadeb8c">

**Comment by aonez** [comment]
> This only happens with compression - extraction is fine

Interesting. Are you compressing a file, a folder or multiple files and/or folders?

For using the Finder Extension you need to enable it (just click the button in the Preferences "The extension is disabled" if it is disabled.

<img width="425" alt="image" src="https://github.com/aonez/Keka/assets/480163/d5b8b28f-19b0-4df9-a88d-8045cf5311de">

### Finder Extension:
<img width="402" alt="image" src="https://github.com/aonez/Keka/assets/480163/2c91e611-1b44-471d-8e93-e75897f9c835">

### Services:
<img width="400" alt="image" src="https://github.com/aonez/Keka/assets/480163/aa1a8e8a-0c0c-4575-8ca5-d6e0931cb4df">

**Comment by drakeyboy** [comment]
Are you compressing a file, a folder or multiple files and/or folders?
all of the above

I've enabled the extension and now...

compress from the keka menu - no pop up pane
compress from services - pop up pane

I have 2 macs, both with the same OS. Happening on both machines

**Comment by romache** [comment]
I've had the same issue happen for a while when decompressing an archive using a keyboard shortcut (Ctrl+Shift+X). If I decompressed using a Finder's context menu, the settings dialog didn't pop up.
I disabled the Finder extension (via pluginkit in Terminal), enabled it again, and the dialog doesn't appear during decompression any longer.

**Comment by aonez** [comment]
Finally managed to find and fix the issue using the Services. Fix coming in the next release, already published a fixed build:
https://d.keka.io/test/Keka-v1.4.5.r5496

 #1512

**Comment by aonez** [comment]
This is publicly fixed now. Thanks to all.
