### ISSUE TITLE
[BUG] - Doesn't show the progress bar when try to encrypt file

### ISSUE THREAD

**Issue by mehadihn** [aonez/Keka#1493]
### Configuration
- Keka version: 1.4.3
- macOS version: 14.5

### Describe the bug
When compressing the files with encryption and after entering the password and clicking encrypt, the encryption starts, but the UI is stuck at the password field and does not show the progress bar with the remaining time. Clicking other buttons puts the UI in the password section loop.

### To Reproduce
Steps to reproduce the behaviour:

Please check the video.

https://github.com/user-attachments/assets/b0cbf3e1-695d-41d3-8893-b6ba8ca19599

### Expected behaviour

After clicking encrypt with a password, it should move to the progress bar and not show the password field.

### Screenshots
Added Video.

**Comment by aonez** [comment]
Thanks a lot for the feedback @mehadihn!

**Comment by aonez** [comment]
This is fixed in the next version 1.4.4. Thanks again @mehadihn!
