### ISSUE TITLE
[BUG]File is not password protected

### ISSUE THREAD

**Issue by Eithcowich** [aonez/Keka#1495]
### Configuration
- Keka version: latest
- macOS version: latest

### Describe the bug
I'm using Keka for mac on a Sonoma OS. I filled the password, and the repeat fields in the UI, and check the Use AES 256 box. Then I drop a text file onto the UI and Keka compresses it to .zip. So far so good. 

But when I decompress the file it doesn't require the password and simply opens it, as if it was not encrypted. Previous versions of this software wouldn't open the file unless I typed in the password, which is the desired behavior. 

### To Reproduce
See above

### Expected behavior
See above.

**Comment by aonez** [comment]
Can you reproduce this issue with any other files or folders? Is that text file empty?

**Comment by Eithcowich** [comment]
> Can you reproduce this issue with any other files or folders? Is that text file empty?
The text file is not empty, and yes, I can reproduce it with other files. Just did with a jpg. 

Here's a screenshot of my UI: 

![keka ui](https://github.com/user-attachments/assets/7279f73c-999b-44c5-bed2-9d4269344c1d)

**Comment by Eithcowich** [comment]
> Note that Keka remembers the last used password of the session and tries to reuse it.

Thanks, now I get it. I encrypted the file, quit Keka, and now it asks me for the password when decompressing.
