### ISSUE TITLE
[REQ] LZ4 v1.10.0 support

### ISSUE THREAD

**Issue by YunsuChoi** [aonez/Keka#1496]
Since 2024. 6. 18, Keka added support lz4 compression and decompression. 
after then [lz4](https://github.com/lz4/lz4/) finally supports multicore mode at version [1.10.0](https://github.com/lz4/lz4/releases/tag/v1.10.0) and it boosts performance from 5x to 10x.
Therefore, please consider upgrade lz4 core to latest version. thanks.

**Comment by aonez** [comment]
Not sure if I'm missing something here but the current version used in Keka (v1.9.4) already has multithread support and Keka integrates and uses it. I did some test comparing it to v1.10.0 and speeds and processor use is similar if not the same.

**Comment by aonez** [comment]
Just posting this it's clear to me that I've used a code between 1.9.4 and 1.10.0, dubbed 1.9.5. This code most probably already had multithread support. I'll update to 1.10.0 nonetheless.
