### ISSUE TITLE
[BUG iOS iPad] can’t extract 2 parts of a zip files on an iPad . I imported the 2 parts and then i only Could extract one not 2, help please

### ISSUE THREAD

**Issue by Tvfred** [aonez/Keka#1499]
### Configuration
- Keka version: [e.g. 1.1.24 (3421)]
- macOS version: [e.g. 10.14.6 (18G2022)]

### Describe the bug
Attach a log file reproducing the issue: https://github.com/aonez/Keka/wiki/Report-an-issue

### To Reproduce
2. Click on '...'
3. Scroll down to '...'

**Comment by aonez** [comment]
Hi @Tvfred,

Please open the parts directly in the Keka app using the Browse or the Extract options. That should work for you.

If it still does not work, can you please provide some screenshots?

**Comment by aonez** [comment]
I you can provide more information reopen the issue. Thanks!
