### ISSUE TITLE
OK button on password window should be all uppercase 

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#150]
currently it is: Ok

should be: OK

![screen shot 2018-03-14 at 15 43 45](https://user-images.githubusercontent.com/49612/37413305-a5de0846-279e-11e8-9253-6ed7fca66bac.png)

**Comment by gingerbeardman** [comment]
https://developer.apple.com/macos/human-interface-guidelines/buttons/push-buttons/

> Use title-case for push button titles. Capitalize every word except articles, coordinating conjunctions, and prepositions of four or fewer letters.

**Comment by aonez** [comment]
I may change it to “Done”
