### ISSUE TITLE
[REQ] Is it possible to support iOS 14 version?

### ISSUE THREAD

**Issue by Undefined-User** [aonez/Keka#1506]
### Is your feature request related to a problem? Please describe
I stayed on iOS 14 due to TrollStore, and I noticed that the minimum requirement for the app is iOS 15, is there any chance I can use this familiar app on iOS?

**Comment by aonez** [comment]
Sorry @Undefined-User but Keka for iOS was designed with iOS 15.5 as the minimum requirement due to the APIs used so it is not possible to lower it to iOS 14 without heavy code changes.
