### ISSUE TITLE
Issues with uncompressing .cpgz

### ISSUE THREAD

**Issue by MaxPower85** [aonez/Keka#151]
Create some folder in your working directory, name it "folder", add some random files to it and try this:
`ditto -cz folder folder.cpgz` or this `ditto -cj folder folder.cpgz`

Try uncompressing that with Keka... in both cases Keka extracts it like it's all one big text file instead of a folder with files inside.

The issue seems to be that it just uncompresses it as GZ or BZIP2 ("ditto -cz" is for GZ and "ditto -cj" is for BZIP2), but that it doesn't recognize that CPIO is inside... I tried to add .cpio extension after Keka decompresses it and then it can extract the files.

Archive Utility.app doesn't seem to have that issue extracting it... although in the 2nd case (with an archive created using "ditto -cj") it seems that it briefly shows one file name "folder" before removing it and showing a folder with files named "folder 2".

Using `tar -xf folder.cpgz` in Terminal extracts the files to the working directory, without the need to manually add .cpio and to extract files from that.

Using `ditto -x folder.cpgz folder` works too, as expected, since ditto created those archives.

Using `cpio -idv -F folder.cpgz` also works.

I tried it with Unarchiver too... it doesn't have that issue extracting from archives created by the 1st command I mentioned (with "ditto -cz"), but it seems that there is the same issue as with Keka if the 2nd command ("ditto -cj") is used to create the archive.

**Comment by aonez** [comment]
I did no treated it as a gz+cpio or bzip2+cpio. So right now it is extracted using p7zip and the resulting file is a cpio without extension. So:

- Enhance `cpio` format recognition
- Extract directly using `bsdtar`
