### ISSUE TITLE
[BUG] Keka window stays open when used via Send to Keka service

### ISSUE THREAD

**Issue by Stooovie** [aonez/Keka#1512]
### Configuration
- Keka version: 1.4.4
- macOS version: 14.6.1
- 
### Describe the bug
After extraction or archive creation done via Services, the Keka window stays open, despite "close Keka when no windows are open" is checked. This has always been happening, in almost a decade of use. 

I like to assign a keyboard shortcut (ctrl-shift-k) for Send to Keka, it extracts an archive or creates an archive when a file or folder is selected. It's my preferred way of working, but it leaves the Keka window open.

### To Reproduce
1) select an archive
2) Services-Send to Keka
3) operation carries out succesfully, but window stays open.

### Expected behavior
Keka window closes after completion

**Comment by gingerbeardman** [comment]
Check this issue, it was one of the first I reported and the info provided resolved it for me. YMMV

https://github.com/aonez/Keka/issues/224

**Comment by gingerbeardman** [comment]
@Stooovie is this before or after deleting prefs? or no change?

**Comment by Stooovie** [comment]
After. No change.

**Comment by gingerbeardman** [comment]
Will have to wait for developer to chime in.

I use Keka exactly the same way as you (my key combo is Cmd+Option+Control+A) and the window closes just fine since #224

**Comment by aonez** [comment]
Thanks a lot @Stooovie for the feedback and sorry for the late reply. I think I've finally found the issue and fixed it for the next release. You can check this fixed build:

https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.4.5.r5496.7z

**Comment by Stooovie** [comment]
Ooh, works perfectly! This has made working with Keka so much more enjoybale for me! Thanks!
