### ISSUE TITLE
[BUG] Window Hierarchy changed in MacOS 15 (Sequoia) 

### ISSUE THREAD

**Issue by mB-PiBox** [aonez/Keka#1518]
### Configuration
- Keka version: 1.4.4
- macOS version: 15.1 [Sequoia](https://www.apple.com/macos/macos-sequoia/)

### Describe the bug

When launching Keka from Finder (Right Click > Open With) the window rendered by Keka appears behind all active windows, especially behind Finder.

This is cumbersome when the file is password protected, as you have to start moving windows around to find the Keka window to enter the password. 

### To Reproduce
1. Right Click compressed file in Finder
2. Select "Open With.." > "Keka"

### Expected behavior

Keka window should render on top of all windows..

**Comment by aonez** [comment]
Should be fixed in this build:
https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.4.5.r5498.7z

Coming in the next release. Thanks again!

**Comment by aonez** [comment]
Updated build with option to enable/disable this. The option is enabled by default:

https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.4.5.r5508.7z

<img width="736" alt="Screenshot 2024-10-16 at 11 38 46" src="https://github.com/user-attachments/assets/e8b75f74-ed45-4424-bc98-9c5da5a22d20">

**Comment by Saratxe** [comment]
> Updated build with option to enable/disable this. The option is enabled by default:
> 
> https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.4.5.r5508.7z
> 

The extraction GUI remains active, but packing / unpacking is not possible with this version. I get error messages like this:

There was some error accessing the binary "unar"
Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"

There was some error accessing the binary "7zz"
Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"

**Comment by aonez** [comment]
@Saratxe please open Keka with right-click "Open". Clearly macOS sandboxing is doing magic there.

**Comment by aonez** [comment]
This is publicly fixed now. Thanks to all.

**Comment by mB-PiBox** [comment]
Appears to be resolved in 1.4.5 update received recently. 
Thanks for the fix.
