### ISSUE TITLE
Make the .dmg's window taller in case the path bar is visible

### ISSUE THREAD

**Issue by MaxPower85** [aonez/Keka#152]
![screen shot 2018-03-19 at 6 25 51 pm](https://user-images.githubusercontent.com/37249460/37611695-5a9c3912-2ba3-11e8-9742-3b4ba39991f3.jpg)

Just make the window somewhat larger, so the Status Bar wouldn't cover the text

Also... in case someone decided to show hidden folders, move the hidden folders to the side or more down, so those wouldn't be visible right away when the .dmg's window opens

![screen shot 2018-03-19 at 6 30 37 pm](https://user-images.githubusercontent.com/37249460/37611934-0aef2b62-2ba4-11e8-813d-d72556732d56.jpg)

**Comment by aonez** [comment]
Better use the beta package for those tests, since it has another background. But I'm pretty sure it will have those two issues too.

**Comment by aonez** [comment]
Increased the height:
![screen shot 2018-03-21 at 11 05 13](https://user-images.githubusercontent.com/480163/37704067-079ded86-2cf8-11e8-947e-51d5400b41f4.png)

The hidden files are already hidden in the current beta package:
![screen shot 2018-03-21 at 11 06 32](https://user-images.githubusercontent.com/480163/37704090-1fbadc08-2cf8-11e8-8a3e-c5b5c96c029b.png)

If an user has both path bar and hidden files shown, which causes scrollbars to appear, the text is clipped. But to solve this issue more height is needed and the usual user (no path bar and no hidden files visible) will see too much white space on the bottom. So I'll stick to the increment for path bar OR scrollbars, not both. Sure advanced users will understand 🤓

**Comment by aonez** [comment]
Just realized (while committing the changes) that the height is the same as before, so no adjustment was needed for the beta package. Anyway I've optimized the background image with the tips from https://github.com/aonez/Keka/issues/149.

**Comment by aonez** [comment]
@MaxPower85 just redesigned the package background, inspired on the [VLC](https://www.videolan.org) 3.0 version. This way the text never gets cut.
