### ISSUE TITLE
[REQ] Show only "Compress" instead of full filename

### ISSUE THREAD

**Issue by Dzialowy** [aonez/Keka#1528]
Is it possible to just show "Compress" instead of "Compress [full filename]"?
<img width="794" alt="Screenshot 2024-10-09 at 17 49 34" src="https://github.com/user-attachments/assets/d5f277a8-4cb1-47ca-bd51-c3fa50bc3cae">
Context menu gets all stretched on large filenames.

**Comment by gingerbeardman** [comment]
This is macOS, nothing to do with Keka.

**Comment by aonez** [comment]
Thanks Matt. @gingerbeardman is right, in fact the Keka extension is preventing this as shown:

<img width="1491" alt="Screenshot 2024-10-09 at 18 36 34" src="https://github.com/user-attachments/assets/db851488-0e91-4722-8fe1-e1316d306b16">

**Comment by Dzialowy** [comment]
Oh your right, my bad lol
