### ISSUE TITLE
[BUG] Can't select other format when not using unified toolbar

### ISSUE THREAD

**Issue by Undefined-User** [aonez/Keka#1539]
### Configuration
- Keka version: 1.4.5 (5509)
- macOS version: 13.6.9 (22G830)

### Describe the bug
When not using unified toolbar mode, I can't see format selector in UI, it's hidden.

### To Reproduce
1. Go to 'Setting'
2. Click on 'Use unified toolbar (resets customizations)'
3. See error

### Screenshots
<img width="454" alt="image" src="https://github.com/user-attachments/assets/1adb8a10-bb5d-4413-ac5e-009ad7626f7d">

<img width="336" alt="image" src="https://github.com/user-attachments/assets/2c6d0d34-44b6-4690-8eb0-bad8b2a9eb6a">

**Comment by aonez** [comment]
Sadly that kind of buttons is no more loved on recent macOS versions. You can remove GZIP from the equation and then the toolbar will have space for the format selector:

<img width="685" alt="Screenshot 2024-10-29 at 11 03 21" src="https://github.com/user-attachments/assets/bda21174-4174-44ee-a938-c8c5f8ca8e9c">

I'll check if the window can be resizable so you can accommodate as much icons as you want.

**Comment by gingerbeardman** [comment]
Or remove the flexible space:

<img width="448" alt="Screen shot 2024-10-29 at 13 52 52" src="https://github.com/user-attachments/assets/5c86ee4a-7285-4d5e-945a-bae71540da78">

**Comment by aonez** [comment]
@gingerbeardman I think you have 7Z selected, restarting the app showed all formats in the selector?

**Comment by aonez** [comment]
@Undefined-User v1.4.7 is publicly released now with the option to use resizable windows. You can use that option to fit more formats.

<img width="791" alt="Screenshot 2024-11-27 at 20 17 53" src="https://github.com/user-attachments/assets/9ce7d84d-bfb1-4c1b-a2a2-2e905bfb64b7">
<img width="848" alt="Screenshot 2024-11-27 at 20 20 04" src="https://github.com/user-attachments/assets/ffcf2f6d-7aa9-4d2b-ac46-db44df965440">
