### ISSUE TITLE
[BUG] File access popup appears always on macOS 15 Sequoia

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#1558]
Some users report the file access popup appearing in bucle, with file access apparently not working.

I'm still unable to reproduce it not once. If you can reproduce this issue, please [create a debug session](https://github.com/aonez/Keka/wiki/Report-an-issue) and send the logs here.

Also check out in the `System Settings` - `Privacy & Security` - `Files & Folders` if you have the offending folders enabled or disabled there:

<img width="495" alt="Screenshot 2024-12-06 at 14 08 41" src="https://github.com/user-attachments/assets/624e8d1c-075f-4169-9a03-7e1852e0546f">

Any additional information can be very helpful so I can reproduce and fix the issue.

**Comment by aonez** [comment]
@formattatoio are you still facing this issue?

**Comment by Moppel133** [comment]
I have the same problem after upgrading from macOS 13 to 14 (Sonoma). The only solution for me was to downgrade to V1.1.1 (which I found on my hard disk, fortunately).

**Comment by Moppel133** [comment]
I am using an iMac Pro (Intel) 2017 and Sonoma 14.7.1!

**Comment by aonez** [comment]
Thanks for the feedback @Moppel133! Can you reproduce the issue while [creating a debug session](https://github.com/aonez/Keka/wiki/Report-an-issue) as stated above?

**Comment by Moppel133** [comment]
[Keka_2024-12-11-192254238.log](https://github.com/user-attachments/files/18100464/Keka_2024-12-11-192254238.log)
After replacing the old version with the actual one, Keka ask me for the path and I said ok and it worked without repeatedly asking for the path. Before I give Keka access to all files via System Preferences and the Keka preferences.
Nevertheless, Keka asks for the path. And allow access to a special folder in the file access preferences was not possible (the folder was not listed in then window after I had chosen it.
I now go back to version 1.1.1 ))-:

**Comment by aonez** [comment]
Thanks a lot @Moppel133. Can you execute this on the Terminal and let me know the result?
```sh
xattr -l /Applications/Keka.app > ~/Desktop/keka-xattr.txt
```

After that you can try this other command an see if it fixes the issue:
```sh
xattr -cr /Applications/Keka.app
```

You can keep two versions of Keka, just rename one of those.

**Comment by Moppel133** [comment]
Thank you for your effort! Here are my results:
[keka-xattr.txt](https://github.com/user-attachments/files/18109006/keka-xattr.txt)

The "xattr -cr" does not work. I've got (even with sudo); see below. And it did not change the behavior of Keka.
Cheer, Klaus

[iMac-Pro:~] bluemelk% xattr -cr /Applications/Keka.app
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/CodeResources'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/_CodeSignature/CodeResources'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/_CodeSignature'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/kekapbzip2'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/kekalz4'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/kekaxz'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/Codecs/Rar.so'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/Codecs'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/kekaplzip'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/kekaunrar'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/kekalzip'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/kekapigz'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/kekalrzip'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/keka7zz'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/kekazstd'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/kekakwet'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/kekatar'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/keka7z'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS/7z.so'
xattr: [Errno 1] Operation not permitted: '/Applications/Keka.app/Contents/MacOS

**Comment by Moppel133** [comment]
sudo xattr -cr works if I type it in terminal by myself (before I did copy it from the email). But the behavior of Keka  is the same as before!

**Comment by aonez** [comment]
Thanks for all the feedback @Moppel133. Closing this one in favor of #1529 that was created previously.
