### ISSUE TITLE
The Archive Browser 1.11.1

### ISSUE THREAD

**Issue by SteroidMoe** [aonez/Keka#16]
Files in password protected 7z and Zip archives can be extracted with The Archive Browser 1.11.1. Don't know about Tar, Gzip, Bzip2. It cannot extract files from Dmg and ISO images.

**Comment by aonez** [comment]
I don't get what you're asking.

**Comment by aonez** [comment]
Maybe here? https://bitbucket.org/WAHa_06x36/theunarchiver/issues?status=new&status=open
