### ISSUE TITLE
Better English translation?

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#165]
Would you be open for me to revise the English translation?

Example:
"Move to trash compressed file(s) after been extracted"
->
"Move compressed file(s) to Trash after extraction"

"Automatic action: depending on file extensions Keka will decide if compress or uncompress"
->
"Automatic action: Keka will decide whether to compress or uncompress based on file extensions"

**Comment by aonez** [comment]
Sure, being not native any help is very appreciated!

**Comment by gingerbeardman** [comment]
OK! https://github.com/aonez/Keka/pull/167

**Comment by aonez** [comment]
Feel free to improve further in the future 👍

**Comment by aonez** [comment]
@gingerbeardman, for the example, you've replaced `ex` with `eg`, would it be better `e.g.` or `i.e.`?

**Comment by gingerbeardman** [comment]
I had e.g. without the colon in there for a while, feel free to do that

**Comment by aonez** [comment]
Don't know why I've reopened it! Merged for next release!
