### ISSUE TITLE
rar extract not working

### ISSUE THREAD

**Issue by Basic-income** [aonez/Keka#168]
Hello keka developer,

I use iMac and macOS 10.13.4 and Keka 1.0.15 (1804). But if extract this file not working, why??

please extract the zip file and then the rar file.

[R4i Germany V2.7.RAR.zip](https://github.com/aonez/Keka/files/1879679/R4i.Germany.V2.7.RAR.zip)

**Comment by aonez** [comment]
I'm taking a look at this one. The latest [beta](https://github.com/aonez/Keka/releases/tag/v1.1.0-beta.9) version opens it, if you need it ASAP.

**Comment by aonez** [comment]
Ok, so it is not a RAR file, it is a 7z file. Just change the extension to 7z and you are good to go. Newer Keka 1.1.0 version (currently in beta) detects it as a 7z, thus extracts it correctly.
