### ISSUE TITLE
Highlight extracted folder in Finder when original archive is trashed

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#169]
when using the "Move to trash compressed file(s) after been extracted" option

Currently after the expanded archive is trashed, there is no highlight in Finder.

it makes sense to highlight the newly created folder just before trashing the original archive file

goes with https://github.com/aonez/Keka/issues/164

**Comment by aonez** [comment]
What do you mean with highlight in Finder? You can bundle the trash action with the show in Finder one.

**Comment by gingerbeardman** [comment]
Video: https://youtu.be/PMvb-EvNr80

**Comment by gingerbeardman** [comment]
Ah! I see what you mean now, I have activated "Show content in Finder after extraction"
