### ISSUE TITLE
Keka failing to extract files on external hard drives

### ISSUE THREAD

**Issue by nickthurston90** [aonez/Keka#178]
I just bought Keka recently as a tool for Mac and it is not functional for basic operations. Please fix this. Mac OS X Sierra 10.12

**Comment by aonez** [comment]
Can you provide more information? What format has this external hard drive? Is it read-only?

**Comment by Basic-income** [comment]
with me it comes sometimes, but not always.

I use macOS 10.3.4, sd reader with an sd card 2gb (fat16). if add a zip file and unzip this. sometimes not working.

**Comment by MaxPower85** [comment]
Is the external drive writable in Finder? Is there enough free space on it?

BTW... not sure did I mention this before, but when trying to compress files from a read-only partition or to extract from archives on read-only partitions, I think it would be good to offer an option to put new files on the desktop if Keka can't write to that partition.

**Comment by gingerbeardman** [comment]
@MaxPower85 yes, Archive Utility does that by default

**Comment by Basic-income** [comment]
microsd 2gb card with fat/fat16.
add a rar file on this external hard drive and extract. not working
