### ISSUE TITLE
Trac internal error

### ISSUE THREAD

**Issue by seitsme** [aonez/Keka#181]
i was reading the info on kekaosx website and the legal reason the code is not open - a link to the page, seems is not working and would be nice to fix it so i can read the text on it please.

this is the error i get
http://trac.kekaosx.com/ticket/14

 Trac detected an internal error:
OperationalError: (1030, 'Got error 122 from storage engine')
i cannot create a ticket also.

**Comment by aonez** [comment]
Seems that something got updated in the server and Trac can't work properly. I might fix this but will take a while. Take a look here #13 instead.

**Comment by aonez** [comment]
So the trac.log was about 40 GB in size... now it's working.
