### ISSUE TITLE
Support encrypt file names

### ISSUE THREAD

**Issue by Basic-income** [aonez/Keka#194]
can you support encrypt file names?
I am not sure, but for zip file possible??

**Comment by gingerbeardman** [comment]
Not possible for ZIP

Possible for 7Z

**Comment by gingerbeardman** [comment]
@Basic-income See https://github.com/aonez/Keka/issues/179#issuecomment-386256427

**Comment by aonez** [comment]
@Basic-income as @gingerbeardman pointed this can't be done for ZIP at the moment but you can (and it's the default behaviour) in 7Z.

**Comment by aonez** [comment]
As a workaround for ZIP, you can pack the files first in a TAR or another format with the store option (no compression) and then compress it in ZIP. That way only the name of the intermediate packed file will be visible.

**Comment by aonez** [comment]
Also, for reference, take a look at what WinZIP states: http://kb.winzip.com/kb/entry/147

They also mention the workaround 😊

**Comment by aonez** [comment]
Just added this one to the wiki ([c1efc36](https://github.com/aonez/Keka/wiki/Compressing-with-Keka/c1efc36dddbff648e1934ddf378567fda252d37b) & [0c60951](https://github.com/aonez/Keka/wiki/Compressing-with-Keka/0c60951245071623b0c62e12187e8088e0498f59)), in case others look for it.
