### ISSUE TITLE
Let the user choose the configuration on "Send to Keka" service

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#197]
As commented [here](https://twitter.com/Wdavery/status/1004102322559913984) by Wyatt, let the user choose the options (compression, extraction, format...) when using the service "Send to Keka".

Currently it will do the selected operation in the preferences, automatic by default.

**Comment by plaa** [comment]
What's the difference with "Compess using Keka" and "Send to Keka" currently?  Both automatically create the archive without any prompting.  I assumed one would compress immediately, the other would open and ask for settings/password.

What we're looking for is a simple way for non-technical users to create password-protected ZIPs, as it's not possible through the default Mac GUI.

**Comment by aonez** [comment]
@plaa "Send to Keka" currently chooses the automatic action (extraction for compressed files, compression for the rest) but does not show any intermediate GUI to choose options, does the operation right away.

For what you're asking, the users just needs to open Keka, set the password (in both password fields) and then drop the files they want to compress. With the Keka window opened and the password set, you can also use the services, both "Compress.." and "Send...", they will create a password protected file. With this ticket enhancement the option to set the password/format from the services will be added, no timeline yet.

You can get more info and visual examples in the wiki: [Compressing-with-Keka](https://github.com/aonez/Keka/wiki/Compressing-with-Keka#password-protected-and-encrypted-files)

**Comment by andrewcrook** [comment]
I agree the functioality to select the compression type should be available as an option in services.
As to some way to add and remove files to an archive. Maybe a browse mode?

**Comment by aonez** [comment]
> Maybe a browse mode?

@andrewcrook #100

**Comment by andrewcrook** [comment]
> > Maybe a browse mode?

keep the current functionality as a quick mode 
but add a mode offering greater flexability e.g 

- the ability to open up an archive file 
- see its contents, search and sort columns
- md5 crc32 etc checking 
- drag and drop file(s) into it to add
- drag file(s) out to uncompress
- be able to remove file(s) from the archive.  
- recompress using different options e.g add / change passwords or compression levels
- ability to create a new archive in this mode and select options such as archive type. 

I don't know how to achieve all this , maybe some of it by uncompressing into a temporary directory and cleaning up afterwards?

**Comment by aonez** [comment]
This will be done in #292.
