### ISSUE TITLE
zip loses permission, renders unusable

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#2]
As stated here:
https://twitter.com/blynxical/status/802136463446077440

Example file here:
https://t.co/UJJFTPSz0Y

PKG installer looses permissions and can't be executed.

**Comment by aonez** [comment]
Hearthstore installer is also affected: https://eu.battle.net/account/download/?show=bnetapp

**Comment by jojoman02** [comment]
StarCraft installer is also affected: [https://starcraft.com/en-us/articles/20674424](https://starcraft.com/en-us/articles/20674424)

**Comment by aonez** [comment]
Usually adding the execute permission to all the binaries solves the issue. As a workaround:

`chmod +x /PATH_TO_THE_APP_PKG/Contents/MacOS/*`

**Comment by eriksneff** [comment]
FWIW - I would consider this bug to be a SHOWSTOPPER. I've probably spent 10 hours troubleshooting this, and now that I've finally figured out it was Keka all along, well, I'm super pissed, and depending on how quickly this gets resolved, may be uninstalling it for good.

A few more zips that I've personally confirmed lose their ability to be executed when Keka unzips them:
1) The Sonarr app is affected: https://download.sonarr.tv/v2/master/latest/NzbDrone.master.osx.zip
2) The Radarr app: https://github.com/Radarr/Radarr/releases/download/v0.2.0.778/Radarr.develop.0.2.0.778.osx-app.zip
3) The Sophos installer (I can't link to it, but I can confirm that the entire thing was broken after being unzipped by Keka, and not broken when using the macOS native archive app).

**Comment by aonez** [comment]
@eriksneff sorry about that one. I've also spent some time on this without any luck. I'll spend some time looking at the [Radarr](https://github.com/Radarr/Radarr) packaging process.

**Comment by aonez** [comment]
This one is fixed now. Will come in a few days as Keka 1.0.11.

**Comment by eriksneff** [comment]
Thanks @aonez !
