### ISSUE TITLE
Slow extraction of multiple files

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#202]
This is the collection of 118 zips I was expanding: https://0x0.st/s_2w.zip

> Why is Keka so slow here?

Times...

| App  | Time (seconds) |
| :--- | :---: |
| The Unarchiver | 10 |
| Keka (old queue)  | 20  |
| Archive Utility | 35 |
| BetterZip  | 50  |
| Keka (new queue)  | 60  |

**Tested these Keka versions**
- 1.1.0 (new queue)
- 1.1.0 (old queue)
- 1.0.16
- 1.0.4

**My setup...**

![41066077-93aa0018-69d8-11e8-97ef-894c4b60e00d](https://user-images.githubusercontent.com/480163/41068373-6ec767d4-69e9-11e8-9d21-39b974cbfad6.png)

**Comment by aonez** [comment]
Just for fun (and so you can add another time to the table) try with the old queue system (be prepared to scream 😰):

`defaults write com.aone.keka ForceOldQueue -bool true`

There's something slowing the new queue system. I must check that one. Thanks a lot @gingerbeardman!

**Comment by aonez** [comment]
By the way, https://0x0.st is very cool. Never heard of that one.

**Comment by gingerbeardman** [comment]
Added the time for the old queue (20 seconds!)

I used to use transfer.sh for temporary files, but it closed. so now I am trying out 0x0.st and file.io using the [Context Menu app](https://itunes.apple.com/us/app/context-menu/id1236813619?mt=12)

**Comment by gingerbeardman** [comment]
Not shown on my specs, I gave an SSD drive and am using APFS.

**Comment by aonez** [comment]
> SSD drive

Here too, but no APFS on 10.11. Really hoping for newer Mac Minis. I like to choose my monitors.

**Comment by gingerbeardman** [comment]
I use an old Apple Cinema HD Display with my rMBP in clamshell mode 🏚

Here's the script I use with Context Menu to upload to 0x0: https://gist.github.com/gingerbeardman/5398a5feee9fa1e157b827d245678ae3

**Comment by gingerbeardman** [comment]
Any progress?

**Comment by aonez** [comment]
Not yet

**Comment by aonez** [comment]
Now I see this one crystal clear. The problem here is that the queued operation in Keka (for 10 or more files at once) makes **one operation at a time**, while the other apps (and Keka with the old queue system or less than 10 files) do multiple operations at once, using more system resources and finishing sooner.

So this one will be fixed in #21, since the **one operation at a time** queue will be dismissed 😃 

Really the one operation at a time queue was a really bad feature. Ditching it will be the next big thing for Keka.

**Comment by aonez** [comment]
This is fixed in #21, thanks for the time @gingerbeardman!

**Comment by gingerbeardman** [comment]
Thanks!

**Comment by momomo** [comment]
real slow.

**Comment by momomo** [comment]
it is real slow even for one single file extraction of size no larger than 250 kb.

**Comment by gingerbeardman** [comment]
This issue was resolved and closed almost a year ago. 

@momomo if you're having problems, please start a new issue and give details of the version of Keka you are using as well as details of, or better a download of, a file that can reproduce the issue. Thank you!

**Comment by momomo** [comment]
I still have similar issues. I will continue here: 

Nothing is going on for it freaking queue: 

![image](https://user-images.githubusercontent.com/9274346/136594852-d725a982-d73b-443b-b1c1-227d185d1604.png)

**Comment by momomo** [comment]
Can it just start extracting? I have the lastest update.
