### ISSUE TITLE
Set as default app fails on 1.1.0

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#209]
As reported via mail by Wenzel, Keka fails to register as the default app.

- `LSSetDefaultRoleHandlerForContentType` was used to register, and seems it's not allowed on a sandboxed environment.

So far, the only solution is to install a helper app.

Take a look at the wiki page: [Default-application](https://github.com/aonez/Keka/wiki/Default-application)

**Comment by gingerbeardman** [comment]
There's no way. Maybe encourage use of an external script/app?

https://github.com/moretension/duti/

cf. https://superuser.com/a/1092184/33005

**Comment by aonez** [comment]
@gingerbeardman already on it 🤓 I did not expected that.

**Comment by aonez** [comment]
@gingerbeardman I suppose duti will fail from the same issue. I'm creating a custom procedure...

**Comment by aonez** [comment]
This should do it.

A non sandboxed app/extension, that sets Keka as the default app. This application moves itself to the sandbox container, so it can be used from Keka: [KekaDefaultApp-1.0.0.zip](https://github.com/aonez/Keka/files/2086303/KekaDefaultApp-1.0.0.zip)

Updated Keka version, that uses the extension: [Keka-1.1.1r2722.zip](https://github.com/aonez/Keka/files/2086305/Keka-1.1.1r2722.zip)

All will be documented [here](https://github.com/aonez/Keka/wiki/Default-application).

**Comment by gingerbeardman** [comment]
> I needed to move the the extension to the Desktop once extracted

I think this is an effect of app translocation, see https://github.com/potionfactory/LetsMove/issues/56

**Comment by aonez** [comment]
Thanks for the reference @gingerbeardman! I’ll edit the process in a few hours.

Sadly also LetsMove is not working in sandbox, although it can using XPC services, as Sparkle does. But for the next revision (and the one in the comment above) I’ve removed the framework completely 😔

**Comment by mvught** [comment]
Can you make a Universal version off "KekaDefaultApp" app?
