### ISSUE TITLE
Preferences for controlling tasks queue

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#21]
- [x]  Make the limits variables
- [x]  Add some pickers in the Preferences window
- [x]  ~By default set to the system # of logical CPUs~
- [x] ~By default limit to one operation per source/destination disk~
- [x] Add scroll to the tasks window
- [x] Implement thread limits 

As asked [here in the forum](http://forum.kekaosx.com/viewtopic.php?f=6&t=2113&p=2422#p2421), add settings in preferences, similar as in programs like [Transmission](http://www.transmissionbt.com).

General, compression and extraction settings.

**Comment by masklinn** [comment]
Maybe a good start would be to default to the number of logical CPUs on the system (`sysctl -n hw.ncpu` or [`ProcessInfo.processInfo().processorCount`](https://developer.apple.com/documentation/foundation/processinfo/1415622-processorcount) instead of some hard-coded number?

**Comment by aonez** [comment]
@masklinn I like the idea

**Comment by aonez** [comment]
Asked in the [forum](http://forum.kekaosx.com/viewtopic.php?f=6&t=2378), hope to start with this one very soon.

**Comment by gingerbeardman** [comment]
Good news

**Comment by aonez** [comment]
Just released a test version with the queue implemented: 
https://github.com/aonez/Keka/releases/tag/v1.2.0-dev.3417

**Comment by gingerbeardman** [comment]
Nothing extracted when I dropped 34 zips onto Keka 1.20 dev.

![Screen Shot 2019-04-03 at 23 06 32](https://user-images.githubusercontent.com/49612/55516481-3d33c780-5665-11e9-9859-4fabf8bf4415.png)

**Comment by aonez** [comment]
> dropped 34 zips

This remembers me I must add scroll... This happens also with 7z files? Can you share one of those first two files?

**Comment by gingerbeardman** [comment]
If I opened files through Finder to launch Keka they extracted.

**Comment by aonez** [comment]
Just uploaded a new build with far more stable and usable queue plus thread limit capabilities.
Test build: [v1.2.0-dev.3494](https://github.com/aonez/Keka/releases/tag/v1.2.0-dev.3494)
