### ISSUE TITLE
Something about the format of localization

### ISSUE THREAD

**Issue by chinnnki** [aonez/Keka#210]
I couldn't help but notice something about the localization.

Apple tends to use no space between Latin and non-Latin characters. For example, when Archive Utility.app is set as the default app, a ZIP archive is shown as a "ZIPアーカイブ" when the system locale is Japanese. However, when Keka.app is set, it shows "ZIP アーカイブ" instead. So are all the other translation strings in ja.lproj, zh-Hans.lproj & zh-Hant.lproj, all the .strings files included.

It may be a minor issue, but is this intended?

**Comment by aonez** [comment]
@chinnnki I'm not sure about that. Maybe @maxsky, @jihoongks or @wangcheng678 know?

**Comment by jihoongks** [comment]
Is OP talking about Finder? No problems with Korean. Whether the default app is Archive Utility or Keka, file descriptions have a space between Latin and Korean.
<img width="104" alt="abc" src="https://user-images.githubusercontent.com/39799470/41241936-308e98b8-6dd9-11e8-8d45-eb44c24ceeba.png">

**Comment by aonez** [comment]
thanks @jihoongks!

**Comment by maxsky** [comment]
I personally prefer to use a space between Chinese and English. I think this is a good habit for me and many developers. 💯

**Comment by chinnnki** [comment]
Thanks for the clarification!

I personally prefer spaces between Latin and CJK characters too.
However, rationally I think text spacing should be handled by OS's built-in mechanism (like the one in the upcoming CSS Text Module Level 4), rather than manually inserted spaces, which is only a workaround for better typography.

However, since Chinese and Korean stay with spaces, I think it's okay for Keka to stay with spaces for Japanese for now.

**Comment by aonez** [comment]
Then let's leave it with spaces for now, @chinnnki, but I'll be watching for further changes in Mojave and future releases, in case all adopt the no space strings. Thanks you all! :)
