### ISSUE TITLE
Question: Best options for reliable 7z files?

### ISSUE THREAD

**Issue by max-zhukov** [aonez/Keka#212]
Hello,

I would like to know which are the best options to choose if I want to have reliable 7z archives if it was damaged?

- Solid Archive?
- Archive as Single file?

With gratitude,
Maxim

**Comment by aonez** [comment]
@max-zhukov if you need recovery in case of damage, do NOT use solid archive. Solid archives are usually smaller and can be faster to create, but in case of damage the chances of getting back the data are smaller.

As for archive as single files this does not affect to recovery in any case. With this option if you drop 2+ files, each of them will be compressed in a separate 7z (or specified format) file.

Hope this helps 😊

**Comment by max-zhukov** [comment]
Thank you @aonez! 🙂
