### ISSUE TITLE
Keka keeps requiring access each time application is used

### ISSUE THREAD

**Issue by amazingrobie** [aonez/Keka#213]
High Sierra 10.13.4, mid-2011 iMac. Keka version 1.1.0.

Was requested to update over the past 24 hours and now program continues to ask to grant access to same drive over and over again each time it is opened.

Cannot make it stop. Is there a fix or is something setup improperly.

Preference Screenshots attached.

![screen shot 2018-06-12 at 1 27 13 am](https://user-images.githubusercontent.com/40194292/41273634-e11cee04-6ddf-11e8-8604-1320fd1822e9.png)
![screen shot 2018-06-12 at 1 27 19 am](https://user-images.githubusercontent.com/40194292/41273635-e13256cc-6ddf-11e8-9eb4-c65a1fc8971d.png)
![screen shot 2018-06-12 at 1 27 28 am](https://user-images.githubusercontent.com/40194292/41273636-e1474a64-6ddf-11e8-8c43-9f21c1adbdd2.png)

**Comment by amazingrobie** [comment]
And not to complain, but my eyesight is pretty crap already, but these new bright colors are stinging my retina. Is there any way to bring back the option for darker colors? All of these different oranges and purples are really confusing as well...

**Comment by aonez** [comment]
Hi @amazingrobie! There's nothing to change in the preferences. Just follow the [instructions](https://github.com/aonez/Keka/wiki/Sandbox). Be sure you're giving Keka access to the main disk, the one that has macOS installed.

But I'm assuming you already did that, so my recommendation is:

1. Close Keka if open
2. Remove the disk access [following this steps](https://github.com/aonez/Keka/wiki/Sandbox#remove-disk-access)
3. Restart your Mac 
4. Give Keka access again

Be sure you close Keka properly, since it needs to release the disk access each time it closes. Otherwise macOS can ban Keka this access, so Keka will need to ask for it again until the machine restarts.

If the above does not help, take a look at the Console.app to see the logs filtered by "Keka" and    execute this on the terminal and let me know what those says:

`defaults read com.aone.keka Bookmarks`

**Comment by aonez** [comment]
> And not to complain, but my eyesight is pretty crap already, and these new bright colors are stinging my retina. Is there any way to bring back the option for darker colors? All of these different oranges and purples are really confusing as well...

Sorry very about that. I've received some feedback about the icons already, I might consider some changes. If you use the web version you can replace it manually, no easy way.

**Comment by amazingrobie** [comment]
Did not find anything in Console app.

Below is what was received from Terminal command and its still situation after revoking/granting access and rebooting.

Can we have a direct link to the previous version of Keka to reinstall? We've been using it pretty heavily as of late and this having to repeatedly give access each time is really inhibiting workflow. Unfortunately, we already deleted the one from the trash, otherwise we would just use it.

defaults read com.aone.keka Bookmarks
(
    <626f6f6b f4010000 00000410 30000000 97ad48d1 b28771b8 12ce57a7 2e7a5108 4e203ab9 09d9d455 9cacb643 411cf187 08010000 04000000 03030000 00080028 00000000 01060000 05000000 01010000 6d61634f 53000000 08000000 00040000 41bfac40 9c000000 18000000 01020000 0a000000 00000000 0f000000 00000000 00000000 00000000 08000000 01090000 66696c65 3a2f2f2f 08000000 04030000 0000681f 3a000000 24000000 01010000 45443039 31393742 2d353045 442d3332 36422d38 3030302d 33313530 39313646 30343832 18000000 01020000 81000000 01000000 ef130000 01000000 00000000 00000000 01000000 01010000 2f000000 00000000 01050000 1a000000 01010000 4e535552 4c446f63 756d656e 74496465 6e746966 6965724b 65790000 04000000 03030000 02000000 b4000000 feffffff 01000000 00000000 0e000000 04100000 10000000 00000000 10100000 38000000 00000000 20100000 18000000 00000000 40100000 28000000 00000000 02200000 c4000000 00000000 05200000 58000000 00000000 10200000 18000000 00000000 11200000 78000000 00000000 12200000 68000000 00000000 13200000 28000000 00000000 20200000 a4000000 00000000 30200000 d0000000 00000000 10d00000 04000000 00000000 d8000080 fc000000 00000000>
)

**Comment by aonez** [comment]
> Can we have a direct link to the previous version

Sure, you can always get older versions in the [releases](https://github.com/aonez/Keka/releases) section or in the [legacy](https://www.keka.io/en/#legacy) section. Here the one you want: http://legacy.keka.io/lion

**Comment by amazingrobie** [comment]
Thanks.

**Comment by aonez** [comment]
If you will keep trying to solve this, please [activate the default verbose](https://github.com/aonez/Keka/wiki/Console-verbose#default) mode and let me know what the Console.app says. This will help a lot.

Thanks and very sorry for the issue @amazingrobie.

**Comment by amazingrobie** [comment]
When we get some time. Will try. Working on projects pretty steadily and right now, it's the middle of the night and I should be sleeping. :(

**Comment by aonez** [comment]
Sure @amazingrobie, when you find the time. Here a test version that might fix this or at least give some more information (in the Console.app): [Keka-1.1.0r2729.zip](https://github.com/aonez/Keka/files/2093054/Keka-1.1.0r2729.zip)

Also removing the Keka preferences might help: `rm -R ~/Library/Containers/com.aone.keka`

Hope you can go to sleep very soon :)

**Comment by petergi** [comment]
Hi this latest version of keka seems broken on High Sierra. I've never had ANY issues with Keka before and have recommended it and even purchased it for my employees.
But this version is soooooo exasperating. It continuously asks for file permissions. Doesn't remember settings... and worst of all can't DECOMPRESS anything. When I try it gives IO errors and then DELETES the zip/rar/whatever permanently without even putting it in the TRASH!!!!

Argh. I'd like to go back to the last version. It worked. Period.

**Comment by aonez** [comment]
@petergi (and @amazingrobie) I found a bug that did not removed a bad access bookmark, meaning that If for any reason Keka needed to ask permission again, was not saving that new access, so each time was asking for it. I'm updating this ASAP.

The version posted above ([Keka-1.1.0r2729.zip](https://github.com/aonez/Keka/files/2093054/Keka-1.1.0r2729.zip) has this fixed.

**Comment by bisherbas** [comment]
1.1.4 on macOS Majova and having this problem. Any thoughts?

**Comment by aonez** [comment]
@bisherbas can you try this:
https://github.com/aonez/Keka/issues/304#issuecomment-428078742

Let me know if it helps.
