### ISSUE TITLE
Can no longer drag files to the Keka dock icon in v. 1.1.0

### ISSUE THREAD

**Issue by Stevedore9** [aonez/Keka#217]
I’ve been using Keka for many years and love it.  However, v. 1.1.0 no longer allows me to drag a file to the Keka dock icon.  When I do so, nothing happens — I must first open the Keka application, then drag my file to it.  I've had to go back to v. 1.0.16.

Using macOS 10.13.5.

**Comment by aonez** [comment]
Can you try the just released 1.1.1 version? Maybe the bug there was the cause, but not sure.

**Comment by Stevedore9** [comment]
Yep, version 1.1.1 fixed the problem.  Thanks, aonez!
