### ISSUE TITLE
Check custom path availability

### ISSUE THREAD

**Issue by akrabu** [aonez/Keka#220]
Every time I try to create a zip file, I get "Error code 2 using "p7zip".  Fatal error."  I'm on v1.1.1 (2733).

**Comment by akrabu** [comment]
Nevermind, I'm an idiot lol

I had a custom compress-to path that no longer exists...  🙄😅

**Comment by aonez** [comment]
I'm reopening this one since this can be fixed for the future:

- [ ] Check custom path availability
- [ ] If not available ask for destination

**Comment by akrabu** [comment]
Good idea, and thanks!  Looking forward to 1.2.0!  Especially the better queueing for compressing several things at once.  That's going to be a lifesaver!  😁👍
