### ISSUE TITLE
Keep the encryption password even if Keka is closed

### ISSUE THREAD

**Issue by jodifu** [aonez/Keka#223]
Hello Jorge,

this turned up to be an issue with a friend of mine: Is it possible to store the configured encryption password and its settings for the chosen file type even if Keka is closed? So that you don't have to re-enter it every time you want to create an encrypted archive?

Thx and best regards,
Jochen

**Comment by aonez** [comment]
Hi @jodifu! Currently this is not possible, but it is something that will come in the future. I'm closing this one in favor of #26. Note the second point there (also asked on #118).

Salut Jochen!
