### ISSUE TITLE
App stays open after using "Compress using Keka" service

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#224]
**Process**
1. Keka is in my Dock
2. Keka is not open/running
3. use "Compress using Keka" service 
4. Keka opens and compresses file

**Expected**
5. Keka quit after compression completion

**Actual**
5. Keka stays running

**Settings**
- _Close Keka when no windows are open_ is ON
![screen shot 2018-06-24 at 00 36 03](https://user-images.githubusercontent.com/49612/41814521-045d79e0-7747-11e8-815d-994dde122169.png)

**Comment by aonez** [comment]
@gingerbeardman I can't reproduce this one. Can you remove the preferences and try again?

```
rm ~/Library/Containers/com.aone.keka/Data/Library/Preferences/com.aone.keka.plist
```

**Comment by gingerbeardman** [comment]
OK, it seems that it takes a couple of seconds and it closes.

Oddly, after deleting the prefs the first launch showed me the old toolbar with the archive files across the top and the dropdown to the right.

**Comment by aonez** [comment]
Ah ok! This is a feature, Keka waits for the notification to close, so in case you click on it it can show in the finder the extraction/compression files. This is a 5 seconds wait.

**Comment by gingerbeardman** [comment]
OK, it was not closing at all in my original issue.

But I'm happy now with this wait.

**Comment by viniciusbig** [comment]
This problem is still happening to me.
After I extract the file, Keka stays open.

**Comment by gingerbeardman** [comment]
>This problem is still happening to me. ...

@viniciusbig did you follow the advice in this thread?

**Comment by viniciusbig** [comment]
Yes! Thanks!
I've updated Keka here and now it's working properly
