### ISSUE TITLE
Delete package after decompression

### ISSUE THREAD

**Issue by khanhthietbi** [aonez/Keka#225]
With single compressed package, Keka runs well to move the package to Trash after decompressing. However, with package that divided/separated into multiple parts, Keka just moved the first one to Trash and the rest still remain there. E.g. a.part1.rar, a.part2.rar, a.part3.rar -> only a.part1.rar is moved to Trash.

**Comment by aonez** [comment]
@khanhthietbi what version of Keka are you using? This was fixed in 1.1.0 #8.

**Comment by anazhd** [comment]
Can confirm even on 1.1.1, Keka deleted all parts accordingly.

**Comment by aonez** [comment]
Thanks @anazhd! @khanhthietbi reopen this one if you still found this issue on the latest Keka version.
