### ISSUE TITLE
No read access to the user defaults on first launch 

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#226]
`rm ~/Library/Containers/com.aone.keka/Data/Library/Preferences/com.aone.keka.plist`

Oddly, after deleting the prefs the first launch showed me the non-unified toolbar with the archive files across the top and the dropdown to the right, despite unified toolbar being the default option. And I had to regrant permission.

![screen shot 2018-06-26 at 10 40 33](https://user-images.githubusercontent.com/49612/41903268-60d2ff64-792d-11e8-87eb-2196d3367db4.png)

Next launch I had to grant permissions again, but this time the window looked as expected.

![screen shot 2018-06-26 at 10 42 46](https://user-images.githubusercontent.com/49612/41903403-b0a30c50-792d-11e8-9153-cf6ce711f722.png)

**Comment by aonez** [comment]
It’s possible you still have some of the RC or Betas in your machine?

**Comment by gingerbeardman** [comment]
I do not. I thought that and checked.

Just version 1.1.1 (2733)

Here's a video: https://youtu.be/uEh2hjS84AY

**Comment by aonez** [comment]
Reproduced it. Thanks @gingerbeardman!

**Comment by aonez** [comment]
Here the problem:

```
rejecting read of { com.aone.keka, aone, kCFPreferencesAnyHost, /Users/aone/Library/Containers/com.aone.keka/Data, managed: 0 } from process 978 because accessing preferences outside an application's container requires user-preference-read or file-read-data sandbox access
```
```
Couldn't read values in CFPrefsPlistSource<0x6040000e6880> (Domain: com.aone.keka, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: Yes): accessing preferences outside an application's container requires user-preference-read or file-read-data sandbox access, detaching from cfprefsd
```

Not sure why yet.

**Comment by gingerbeardman** [comment]
Was reminded by #228 that after half defaults it took two presses of Quit (hotkey  or menu) to quit the app

**Comment by aonez** [comment]
So finally I've determined that the whole container should be deleted. If only the plist file is deleted, the App internals treats the container as if its from a third party application and has no access. So:

```sh
rm -r ~/Library/Containers/com.aone.keka
```

I should remember that 🤓
