### ISSUE TITLE
reCaptcha on forum have an error!

### ISSUE THREAD

**Issue by deyanm** [aonez/Keka#227]
When I try to register on the Keka forum, the reCaptcha is not working, and displaying error with domain: 
```
ERROR for site owner:
Invalid domain for site key
```

**Comment by gingerbeardman** [comment]
I also see this.

**Comment by aonez** [comment]
That makes sense with the new domain. I’ll change that. Thanks!

**Comment by aonez** [comment]
Should work now 👍🏼
