### ISSUE TITLE
Can’t shutdown after Keka installation.

### ISSUE THREAD

**Issue by Rahzah** [aonez/Keka#228]
After Keka is installed my Mac needs hours to shutdown or does not make it anyhow. Do you have any solution for this?

**Comment by aonez** [comment]
Can’t you close Keka?

**Comment by Rahzah** [comment]
Yes, Keka can be closed and I closed it. Right now I experimented uninstalling everything with AppCleaner. I got 3 Macs to maintain and after uninstall and reinstalling Keka 2 of 3 computers shut down again. The third one keeps struggling.

**Comment by Rahzah** [comment]
I’ve got 1 Mac Pro, iMac both roundabout 2010 which shutdown with osx 10.11 and 10.10 and the struggling third is a Mac mini also with Yosemite.

**Comment by Rahzah** [comment]
But it worked after uninstalling your app. What am I Looking for in the console app. Not that experienced in that regard.

I installed the app from your website.
