### ISSUE TITLE
Keka thinks compressed files already exist?

### ISSUE THREAD

**Issue by grimmermatt** [aonez/Keka#229]
Keka is naming all of my compressed files *[space]2.7z, as if there were already a file named *.7z in the same directory. Any idea why this is happening? I’ve looked around everywhere. Oddly, this happens with a 2018 5k iMac but not with a 2016 15" MBP. I'm on Version 1.1.1 (2733) and the latest OSX with both.

**Comment by aonez** [comment]
Hi Matt! What option are you using for the compression naming? You can look at it in the Keka preferences, Conpression tab.

**Comment by gingerbeardman** [comment]
Oh! That will teach me. I did not even check the preferences

**Comment by grimmermatt** [comment]
I saw that and it did nothing. Two different machines, same Keka settings, one creates *.7z archives / one creates *[space]2.7z archives. I don't typically ask questions without looking through the settings. Thanks.

**Comment by grimmermatt** [comment]
Uninstall/reinstall seems to have fixed this entirely.

**Comment by aonez** [comment]
Perfect!
