### ISSUE TITLE
Please add extraction support for WIM files

### ISSUE THREAD

**Issue by TGOS** [aonez/Keka#23]
WIM files ("Windows imaging (WIM) image", says `file`) are supported by the 7z compressor and they are also supported by Keka, yet Keka doesn't know it is supporting them. All I need to do is to rename `archive.wim` to `archive.wim.7z` and Keka will extract it just fine. So the WIM support is almost ready, just register the file extension, let Keka know what to do with it and announce WIM extraction support on the webpage. One of the least expensive features ever! ;-)

**Comment by aonez** [comment]
Thanks for the tip, going into next release!

**Comment by aonez** [comment]
Added to r1735 revision. Coming in 1.1.0!
