### ISSUE TITLE
Don't create folder!

### ISSUE THREAD

**Issue by nicmare** [aonez/Keka#232]
Keka always creates folders in the zip archive. even when i select multiple files and put them into keka. keka will always wrap them in a folder withhin the archive. how can i stop that?! i need the files without folder after extracting. thanks

**Comment by gingerbeardman** [comment]
@nicmare Actually, an enclosing folder isn’t added to the zip at all. You can check by opening in BetterZip or QuickLook or similar. 

The enclosing folder is created during extraction, to keep the files from the archive together. But you’re correct that there is currently no option to avoid this when using Keka.

**Comment by aonez** [comment]
This is in fact a duplicate #72. As @gingerbeardman states the folder is created during extraction, not in the compression.
