### ISSUE TITLE
The Terminal command isn't working

### ISSUE THREAD

**Issue by Amsdame** [aonez/Keka#233]
It was unclear to me whether to first copy & paste the full command to set all parameters up, because when attempting that I got a syntax error. Instead I wrote the command I wanted (the password one) as the parameter, and then ended with true (all lower case). I did not get a syntax error but when attempting to check if it was actually working it failed to create a password file for me.  What am I doing wrong?

**Comment by gingerbeardman** [comment]
Are you doing this `defaults write com.aone.keka ExportPassword -bool TRUE`

**Comment by Amsdame** [comment]
My bad, I had to restart and now it is working!

**Comment by Amsdame** [comment]
Yes, I tried yet again and no file with the password is to be seen nearby the extracted file, or the zip file, or the original file

**Comment by aonez** [comment]
@Amsdame is working for you or not? Always to set a preference from the terminal first close Keka, then set the preference and start Keka again.
