### ISSUE TITLE
[Feature request] Preview content of archive

### ISSUE THREAD

**Issue by Vadammt** [aonez/Keka#234]
Yes, I came from Windows (where all archiver provide such an archive privew) to Mac.

This comes in handy if I download archives where I only need a few file from, or have an untrusty source of the file and first want to peek into the archive before extracting it.

Maybe separate it from the current app workflow; like "Open With" > "Keka Archive Preview"

**Comment by gingerbeardman** [comment]
See 

Until Keka gets this there are numerous Quick Look plugins that offer peeking inside archives. Or there's BetterZip

**Comment by Vadammt** [comment]
Sorry for duplicate. I couldn't find this issue.

**Comment by aonez** [comment]
Thanks @gingerbeardman and @Vadammt. Better closed since this is a duplicate, any discussion better on #100. Salut!
