### ISSUE TITLE
Maintain "resource fork" setting between sessions

### ISSUE THREAD

**Issue by gabrielwhite** [aonez/Keka#238]
I always exclude MacOS resource forks from my archives, and I'm sure this is the same for many others.

I would like Keka to maintain this setting between sessions, so I don't have to check it every time I open the app.

Thanks.

**Comment by aonez** [comment]
@gabrielwhite enable this option on the Keka Preferences. There you can set permanent preferences. Next time you run Keka the exclude option will be enabled.

![screen shot 2018-07-11 at 15 33 11](https://user-images.githubusercontent.com/480163/42574884-d02bc4d8-851f-11e8-9f18-94e1be9f0fed.png)

**Comment by gabrielwhite** [comment]
Thanks! This design is non-obvious and probably is the opposite behaviour to what the majority of users would like.

I'd suggest BY DEFAULT retaining the state of the settings on the main app screen and have a setting in Preferences which is something like "Reset archive settings after quitting" (but better worded).

But at least my problem has been solved.

Thanks!

**Comment by aonez** [comment]
This way you can set one-time configuration and also set permanent configuration. Thanks for the feedback @gabrielwhite!
