### ISSUE TITLE
Archive as single files with 7zip

### ISSUE THREAD

**Issue by tisz0501** [aonez/Keka#24]
In the settings I've enabled 'Archive as single files'. But this feature is only working for zip compression. Can you fix this please? I'm on Sierra. I'm using the context menu feature as well but both doesn't work. Moving to the Keka.app dock or create with context both is archiving individual. 

Thank you.

**Comment by aonez** [comment]
**Archive as single files** makes a separated compressed file for any archives/folders you drop in. So if you drop **hello.txt** and **bye.txt**, you'll get **hello.7z** and **bye.7z**. If you uncheck this option, you'll get just one **compressed file.7z** containing both txts. Is that the case?

Also note that you have the temporary option in the advanced window, which only affects while Keka is onened:
![screen shot 2017-02-13 at 11 46 27](https://cloud.githubusercontent.com/assets/480163/22890013/4896a50e-f20b-11e6-9cd0-7a407fe91ffb.png)

And the global option in Preferences, that will be the default each time you call Keka:
![screen shot 2017-02-13 at 11 46 17](https://cloud.githubusercontent.com/assets/480163/22890016/4d804c50-f20b-11e6-8e44-77cfe34b7d53.png)

**Comment by tisz0501** [comment]
That is not what I meant. I have already changed the global settings and enabled 'Archive as single files'. But when I'm trying to archive some files for example a few photo's and I compress them with 7zip than they are not archived as single files but all as individual. When I change the settings back to zip compression than archiving as single files is working. It seems a bug.

**Comment by aonez** [comment]
I don't really understand.

> with 7zip than they are not archived as single files but all as individual

You mean each photo is compressed separately? Or all fotos become one 7z?

> When I change the settings back to zip compression than archiving as single

You mean with 7z format it does not work as you expect and with Zip format it does?

**Comment by tisz0501** [comment]
> You mean each photo is compressed separately? Or all fotos become one 7z?
> 
All photo is compressed separatly and I want them to compress them as one 7zip file instead of photo1.7zip photo2.7ip etc. 

Verstuurd vanaf mijn iPhone

**Comment by aonez** [comment]
@tisz0501, **Archive as single files** is just supposed to do that. Just disable this option (it comes disabled by default) if you want to get all files in one file, **photos.7z** in your case.

**Comment by tisz0501** [comment]
No it won't work. Where can I add a (video) screen record to show what I mean?

**Comment by aonez** [comment]
Dropbox or similar? You can also send it to me via mail: info@kekaosx.com

**Comment by tisz0501** [comment]
http://tinypic.com/r/348hgm0/9

Verstuurd vanaf mijn iPhone

> Op 18 feb. 2017 om 10:47 heeft aONe <notifications@github.com> het volgende geschreven:
> 
> Dropbox or similar? You can also send it to me via mail: info@kekaosx.com
>

**Comment by aonez** [comment]
Now I get it. This is a known bug: https://github.com/aonez/Keka/issues/4

You can add Keka to your dock and drag the files to it meanwhile. Sorry about the inconvenience.

**Comment by tisz0501** [comment]
That's the same bug mate. I tried that as well. Only zip compression and the others seems to work. No problem, thank you for creating such a great masterpiece. Much love for free software. Want to donate a small amount. Please let me know when the bug is solved. 

Verstuurd vanaf mijn iPhone

**Comment by aonez** [comment]
In case you did not noticed, I've closed #4 since in next version 1.1.0 this bug is no more an issue. You can try the [latest beta](https://github.com/aonez/Keka/releases) now, if you like 😊

**Comment by tisz0501** [comment]
Hi mate,

Thank you for letting this know! Very kind of you ;)

Have a great weekend.

Cheers.
