### ISSUE TITLE
Detect stale access bookmark on demand

### ISSUE THREAD

**Issue by grgo69** [aonez/Keka#241]
I have created archive with old version of keka, but now with new I cannot open files, it doesnt even ask me for passwords??

**Comment by gingerbeardman** [comment]
@grgo69 can any other apps extract the archive using the password?

**Comment by aonez** [comment]
Thanks @grgo69, just seeing the screenshot there’s definetly some problem there. Let me check the files and come back to you.

**Comment by grgo69** [comment]
@gingerbeardman Yes I was able to open file with another program (WinZip on Windows )

**Comment by aonez** [comment]
![screen shot 2018-07-17 at 23 23 43](https://user-images.githubusercontent.com/480163/42889745-747201fc-8aab-11e8-965e-7c1ba5c58fe9.png)

This seems like a rare character in the path (wether input or output) crashed the process.

**Comment by grgo69** [comment]
hi 
Now I tried again and did work but asked me to grant permission to disk and than it did ask for password and extract.
Before it didnt ask me to gran permission.
It might be due to the fact that I am running Bootcamp and I renamed the disk name of MacOS partition
Thanks, G

**Comment by aonez** [comment]
I'll try to detect the permission revocation and ask for it before Keka fails. I assume restarting Keka was enough in this case, since it detects bad permission on start.

Thanks @grgo69!

**Comment by grgo69** [comment]
@aonez I did restart computer as I had to start the bootcamp for Windows. I think I did restart KEKA before few times before I gave up

**Comment by aonez** [comment]
Oh ok, thanks @grgo69. I'll do some tests 👍

**Comment by aonez** [comment]
Anyway, just to be sure, @grgo69 the input/output paths have any special character or punctuation?

**Comment by grgo69** [comment]
@aonez I will send you paths to email

**Comment by aonez** [comment]
Just to state it here, path is the default downloads folder, no special characters or punctuation.

**Comment by aonez** [comment]
This should be fixed in 1.1.2, the file access is checked before every operation 🤓
