### ISSUE TITLE
BUG: Keka crashes when trying to unpack 7zip file

### ISSUE THREAD

**Issue by bjesuiter** [aonez/Keka#242]
## How to replay the issue
- double click on 7z file
- "Keka needs file access" - Message
- Klick 'Give Access'
- Macintosh HDD is preselected (as expected)
- click "Give Access to Keka"

## Expected 
- 7z file will be unpacked besides the original 7z file

## Observed: 
- Keka crashes with the message

> "Entpacken von "Filename" Fehlgeschlagen
> Fehlercode 2 mit "p7zip"
> Fataler Fehler

- The original 7z file which I wanted to extract, is gone.

## Additional Information
- 7z File could be password protected, can't test that now
- I testet unpacking it on the Desktop, after failing to unpack it on a mounted cryptomator volume. 
- When I try unpacking this file again, Keka still asks for access permission

## System
- MacBook Pro (15 Zoll, 2016)
- High Sierra Version 10.13.6

**Comment by aonez** [comment]
@bjesuiter thanks for the feedback! Can you remove the Keka bookmarks (close Keka first):

```
defaults delete com.aone.keka Bookmarks
```

This will force the recreation of the access bookmark. I'm almost finishing an updated version 1.1.2 that will fix most of those issues.

**Comment by aonez** [comment]
Also a system restart may fix this, since the system may deny Keka access to files until a reboot.

**Comment by gingerbeardman** [comment]
Maybe try granting access, quitt Keka, relaunch, then extract?

**Comment by aonez** [comment]
@bjesuiter can you try with the newly released 1.1.2 version?

**Comment by ParthPadg** [comment]
note: this is still happening on `1.1.3`, but the `defaults delete com.aone.keka Bookmarks` seems to have fixed it.

**Comment by aonez** [comment]
@ParthPadg also the original file deletion part? Can you take a look if there are any Keka logs in the Console.app? Thanks in advance!

**Comment by ParthPadg** [comment]
ah, sorry, I misread the original report. There wasn't any file deletion; I would double-click on a ZIP file, Keka would immediately crash, and the ZIP was untouched. 

I found this in the Console:
```Identifier:            com.aone.keka
11  com.aone.keka                 	0x00000001082031eb 0x108200000 + 12779
12  com.aone.keka                 	0x00000001082068a3 0x108200000 + 26787
       0x108200000 -        0x108230fff +com.aone.keka (1.1.2 - 2787) <53976661-EFF6-3A24-8F54-44AF4F82486B> /Applications/Keka.app/Contents/MacOS/Keka
```
hopefully that means more to you than it does to me! ;)

**Comment by ParthPadg** [comment]
[crashes.zip](https://github.com/aonez/Keka/files/2353980/crashes.zip)

**Comment by bjesuiter** [comment]
It seems to be fixed right now. Thank you!

Am Mi., 5. Sep. 2018 um 19:56 Uhr schrieb Parth <notifications@github.com>:

**Comment by aonez** [comment]
Glad to hear that @bjesuiter!

@ParthPadg those crashes where form the 1.1.2 version. If you find any problem with the current 1.1.3 let me know in a new issue! Thanks a lot for the feedback! :)

**Comment by ParthPadg** [comment]
@aonez that's strange; I'm on 1.1.3...but my issue is resolved, so I'll hang tight for now. Thanks for such an awesome tool!
