### ISSUE TITLE
Exclude Mac resource forks does not exclude .DS_Store

### ISSUE THREAD

**Issue by brianduguid** [aonez/Keka#248]
I just started using Keka to solve the issue of excluding ._ and .DS_Store files in tar.gz files to be used on a Linux box.  I have "Exclude Mac resource forks (eg: .DS_Store)" checked in preferences as well as the drag and drop box.  The ._ files are excluded, but the .DS_Store files are included.

Keka Version 1.1.2 (2787)
macOS High Sierra 10.13.6

**Comment by brianduguid** [comment]
![checked-left_unchecked-right](https://user-images.githubusercontent.com/14977973/43336754-07d983a2-91a0-11e8-930d-187250fba5a3.png)
The checkbox checked on the left and the checkbox unchecked on the right.

**Comment by alvarnell** [comment]
Technically, .DS_Store files are not resource forks, although I suppose Keka could handle them in the same way, I suppose.

-Al-

**Comment by aonez** [comment]
You're booth right. Technically the .DS_Store is not metadata, but Keka should ignore this one and other Mac specific hidden files when the flag is checked.

**Comment by aonez** [comment]
Fixed for 1.1.3. @brianduguid can you test it? [Keka-1.1.2r2794](https://t.keka.io/Keka-1.1.2r2794.7z)

**Comment by brianduguid** [comment]
It looks great.  Thank you.

![snip20180731_1](https://user-images.githubusercontent.com/14977973/43458565-ad49c856-9498-11e8-93f4-54e62471be35.png)

**Comment by davidysoards** [comment]
i'm having this same problem with 1.1.4 Both .DS_Store and _MACOSX folder are showing up in files opened on windows.

**Comment by aonez** [comment]
@davidysoards what format are you using?

**Comment by davidysoards** [comment]
.ZIP
I also don't like how it creates a folder within a folder, unlike the default Mac compress behavior.

**Comment by aonez** [comment]
@davidysoards Keka does not create the `_MACOSX` folder, so maybe you're creating those ZIP files with the bundled compressor?

> I also don't like how it creates a folder within a folder, unlike the default Mac compress behaviour.

Can you give me an example so I understand this on better?

**Comment by davidysoards** [comment]
i had set Keka as the default compressor using the helper KekaDefaultApp. I right-clicked a folder, selected compress and it created .zip folder. When I would open that zip, there would be another folder just like the one I had right clicked initially and also a _MACOSX folder inside.

**Comment by aonez** [comment]
@davidysoards the `Compress "file.ext"` option cannot be overridden by Keka. When you set it as the default application, this is only true for extraction. I must change that button text #291.

You can use the Keka services, that are in the bottom of the context menu:

![screen shot 2018-09-27 at 15 54 59](https://user-images.githubusercontent.com/480163/46151123-60248f80-c26e-11e8-9a18-c2ed1c7a3cdd.png)

Those also can be called with a keyboard shortcut:

![screen shot 2018-09-27 at 15 59 35](https://user-images.githubusercontent.com/480163/46151126-61ee5300-c26e-11e8-906f-412214e981b8.png)

**Comment by gingerbeardman** [comment]
How do you get those Services to list in the menu? Mine are all in a Services sub menu.

**Comment by aonez** [comment]
@gingerbeardman if you have more than four services, the group in the sub menu 😞

**Comment by aonez** [comment]
@gingerbeardman added #292 to talk about it.
@davidysoards please open a new issue if you still have problems with this.

**Comment by alanhg** [comment]
## config

![image](https://user-images.githubusercontent.com/9245110/128445759-f8e2c607-7af9-4866-b308-1a15284a2c87.png)
