### ISSUE TITLE
Download link fails on kekaosx.com

### ISSUE THREAD

**Issue by rustymyers** [aonez/Keka#25]
Hello, this probably isn't the best place to report this issue, but I'm awaiting forum access for the kekaosx.com site so here I am.

The download link, as well as a few others like Project, on the keka website (http://www.kekaosx.com/en/index.php) fail. The links report 404 for some reason. 

To reproduce the issue. Visit http://www.kekaosx.com/en/index.php and click the large green Download button (Download Keka 1.0.8 (19.2 MB). This produces the 404 page.

Thanks

**Comment by aonez** [comment]
It must work now. Playing with htaccess is not always recommended 😅
