### ISSUE TITLE
Keka keeps crashing

### ISSUE THREAD

**Issue by lifehome** [aonez/Keka#253]
## Steps to reproduce
1) Open Keka or uncompress a file
2) It crashed.

## Crash Log
https://gist.github.com/lifehome/22ab80f15691f41ef770e9aa13ad0cf0

**Comment by aonez** [comment]
Can you share the Keka preferences file?

Is located on:

```
~/Library/Preferences/com.aone.keka.plist
~/Library/Containers/com.aone.keka/Data/Library/Preferences/com.aone.keka.plist
```

I'm mostly sure just deleting those files (the first is for versions older than 1.1) will make Keka work, but having that file to replicate the issue will help :)
