### ISSUE TITLE
Contextual 'Send to Keka' menu does not respect compression format

### ISSUE THREAD

**Issue by jasonfist** [aonez/Keka#256]
Even if Keka is set to compress a file to .zip format, the file created is a .7z is you control-click and choose 'Send to Keka' in the contextual menu.

**Comment by aonez** [comment]
@jasonfist the context menu items will respect the default format you've selected in the Keka preferences, unless you have Keka opened, in that case will use the currently selected format.

So for example, if you have ZIP set in the Keka preferences and 7Z selected in the main window:

- If Keka is closed, the context menu actions will create ZIP files
- If Keka main window is opened, the context menu actions will create 7Z files

**Comment by jasonfist** [comment]
Got it. Thanks!

**Comment by aonez** [comment]
@jasonfist which was the issue for you? The main window opened or the default format selected? Maybe I can improve this just adding a checkbox in the preferences.

**Comment by jasonfist** [comment]
I didn't realise there was a default compression option in the preferences. I just assumed that the main Keka window's selected format (or last selected format, if the app was closed) would be used.

**Comment by gingerbeardman** [comment]
I also had this confusion. It's confounded by both windows looking quite similar.
