### ISSUE TITLE
Attempting to operate with two or more files from different folders stalls Keka

### ISSUE THREAD

**Issue by zdlo** [aonez/Keka#267]
When I right click and "Open" multiple RAR files, even just 2, Keka runs and stalls without even showing an extraction window. It requires force quitting afterwards.

(Keka 1.1.3 on macOS 10.13.6)

**Comment by gingerbeardman** [comment]
Try `ForceOldQueue` hidden preference?

https://github.com/aonez/Keka/wiki/Hidden-configuration

**Comment by zdlo** [comment]
> Try ForceOldQueue hidden preference?

Didn't have any effect.

**Comment by aonez** [comment]
@zdlo it happens with more formats or just RAR?

Can you enable the Keka logging and share what the Console.app (filtered with Keka) says?

https://github.com/aonez/Keka/wiki/Console-verbose

**Comment by zdlo** [comment]
default	16:23:49.586900 -0300	launchservicesd	CHECKIN:0x0-0x35bc5b9 99584 com.aone.keka
default	16:23:49.682094 -0300	Keka	Updating user defaults from 2809...
default	16:23:49.684933 -0300	Keka	Cleaning Keka proccesses...
default	16:23:50.089239 -0300	Keka	Dev mode enabled
default	16:23:50.090466 -0300	Keka	Dev reader mode enabled
default	16:23:50.091711 -0300	Keka	Running on OS X/macOS version 10.13.6 (Build 17G65)
default	16:23:50.092777 -0300	Keka	Running Keka (WEB) version 1.1.3 (2809)
default	16:23:50.095515 -0300	Keka	Used localization: en
default	16:23:50.280340 -0300	Keka	Adding 2 files
default	16:23:50.281755 -0300	Keka	Waiting for more input: 0.250000
default	16:23:50.283769 -0300	Keka	Requesting access to all bookmarks...
default	16:23:50.285203 -0300	Keka	Bookmarks updated: 2
default	16:23:50.286691 -0300	Keka	Bookmark paths updated: (
    "/Users/***",
    "/Volumes"
)
default	16:23:50.358035 -0300	Keka	DEPRECATION: SUUpdater is now deprecated. Please use SPUStandardUpdaterController as a nib instantiated replacement, or SPUUpdater.
default	16:23:50.495560 -0300	org.sparkle-project.Downloader	Faulting in NSHTTPCookieStorage singleton
default	16:23:50.495609 -0300	org.sparkle-project.Downloader	Faulting in CFHTTPCookieStorage singleton
default	16:23:50.495646 -0300	org.sparkle-project.Downloader	Creating default cookie storage with default identifier
default	16:23:50.497666 -0300	org.sparkle-project.Downloader	TIC Enabling TLS [1:0x7fd788407af0]
default	16:23:50.497726 -0300	org.sparkle-project.Downloader	TIC TCP Conn Start [1:0x7fd788407af0]
default	16:23:50.497915 -0300	org.sparkle-project.Downloader	Task <588EB28B-144A-4ECE-AC05-DA80BE904275>.<1> setting up Connection 1
default	16:23:50.497948 -0300	org.sparkle-project.Downloader	[1 <private> <private>] start
default	16:23:50.533848 -0300	Keka	Detecting needed path access...
default	16:23:51.173788 -0300	org.sparkle-project.Downloader	TIC TLS Event [1:0x7fd788407af0]: 1, Pending(0)
default	16:23:51.925853 -0300	org.sparkle-project.Downloader	TIC TLS Event [1:0x7fd788407af0]: 2, Pending(0)
default	16:23:51.967728 -0300	org.sparkle-project.Downloader	TIC TLS Event [1:0x7fd788407af0]: 11, Pending(0)
default	16:23:51.968606 -0300	org.sparkle-project.Downloader	TIC TLS Event [1:0x7fd788407af0]: 12, Pending(0)
default	16:23:51.969229 -0300	org.sparkle-project.Downloader	TIC TLS Event [1:0x7fd788407af0]: 14, Pending(0)
default	16:23:52.909348 -0300	org.sparkle-project.Downloader	TIC TLS Trust Result [1:0x7fd788407af0]: 0
default	16:23:53.788634 -0300	org.sparkle-project.Downloader	TIC TLS Event [1:0x7fd788407af0]: 20, Pending(0)
default	16:23:53.789040 -0300	org.sparkle-project.Downloader	TIC TCP Conn Connected [1:0x7fd788407af0]: Err(16)
default	16:23:53.789353 -0300	org.sparkle-project.Downloader	TIC TCP Conn Event [1:0x7fd788407af0]: 1
default	16:23:53.789478 -0300	org.sparkle-project.Downloader	TIC TCP Conn Event [1:0x7fd788407af0]: 8
default	16:23:53.789588 -0300	org.sparkle-project.Downloader	TIC TLS Handshake Complete [1:0x7fd788407af0]
default	16:23:53.808963 -0300	org.sparkle-project.Downloader	Task <588EB28B-144A-4ECE-AC05-DA80BE904275>.<1> now using Connection 1
default	16:23:53.809058 -0300	org.sparkle-project.Downloader	Task <588EB28B-144A-4ECE-AC05-DA80BE904275>.<1> sent request, body N
default	16:23:58.790633 -0300	org.sparkle-project.Downloader	Task <588EB28B-144A-4ECE-AC05-DA80BE904275>.<1> received response, status 301 content K
default	16:23:58.791209 -0300	org.sparkle-project.Downloader	Task <588EB28B-144A-4ECE-AC05-DA80BE904275>.<1> response ended
default	16:23:58.791661 -0300	org.sparkle-project.Downloader	Task <588EB28B-144A-4ECE-AC05-DA80BE904275>.<1> now using Connection 1
default	16:23:58.791717 -0300	org.sparkle-project.Downloader	Task <588EB28B-144A-4ECE-AC05-DA80BE904275>.<1> sent request, body N
default	16:23:59.644946 -0300	Keka	LSExceptions shared instance invalidated for timeout.
default	16:23:59.654744 -0300	org.sparkle-project.Downloader	Task <588EB28B-144A-4ECE-AC05-DA80BE904275>.<1> received response, status 302 content K
default	16:23:59.654966 -0300	org.sparkle-project.Downloader	Task <588EB28B-144A-4ECE-AC05-DA80BE904275>.<1> response ended
default	16:23:59.655706 -0300	org.sparkle-project.Downloader	Task <588EB28B-144A-4ECE-AC05-DA80BE904275>.<1> now using Connection 1
default	16:23:59.655773 -0300	org.sparkle-project.Downloader	Task <588EB28B-144A-4ECE-AC05-DA80BE904275>.<1> sent request, body N
default	16:24:01.166953 -0300	org.sparkle-project.Downloader	Task <588EB28B-144A-4ECE-AC05-DA80BE904275>.<1> received response, status 200 content K
default	16:24:01.167230 -0300	org.sparkle-project.Downloader	Task <588EB28B-144A-4ECE-AC05-DA80BE904275>.<1> response ended
default	16:24:01.173692 -0300	org.sparkle-project.Downloader	TIC TCP Conn Cancel [1:0x7fd788407af0]
default	16:24:01.173936 -0300	org.sparkle-project.Downloader	[1 <private> stream, pid: 99625, url: https://www.keka.io/update, traffic class: 200, tls] cancelled
	[1.1 A27D27FC-F55B-4192-A632-22433DAAD9F7 <private>.58686<-><private>]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 10.676s, DNS @0.000s took 0.201s, TCP @0.205s took 0.468s, TLS took 2.617s
	bytes in/out: 17499/798, packets in/out: 18/10, rtt: 0.651s, retransmitted packets: 0, out-of-order packets: 10
default	16:24:01.174211 -0300	org.sparkle-project.Downloader	TIC TCP Conn Destroyed [1:0x7fd788407af0]
error	16:24:01.175001 -0300	org.sparkle-project.Downloader	TIC Read Status [1:0x0]: 1:57
error	16:24:01.175028 -0300	org.sparkle-project.Downloader	TIC Read Status [1:0x0]: 1:57
default	16:25:21.394747 -0300	kernel	process Keka[99584] thread 26630211 caught burning CPU! It used more than 50% CPU over 180 seconds (actual recent usage: 97% over ~92 seconds).  Thread lifetime cpu usage 90.440271s, (82.596610 user, 7.843661 sys) ledger balance: 90009879807 mabs credit: 90012957546 mabs debit: 3077739 mabs limit: 90000000000 mabs period: 180000000000 ns last refill: 92020998946 ns.
default	16:25:21.456896 -0300	symptomsd	Received CPU usage trigger: 
  Keka[99584] () used 90.01s of CPU over 92.02 seconds (averaging 97%), violating a CPU usage limit of 90.00s over 180 seconds.

**Comment by zdlo** [comment]
> @zdlo it happens with more formats or just RAR?

I'll have to check that later if necessary.

**Comment by zdlo** [comment]
Tried with multiple ZIP files, worked fine.

The RAR files were the kind that triggers the extraction through multiple RAR containers (r00, r01, r02...). When I select a single main RAR file, it extracts. The log shows what happens when I select a couple of main RAR files and attempt to extract them at the same time.

Queueing the files for sequential operation (#21) would probably solve this too, I suppose, as well as shortening the extraction time. I read that you were considering to cancel implementing "one operation at a time", and queueing in multiple operations instead (#202). I wonder how that would affect the RAR archives in multiple containers.

**Comment by aonez** [comment]
> The log shows what happens when I select a couple of main RAR files and attempt to extract them at the same time

Thanks for that, now I can do some tests. With the "burning CPU" message in the log I thought there's an infinite bucle there...

> you were considering to cancel implementing "one operation at a time"

Note that for this mode to work you need to pass 10+ operations at once. With only two RAR files the normal queue is working.

**Comment by aonez** [comment]
@zdlo can you check 1.1.4?

**Comment by aonez** [comment]
@zdlo Could you check this build? https://t.keka.io/Keka-1.1.4-norarcheck.7z

**Comment by aonez** [comment]
@zdlo If it also fails, could you give me more information about the RAR volumes you use? Total size, number of volumes, format (4 or 5)... Or if you can share them it will be awesome.

**Comment by zdlo** [comment]
Still no change.

The log shows what happened when I attempted to extract two RAR archives that had 10 50MB volumes each. I had also tried it with various different archives with more volumes of 50MB each. Not sure how to see their format.

**Comment by zdlo** [comment]
Yes, their extensions are .rar, .r00, .r01 and so on.

**Comment by aonez** [comment]
@zdlo makes any difference if instead 

> right click and "Open"

you drop the files to the Dock icon or the Advanced Window?

Here you have two test files, let me know if they also cause the issue: [test.zip](https://github.com/aonez/Keka/files/2407785/test.zip)

**Comment by zdlo** [comment]
> @zdlo makes any difference if instead
> 
> > right click and "Open"
> 
> you drop the files to the Dock icon or the Advanced Window?
> 
Same result in all three ways.

> Here you have two test files, let me know if they also cause the issue

Test files extracted fine. Perhaps something to do with the volume sizes, or the compression method? I've tried with different archives from different sources, and the one thing in common was the volumes being large (~50MB).

**Comment by aonez** [comment]
I’ve tested with 100MB volumes before and did not crashed.

Can you share with me some of these files? You can contact via mail/Twitter also...

**Comment by aonez** [comment]
Turns out the issue was in the file access check. Dropping two or more files that are stored in different folders causes an infinite bucle. It affects compression and extraction.

Thanks a lot for spotting this and all the subsequent feedback, @zdlo 👍

**Comment by aonez** [comment]
Version 1.1.5 released with this one fixed! Thanks @zdlo and @gingerbeardman for the feedback!
