### ISSUE TITLE
APK File info | New Keka Break QuicklookAPK

### ISSUE THREAD

**Issue by JARVIS-AI** [aonez/Keka#276]
Hello
Thanks for best clean archive manager

One issue that I have found,

There is one QuickLook plugin that show info about APK files 
And there is another for IPA files

The new versions after 1.0.16 version corrupted this mechanism

Up to 1.0.16 version is OK

 I think because you design a new mime type and make a icon for it and this collision with APK quicklook plugin

But in new version IPA files are OK and the QL Plugins working correctly

In new version you have designed a orange icons for APK and set mime type for it so
QL pl not work anymore in versions after 1.0.16 

So can you make it possible return it back for new versions
I mean remove that mime type known for keka that don't change the icons.

Or another way or better way maybe you have for this
The QL plugins that shows information about APK files and this PL is very important for Applications developers because meta data in APK files shown themselves with this PL and we dont need to open each APK in Studio or IDE and decompress them.

Note : I installed new version and QL Plugin break and return to 1.0.16 Keka again QL Plugins Works
and in macOS icons back from orange to their real App's icons. (I TEST IT)

Thanks in advance

**Comment by aonez** [comment]
Hi @JARVIS-AI, can you share that pluguins? Thanks!

**Comment by JARVIS-AI** [comment]
yes sure
i forgot its github page so i upload it here you can download it

https://www.dropbox.com/s/ebb3aunwzpofxi4/QuickLookAPK?dl=0

**Comment by aonez** [comment]
Thanks @JARVIS-AI. The plugin looks for UTI `com.android.package-archive` and Keka declares the `apk` package as `public.archive.apk`, that's why it breaks that one. I'm gonna send a pull update to the plugin repository, so it uses booth UTI and also the MIME type (most commonly used) `application/vnd.android.package-archive`.

Can you try this build?

[QuickLookAPK.qlgenerator.zip](https://github.com/aonez/Keka/files/2352789/QuickLookAPK.qlgenerator.zip)

**Comment by JARVIS-AI** [comment]
Yes this is work. Really good man you are in high rank top archiver with cool support (what am i saying ;) )

Completely Working with new version and the new qlgenerator is about 400 KB bigger than the original one and changes for UTI worked with added mime type to ql plugin

The qlgenerator that you have edited is completely working with new version and the icons are almost correct with both side 

If the APK package is NULL, corrupted or not compiled and compressed correctly so the icon remains as Orange APK that Keka set to it.

And if the APK compressed, compiled correctly so the qlgenerator work with it and show the package icon not orange APK the Keka has

This is what the Keka should be, great design I love it

Also I checked the pull in ql plugin GitHub and read about your changes,
I documented that and I will use it for other ql plugins for Mojave new quicklook and maybe it will be useful for other ql plugins or maybe new APK for Mojave quicklook has better functional for these and not needed plugins

I don't have internet to download the latest Mojave but I have beta 2 , and still I don't not test new Keka on it cause of some project that I need to finish them soon in High Sierra and not to waste my time for installing OS so I don't change the my MacBook OS to Mojave and do some development stuff

By The Way thanks for this quick fix 

So we should wait for ql plugin author to release the new version with your changes and there is no need to fix for Keka ?
Also if need any help for Keka itself just say it ;)
Thanks for pull request in Ql plugin GitHub repo

**Comment by aonez** [comment]
> So we should wait for ql plugin author to release the new version with your changes and there is no need to fix for Keka ?

Sure, I would wait for the [QuickLookAPK](https://github.com/hezi/QuickLookAPK) developer to merge the pull and then get it's own release. If there's some other changes needed in Keka, they'll be available in 1.1.4. Just shared a QuickLookAPK compiled version with you for test purposes :)

**Comment by gingerbeardman** [comment]
@aonez the Travis build has failed for that PR

**Comment by aonez** [comment]
> the Travis build has failed for that PR

@gingerbeardman yep, the current source of that repo fails, nothing to do with the PR...

**Comment by aonez** [comment]
@JARVIS-AI the pull is already merged, although the compiled file is not updated. You can either use the one I've shared, compile it yourself or ask for it to be updated. Closing this one now :)
