### ISSUE TITLE
.xpi: automatic -> compresses to zip, should expand (.xpi is zip)

### ISSUE THREAD

**Issue by ProBackup-nl** [aonez/Keka#277]
Mozilla Extension files are ending in .xpi which is a disguise for a zip file.

I would **expect** Keka version 1.1.3 (2809) in Automatic mode to extract the files inside.

What happens? The .xpi is compressed to a .zip file.

**Comment by aonez** [comment]
Added to the supported extraction list. Thanks for the tip! 👍

**Comment by gingerbeardman** [comment]
How about .IPA (also zip) and .JAR (also zip, I think)

**Comment by aonez** [comment]
> How about .IPA (also zip) and .JAR (also zip, I think)

@gingerbeardman adding IPA too! JAR (along with APK and APPX) where added on 1.1.0 https://github.com/aonez/Keka/issues/170#issuecomment-380127696

**Comment by gingerbeardman** [comment]
Could we also add .safariextz (zipped legacy Safari Extension) @aonez

**Comment by alvarnell** [comment]
Those are going away very shortly, in the next WebKit.

Sent from my iPad

-Al-

**Comment by gingerbeardman** [comment]
> Those are going away very shortly, in the next WebKit.

@alvarnell support for them is, hence my use of "legacy". I will still have the need to work with old files on my drive.

**Comment by alvarnell** [comment]
Not only support, they will no longer load with WebKit currently in test.

**Comment by gingerbeardman** [comment]
> Not only support, they will no longer load with WebKit currently in test.

Yes, that's what I meant when I said they will not be supported. 

The Safari/WebKit team really have really screwed extension creators & users.

**Comment by aonez** [comment]
> add .safariextz

Makes sense @gingerbeardman, now that they're legacy more than ever.

@alvarnell As far as I know the current version 12 of Safari already does not load extensions, only using the Extension Builder. I myself already had to [rebuild an extension](https://github.com/aonez/GitHubCounter) to be able to use it. Really sad about this, but extensions never got to a Firefox/Chrome feature capable level.

> The Safari/WebKit team have really screwed extension creators & users.

Yep.  I suppose the Extensions Gallery did not worked at all and bundling extensions in a container app and throw it to the MAS is easier for them.

**Comment by alvarnell** [comment]
Safari 12.1.1 is more selective about which extensions it loads, but I am still able to load many (all) as long as they come from the extensions gallery.

Safari Technology Preview 12.2 won’t load any .safariextz and the option at the bottom of the Extensions preference window “Automatically update extensions from the Safari Extensions Gallery” has been removed. The only extension allowed must come from the Mac App Store.

-Al-

**Comment by gingerbeardman** [comment]
In addition, Safari Technology Preview in its most recent version kicked out everything but Mac App Store extensions.
