### ISSUE TITLE
Support for archives generated with yaa (command line)

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#280]
I just found out macOS has built-in tools to support compression using LZFSE (Apple's compression format that is very efficient, ie. it has a very good power-usage vs compression ratio). 

> LZFSE claims: better compression, 3 times faster (compression) than zlib and 60% reduction in energy use. In other words: roughly equivalent to ZLIB level 5, but many times quicker! 

![](https://imgur.com/2KNLyq7.png)

The in-built command, yaa, to compress/expand archives using a variety of algorithms: 
- _algorithm (archive file header)_
- lzfse (pbze)
- lzma (pbzx)
- lz4 (pbz4)
- zlib (pbzz)

I think it would be great to support the YAA format with all algorithms. Personally, I would be very happy with super fast LZFSE archiving, with the tradeoff of slightly less compression. For me it would be the new default. 

Maybe a good choice of file extension would be .PBZ?

### Commands
Ref: https://www.keolo.com/blog/post/terminal-commands/

Compressing a folder using LZFSE
`yaa archive -d Folder -o File.yaa`

Decompressing a folder using LZFSE
`yaa extract -i File.yaa -d Folder`

### Benchmarks
Ref: https://artandlogic.com/2017/02/save-time-energy-libcompression/

![](https://cdn.artandlogic.com/wp-content/uploads/filesize-768x523.png)
File sizes, in MB. Shorter bars are better.

![](https://cdn.artandlogic.com/wp-content/uploads/time-768x593.png)
Time in seconds. Shorter bars are better.

**Comment by gingerbeardman** [comment]
My tests, using 30MB of English and Japanese text.

### Keka 
```
7z (Normal)

~ 0m13.5s

Result: 1.2MB
```

### LZMA
```
$ time yaa archive -d 2018-08-29/ -o LZMA.yaa -a lzma

real	0m7.413s
user	0m22.959s
sys	0m0.345s

Result: 1.2MB
```

### LZFSE
```
$ time yaa archive -d 2018-08-29/ -o LZFSE.yaa -a lzfse

real	0m0.226s
user	0m0.619s
sys	0m0.036s

Result: 4.2MB
```

### ZLIB
```
$ time yaa archive -d 2018-08-29/ -o ZLIB.yaa -a zlib

real	0m0.419s
user	0m1.159s
sys	0m0.042s

Result: 6.6MB
```

### LZ4
```
$ time yaa archive -d 2018-08-29/ -o LZ4.yaa -a lz4

real	0m0.073s
user	0m0.107s
sys	0m0.044s

Result: 12.3MB
```

**Comment by gingerbeardman** [comment]
My tests, using 755MB PlayStation game (CUE+BIN+jpgs).

### Keka 
```
7z (Normal)

~ 1m17.0s

Result: 634.3MB
```

### LZMA
```
$ time yaa archive -d Corpus/ -o LZMA.yaa -a lzma

real	1m9.776s

Result: 642.3MB
```

### LZFSE
```
$ time yaa archive -d Corpus/ -o LZFSE.yaa -a lzfse

real	0m5.879s

Result: 678.8MB
```

### ZLIB
```
$ time yaa archive -d Corpus/ -o ZLIB.yaa -a zlib

real	0m9.578s

Result: 675.9MB
```

### LZ4
```
$ time yaa archive -d Corpus/ -o LZ4.yaa -a lz4

real	0m1.692s

Result: 706.2MB
```

**Comment by gingerbeardman** [comment]
Some additional references: 

https://github.com/sskaje/unzip-lzfse
https://encode.ru/threads/2221-LZFSE-New-Apple-Data-Compression
http://fileformats.archiveteam.org/wiki/LZFSE

**Comment by aonez** [comment]
Amazing report @gingerbeardman!

**Comment by aonez** [comment]
> 60% reduction in energy use

I would love to test this

**Comment by aonez** [comment]
Just tested that the YAA binary is sandbox usable... So Keka can directly use it from `/usr/bin/yaa` ✌️

**Comment by gingerbeardman** [comment]
I think Keka will be a trend setter for this archive format :) 👍
