### ISSUE TITLE
Toolbar icons missing in MAS version

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#288]
Following the addition of assets for better image performance, the toolbar icons are unavailable on the MAS version. Only affects to the non unified toolbar (legacy, mostly for use in Mac OS X 10.9) and the Preferences -> Compression item.

**Comment by GuillaumeBringard** [comment]
Hello

I just bought Keka from the Mac App Store (Version 1.1.4 (2867)), but it's still missing one icon (the second one) in the Preferences tab, see screenshot (with relevant Console log in the background)
![keka_missing_icon](https://user-images.githubusercontent.com/43640074/46141448-3bbbb980-c254-11e8-9ef4-80f59d20d3f4.png)

Best regards

**Comment by aonez** [comment]
Yes, sorry @GuillaumeBringard. The fixed version 1.1.5 was pushed last Friday, but is being hold by the Apple reviewer. Hope to release it very soon.

**Comment by aonez** [comment]
1.1.5 released! The update should appear soon on MAS 😊 Thanks @GuillaumeBringard for the feedback!
