### ISSUE TITLE
Official RARLAB binaries + Create RAR files!

### ISSUE THREAD

**Issue by TCB13** [aonez/Keka#295]
Hello, many thanks for this great App, I've been using it for a while and as we all know it lacks the ability to create RAR files. I believe this restriction is due to legal issues related to RARLAB's products, however I'm going to point a few things.

- Keka already uses RARLAB code but "Modified by aONe for use in Keka";
- Archiver for Mac has the ability to create RAR files using the RARLAB's official, unmodified binary;
- RAR command line tools use whatever license is installed on the system - no need to send anything built in;

Why can't we have nice things on Keka as well? ;) Let me show you how Archiver does it to avoid legal issues:

![captura de ecra 2018-10-01 as 12 00 18](https://user-images.githubusercontent.com/6315832/46284978-ab41e980-c571-11e8-9c7d-a2b6be8ae86d.png)
![captura de ecra 2018-10-01 as 12 00 35](https://user-images.githubusercontent.com/6315832/46284980-ada44380-c571-11e8-8999-10ab0cf2b8e1.png)
![captura de ecra 2018-10-01 as 12 00 50](https://user-images.githubusercontent.com/6315832/46284984-aed57080-c571-11e8-8abf-f2a1d4de0913.png)

**They shift the responsibility of the RAR licensing from themselves to the final user**, provide the license agreement and all that stuff. **They avoid App Store issues by downloading it later as an extra**. A solution like this would greatly improve Keka without having to deal with extra stuff. The final **user is supposed to have a valid RAR license installed on their home folder** or some other alternative places where RARLAB's search.

The other advantage of using official RAR binaries is a faster integration of new RAR versions. RARLAB's binaries output is very stable, it hasn't changed for years, however there have been a lot of optimizations under the hood. Without the need for a custom version it would be faster to get updates.

**Comment by aonez** [comment]
Thanks a lot for the feedback @TCB13!

About the modified binary, it just uses a few patches so updating to newer versions is very quick. Usually is more about knowing when they're released.

About RAR compression, I've already contacted with RARLAB and they did not gave permission to bundle the binary. Using an external binary is not allowed in sandbox, so I'm not sure what Archiver does there. Is that app sandboxed?

**Comment by aonez** [comment]
Relative to #123

**Comment by aonez** [comment]
> Archiver places the RARLAB's binaries at...

I was just looking at this 😂. So the web version is not sandboxed and can use it. I'm currently sandboxing both MAS and WEB versions so the development works for both. Maybe in the future sandbox will be required for all macOS apps.

Anyway maybe I should give an non-sandboxed alternative download. This makes me think about the issues I'm having in the Apple Store review process for asking file access support to the user, and how some users will be happy with no sandbox at all for some applications.

**Comment by aonez** [comment]
I forgot to mention that RAR compression was developed for Keka 1.1.0, but sandbox killed that development. You can still try (and use) this in [Keka-1.1.0-rc.1](https://github.com/aonez/Keka/releases/tag/v1.1.0-rc.1).

**Comment by TCB13** [comment]
> > Anyway maybe I should give an non-sandboxed alternative download. This makes me think about the issues I'm having in the Apple Store review process for asking file access support to the user, and how some users will be happy with no sandbox at all for some applications.

I believe Keka's permission system is very, very well implemented. The preferences allow users to control in an easy and transparent way what Keka has access to and this is very good, however I would give up the sandbox for a version that could use RARLAB's binaries.

If you consider this "non-sandboxed alternative" please note one thing where Archiver fails: Archiver always downloads some old version of RAR CLI tools and stores them at `/Users/TCB13/Library/Application Support/com.incrediblebee.Archiver3`. In a better implementation, before downloading, it should check if the system already has the binaries installed at `/usr/local/bin/` and other common paths and use them.

**Comment by aonez** [comment]
> I believe Keka's permission system is very, very well implemented. The preferences allow users to control in an easy and transparent way what Keka has access to and this is very good

Thanks a lot for that :)

> downloads some old version of RAR CLI tools

Noticed that, 5.00 version, but since your screenshot had 2018 version thought it was just my case.

The rc.1 version (and newer, although inactive in sandbox) uses the user installed binaries, so no problem there. Implementing the download will be the improvement in Keka, was suggester in #295.

**Comment by TCB13** [comment]
> Noticed that, 5.00 version, but since your screenshot had 2018 version thought it was just my case.

I replaced the binaries myself due a to a bug where the old version crashed with some RAR files protected by password. But as you saw, by default it uses a very old version.

The fact the I could replace the binaries without issues just proves that the CLI tools output is very stable.

**Comment by aonez** [comment]
Just for the record, this was the capture of the downloaded by Archiver:

![screen shot 2018-10-01 at 13 37 02](https://user-images.githubusercontent.com/480163/46287533-22cc4480-c583-11e8-9223-1528fbc4fa9f.png)

**Comment by aonez** [comment]
I'm closing this one in favor of #123. Thanks for all the feedback @TCB13!
