### ISSUE TITLE
Suggestion: for .app, use its original filename for default extraction location

### ISSUE THREAD

**Issue by advicepyro** [aonez/Keka#297]
I might be misremembering, but in older versions of Keka when I extract an archive containing a .app, and I opt to have Keka prompt me each time where to extract the files, the .app takes on its original name. For example, extracting FileZilla from `FileZilla_3.37.1_macosx-x86.app.tar.bz2` produces `FileZilla.app`

Now this continues to apply if I have Keka extract beside the archive or in the folder of my choosing. But if I choose a folder, and don't change the destination filename, the resulting .app takes on the name of the archive, producing `FileZilla_3.37.1_macosx-x86.app.tar.bz2.app`

Maybe have a way to detect if there's an .app in advance, and set the default destination name to be that?

**Comment by aonez** [comment]
Thanks for the feedback @advicepyro! This was indeed changed in 1.1.X, can't remember exactly the revision.

I'll consider to do this when possible and only if the file contains one file or bundle (.app being a bundle), since it makes sense to keep the original name.
