### ISSUE TITLE
How to modify the encoding method?

### ISSUE THREAD

**Issue by andyliu24** [aonez/Keka#299]
I am a native Chinese speaker. I have to receive files from Windows that are encoded in GBK, but keka will treat them as ANSI, so the extracted files are garbled. 

How do I choose the encoding method of the files when decompressing? (It seems that Unarchiver could handle it)?

![123](https://user-images.githubusercontent.com/24978668/46427731-bb75e680-c774-11e8-9375-75b657c6bef4.jpg)

**Comment by aonez** [comment]
@andyliu24 this is a know issue #12. Sadly no fix yet, but I'm working on it. Hopefully would not take too much time until this is fixed.

I'm closing this ticket in favor of #12. Thanks for the feedback :)
