### ISSUE TITLE
Revert/change to the original/old icon, please!

### ISSUE THREAD

**Issue by LivorMortis** [aonez/Keka#300]
The new icon is quite ugly. It was much better the old one. Please, consider redesigning the icon or reverting to the old one. Thanks for your attention.

**Comment by gingerbeardman** [comment]
You can do this yourself: see https://github.com/aonez/Keka/issues/281

**Comment by LivorMortis** [comment]
I can live with the new icon anyway. Replacing the icon by the "get info" method is not a solution, just an illusive patch. It's ok, it was just a suggestion. The old icon was perfect, though. The new one is not that bad, perhaps a bit naive. That's all. Thanks for your help.

**Comment by aonez** [comment]
Thanks @LivorMortis for the feedback. You’re not the first or the last to dislike the new icon... it’s really hard to do something that all people like. I’ll try to twek the brightness and the color of it, but the old one can’t be used anymore, just in the legacy versions. You can apply it with the “Get Info” as pointed by @gingerbeardman, I get is not what you want though.
