### ISSUE TITLE
Correct French translations

### ISSUE THREAD

**Issue by ejb4u** [aonez/Keka#302]
There are some translations missing in French.
I've uploaded the latest files and added the missing translations. Some non consistencies were also corrected.
The translation files are attached.
[KekaFrench.zip](https://github.com/aonez/Keka/files/2456097/KekaFrench.zip)

**Comment by aonez** [comment]
Thanks a lot @ejb4u! You can check this build with your changes: [Keka-r2952-fr.7z](https://t.keka.io/Keka-r2952-fr.7z)

How would you like to appear in the credits?

**Comment by ejb4u** [comment]
[Localizable.strings.zip](https://github.com/aonez/Keka/files/2483339/Localizable.strings.zip)
There was a space missing in the Localizable.strings file. Here is the latest release.

You can add me as "Ejb4u", it's fine, it's my developer name ;-)
But the credit also goes to a friend who reviewed all the translations and who found some improvements. Could you please add him to the credits as "Jayflo276" ?

We tried your build with the translations, and except for the space missing, everything is fine.
By the way, when do you expect to release a new version of Keka with the updated French translations?

Thanks

**Comment by aonez** [comment]
Thanks a lot @ejb4u! I'll add both of you :)

> By the way, when do you expect to release a new version of Keka with the updated French translations?

Version 1.0.5 was blocked in the MAS review process, so I was forced to rework (again) some of the file access elements of Keka before a new release can be publicly available. Hopefully no more than two weeks...

**Comment by aonez** [comment]
@ejb4u 1.1.5 released with your updates! Thanks again 😁

**Comment by aonez** [comment]
@ejb4u I'm so so sorry I've missed to add you both on the credits! I've added you right away, for the next v1.2.3 revision.

Thanks again for your collaboration!
