### ISSUE TITLE
Quit Keka after Extraction

### ISSUE THREAD

**Issue by 7s3** [aonez/Keka#307]
Is it possible to have Keka quit after extraction?
I have the feature enabled that closes the app when there are no windows open, but unfortunately it doesn't do what I mentioned above.

Thanks!

**Comment by aonez** [comment]
@7s3 would be amazing if you can share with me the Keka preferences file so I can try to replicate this issue. It is located here:

```
~/Library/Containers/com.aone.keka/Data/Library/Preferences/com.aone.keka.plist
```

Just zip this `plist` file and upload it here.

Then, take a look at this thread, this might fix your issue: https://github.com/aonez/Keka/issues/200#issuecomment-395018033

Let me know if that helps.

**Comment by 7s3** [comment]
I already had the "Quit after extraction" setting checked, but I toggled it off and on.
Maybe the setting wasn't sticking?

plist before:
[com.aone.keka.plist.zip](https://github.com/aonez/Keka/files/2477802/com.aone.keka.plist.zip)

plist after:
[com.aone.keka.plist 2.zip](https://github.com/aonez/Keka/files/2477837/com.aone.keka.plist.2.zip)

This feature seems to be working now, although it takes about 8 seconds for the app to quit after the progress box closes.

**Comment by aonez** [comment]
Thanks @7s3! I'll test with the preferences file 😊

> although it takes about 8 seconds for the app to quit after the progress box closes

This is a feature, so in case you click on the notification that appeared on Notification Center Keka can handle it properly. You can disable this feature though:
`GrowlBlocksExit ` [wiki/Hidden-configuration#notifications](https://github.com/aonez/Keka/wiki/Hidden-configuration#notifications)

**Comment by 7s3** [comment]
Working perfectly now, thanks!

**Comment by aonez** [comment]
Sadly the plists files are virtually identical, with the proper value set to quit. So, again as in #200, I'm not sure what is happening here. Will leave this issue open as a workaround for others.

**Comment by megadr01d** [comment]
You can replicate the issue using some kind of app switcher that hides apps by default (Single Application Mode) or manually hiding Keka with <kbd>⌘</kbd><kbd>H</kbd> while the progress is up.

In my case, I found this issue using LiteSwitch X and when using <kbd>⌘</kbd><kbd>Tab</kbd> to switch to another app, I have it configured to hide all other apps, by default. So, switching away from Keka while it's compressing/extracting, is like hiding it and **it doesn't quit automatically** when finished (no `...` badge on Keka's dock icon).

**Comment by aonez** [comment]
> manually hiding Keka with ⌘H while the progress is up

Thanks @megadr01d! Replicated this 👍

**Comment by gingerbeardman** [comment]
Great to see this old one found and fixed!

**Comment by megadr01d** [comment]
@aonez No problem, man.
I'm glad to report that `Keka-autoquit.7z` works correctly and auto quits Keka whether it's hidden or not.

**Comment by chrsjhnsn** [comment]
Keka won't close windows for me after decompressing no matter what. I've tried toggling "Close Keka When No Windows are Open", using the main branch download, using the dev "autoquit" branch listed above, and setting these two variables:

```
defaults write com.aone.keka GrowlBlocksExit -bool FALSE
defaults write com.aone.keka UseGrowl -bool FALSE
```

Kind of at a loss. I love how powerful keka is, but hate that it takes over my screen any time I unarchive something.

**Comment by aonez** [comment]
@chrsjhnsn could you remove the Keka preferences (close Keka first) and try the [Keka-autoquit](
https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-autoquit.7z) again? If it works, you can delete the preferences again and try the stable version.

To remove the preferences using the terminal:
```sh
k='com.aone.keka'; rm ~/Library/Preferences/$k; rm -r ~/Library/Containers/$k;
```

If it does not work I'll make a custom build to get some logs, if it is ok.

**Comment by chrsjhnsn** [comment]
@aonez that didn't do it on it's own, but helped get me there. after removing the prefs, Keka-autoquit was still not autoquitting. Rerunning the terminal boolean commands for toggling off Growl and for allowing Growl to block exit fixed it perfectly though.

Thanks so much. Amazing utility. Really glad it works so smoothly now.

**Comment by aonez** [comment]
@chrsjhnsn glad it works now! Note that `UseGrowl` can be enabled/disabled in the Keka preferences, is the "Enable Notification Center integration" check. If this one is disabled, `GrowlBlocksExit` is ignored, because there will be no notifications to wait for.

If you have time to test, it will be interesting to see if enabling both `UseGrowl` and `GrowlBlocksExit` causes the issue again. Note that Keka waits about 5 seconds with `GrowlBlocksExit` enabled.

**Comment by megadr01d** [comment]
@chrsjhnsn Starting from OS X Mavericks, I think, app preferences are cached and even after deleting them you need to reboot.
I suspect the Terminal hidden settings for Growl were not necessary, since I never applied them and the autoquit dev build worked just fine, out of the box.
For peace of mind, if you want to try it, delete all Keka preferences again, reboot and try the autoquit build again.

**Comment by aonez** [comment]
@megadr01d you're right, I usually just kill the `cfprefsd` processes but restarting might be safer.

**Comment by aonez** [comment]
Just released 1.1.12, @megadr01d your issue is fixed there. I'm leaving this one open anyway.

**Comment by Stooovie** [comment]
Still unfixed as of 2024

**Comment by aonez** [comment]
@Stooovie https://github.com/aonez/Keka/issues/200#issuecomment-2344163682
