### ISSUE TITLE
Getting "failed to create bookmark" when starting keka

### ISSUE THREAD

**Issue by jsilverman-blispay** [aonez/Keka#308]
I have a user that is getting "failed to create bookmark" when opening keka.

Please advise.
-JDS

**Comment by aonez** [comment]
But the application opens? Go to Keka - Preferences and delete all the file access:

https://github.com/aonez/Keka/issues/306#issuecomment-429642359

**Comment by aonez** [comment]
@jsilverman-blispay the application opens? Go to Keka - Preferences and delete all the file access:
![test](https://user-images.githubusercontent.com/480163/46650772-186f0380-cb9e-11e8-82cc-a979326536fb.gif)
