### ISSUE TITLE
Unable to extract a .tgz file

### ISSUE THREAD

**Issue by bisherbas** [aonez/Keka#311]
This one in particular: `https://download.configserver.com/csf.tgz`

Receiving an `Unknown error`.

![image](https://user-images.githubusercontent.com/42714627/47260227-3d5c5400-d485-11e8-9d06-9d1b8f90386a.png)

Archive Utility app is able to extract the file properly.

Environment:

`Keka v1.1.4`
`macOS Mojave`
`Macbook Air`

**Comment by aonez** [comment]
Just to test what I'm saying:

- Rename `csf.tgz` to `csf.gz` and extract it
- Add a `.gz` extension to the resulting file and extract it
- Add a `.tar` extension to the resulting file and expand it

**Comment by aonez** [comment]
It seems all packages from `https://www.configserver.com` are compressed in the same way...

**Comment by gingerbeardman** [comment]
I wonder that that website is using to compress in this funky way?

**Comment by aonez** [comment]
Yeah @gingerbeardman, I suppose they must have some reasoning or maybe just a script issue.

**Comment by gingerbeardman** [comment]
Yes, most likely an alias or shortcut that was "set and forget"

**Comment by aonez** [comment]
Just added a post to their forum: https://forum.configserver.com/viewtopic.php?f=6&t=11007

Anyway this should be fixed in Keka too. Thanks @bisherbas for the feedback!

**Comment by bisherbas** [comment]
Awesome! Thank you.

**Comment by aonez** [comment]
This is fixed for 1.2.0 :)

**Comment by aonez** [comment]
#337
