### ISSUE TITLE
With Mojave update 10.4, Keka fails with this dialog "Error code 2 using "p7zip"; Fatal Error"

### ISSUE THREAD

**Issue by gkillmaster** [aonez/Keka#313]
Has been working for years and all of a sudden its not working. Would love some hints on where to look for the problem?

Best,

Greg

**Comment by aonez** [comment]
Try this one: https://github.com/aonez/Keka/issues/306#issuecomment-429642359

Let me know if that doesn’t help.

**Comment by gkillmaster** [comment]
Thank you! It didn't work at first but I was eventually able to finagle it into working so thanks alot for pointing me in the right direction. I'm not sure how I ended up getting it to work but I think the act of resetting access did help finally. Then I had to figure out how to get it to be my default decompressor. It kept being reset. The app didn't work for that, but setting it manually did. Appreciate the quick reply!

**Comment by aonez** [comment]
Glad it works now! Sandbox is being a nightmare, 1.1.5 will come with lots of changes for that, hopefully no more problems then.

**Comment by gkillmaster** [comment]
Thanks so much for all the work. I'd hate to be without it! :)

**Comment by omata** [comment]
Hello,

I have the same issue and I tried the proposed fix, then I figured out that `Keka` was failing when I use **ZIP** format with a folder with over `43K` file count, _(around 1.1 GB)_. If I try to compress an smaller folder it works.

**Keka version:** `1.1.8`
**OSX version:** `10.14.1`

Regards,
Oscar.

**Comment by aonez** [comment]
@omata same happens with 7Z? Or just with ZIP?

**Comment by omata** [comment]
> @omata same happens with 7Z? Or just with ZIP?

Here my tests:
**7Z:** Fail
**ZIP:** Fail
**TAR:** Does work
**GZIP:** Does work
**BZIP2:** Does work
**XZ:** Does work
**LZIP:** Does work
**DMG:** Fail with error 1 using hdutil
**ISO:** Fail with error 1 using hdutil

Regards,

**Comment by aonez** [comment]
Any special files there? Any example so I can replicate the issue as similar as possible?

Jordi

**Comment by omata** [comment]
> Any special files there? Any example so I can replicate the issue as similar as possible?

It is an Apache `httpdocs` file structure with a lot of php files and hidden dot files.

The directory looks like:
```
total 150336
     0 drwxr-x---   42 user  staff   1.3K Dec  7 22:39 ./
     0 drwxr-xr-x   21 user  staff   672B Dec 10 22:37 ../
     8 -rw-r--r--    1 user  staff   348B Jul 24 15:27 .eslintrc.json
     8 -rw-rw-rw-    1 user  staff   3.1K Dec  6 13:29 .htaccess
     0 drwxr-xr-x    3 user  staff    96B Sep 10 19:45 .well-known/
  3608 -rw-rw-rw-    1 user  staff   1.8M Dec  4 19:41 1_en_0_sitemap.xml
     8 -rw-rw-rw-    1 user  staff   239B Dec  4 19:41 1_index_sitemap.xml
    16 -rw-r--r--    1 user  staff   4.8K Jul 24 15:27 INSTALL.txt
   360 -rw-r--r--    1 user  staff   179K Jul 24 15:50 LICENSES
     0 drwxr-xr-x   30 user  staff   960B Jul 24 15:50 admin770mwf03t/
     0 drwxr-xr-x    8 user  staff   256B Dec  7 22:39 app/
     8 -rw-r--r--    1 user  staff   1.2K Jul 24 15:27 autoload.php
     0 drwxr-xr-x    5 user  staff   160B Jul 24 15:50 bin/
     0 drwxr-xr-x   11 user  staff   352B Jul 24 15:27 cache/
     0 drwxr-xr-x  132 user  staff   4.1K Jul 24 15:27 classes/
   536 -rw-r--r--    1 user  staff   266K Jul 24 15:27 composer.lock
     0 drwxr-xr-x   18 user  staff   576B Dec  7 22:39 config/
     0 drwxr-xr-x    6 user  staff   192B Jul 24 15:27 controllers/
     8 -rw-r--r--    1 user  staff   878B Jul 24 15:27 docker-compose.yml
     0 drwxr-xr-x   13 user  staff   416B Jul 24 15:27 docs/
     0 drwxr-xr-x    4 user  staff   128B Nov 23 11:02 download/
     8 -rw-r--r--    1 user  staff   2.4K Jul 24 15:27 error500.html
    16 -rw-r--r--    1 user  staff   4.6K Jul 24 15:27 images.inc.php
     0 drwxr-xr-x   40 user  staff   1.3K Dec  7 22:39 img/
     8 -rw-r--r--    1 user  staff   1.1K Jul 24 15:27 index.php
     8 -rw-r--r--    1 user  staff   1.1K Jul 24 15:27 init.php
     0 drwxr-xr-x   22 user  staff   704B Jul 24 15:27 js/
     0 drwxr-xr-x   93 user  staff   2.9K Jul 24 15:27 localization/
     0 drwxr-xr-x    6 user  staff   192B Nov 23 11:02 mails/
     0 drwxr-xr-x   85 user  staff   2.7K Nov 26 15:26 modules/
     0 drwxr-xr-x    8 user  staff   256B Jul 24 15:27 override/
     0 drwxr-xr-x   41 user  staff   1.3K Jul 24 15:27 pdf/
145728 -rw-r--r--    1 user  staff    71M Sep 12 14:34 prestashop.zip
     8 -rw-r--r--    1 user  staff   2.7K Nov 15 18:28 robots.txt
     0 drwxr-xr-x    6 user  staff   192B Jul 24 15:27 src/
     0 drwxr-xr-x   12 user  staff   384B Dec  7 22:39 themes/
     0 drwxr-xr-x    7 user  staff   224B Jul 24 15:50 tools/
     0 drwxr-xr-x   16 user  staff   512B Nov 23 11:02 translations/
     0 drwxr-xr-x    3 user  staff    96B Nov 23 11:02 upload/
     0 drwxr-xr-x    8 user  staff   256B Jul 24 15:50 var/
     0 drwxr-xr-x   43 user  staff   1.3K Jul 24 15:50 vendor/
     0 drwxr-xr-x    4 user  staff   128B Jul 24 15:27 webservice/
```

**Comment by omata** [comment]
> @omata just compressed 14GB of data containing 58K files in 7Z with no problem, both in `store` and `fastest` methods.

It fails for me in both methods.
<img width="421" alt="captura de pantalla 2018-12-11 a la s 12 53 48 p m" src="https://user-images.githubusercontent.com/792294/49816253-db60f200-fd43-11e8-8e2f-422d011ac633.png">

**Comment by omata** [comment]
> ```shell
> defaults write com.aone.keka DevLogReader -bool TRUE
> ```

@aonez As per your request I enabled **Keka** logging and I found that the issue was related with a permission settings for a single specific directory inside of `httpdoc`. So, I set it to `755` and I was able to compress the directory with **zip** and **7z** formats.

Thank you for your help and best regards!

**Comment by macssi** [comment]
Hi, I tried the following methods: delete and re-add the location and restart the mac; delete app and download keka from the website. Nothing worked here on my MacBook pro Mojave. Still showing error code 2 etc, Any advice would be appreciated, thanks

**Comment by macssi** [comment]
<img width="386" alt="Untitled" src="https://user-images.githubusercontent.com/48653290/54494744-7efc0880-4918-11e9-9c90-cf310f2d619a.png">
this is what happened on console.app

**Comment by macssi** [comment]
![image](https://user-images.githubusercontent.com/48653290/54494786-03e72200-4919-11e9-83bd-eff09aa2b8f9.png)

This happened if this helps in your understanding...

**Comment by aonez** [comment]
Hi @macssi, it fails on any operation? Compression and extraction?

**Comment by macssi** [comment]
Hi, thansk for replying, compression is fine, It's been working well till now..

**Comment by aonez** [comment]
@macssi does this happen for every extraction? or it is just one file error?

**Comment by macssi** [comment]
@aonez thanks! the one that doesn't get extracted is pdf.exe. and unfortunately, it still doesn't work. I haven't tried with other pdf.exe, but I tried with a compressed folder, and it gets extracted well. Thank you for your help and I will find it out sooner or later and leave some messages to your email address. Thanks again!

**Comment by aonez** [comment]
@macssi not all exe files can be extracted. If you find the moment to send it I'll confirm you if it has any compressed data. Thanks for the feedback!

**Comment by cyb3rsalih** [comment]
Native  `$ unzip the_file.zip` command works proper.

**Comment by MrCee** [comment]
I'm having the same issue extracting one particular zip file, which isn't recognised as a zip file, although other unzip tools extract fine.
```
Extraction output: 
ERROR: /Users/name/Downloads/myfile.zip
/Users/paulcee/Downloads/myfile.zip
Open ERROR: Can not open the file as [zip] archive

ERRORS:
Is not archive
```

**Comment by aonez** [comment]
@MrCee can you share that file?

**Comment by MrCee** [comment]
I did not want the link to be posted

magnet:?xt=urn:btih:D97628155E4AABA2652B13F5522415CC5F8267E6&dn=Udemy+-+Salesforce+Certified+Administrator+%28aka+201%29+2018&tr=udp%3A%2F%2Finferno.demonoid.pw%3A3391%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftorrent.gresille.org%3A80%2Fannounce&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Fshadowshq.yi.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce

**Comment by MrCee** [comment]
Sure, hoping you received my email.

**Comment by aonez** [comment]
@MrCee I've extracted the file successfully. Maybe you've tried to extract it before the download was complete? Can you try again?

**Comment by berniezz** [comment]
@aonez hi bro, im so sorry but I'm facing the same exact problem which never occurred to me. I did all the reinstalling and restarting following your post #306 but it's still the same. Keep facing this problem:

_**Error code 2 using "p7zip" Fatal error**_

Please help me~

**Comment by Cuxs** [comment]
I'm facing this error right now. I've downloaded and updated keka from keka.io.
I'm trying to compress and split a file and when it's about to end, all files created disappear and that error pops up.

**Comment by aonez** [comment]
@Cuxs please follow these steps and share the log containing the error:

https://github.com/aonez/Keka/wiki/Report-an-issue

**Comment by OPStellar** [comment]
I've followed all these steps:
• Run like normal (version 1.1.5)
• Update Keka (to version 1.2.3) —{assuming this counts as uninstallation + reinstallation
• Remove file accesses directories
• Restore file access directories manually
• Run again

[Keka_2020-11-25-123324370.log](https://github.com/aonez/Keka/files/5598361/Keka_2020-11-25-123324370.log)

**Comment by aonez** [comment]
@OPStellar does it fails with other files or just that ISO image?

**Comment by OPStellar** [comment]
I figured out the problem. Thanks, though.
Apparently, some .ISO files operate differently, despite serving the same purpose.
This is one of a few that all fall into that same category.

**Comment by kakadais** [comment]
Here's a same problems.
Hope to be helpful.

![image](https://user-images.githubusercontent.com/5265343/103491542-06a56500-4e68-11eb-996d-99064949bcee.png)



OS: Version 11.1 (Build 20C69)
Keka: v1.2.6-r4371 (WEB) (Sandboxed) (en)
Format detected: Unknown
Binary used: keka7z
Arguments: (
    x,
    "/Volumes/01066176309/torrent/untitled folder/[\U1106\U1161\U11ab\U1112\U116a,\U110b\U116a\U11ab] \U110b\U1163\U110b\U116a\U1105\U1161! - YAWARA! (1-29) - \U110b\U116e\U1105\U1161\U1109\U1161\U110b\U116a \U1102\U1161\U110b\U1169\U110f\U1175.zip",
    "-o/Volumes/01066176309/torrent/untitled folder/[\U1106\U1161\U11ab\U1112\U116a,\U110b\U116a\U11ab] \U110b\U1163\U110b\U116a\U1105\U1161! - YAWARA! (1-29) - \U110b\U116e\U1105\U1161\U1109\U1161\U110b\U116a \U1102\U1161\U110b\U1169\U110f\U1175.kextraction/Operation",
    "-aou",
    "-xr!__MACOSX"
)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)
Modified by aONe for Keka

Scanning the drive for archives:
  0M Scan /Volumes/01066176309/torrent/untitled folder/

1 file, 0 bytes

Extracting archive: /Volumes/01066176309/torrent/untitled folder/[áá¡á«ááª,ááªá«] áá£ááªáá¡! - YAWARA! (1-29) - áá®áá¡áá¡ááª áá¡áá©ááµ.zip

ERROR: /Volumes/01066176309/torrent/untitled folder/[áá¡á«ááª,ááªá«] áá£ááªáá¡! - YAWARA! (1-29) - áá®áá¡áá¡ááª áá¡áá©ááµ.zip
Can not open the file as archive


  0%

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

Error code 2
