### ISSUE TITLE
Keka doesn't open in Mojave

### ISSUE THREAD

**Issue by amohap2** [aonez/Keka#314]
Keka was working before upgrading to Mojava. Now when I try to open i, it keeps trying to open and qui t the app. No way to force quit since process keeps trying to open and then close causing disruption.

**Comment by amohap2** [comment]
Eventually got this error. 
https://puu.sh/BQhGe/f17e82d378.png

Trying to redownload from app store didn't work.

**Comment by aonez** [comment]
Can you try to delete the Keka preferences? https://github.com/aonez/Keka/issues/208#issuecomment-397872166

Let me know if this helps :)

**Comment by PsukheDelos** [comment]
That worked @aonez! 😀Nice!

**Comment by excellinked** [comment]
> Eventually got this error.
> https://puu.sh/BQhGe/f17e82d378.png
> 
> Trying to redownload from app store didn't work.

Hello! Exactly same issue over here. I run the command to delete Keka preferences with Terminal, but it says: "No such file or directory". Either reinstalled or uninstalled Keka

**Comment by aonez** [comment]
@excellinked MAS o WEB version?

**Comment by excellinked** [comment]
> @excellinked MAS or WEB version?

Hello @aonez Mac-Mojave Apple Store

**Comment by PsukheDelos** [comment]
Just for more info, I am using the WEB version. Keep up the good work!

**Comment by aonez** [comment]
@excellinked 1.1.5 version was just released, please check out the update and let me know if you still have trouble with Keka.

**Comment by excellinked** [comment]
> @excellinked 1.1.5 version was just released, please check out the update and let me know if you still have trouble with Keka.

Hello. I confirm issue was resolved with latest update.
Thank you!
