### ISSUE TITLE
Compression options for tarball are disabled

### ISSUE THREAD

**Issue by applebait** [aonez/Keka#317]
I can't remember the exact version but it isn't possible to change the tarball creation compression settings.
TIA

**Comment by aonez** [comment]
@applebait I'm not sure what you mean.

Note that TAR does not compress data, so no method selection here:

![screen shot 2018-11-02 at 08 47 22](https://user-images.githubusercontent.com/480163/47900081-ecccf980-de7b-11e8-9710-746d8c52e67c.png)

For GZIP, BZIP, XZ and LZIP, you can choose the method. Those are the TARBALLs:

![screen shot 2018-11-02 at 08 47 31](https://user-images.githubusercontent.com/480163/47900123-18e87a80-de7c-11e8-9c3f-80172751258f.png)

**Comment by applebait** [comment]
![screen shot 2018-11-02 at 17 35 20](https://user-images.githubusercontent.com/44685612/47931085-b5833a80-dec5-11e8-8238-9e4b438c9b19.png)
If you go to the Preferences the Default method for TAR is greyed out. In the past we could set the level of compression for a tarball, not that it's what I want, I need it to compact a file always without compression, and if you say so, so in the past there was something wrong.

**Comment by aonez** [comment]
@applebait just checked and even version 0.1.2.1 (from 2009) has this option disabled in the preferences. This was the behaviour since the first begging, since TAR has no compression and this combo is useless there. GZIP, BZIP, XZ or LZIP can create tarballs and since they provide compression the combo is activated.

It was funny to check out 2009 work anyway. Thanks for the feedback @applebait 😊

**Comment by aonez** [comment]
You can upload it to YouTube/Dropbox or your preferred site and attach the link :)

**Comment by applebait** [comment]
Oh boy, you're right! :) I'm really sorry! I've checked and as soon as I choose the TAR method again the compression field gets greyed out. What was tricking me was this compression option that if we choose ZIP with some compression as soon as we choose TAR we can't switch it back to No Compression. This now makes sense if you say the TAR is a file with no compression.
