### ISSUE TITLE
Typo in russian localization

### ISSUE THREAD

**Issue by olderor** [aonez/Keka#319]
Text on the button "Enable home folder access" in the "File Access" window must be "Дать доступ к домашней папке" instead of "Дать доступ к доашней папке" (letter 'м' is missing).

<img width="649" alt="2018-11-07 20 32 30" src="https://user-images.githubusercontent.com/11135046/48152427-8822fc00-e2cc-11e8-9ca8-0377ee0dc320.png">

**Comment by olderor** [comment]
#320

**Comment by aonez** [comment]
Really the Dark Mode looks so great.
