### ISSUE TITLE
macOS .app invalid with Keka, works with Archive Utility 

### ISSUE THREAD

**Issue by jpillora** [aonez/Keka#32]
The [Heroes of the Storm](http://us.battle.net/heroes/en/) installer app (found [here](https://www.battle.net/download/getInstallerForGame?gameProgram=HEROES_OF_THE_STORM&os=mac&locale=enUS)) extracts an invalid .app with Keka, though succeeds with Archive Utility. When opening the Keka extracted .app:

![screen shot 2017-03-02 at 1 19 28 pm](https://cloud.githubusercontent.com/assets/633843/23490177/e3525998-ff4a-11e6-9ebb-91decd04d753.png)

The Archive utility extracted .app:

![screen shot 2017-03-02 at 1 19 08 pm](https://cloud.githubusercontent.com/assets/633843/23490182/eae04274-ff4a-11e6-852c-2e1594c6dd4e.png)

**Comment by aonez** [comment]
This is the same as #2. I'm working on a fix already, hope to bring it soon.
