### ISSUE TITLE
Keka-created 7z archives only decompressible in OSX Terminal 

### ISSUE THREAD

**Issue by grimmermatt** [aonez/Keka#326]
All .7z archives created with Keka in the past 6 months (I've only spot checked back that far) cannot be decompressed by the Unarchiver, Forklift, or Keka Version 1.1.5 (3031), claiming the archives are corrupted. Terminal (7za x foo.7z) however can decompress the archives just fine. Weird, weird stuff.  

<img width="668" alt="screen shot 2018-11-20 at 11 44 55 am" src="https://user-images.githubusercontent.com/8368808/48798642-edf28900-ecb9-11e8-9e78-eaae4e708ac2.png">
<img width="417" alt="screen shot 2018-11-20 at 11 43 44 am" src="https://user-images.githubusercontent.com/8368808/48798643-edf28900-ecb9-11e8-8a69-551d7cfcf31d.png">
<img width="438" alt="screen shot 2018-11-20 at 11 43 23 am" src="https://user-images.githubusercontent.com/8368808/48798644-edf28900-ecb9-11e8-801d-233665aa3499.png">
<img width="454" alt="screen shot 2018-11-20 at 11 42 56 am" src="https://user-images.githubusercontent.com/8368808/48798645-edf28900-ecb9-11e8-9930-621f8d874356.png">

**Comment by aonez** [comment]
Can you replicate this? Just create a new file with Keka and check if it is corrupted.

Do you have any of those file in a Time Machine backup?

**Comment by aonez** [comment]
This happened on the same machine as #229?

**Comment by grimmermatt** [comment]
Bad news: Same behavior on 26 .7z files created ~weekly over the past 5 months.
Good news: Uninstall/reinstall seems to have fixed this entirely. Now to go recompress everything...

**Comment by aonez** [comment]
This is very weird indeed... Glad it is solved now. If you still have that Keka.app and the preferences in a backup would be worth taking a look at it (if with those this can be replicated).

**Comment by aonez** [comment]
Please reopen this ticket if you can replicate it. Thanks for the feedback!
