### ISSUE TITLE
"Dummy" name for archives made from multiple folders

### ISSUE THREAD

**Issue by puciak** [aonez/Keka#327]
I don't know why if I drag multiple folders to Keka window, it only asks for location for the new archive - doesn't ask for name. In Preferences I set in "Name and location/Save to location" to "Ask each time". As the result I'm getting files like: dummy.7z.001, dummy.7z.002, dummy.7z.003, dummy.7z.004 (with splitted archive).

**Comment by aonez** [comment]
Sorry about the “dummy” one, it’s already fixed in the upcoming 1.1.6 version.

Keka needs folder access when creating a parted file, that’s why it does ask for a folder and you can’t set a file name. But maybe this can be better handled.

**Comment by aonez** [comment]
> doesn't ask for name

This will be introduced in 1.1.9.
