### ISSUE TITLE
[DISCUSS] Formatting of time taken/remaining

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#329]
Not sure why I am adding this, but I just switched between Keka progress and ForkLift progress and noticed the difference.

Keka
<img width="266" alt="screen shot 2018-11-22 at 12 38 58" src="https://user-images.githubusercontent.com/49612/48919773-be47aa80-ee8c-11e8-958f-7d23909e55c5.png">

ForkLift
<img width="264" alt="screen shot 2018-11-22 at 17 19 35" src="https://user-images.githubusercontent.com/49612/48919774-be47aa80-ee8c-11e8-8ded-dd549fc925e6.png">

I prefer the way ForkLift does it.

Feel free to ignore :)

**Comment by aonez** [comment]
It really is cool to see the data transfer stats. Maybe for TAR it would be useful, for compression I'm not sure.

**Comment by gingerbeardman** [comment]
I think it's the excess of labels in the Keka way?

"time elapsed" and "remaining"

And there are no labels in ForkLift. 

I don't know, maybe this is an unnecessary issue

**Comment by aonez** [comment]
> I don't know, maybe this is an unnecessary issue

No, I also thought some time ago to remove the elapsed time part and leave it only to the remaining part.

**Comment by aonez** [comment]
So this is the new formatting:

- Remaining time
![Screen Shot 2019-06-19 at 13 24 51](https://user-images.githubusercontent.com/480163/59761648-a6ef6500-9295-11e9-875c-94e849895c91.png)

- Undetermined progress, elapsed time
![Screen Shot 2019-06-19 at 13 22 35](https://user-images.githubusercontent.com/480163/59761568-73143f80-9295-11e9-83f4-5c59e53407c4.png)

**Comment by ahydronous** [comment]
If I might suggest a slight tweak to this @aonez, use a monospaced font for all the progress text. Currently if it goes from 19s to 18s to 17s etc it constantly jumps around.
