### ISSUE TITLE
Option to extract to folder with the same name as archive

### ISSUE THREAD

**Issue by filliph** [aonez/Keka#333]
In my opinion, it should work like this:
* If the archive contains 1 file, preserve current behaviour and extract next to the archive
* If the archive contains a folder, or more than one file, extract to a folder with the same name as the archive

It would be perfect if Keka could also detect if the archive contained a folder with the same name as the archive, and not create nested folders.

Thanks for considering!

**Comment by aonez** [comment]
I'm not sure I'm getting that one right, since I think it's already the current behaviour:

- If the extraction contains multiple files/folders, a folder nesting all the contents is created named as the compressed archive
- If the extraction only contains one file/folder, no parent folder is created and the file/folder retains it's name, is not named as the compressed archive

Can you supply some test files so I can better understand what's the change you're proposing?

**Comment by belazor** [comment]
I confess I made an assumption when it came to multiple files and folders, sorry about that!

I only purchased Keka off the MAS an hour or so before submitting the feedback as The Unarchiver failed to extract the attached zip file, but Keka managed it fine.

[xf-patch-2011.zip](https://github.com/aonez/Keka/files/2613024/xf-patch-2011.zip)

When I extract this file, I would want Keka to create a folder named `xf-patch-2011` with the `src` folder inside it.
Currently, with the "Extract to location" setting set to "Next to original file", it simply creates a folder `src`.

The primary reason why I believe this should change is that if I'm extracting a file I don't know the contents of into a large "Downloads" folder, it's not always obvious to me where exactly the resulting file(s) went. 

In the case of that particular zip file, I'd need to look at the "Date Modified" column to figure it out, if the Downloads folder was large enough that the extracted "src" folder didn't spring into view.

Assuming this isn't already possible somewhere, and I'm just missing the setting, maybe a sub-option of the "Extract to location" could be added that always creates a parent folder (with the detection mentioned in the OP).

Thanks!

**Comment by gingerbeardman** [comment]
This is an interesting request. 

I tested the attached zip with various programs and they all act exactly the same way: they just extract what is in the file.

- Keka 1.1.5
- The Unarchiver 4.0.0 (worked fine for me)
- BetterZip 4.2.1
- Archive Utility (macOS) 10.10
- Archiver 3.0.4

**Comment by gingerbeardman** [comment]
Yes, I have used that in the past with WinRAR and 7zip.

How would you see such an option being presented or activated on macOS?

**Comment by gingerbeardman** [comment]
This also reminds me of #188

**Comment by belazor** [comment]
> How would you see such an option being presented or activated on macOS?

Inside the "Location" fieldset in Keka preferences, underneath the "Extract to location:" drop-down, there could be a checkbox with label "Extract to sub-folder with archive name".

Alternatively, the checkbox could simply read "Extract to sub-folder" and descriptive text (such as the one found under the "Format" fieldset on the Compression tab) could elaborate, with something like "A folder with the same name as the archive will be created in the specified location."

**Comment by aonez** [comment]
> When I extract this file, I would want Keka to create a folder named `xf-patch-2011` with the `src` folder inside it.

@belazor this will be like the "Extract on xf-patch-2011 folder" for 7-Zip in Windows contextual menu. This should be easy to do :)

**Comment by aonez** [comment]
Coming in the next 1.2.0 beta:

![Screenshot 2020-06-05 at 11 56 40](https://user-images.githubusercontent.com/480163/83863455-a6104700-a723-11ea-8495-3d1a9f01e87f.png)

**Comment by filliph** [comment]
Shouldn't that be "Extract to" rather than "Extract on", like WinRAR in my previous screenshot https://github.com/aonez/Keka/issues/333#issuecomment-441448568? :)

**Comment by aonez** [comment]
You're right @filliph, I always get confused with "on, to, in"...
