### ISSUE TITLE
Kekaosx.com website is down

### ISSUE THREAD

**Issue by hanxue** [aonez/Keka#334]
Going to `https://www.kekaosx.com` will result in 

```
This site can’t provide a secure connection kekaosx.com sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

SSL test fails at https://www.ssllabs.com/ssltest/analyze.html?d=www.kekaosx.com

![image](https://user-images.githubusercontent.com/760008/49068182-071eab00-f261-11e8-9658-4d0edbd7c84c.png)

**Comment by aonez** [comment]
Thanks @hanxue!

The old domain does not have (and never had) an SSL certificate. http://www.kekaosx.com should properly redirect to https://www.keka.io. Did you found that address on the wild?

Just testing this one, found that http://kekaosx.com does indeed translate to or httpS://kekaosx.com and fails. Fixing that one.

**Comment by aonez** [comment]
> Just testing this one, found that http://kekaosx.com does indeed translate to or [httpS://kekaosx.com](httpS://kekaosx.com) and fails. Fixing that one.

It seems like the browser does this translation 😓
