### ISSUE TITLE
Can't drag and drop

### ISSUE THREAD

**Issue by PeterK44** [aonez/Keka#336]
I just updated Keka from version 1.1.5 to version 1.1.6 on my Mac running macOS Mojave 10.14.1.
Dragging and dropping files onto the app in order to compress them no longer works.

**Comment by aonez** [comment]
@PeterK44 can you:

1. Open the Console.app
2. Filter by Keka
3. Open Keka
4. Drag some files

Let me know if there appears any message in the Console.app.

**Comment by PeterK44** [comment]
I rebooted Mac and Keka behaves normally. I guess I should have done that before contacting you. Sorry to bother you.

**Comment by aonez** [comment]
Thanks @PeterK44! Glad it is solved. If you find anything in the Console.app regarding that moment if didn't worked as expected, reopen this ticket :)
