### ISSUE TITLE
Non-executable app after extraction

### ISSUE THREAD

**Issue by Wdavery** [aonez/Keka#340]
Ran into this with Sonarr and Radarr, but it seems to be a non-issue with the built in decompressor, so might be worth looking into. See: Sonarr/Sonarr#2818 and Radarr/Radarr#3206

**Comment by aonez** [comment]
Thanks for the feedback @Wdavery! This is a regression of https://github.com/aonez/Keka/issues/2. It should affect Keka since 1.1.6.

**Comment by aonez** [comment]
@Wdavery what version of Keka are you using? Can't reproduce this one.

**Comment by Wdavery** [comment]
Must've been having a brain fart. I just realized I installed Sonarr via homebrew not manually, and obviously is unrelated to Keka, it must be using it's own decompression for some reason.

**Comment by aonez** [comment]
No problem @Wdavery! 😊
