### ISSUE TITLE
Keka always asks where the rest of the multi-part archive is

### ISSUE THREAD

**Issue by kennethlynne** [aonez/Keka#351]
I have configured keka to extract to location "next to original file" by default
![image](https://user-images.githubusercontent.com/390817/50904023-8803c180-141f-11e9-90e8-7f426a075e6a.png)

But I always get this dialog and have to pick the folder that the original file was located in
![image](https://user-images.githubusercontent.com/390817/50904009-7e7a5980-141f-11e9-9353-1c8a0cbb0a98.png)

Using Keka 1.1.8

**Comment by kennethlynne** [comment]
And it fails to extract still, with no proper feedback 
![image](https://user-images.githubusercontent.com/390817/50904390-69ea9100-1420-11e9-8ec6-fa7a74cfdb3f.png)

**Comment by kennethlynne** [comment]
After going to "Enable external volume access" it performs a lot better! 💃 

![image](https://user-images.githubusercontent.com/390817/50904517-c3eb5680-1420-11e9-8f24-5596c0042b04.png)

**Comment by aonez** [comment]
> After going to "Enable external volume access" it performs a lot better! 💃

🎉🎉🎉

This is in fact a limitation of the sandboxing in macOS. The safest way to extract a parted file is to have full access to the parent folder, so if there're A LOT of parts, you can just click on Extract without selecting any part so Keka has access to the entire folder.
