### ISSUE TITLE
No feedback when failing to extract rar file

### ISSUE THREAD

**Issue by kennethlynne** [aonez/Keka#352]
![image](https://user-images.githubusercontent.com/390817/50904748-69062f00-1421-11e9-94b9-c329e390ceaf.png)

It starts out just fine, but after a while I just get this dialog. Any way to figure out what's wrong?

**Comment by aonez** [comment]
Try this to see more info: https://github.com/aonez/Keka/issues/350#issuecomment-452709646

**Comment by aonez** [comment]
There's already a ticket for improving the error messages, hope to implement #116 soon.

**Comment by aonez** [comment]
@kennethlynne you've solved the issue?
