### ISSUE TITLE
 DICOM files into OsriX Medical Viewer.

### ISSUE THREAD

**Issue by SimonYork** [aonez/Keka#359]
I appear to be experiencing difficulty in extracting  DICOM files to load into OsriX using KeKa.  Is this a file type that the software accommodates?

Regards Simon

**Comment by aonez** [comment]
I’m not familiar with such files. Are those compressed or extracted with Keka before loaded into OsriX? Can you share an example file?

**Comment by gingerbeardman** [comment]
Perhaps this helps?

https://fry-it.atlassian.net/wiki/spaces/PKB/pages/100634363/Uploading+DICOM+images

**Comment by aonez** [comment]
From what I've seen in the @gingerbeardman link, seems like a fairly common ZIP expecting a folder-file structure inside. @SimonYork let me know what was the issue.
