### ISSUE TITLE
New Archiver Icons

### ISSUE THREAD

**Issue by Jax0rz** [aonez/Keka#36]
I created an icon pack to make Keka feels more elegant and beautiful .
**Here is the download [link](https://github.com/Jax0rz/Keka-Icons)**

![show](https://cloud.githubusercontent.com/assets/7557357/24584558/007a37c2-17a4-11e7-8817-06fd39ad8c64.png)
![tab bar](https://cloud.githubusercontent.com/assets/7557357/24584559/0d951562-17a4-11e7-9174-b72793960abb.png)

**Comment by aonez** [comment]
They look pretty cute!

**Comment by aonez** [comment]
Gonna run a poll on twitter with this ones, to see what users think about them!

You'll have any problem on retouching them if needed? Love that you've made them vectorial. Are Sketch files exportable to SVG? I'm not familiar with this app, though it seems very robust (and expensive for occasional designers as me 😛).

Thanks @Jax0rz !

**Comment by Jax0rz** [comment]
I've add a svg source file.[Download SVG](https://github.com/Jax0rz/Keka-Icons/tree/master/src/SVG)
