### ISSUE TITLE
No RAR Preferences

### ISSUE THREAD

**Issue by fullcity** [aonez/Keka#360]
There aren't any options in preferences for RAR files. Specifically, I'd like to be able to delete the archive after extraction.

**Comment by aonez** [comment]
Hi @fullcity,

You have a global option in the Keka Preferences to detele any archive (RAR or other format) after an extraction:

1. Open the Keka Preferences
2. Got to the Extraction section
3. Enable ‘Move to trash compressed files after extraction’

https://github.com/aonez/Keka/wiki/Keka-Preferences#extraction-preferences
