### ISSUE TITLE
Feature request: Turn AutoUpdate on/off in settings or in plist

### ISSUE THREAD

**Issue by Soteyy** [aonez/Keka#365]
With Keka version 1.1.11, it only asks to turn on AutoUpdates when first opening it. I don't see any options to toggle that setting in any preferences, would be cool to have!

**Comment by aonez** [comment]
Coming in next dev build :)

**Comment by aonez** [comment]
@Soteyy the latest dev build already has it:
https://github.com/aonez/Keka/releases/tag/v1.2.0-dev.3742

Salut!
