### ISSUE TITLE
British English Localisation

### ISSUE THREAD

**Issue by anosidium** [aonez/Keka#368]
I would like to localise the software into British English. I am aware that it is already in English but it is actually American English. It annoys me that American English is considered the default English when English actually come from England.

The Base.Ipoj is (American) English but I need en-GB.Ipoj for British English.

Would you be willing for this particular localisation?

**Comment by gingerbeardman** [comment]
What words or phrases are American English?

(I'm also English and don't have a problem with the current localisation)

**Comment by aonez** [comment]
@gingerbeardman just was thinking about that. The current localization is mainly made by me, I'm not American or English.

All that said, there's always room for improvement @anosidium.

**Comment by anosidium** [comment]
Looking through Base.lproj files, some texts can be rewritten in British English. Here are some samples:

> You can also customize the access below:

Can be rewritten as:

> You can also customise the access below:

Another example:

> Move original file(s) to Trash after compression

Can be rewritten as:

> Move original file(s) to the bin after compression

Etc.

So I am interested in doing that. @aonez  What is your say? Will there be an en-GB.Ipoj for British English?

**Comment by aonez** [comment]
> You can also customise the access below

This one I buy. Now I see why the corrector always tries to change the z with an s. 
The Trash one no, simply because it refers the Mac Trash and not a generic trash/bin.

![image](https://user-images.githubusercontent.com/480163/53231760-fb892780-3689-11e9-9fbb-b010d463282a.png)

Sure, I'm up to a en-GB addition!

**Comment by anosidium** [comment]
I am surprised that it spelt as Trash.

https://www.reddit.com/r/apple/comments/8wu3nn/trash_renamed_to_bin_in_mojave/

https://twitter.com/greyham/status/1011942261469245440?lang=en

Other people on the Internet said that in macOS Mojave, Apple has renamed it as Bin. I do not know why it is spelt as Trash for you.

**Comment by aonez** [comment]
> I am surprised that it spelt as Trash

I'll double check that one! @gingerbeardman?

**Comment by anosidium** [comment]
I have submitted a British English localisation. Let me know if it is fine or need any other changes.

**Comment by gingerbeardman** [comment]
I do not use Mojave, but it's Trash on High Sierra.

Not sure how you'd cope with different strings for different versions of the OS?

**Comment by aonez** [comment]
@anosidium feel free to keep updating the British localization. I'm closing this ticket now :)

**Comment by anosidium** [comment]
@aonez I will be happy to update the localisation. How can I get my fork to be in sync? It has been years.

**Comment by aonez** [comment]
@anosidium the fastest way is to delete your current fork and create a new one :)

**Comment by anosidium** [comment]
@aonez Wouldn't I lose my contribution on the contribution graph?

**Comment by aonez** [comment]
Not sure about that @anosidium. You can always update your fork, this tutorial may help you. Look for "**How To Sync or Update Your Forked Repo Using the Github Website**":

https://www.earthdatascience.org/courses/intro-to-earth-data-science/git-github/github-collaboration/update-github-repositories-with-changes-by-others/

**Comment by aonez** [comment]
@anosidium any luck with that pull?
