### ISSUE TITLE
Preferences don't stick when closed

### ISSUE THREAD

**Issue by kyle95wm** [aonez/Keka#369]
# Workaround

If you have this issue please try the steps at [this comment](https://github.com/aonez/Keka/issues/369#issuecomment-466950445).

### Original issue

I seem to be experiencing an issue with Keka, where setting the preferences won't save them when Keka is closed. What can I do to fix this? I've already tried uninstalling via AppZapper and reinstalling it via the website.

**Comment by aonez** [comment]
Are you using the latest version? All the preferences don't stick, or just some?

**Comment by kyle95wm** [comment]
The version I'm running is Version 1.1.11 (3248)

None of my preferences stick (i.e - home access always gets un-set)

**Comment by aonez** [comment]
> home access always gets un-set

Wow. Even if you already used an uninstaller app, please close Keka and remove all the configuration files:

```sh
rm ~/Library/Containers/com.aone.keka
```

You can also remove that folder manually, if needed.

If it stills with the same issue, can you open the Console.app, filter by Keka process and run some operations in Keka to see if there appears any message?

**Comment by kyle95wm** [comment]
So the first solution didn't work. I saw messages like these in the console:

```Couldn't write value for key FinderAfterCompression in CFPrefsPlistSource<0x600002642840> (Domain: com.aone.keka, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access```

**Comment by kyle95wm** [comment]
Are there any updates on this?

**Comment by aonez** [comment]
@kyle95wm this happened always for you? Where're you running Keka from? The default Applications folder or another folder?

**Comment by aonez** [comment]
This issue remembers me of #226, but this one was fixed simply by removing the folder, with the command I've already shared to you.

**Comment by kyle95wm** [comment]
This has been happening to me ever since I installed Keka. I'm running it from the Applications folder like any other app.

**Comment by aonez** [comment]
I suppose you've already restarted your Mac, since Keka was installed. If not, try that one. I'm not sure what's happening here, clearly the system is banning Keka from using the sandbox container.

Please double check Keka is properly running from the Applications folder, and it is not running in translocation (from a temporary folder). Just open the `Activity Monitor.app`, search Keka, double click on it and check Open `Files and Ports`.

![screen shot 2019-02-25 at 10 56 03](https://user-images.githubusercontent.com/480163/53329429-59b54500-38ec-11e9-8213-b591b046faa0.png)

I know you've already did something similar, but what I would try is:
1. Remove the preferences folder again, using the terminal command if you did it manually before
2. Delete the Keka.app
3. Empty the trash
4. Restart the Mac
5. Download Keka again

**Comment by kyle95wm** [comment]
This is the output I get from Activity Monitor:

```cwd
/Users/kylewarwick-mathieu/Library/Containers/com.aone.keka/Data
txt
/Applications/Keka.app/Contents/MacOS/Keka
txt
/Applications/Keka.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
txt
/Library/Preferences/Logging/.plist-cache.PwVqS1Dp
txt
/usr/share/icu/icudt62l.dat
txt
/private/var/db/timezone/tz/2018i.1.0/icutz/icutz44l.dat
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/SystemAppearance.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAppearance.car
txt
/usr/lib/libobjc-trampolines.dylib
txt
/private/var/folders/lk/d3sg12qd3wbgggwv0mcc09p40000gn/0/com.apple.LaunchServices-231-v2.csstore
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAquaAppearance.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets.car
txt
/System/Library/Fonts/SFNSText.ttf
txt
/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/Extras2.rsrc
txt
/private/var/folders/lk/d3sg12qd3wbgggwv0mcc09p40000gn/C/com.aone.keka/com.aone.keka/com.apple.metal/3902/libraries.data
txt
/private/var/folders/lk/d3sg12qd3wbgggwv0mcc09p40000gn/C/com.aone.keka/com.aone.keka/com.apple.metal/AMD Radeon R9 M395X/functions.data
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLightAppearance.car
txt
/System/Library/Caches/com.apple.IntlDataCache.le.kbdx
txt
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/AppleKeyboardLayouts-L.dat
txt
/System/Library/Fonts/SFNSDisplay.ttf
txt
/System/Library/Fonts/Helvetica.ttc
txt
/Applications/Keka.app/Contents/Resources/Assets.car
txt
/Applications/Keka.app/Contents/Resources/7z.icns
txt
/Applications/Keka.app/Contents/Resources/zip.icns
txt
/Applications/Keka.app/Contents/Resources/tar.icns
txt
/Applications/Keka.app/Contents/Resources/gz.icns
txt
/Applications/Keka.app/Contents/Resources/bz2.icns
txt
/Applications/Keka.app/Contents/Resources/xz.icns
txt
/Applications/Keka.app/Contents/Resources/lz.icns
txt
/Applications/Keka.app/Contents/Resources/dmg.icns
txt
/Applications/Keka.app/Contents/Resources/iso.icns
txt
/usr/lib/dyld
0
/dev/null
1
/dev/null
2
/dev/null
3
->0x4838bdb98eb00659
4
/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_stdlib.metallib
5
/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_filters.metallib
6
/private/var/folders/lk/d3sg12qd3wbgggwv0mcc09p40000gn/C/com.aone.keka/com.aone.keka/com.apple.metal/3902/libraries.maps
7
/private/var/folders/lk/d3sg12qd3wbgggwv0mcc09p40000gn/C/com.aone.keka/com.aone.keka/com.apple.metal/3902/libraries.data
8
/private/var/folders/lk/d3sg12qd3wbgggwv0mcc09p40000gn/C/com.aone.keka/com.aone.keka/com.apple.metal/AMD Radeon R9 M395X/functions.maps
9
/private/var/folders/lk/d3sg12qd3wbgggwv0mcc09p40000gn/C/com.aone.keka/com.aone.keka/com.apple.metal/AMD Radeon R9 M395X/functions.data
10
/Users/kylewarwick-mathieu/Library/Containers/com.aone.keka/Data/Library/Saved Application State/com.aone.keka.savedState/data.data
11
/Users/kylewarwick-mathieu/Library/Containers/com.aone.keka/Data/Library/Saved Application State/com.aone.keka.savedState/windows.plist
12
/Users/kylewarwick-mathieu/Library/Containers/com.aone.keka/Data/Library/Saved Application State/com.aone.keka.savedState/window_1.data```

**Comment by kyle95wm** [comment]
Okay, just an update. Recently my Mac lost power. I tried saving my preferences by opening the Keka app directly (instead of using it from an archiving job)  and it seems to work. I even rebooted the Mac for good measure and it works. Not sure what was causing it.

**Comment by sivan** [comment]
> I suppose you've already restarted your Mac, since Keka was installed. If not, try that one. I'm not sure what's happening here, clearly the system is banning Keka from using the sandbox container.
> 
> Please double check Keka is properly running from the Applications folder, and it is not running in translocation (from a temporary folder). Just open the `Activity Monitor.app`, search Keka, double click on it and check Open `Files and Ports`.
> 
> ![screen shot 2019-02-25 at 10 56 03](https://user-images.githubusercontent.com/480163/53329429-59b54500-38ec-11e9-8213-b591b046faa0.png)
> 
> I know you've already did something similar, but what I would try is:
> 
> 1. Remove the preferences folder again, using the terminal command if you did it manually before
> 2. Delete the Keka.app
> 3. Empty the trash
> 4. Restart the Mac
> 5. Download Keka again

Same issue, works for me.
