### ISSUE TITLE
The advanced settings window would be displayed when I called "extract using keka" from service entry

### ISSUE THREAD

**Issue by huamiao** [aonez/Keka#370]
Please check the attachment for how it happens.

And you can find the configuration entries in keka_settings.txt (btw, I didn't touch any config items manually)

[keka_settings.txt](https://github.com/aonez/Keka/files/2892548/keka_settings.txt)

![screen recording 2019-02-22 at 13 34 05](https://user-images.githubusercontent.com/1251303/53222652-7877c980-36a9-11e9-8604-ca0643d9ffb7.gif)

**Comment by aonez** [comment]
@huamiao thanks for the preferences and the preview!
Can you check it is fixed in this version: [Keka-welcome.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-welcome.7z)

This one is labeled as version 1.1.12, so you can double check is the one being opened.

**Comment by huamiao** [comment]
I've tried and it works like a charm.

**Comment by aonez** [comment]
Glad to hear that! If you're using the WEB version you can keep using that build. Let me know if you reproduce the bug again 👍

**Comment by aonez** [comment]
@huamiao just released version 1.1.12 with this issue fixed! Thanks again for the feedback!
