### ISSUE TITLE
Esoteric Japanese self-expanding archives

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#374]
Here are a few self-expanding archives of old Japanese games.

These are more of a curiosity than anything else.

> I'm running these through Wine/CrossOver so the Japanese text does not display correctly. Sorry!

If Keka fails to extract, I try the following:
1. _Archiver.app_ (macOS) and/or _The Unarchiver.app_ (macOS)
2. _7z.exe_ (Windows)

--- 
# LZH

- [hanaw310.exe.zip](https://github.com/aonez/Keka/files/2915549/hanaw310.exe.zip)
  - Archiver.app (macOS) handles this OK
  - ![screen shot 2019-02-28 at 15 07 17](https://user-images.githubusercontent.com/49612/53575987-a1490480-3b6a-11e9-8b82-54218ff386cf.png)

- [otohana110a.EXE.zip](https://github.com/aonez/Keka/files/2915550/otohana110a.EXE.zip)
  - Archiver.app (macOS) handles this OK
  - ![screen shot 2019-02-28 at 15 07 41](https://user-images.githubusercontent.com/49612/53575993-a443f500-3b6a-11e9-8907-f5e4fe90bc15.png)

- [usahana104.exe.zip](https://github.com/aonez/Keka/files/2915580/usahana104.exe.zip)
  - 7zip on (Windows) handles this OK
  - ![screen shot 2019-02-28 at 15 11 42](https://user-images.githubusercontent.com/49612/53576324-4f54ae80-3b6b-11e9-9d88-d7b43f239099.png)

---
# LZX

- [tyq01.exe.zip](https://github.com/aonez/Keka/files/2915574/tyq01.exe.zip)
  - LZX:21
  - Archiver.app (macOS) handles this OK
  - ![screen shot 2019-02-28 at 15 10 21](https://user-images.githubusercontent.com/49612/53576192-0997e600-3b6b-11e9-93a6-48966016eb50.png)

--- 
# GCA

- [hanasol30.exe.zip](https://github.com/aonez/Keka/files/2915548/hanasol30.exe.zip)
  - GCA SelfExtractor
  - [website](http://www.emit.jp/gca/gca_e.html)
  - [SDK](http://www.emit.jp/gca/gcasdk.html)
  - ![screen shot 2019-02-28 at 15 06 11](https://user-images.githubusercontent.com/49612/53575882-6d6ddf00-3b6a-11e9-8c38-b7d06f23650c.png)

--- 
# InstallShield

- [KsHana75b.exe.zip](https://github.com/aonez/Keka/files/2915953/KsHana75b.exe.zip)
  - Archiver.app (macOS) handles this OK

- [Hanafuda_Optmedia116_Setup.exe.zip](https://github.com/aonez/Keka/files/2915954/Hanafuda_Optmedia116_Setup.exe.zip)
  - Archiver.app (macOS) handles this OK

**Comment by aonez** [comment]
Thanks @gingerbeardman! I had different results as in #375. All but `hanasol30` where extracted in my tests.

- `hanaw310`: Extracted with Keka, TUA and Archiver ok
- `otohana110a`: Extracted with Keka, TUA and Archiver
- `usahana104`: Extracted with Keka, bad encoding (failed with TUA and Archiver)
- `tyq01`: Extracted with Keka, bad encoding (TUA and Archiver ok)
- `hanasol30`: Failed with Keka, TUA and Archiver
- `KsHana75b`: Extracted with Keka, TUA and Archiver
- `Hanafuda_Optmedia116_Setup`: Extracted with Keka, TUA and Archiver

Keka handles all EXE files with `p7zip`, maybe some of them can he handled with `unar` for best encoding results.

**Comment by gingerbeardman** [comment]
Great! Sorry for my incomplete testing.

**Comment by gingerbeardman** [comment]
Is it possible my testing was done with an older Keka that would not expand these? I only upgraded to Keka 1.1.12 afterwards

**Comment by aonez** [comment]
No changes regarding this issue were made recently, so I'm not sure why they failed for you before. Are they failing now?

**Comment by gingerbeardman** [comment]
No, but let's mark it down to user error on my part.
