### ISSUE TITLE
Archives with undetected character sets

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#375]
(I have to zip up the LZH archives to add them to GitHub)

# Japanese
- [bakaha10.lzh.zip](https://github.com/aonez/Keka/files/2915676/bakaha10.lzh.zip) (Archiver.app worked OK)
- [hanaf131.lzh.zip](https://github.com/aonez/Keka/files/2915696/hanaf131.lzh.zip) (Archiver.app worked OK)
- [hatiha10.lzh.zip](https://github.com/aonez/Keka/files/2915697/hatiha10.lzh.zip) (Archiver.app worked OK)
- [kikyo11.lzh.zip](https://github.com/aonez/Keka/files/2915698/kikyo11.lzh.zip) (The Unarchiver.app worked OK)
- [Sengoku-Hanafuda_ver.1.09.zip](https://github.com/aonez/Keka/files/2915699/Sengoku-Hanafuda_ver.1.09.zip) (Keka.app prompts for charset selection)

**Comment by aonez** [comment]
Thanks @gingerbeardman, the charset detection must be improved.

My results where different though. In my tests:
- `bakaha10`: TUA asks encoding, Archiver and Keka use bad encoding 
- `hanaf131`: TUA asks encoding, Archiver and Keka use bad encoding
- `hatiha10`: TUA and Archiver ok, Keka uses bad encoding
- `kikyo11`: Archiver ok, TUA guesses correct encoding, Keka uses bad encoding
- `Sengoku-Hanafuda_ver.1.09`: Archiver ok, TUA guesses correct encoding, Keka asks encoding

**Comment by gingerbeardman** [comment]
Let's go with your test results. I'm not sure why mine were different.

**Comment by aonez** [comment]
Just realized Keka has LHA extraction support but no format detection. I'm fixing that.

**Comment by gingerbeardman** [comment]
Just an addition to this, whilst Keka extracts these correctly, the incorrect charset is used:

- [tyq01.exe.zip](https://github.com/aonez/Keka/files/2915574/tyq01.exe.zip)
  - <img width="163" alt="screen shot 2019-03-02 at 09 47 44" src="https://user-images.githubusercontent.com/49612/53680247-9e682400-3cd0-11e9-9f51-2d98dc6bb13e.png">
- [usahana104.exe.zip](https://github.com/aonez/Keka/files/2915580/usahana104.exe.zip)
  - <img width="179" alt="screen shot 2019-03-02 at 09 48 01" src="https://user-images.githubusercontent.com/49612/53680246-990ad980-3cd0-11e9-96fe-0090bc7b5010.png">

**Comment by aonez** [comment]
Thanks @gingerbeardman! Already noted that on https://github.com/aonez/Keka/issues/374#issuecomment-468614633.

It's incredible how many LHA variations there're. Do you think Japanese people still using it for compression? Or are those old files (like golden game gems) that still compressed in that format?

**Comment by gingerbeardman** [comment]
LZH just really took off in Japan, because it was created by a Japanese guy. It's still used widely, in fact Windows 7 Japanese comes with LZH folder support!

**Comment by aonez** [comment]
@gingerbeardman version 1.1.13 just released with most LZH files properly extracted 😊 As for the EXE ones, I'll try to fix that one in #374. It is fairly more complicated to detect the compression method used in some EXE files.

Thanks for the feedback as always!
