### ISSUE TITLE
Unable to extract AES256 zip files - no password prompt

### ISSUE THREAD

**Issue by sdivae** [aonez/Keka#376]
I am trying to extract a medical record that was provided as a zip file with AES 256 encryption and it was recommended that I use keka. However when I try to extract with keka, it throws the following error and **does not prompt the password** for the file. 

![image](https://user-images.githubusercontent.com/39887022/53683354-c184da80-3cb4-11e9-85e6-6674c6125f10.png)

**Comment by aonez** [comment]
Hi @sdivae, please try the following:

1. Close Keka
2. Open the Terminal.app and execute the following command:
   ```sh
   defaults write com.aone.keka UnzipWithUNAR -bool false
   ```
3. Try extracting the file again

If this works, it will be very helpful if you can execute this code in the Terminal.app and let me know what it says:
```sh
xxd -l 8 -ps <THE_FILE.zip>
```
