### ISSUE TITLE
RAR extraction fail

### ISSUE THREAD

**Issue by zstekovic** [aonez/Keka#378]
Hello,
I have problem with extraction of big (1.7GB) RAR file.
File have bunch of small EPS/CDR files in archive.
7Zip does not have this problem.

---
Error code 13 using "unrar"
Unknown error
---

**Comment by aonez** [comment]
Is it possible that you share that file with me?

**Comment by aonez** [comment]
Probably this is a duplicate of #362. Can you test if this Keka build works with that file:

[Keka-unrar570.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-unrar570.7z)

**Comment by zstekovic** [comment]
It’s working perfectly now.

btw sorry about duplicate post I did not see #362.

Regards,
-- 
Zarko Stekovic | Creative Power Plant
—
Phone: (206) 446 7889
Address: 334 Wells Ave South – Suite B, Renton, WA 98057
Web: www.creativepowerplant.com

**Comment by aonez** [comment]
Just to be sure, you mean it's working with the `Keka-unrar570` build? Thanks @zstekovic!

**Comment by zstekovic** [comment]
Yes, the one you send me… 1.1.13 (3268)
-- 
Zarko Stekovic | Creative Power Plant
—
Phone: (206) 446 7889
Address: 334 Wells Ave South – Suite B, Renton, WA 98057
Web: www.creativepowerplant.com

**Comment by aonez** [comment]
@zstekovic was that 1.7GB RAR parted, with multiple volumes? Or was it a single RAR file? Thanks!

**Comment by zstekovic** [comment]
Single file.
Not a problem.
-- 
Zarko Stekovic | Creative Power Plant
—
Phone: (206) 446 7889
Address: 334 Wells Ave South – Suite B, Renton, WA 98057
Web: www.creativepowerplant.com

**Comment by aonez** [comment]
@zstekovic I'm closing this one in favor of #362. Thanks for all the feedback!
