### ISSUE TITLE
Will this ever be able to be ported to gnu/linux?

### ISSUE THREAD

**Issue by Austcool-Walker** [aonez/Keka#380]
Hi I love this app on my hackintosh and macbook pro but will this ever be able to support gnu/linux?

**Comment by Austcool-Walker** [comment]
its also very sad that you have chosen to close your apps source instead of forcing the people who refused to follow GPL3 to release source...

**Comment by aonez** [comment]
@Austcool-Walker there're plenty of good options for Linux, like [File Roller](
https://wiki.gnome.org/Apps/FileRoller) (I love the its icon). Also Keka is coded in Objective-C/Swift, so none of the code will be useful there.

It was very sad indeed but after unsuccessfully trying what you say there was no other way. It was that or ending the project.
