### ISSUE TITLE
Unable to open suddenly, an infinite loop

### ISSUE THREAD

**Issue by Eden-Lin** [aonez/Keka#383]
When I unpack the file, the system pop-up prompts, need I sign Apple ID.
No matter I am rejected or agree, keka will collapse.
Finally, the system pop-up prompts, said that this application is damaged, need to reinstall.
However, this is the second time I reinstall.
Please help me to solve this problem, thank you!

System information：
macOS Mojave  10.14.3
MacBook Pro (Retina, 13-inch, Early 2015)

keka  app version：1.1.12

**Comment by aonez** [comment]
@Eden-Lin, could you try this:

1. Remove Keka.app
2. Empty the Trash
3. Restart the Mac
4. Download Keka again

Let me know if this solves the issue
