### ISSUE TITLE
Use MAS phased release feature

### ISSUE THREAD

**Issue by iDjay** [aonez/Keka#393]
Strange issue, but my AppStore shows that 1.1.14 is the latest version and I‘m still on 1.1.13. However, the update doesn’t appear on the „updates“ screen and I can‘t update it manually. Is it your fault or a problem with a AppStore?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aonez** [comment]
This is the first version Keka is using phased release in the MAS. The update applies automatically in stages during a week. In theory if you go to updates it should appear to be applied manually, but I’m facing the same issue as you.

**Comment by iDjay** [comment]
It‘s online 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aonez** [comment]
I still don't have it, which is funny. Most probably won't use this phased release feature on the next release.

**Comment by aonez** [comment]
This is a new feature for Mac (not for iOS), so probably will work better in a few weeks.

**Comment by aonez** [comment]
The phased release period ended today. Will keep looking when Apple improves it for macOS, right now I'm not using it no more.

**Comment by gingerbeardman** [comment]
Phased release only benefits Apple bandwidth. Such a poor user experience, even on iOS

**Comment by aonez** [comment]
They state it is so you can prevent a bug from spreading too much... And the functionality and idea make a lot of sense. But if power users, those that want the latest version posible, aren't unable to get the update this feature has no purpose.

**Comment by gingerbeardman** [comment]
On iOS I can pull to refresh the updates tab and see the updates that I'm due that were awaiting phased release. 

Not sure if there's a way to do that on macOS (and I'm still on High Sierra)

**Comment by aonez** [comment]
> Not sure if there's a way to do that on macOS (and I'm still on High Sierra)

At least on Mojave <kbd>⌘</kbd><kbd>R</kbd> refreshes the page, but this did not made a difference.

**Comment by aonez** [comment]
Quote from Apple: 

> All users can still install the update manually from the App Store at any time.

From https://developer.apple.com/app-store-connect/whats-new/?id=phased-release-macos

**Comment by iDjay** [comment]
@aonez yes exactly as you mentioned.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
