### ISSUE TITLE
Character encoding in this zip

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#394]
[Manana.zip](https://github.com/aonez/Keka/files/3051696/Manana.zip)

The Unarchiver doesn't know what to do with it, either.

Palm OS app inside is called "Mañana.prc"

Not sure how it is encoded.

**Comment by aonez** [comment]
Probably **Western (DOS Latin 1)** is the right choice. Did you had any problems extracting it? It did extracted properly for me choosing that encoding.

**Comment by gingerbeardman** [comment]
I did eventually find an encoding that worked.

**Comment by aonez** [comment]
Cool! Closing that one then 😊
