### ISSUE TITLE
Error stops queue

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#396]
1. open multiple zips to start queue processing 
2. one archive has an error like this https://github.com/aonez/Keka/issues/395
3. queue does not continue

the queue should be able to recover from an error like this.

**Comment by aonez** [comment]
Stable version? It pauses on any error, you can continue with the play pause. Really the new queue system in 1.2.0 is the way to go.

![Screen Shot 2019-04-11 at 09 17 27](https://user-images.githubusercontent.com/480163/55938005-a3f34b00-5c3a-11e9-83df-63e3aeb3cbab.png)

**Comment by gingerbeardman** [comment]
Stable 

Oh! I'd not see the play button. I just expected it to continue without and leave the error visible.

**Comment by aonez** [comment]
> Oh! I'd not see a play button in the screen grab on #395

The play button only appears on a queue process, if there're more operations on queue. Really #21 would be the proper fix.
