### ISSUE TITLE
Please add option to keep extracted file after error

### ISSUE THREAD

**Issue by Bigwaf** [aonez/Keka#399]
When a rar file throws a CRC error because it's not complete, the extracted file is not saved. Please add an option (or make it the default behaviour) to keep the extracted file even if an error occured during extraction.

That way, when the download of a large file is interrupted before it's finished, one gets the chance to check the partially downloaded file and to decide, if the download is worth starting over.

By the way, thank you for this wonderful tool! I really enjoy using it an reccomend it a lot.

**Comment by aonez** [comment]
Thanks a lot for the feedback @Bigwaf!

I remember [doing the contrary](http://trac.keka.io/ticket/92), not just [one time](https://changelog.keka.io/#v0.1Alpha2). Makes sense to me reading this one.

**Comment by aonez** [comment]
@Bigwaf just double checked and this is the default behavior as long as the compressed file has enough integrity and some of its contents can be extracted. Can you share the file/s where you found the contrary?

Here a test RAR corrupted file: [test.zip](https://github.com/aonez/Keka/files/3112456/test.zip)

**Comment by Bigwaf** [comment]
Sorry, I can’t share an example right now - I don’t keep them  :-)

 Your example files worked perfectly. Maybe my downloaded files were just corrupted…

Sometimes partially downloaded .mp4 files work, sometimes they don’t. So, if Keka keeps the files as long as they work, than this is perfect. 

Thanks for looking into the matter! And keep up the good work, I really appreciate it  :-)



> Am 24.4.2019 um 15:21 schrieb aONe <notifications@github.com>:
> 
> @Bigwaf just double checked and this is the default behavior as long as the compressed file has enough integrity and some of its contents can be extracted. Can you share the file/s where you found the contrary?
> 
> Here a test RAR corrupted file: test.zip
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Viele Grüße

Christian Schmitz
Berlin, Germany

------------------------------------------------
Paradise is exactly like where you are right now
only much, much better         - Laurie Anderson
------------------------------------------------
Klick: http://gold-gelb.de
------------------------------------------------
