### ISSUE TITLE
Add xz format compression

### ISSUE THREAD

**Issue by corsaroquad** [aonez/Keka#40]
It would be nice to use Keka to create xz/lzma compressed archives instead of manually going to the Terminal. Keka already decompresses these files without issues and xz compression is becoming quite popular and useful.

Will it ever be supported as a new compression option? 

Thank you.

**Comment by aonez** [comment]
Sure it will. I'm sorry it's taking that far to add it.

**Comment by aonez** [comment]
Was asked far ago: http://trac.kekaosx.com/ticket/32

**Comment by aonez** [comment]
Coming in 1.1.0 😄
