### ISSUE TITLE
Error(s) on compression

### ISSUE THREAD

**Issue by Cpeters1982** [aonez/Keka#401]
[Keka-log.log](https://github.com/aonez/Keka/files/3114353/Keka-log.log)
Log attached. I can't compress anything, seemingly. Error code 2 using 7z or zip, unknown error when trying to compress using Tar.

**Comment by Cpeters1982** [comment]
Way over 4gb. My mistake.

**Comment by aonez** [comment]
The compression did not fit in the disk? Glad you figure it out. Thanks for the feedback @Cpeters1982!
