### ISSUE TITLE
Compression tarball files that starts with "--"

### ISSUE THREAD

**Issue by psmanek** [aonez/Keka#404]
Hello,

Keka has problem with file names beginning with eg.

"-- Folder 01"
"-- Folder 02"

**Comment by aonez** [comment]
Thanks for the feedback @psmanek! Just testing, it seems that you're right. Only detected that error on tarball compression (tar, tar.xxx). Is that right or did you found the issue on other formats or extraction?

**Comment by psmanek** [comment]
Yes, I didin't mentioned that this issue is on TAR files.

**Comment by aonez** [comment]
@psmanek can you check [this build](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-tar--.7z) works for you?

**Comment by psmanek** [comment]
It works now like it should. Great! Thanks.

**Comment by psmanek** [comment]
It works now for signle archive, but still does not work if you select to use seperate files for each folder.

**Comment by aonez** [comment]
Thanks again @psmanek! Fixing that right away.
