### ISSUE TITLE
Add "drag and drop" advice

### ISSUE THREAD

**Issue by rohdesr** [aonez/Keka#41]
I posted a negative review of Keka about 12 months ago.  Today, finally I received a response but I still don't understand how this app works. In the UI, I see controls for...

- method
- split
- password
- excluding Mac resource fork
- deleting files after compression
- archiving as a single file

...but there's nothing in the user interface or menus that explains how to specify input, i.e. files to compress, to Keka. And there's nothing that show how to initiate the compression process.  No explanatory text, no buttons, nothing.  Can you please explain how your app works?

![2017-06-19_17-46-50](https://user-images.githubusercontent.com/13219552/27307411-9d04584c-5517-11e7-84ac-1e5d7c038484.png)

**Comment by aonez** [comment]
I'm sorry for the late reply, but just 3 months ago Apple enabled developers to reply review. Before, it was a one way communication.

About the use, there's an outdated documentation that I must rework for good, and I'm also sorry for that: http://www.kekaosx.com/en/doc.php

Basically, to work with Keka you drag and drop files in the dock icon or in the main window.

![460](https://user-images.githubusercontent.com/480163/27328952-2e40b1ba-55b4-11e7-874c-af22cc7126cb.gif)

**Comment by rohdesr** [comment]
Oh, that’s easy.  And unintuitive. The UX could be greatly improved by simply adding the instructional text “Drag files or folders here to compress” in the “at rest” user interface. That way it is now, the instructional text doesn’t appear until after the user has already dragged files. 

-Steve

**Comment by aonez** [comment]
Thanks @rohdesr. I'll try to think a proper way to show to the user there's a "drag and drop" area on [1.2.0](https://github.com/aonez/Keka/milestone/7).

**Comment by MaxPower85** [comment]
Maybe add like some "Welcome to Keka" window that would appear when Keka is first installed to show a few screenshot and explain some basic usage for new users... and when Keka updates, you could show some "What's new" window to mention new features.

**Comment by aonez** [comment]
Closing in favor or #562 and #560.
