### ISSUE TITLE
cbz files do not work

### ISSUE THREAD

**Issue by Fixx2** [aonez/Keka#410]
compressing to zip and changing file type to cbz does not validate and is not readable using comic readers like Simple Comic. Fail.

**Comment by gingerbeardman** [comment]
Can you post an example?

Works for me.

**Comment by aonez** [comment]
@Fixx2 same as @gingerbeardman here. Did a quick test and worked. Can you share a file that fails for you?

**Comment by Fixx2** [comment]
Ok, now it works (after apps restart). That was some kind of read problem between Keka & Simple Comic. I hope it does not repeat.
