### ISSUE TITLE
Cant open Zip file

### ISSUE THREAD

**Issue by jennyjob** [aonez/Keka#411]
Im going bananas pls help! I have tried downloading every single zip extractor and keep having the same problem. I download a zipfile try to extract it and it looks like its extracting but I cant find it anywhere! seems like iCloud is saving it but its not there. Where does the file end up? I even created a folder to save it under and I select it but still nothing!

**Comment by aonez** [comment]
I'm not sure how to help here. Maybe move the ZIP file to the desktop and extract it there?

**Comment by jennyjob** [comment]
I tried that already! not working :-(

**Comment by aonez** [comment]
That only happens with one ZIP file or with any file? Try for example this file: [Test.zip](https://github.com/aonez/Keka/files/3197463/Test.zip)

**Comment by jennyjob** [comment]
wow this one worked!! what the heck

**Comment by aonez** [comment]
When extracting the problematic file, Keka does not give any error? Can you share that one?

**Comment by jennyjob** [comment]
it doesnt give any error, it says extracting and then done, but the file is just not where I extract it to.

**Comment by aonez** [comment]
Maybe the ZIP contains a hidden folder/files? Try with <kbd>⇧</kbd><kbd>⌘</kbd><kbd>.</kbd> (Shift-Command-.) to see hidden files.

**Comment by aonez** [comment]
Here an example of a ZIP containing a hidden folder: [Hidden-Test.zip](https://github.com/aonez/Keka/files/3197511/Hidden-Test.zip)

**Comment by jennyjob** [comment]
wow yeah that worked, although a million hidden files appeared haha! Thanks, Ill check with the company that sent the file!

**Comment by jennyjob** [comment]
thank you sooo much!!!

**Comment by aonez** [comment]
you're welcome @jennyjob 😊
