### ISSUE TITLE
Encrypt filenames is not working

### ISSUE THREAD

**Issue by yvancouver** [aonez/Keka#413]
Using Version 1.1.15 (3300), 7Z with the Encrypt filenames checked. 
After compression is finished the filenames are the same as the origin. They are password protected but that's all.
How can I get the filenames encrypted?
Thanks

**Comment by aonez** [comment]
Hi! If you list the file without the password, it prints the file names? 

Note that this encryption does not mean that after extraction the filenames are encrypted. This only means that the list of files in the compressed file is encrypted so you can only know the names of it with the password. With this option unchecked you can know the names of the file without the password, but not the contents.

**Comment by yvancouver** [comment]
Hello,

Thanks for the precision, then I misunderstood the option.
Please feel free to close the issue as invalid.

Thanks
Yvan

**Comment by aonez** [comment]
Glad to help @yvancouver :)
