### ISSUE TITLE
"Archive Items Separately" vs "Archive As Single Files"

### ISSUE THREAD

**Issue by fourdragons** [aonez/Keka#414]
I like the switch to "Archive Items Separately", but I'm 90% certain that you just forgot renaming it in the Preferences, as well.  It still shows "Archive As Single Files" there.  No biggie, just confused me for a minute until I figured out one was the old way of saying it (in Preferences), and one was the new way of saying it (Main Window).

Anyway, great app!  I'm sorry I didn't find it earlier!

**Comment by aonez** [comment]
Thanks @fourdragons! You're right, fixing that right away. Have a nice one :)
