### ISSUE TITLE
Check macOS 10.15.b1 Catalina compatibility (19A471t)

### ISSUE THREAD

**Issue by josuecocoman** [aonez/Keka#415]
The app does not work with any format in this version of os

**Comment by aonez** [comment]
Thanks @josuecocoman! Already pushing an update. Does compression also fails for you? I've only found extraction failed.

**Comment by josuecocoman** [comment]
Failure in format files, zip, rar is the only one that I have been able to test do not compress or decompress

**Comment by aonez** [comment]
What Keka version are you using?

**Comment by josuecocoman** [comment]
Versión 1.1.15 (3300)

**Comment by aonez** [comment]
@josuecocoman please check the [new release](https://github.com/aonez/Keka/releases/tag/v1.1.16) and let me know if it works for you

**Comment by josuecocoman** [comment]
Yes I work now :-D thanks bro very fast support
