### ISSUE TITLE
How to double click to uncompress

### ISSUE THREAD

**Issue by kzhui125** [aonez/Keka#418]
Every time it ask me location to uncompress.

Very annoying.

**Comment by aonez** [comment]
First be sure to have the extract location set to "Next to original file" in the Keka preferences:

![Screen Shot 2019-06-09 at 19 15 13](https://user-images.githubusercontent.com/480163/59162061-fcd04a00-8aea-11e9-8d92-be6a2c571039.png)

With that option set, Keka will only ask for a destination if it has no file access. You have detailed information about file access [here](https://github.com/aonez/Keka/wiki/Sandbox#when-keka-has-no-file-access-at-all-for-example-on-the-first-launch-will-ask-for-it-suggesting-some-recommendations).

Let me know if this helps.

**Comment by kzhui125** [comment]
@aonez 
It helps after file access is enabled.

thanks!
