### ISSUE TITLE
Randomly trying to decompress instead of compress a folder

### ISSUE THREAD

**Issue by nikzic** [aonez/Keka#425]
Hi, 

Ever since of June 25th update, when I run a service to compress a folder with Keka, for some reason it chooses to extract instead of compress a folder.  Since an ordinary folder cannot be extracted, I am getting an error message saying "Extraction of <folder name> failed".  Where "<folder name>" is a the name of the folder I was trying to compress.

Under Preferences, I have "Perform automatic action" selected under General > Actions.

How do I stop Keka from trying to extract a non-archive folder and instead compress it as it is meant to do.

Before the update of June 25th, this has never happened to me, and now it happens approx. every 4th time I try to compress a folder.

**Comment by nikzic** [comment]
Here is a screenshot of the error: <img width="415" alt="Screenshot 2019-07-05 at 10 54 00" src="https://user-images.githubusercontent.com/52564671/60710541-368e4800-9f13-11e9-9896-5e345af61dd2.png">

**Comment by aonez** [comment]
This is really strange. No changes had been made in the Keka services. Just to be sure, you said you're using those services, right?

![Screen Shot 2019-07-05 at 11 08 21](https://user-images.githubusercontent.com/480163/60711428-3abb6500-9f15-11e9-8adc-3897d535e7e9.png)

Can you try to close Keka, [remove its preferences](https://github.com/aonez/Keka/wiki/Uninstall-Keka#2-delete-the-preferences) and see if this happens again?
