### ISSUE TITLE
folder not deleted automatically

### ISSUE THREAD

**Issue by anonymouskeka** [aonez/Keka#427]
uncompressing files creates a temporary ".Keka-[letters and numbers]" folder, which shouldn't exist after finishing the progress. It still exists if you cancel entering a password.

btw Thank you for this very nice app :)

**Comment by aonez** [comment]
Thanks a lot for the feedback @anonymouskeka!

**Comment by aonez** [comment]
Forgot to tell you that easily reproduced this issue when extracting encrypted files with non encrypted filenames. Although when exiting or reopening Keka those temporary files should disappear, I'm fixing this one so they get removed if the task don't need them anymore (like canceling it).

Thanks again!

**Comment by aonez** [comment]
Should be fixed in 1.1.19 😊
