### ISSUE TITLE
Keka always ask every time the filename when creating .zip

### ISSUE THREAD

**Issue by oliversl** [aonez/Keka#428]
I have always(6+ years) has setup keka that never ask for the .zip filename when creating. A few updates ago this was changed and now keka always ask for the new .zip filename when drag and dropping the folder/file to compress.

I tried changing the setting to "always ask" -> compress and then to "never ask" -> compress

The issue remain. Sorry for reporting too late. What can I do? Thanks

**Comment by aonez** [comment]
Hi @oliversl! Thanks for using Keka for so long 😄 and sorry for this issue! Just updated the information regarding file access, take a look at it: https://github.com/aonez/Keka/wiki/Sandbox#disk-access

Basically, if you compress files in the Desktop, you'll need to add the Desktop to the File Access list in Keka so it can read/write there without showing a "Save as" dialog.

Hope this helps 😊

**Comment by oliversl** [comment]
Many thanks! I didn't notice I had to go to preferences and click "Enable access to home folder", that seems to be the solution! Regards and thanks for making an amazing software!
