### ISSUE TITLE
Delete archive parts one by one after extraction

### ISSUE THREAD

**Issue by Drjacky** [aonez/Keka#429]
I'm asking for a feature which removes each parted archive one-by-one after extraction.
Imagine The whole file size is 40GB which separated into 40 files ~ 1GB per each.
When we extract the archive, Keka will remove .part01, then when it finished extracting .part02, it will remove that part, so on.

**Comment by aonez** [comment]
Hi @Drjacky! I get your point but usually the first part has information needed during all the extraction process. Also deleting some parts before finishing may be a bad idea in case the extraction fails.

It will stay as the current behavior, deleting all the parts when the extraction finishes successfully.

Thanks for the feedback!

**Comment by Drjacky** [comment]
Okay, good point, but at least you could add a feature in the options menu about it. So someone like me could use it on my own risk (which doesn't have that much risk cause the archives goes to the Trash).
And/Or you could keep the first part(for its header information) and removing parts after that first part.

**Comment by Drjacky** [comment]
My storage is almost full. When I have an archive with many parts, there is no more space for extracted folders. So, it'd be great to make space by removing those extracted parts.
Just an idea. Right now, I'm removing those parts manually while the archive is extracting 😅

**Comment by gingerbeardman** [comment]
> which doesn't have that much risk cause the archives goes to the Trash

Hmm. Do you use the Trash or not?

Anyway, I think a better use of time and effort is to clean out your computer or upgrade your storage, it will make a real difference. Rather than ask some software to change that will take time and only enable you to limp along for a short while longer.
