### ISSUE TITLE
Is Keka affected as well by this RAR issue allowing arbitrary memory writes?

### ISSUE THREAD

**Issue by rpkoller** [aonez/Keka#43]
https://bugs.chromium.org/p/project-zero/issues/detail?id=1286&can=1&q=unrar&desc=6

**Comment by aonez** [comment]
It is, since it's using unbar 5.4. Updating to 5.50 beta 4 with fixed code right ahead.

Thanks for the tip!

**Comment by aonez** [comment]
Already released: https://github.com/aonez/Keka/releases/tag/v1.0.9
The MAS update will be propagating very soon :)

**Comment by rpkoller** [comment]
MAS is also available now. Thanks a lot for the quick fix!

**Comment by aronkihui** [comment]
This version, v1.0.9 (stable now -in theory- XD), can't unRAR an encrypted password rar file. It drops me an error coded 255. :(

**Comment by aonez** [comment]
@aronkihui this was a bug reintroduced in this version #48, just released 1.0.10 with this fixed. Sorry for that.
