### ISSUE TITLE
Keka doesn't show on options for RAR file

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#431]
Any idea why not?

![Screen shot 2019-07-25 at 13 15 09](https://user-images.githubusercontent.com/49612/61873765-a5413e80-aede-11e9-8cc8-70b4893e333e.png)

**Comment by aonez** [comment]
Sorry, still happening? I don’t know why only RAR...

Jordi

**Comment by aonez** [comment]
@gingerbeardman just did a quick binary that shows information for the RAR extension, if you can check it:

[rar_check.zip](https://github.com/aonez/Keka/files/3569654/rar_check.zip)

Should show something like this:

```sh
Preferred UTI for RAR: com.rarlab.rar-archive
Preferred handler for RAR: com.aone.keka
Possible handlers for preferrer RAR UTI (com.rarlab.rar-archive):
   com.aone.keka
Available UTIs for RAR:
   com.rarlab.rar-archive
```

**Comment by gingerbeardman** [comment]
```
2019-09-09 17:42:06.856 rar_check[90898:6334711] Preferred UTI for RAR: com.eigenlogik.rar-v5-archive
2019-09-09 17:42:06.858 rar_check[90898:6334711] Preferred handler for RAR: com.aone.keka
2019-09-09 17:42:06.858 rar_check[90898:6334711] Possible handlers for preferrer RAR UTI (com.eigenlogik.rar-v5-archive): (
    "com.aone.keka"
)
2019-09-09 17:42:06.858 rar_check[90898:6334711] Available UTIs for RAR:
(
    "com.eigenlogik.rar-v5-archive",
    "com.yacreader.yacreader.rar",
    "com.rarlab.rar-archive"
)
```

**Comment by aonez** [comment]
That results make no sense... In the list from the first comment https://github.com/aonez/Keka/issues/431#issue-472832182 there're a lot of handlers but Keka and in this one only Keka:

```sh
2019-09-09 17:42:06.858 rar_check[90898:6334711] Possible handlers for preferrer RAR UTI (com.eigenlogik.rar-v5-archive): (
    "com.aone.keka"
)
```

If those are the actual results then you already have Keka as the default handler, right?

What I don't like is those custom UTIs from YACReader and Entropy... the UTI string is meant to be unique and RAR uses `com.rarlab.rar-archive`.

**Comment by gingerbeardman** [comment]
I have moved to Mojave since this issue (reported on High Sierra) and you are correct that Keka once again shows in the context menu for RAR files and is the default.

So, maybe close?

**Comment by aonez** [comment]
> I have moved to Mojave

Glad to hear that now that Catalina is about to be released! Always an OS behind, you really love stability 👍🏼

**Comment by gingerbeardman** [comment]
When websites started breaking I knew it was time to put my life aside and spend a weekend doing the upgrade and repairing all the fallout. It was worth it! See you next summer for Catalina. 🤣

**Comment by gingerbeardman** [comment]
Why is the icon not from Keka?

![Screen shot 2019-09-20 at 14 16 22](https://user-images.githubusercontent.com/49612/65331560-f014c500-dbb4-11e9-838d-6fc680d4a788.png)

**Comment by aonez** [comment]
That icon preview shows the file icon. If you have another application assigned to handle RAR files, it will show that icon.

**Comment by gingerbeardman** [comment]
But Keka is my default as we gathered earlier in this issue.
