### ISSUE TITLE
Preferences don't stick (checked #369)

### ISSUE THREAD

**Issue by lelroy** [aonez/Keka#432]
Running v. 1.1.17 (3323).  It is running in /applications/keka...
My preferences don't stick either.

I want to make a uncompressed zip (store only).  I selected store in zip preferences.  But it still compresses.

**Comment by lelroy** [comment]
I uninstalled it.  Rebooted.  Reinstalled the newest beta 1.2.0.  Same thing, preferences don't stick.  This is frustrating - and I PAID for it.  Can you please fix this!

**Comment by aonez** [comment]
Let me check that one!

**Comment by aonez** [comment]
@lelroy just checked and the Preferences work as expected. Note the difference between the temporary configuration and the Keka Preferences. The first is configured here, and will only last while the window is opened:

![Screen Shot 2019-07-31 at 18 51 02](https://user-images.githubusercontent.com/480163/62231346-265b7280-b3c4-11e9-8ef6-e97c3c0e285b.png)

The later, the Keka Preferences, stick even while Keka is closed. Just go to Keka - Preferences:

![Screen Shot 2019-07-31 at 18 51 42](https://user-images.githubusercontent.com/480163/62231401-3ecb8d00-b3c4-11e9-9cac-f3b0e42da8de.png)

Hopefully this solves your issue :)
