### ISSUE TITLE
Enhance visibility of the main/alternative actions in the drop window

### ISSUE THREAD

**Issue by joobei** [aonez/Keka#434]
Correct me if I'm wrong but there is no way currently to split an .iso file into multiple 7z volumes (or any other format for that matter). If an .iso is dragged into the keka window the default action is to uncompress it. If the context menu "compress" is used then there is no option to split it into multiple volumes.

**Comment by joobei** [comment]
ok so it turns out it was an interface problem. After reading it on the wiki I figured it out. But it wasn't immediately apparent so perhaps the store/compress parts of the window should be more salient.

**Comment by aonez** [comment]
You can use the bottom part in the drop action that does the opposite of the action:

https://github.com/aonez/Keka/wiki/Compressing-with-Keka#dont-forget-you-have-a-secondary-option-in-the-keka-window-which-can-be-useful-for-compressing-already-compressed-files

Let me know if that helps :)

**Comment by aonez** [comment]
Relative to #41

**Comment by aonez** [comment]
Closed in favor of #560.
