### ISSUE TITLE
ZIP create: p7zip fatal error when password contains e.g. ÅÖÄåöä

### ISSUE THREAD

**Issue by systemcrash** [aonez/Keka#435]
possibly related to #373 

version: Version 1.2.0-dev (3494)

**Comment by aonez** [comment]
Currently `p7zip` does not accept those. Most compressors do not accept them. Maybe in the future this will change.

**Comment by MaxPower85** [comment]
Maybe just do some simple check for non-ASCII character when someone is typing a password he wants

**Comment by aonez** [comment]
Will prevent the use of non compatible characters in #480

**Comment by maxsky** [comment]
I know WinRAR could set Chinese password when compression. I also test with Windows 10. 7-Zip can be set Chinese password same as WinRAR, and no any problem when extraction.

Sample image:

![chs-pwd-test](https://user-images.githubusercontent.com/7405522/68458963-0519e600-023f-11ea-82ae-ed396a4c0909.gif)

**Comment by aonez** [comment]
@MaxPower85 maybe you mean extraction. Compression is not possible with 7-Zip:

![Screen Shot 2019-11-08 at 10 39 49](https://user-images.githubusercontent.com/480163/68466175-29140200-0214-11ea-9a48-4ee31469fed4.png)

**Comment by maxsky** [comment]
> @MaxPower85 maybe you mean extraction. Compression is not possible with 7-Zip:
> 
> ![Screen Shot 2019-11-08 at 10 42 00](https://user-images.githubusercontent.com/480163/68466313-6e383400-0214-11ea-9a6d-714a38fa4c77.png)
> ![Screen Shot 2019-11-08 at 10 41 40](https://user-images.githubusercontent.com/480163/68466314-6e383400-0214-11ea-8eb5-56ce6695eab7.png)

I'm sure `zip` ext cannot use Chinese as password, but `7z` could.

**Comment by aonez** [comment]
Sure, 7Z works flawlessly :)
