### ISSUE TITLE
Keka brings Mac to a crawl - MacOS Mojave 10.14.6

### ISSUE THREAD

**Issue by kubik101** [aonez/Keka#436]
Hi I have been using Keka for many years.

Recently after I finally updated to Mojave I noticed that when I was extracting something in Keka that all other apps on my machine would slow down to a crawl.

I made sure Keka was updated to the latest version and still the machine runs super slow when extracting.

In Activity monitor Keka is only using 1 to 1.5 % CPU.

Symptoms:
Google Chrome: App opens but takes an incredible long time for a web page to load.
Safari: App opens and web pages open fine.
Photoshop: Almost impossible to open App. Sometimes it just hangs "Application not responding".

Please note the machine comes back to life after Keka has finished.

Specs of my machine:
iMac (Retina 5K, 27-inch, Late 2014)
Processor: 4GHz Intel Core i7
Memory 32GB

**Comment by aonez** [comment]
When compressing, Keka can use even all the CPU, depending on the format and method selected. Note that Keka uses binaries such as “keka7zip” (p7zip) that will be the ones using the majority of the CPU. Can you check that is the case?

The upcoming version can be configured to use a number of CPU threads, so if your i7 is a Quad Core with multithreading (8 threads total), you can set Keka to only use 6 threads so your CPU is never fully used by it.

Let me know if you test the beta :)

**Comment by kubik101** [comment]
Sounds good.
How do I check if Keka is using “keka7zip” (p7zip) ?

**Comment by aonez** [comment]
In the Activity Monitor search for “Keka” and you’ll see all processes Keka uses

**Comment by kubik101** [comment]
This is what I see in Activity monitor:
Keka  0.2%CPU  0.36CPU Time   5 Threads
kekaunrar   7.5CPU   4.07CPU Time   1 Thread

My processor is in an iMac: 4 GHz Intel Core i7
Retina 5K, 27-inch, Late 2014
32 GB 1600 MHz DDR3

**Comment by aonez** [comment]
> Keka 0.2%CPU 0.36CPU Time 5 Threads
> kekaunrar 7.5CPU 4.07CPU Time 1 Thread

This seems pretty fine, less than 10% of the CPU used. Normally this is what happens on extractions. When compressing things change and it may use most of your CPU.

I'm working in a thread limit, so you can choose how much CPU to use per operation.

**Comment by aonez** [comment]
@kubik101 you can indeed test the threads limit in the current [beta](https://beta.keka.io) version:

![Screen Shot 2019-09-05 at 07 22 12](https://user-images.githubusercontent.com/480163/64314056-ee8caf80-cfad-11e9-9073-ede925aa4172.png)
