### ISSUE TITLE
extract error

### ISSUE THREAD

**Issue by IceSnow** [aonez/Keka#437]
```
Error code 2 using "p7zip"
Fatal error
```
Mac mini (Mid 2011)
version: 10.13.6 (17G65)
Model Name:	Mac mini
Model Identifier:	Macmini5,1
Processor Name:	Intel Core i5
Processor Speed:	2.3 GHz
Number of Processors:	1
Total Number of Cores:	2
L2 Cache (per Core):	256 KB
L3 Cache:	3 MB
Memory:	8 GB

**Comment by aonez** [comment]
Does it fail for any file? On compression and extraction?

**Comment by IceSnow** [comment]
> Does it fail for any file? On compression and extraction?
> […](#)
> On 21 Aug 2019, at 03:59, Roster ***@***.***> wrote: Error code 2 using "p7zip" Fatal error Mac mini (Mid 2011) version: 10.13.6 (17G65) Model Name:	Mac mini Model Identifier:	Macmini5,1 Processor Name:	Intel Core i5 Processor Speed:	2.3 GHz Number of Processors:	1 Total Number of Cores:	2 L2 Cache (per Core):	256 KB L3 Cache:	3 MB Memory:	8 GB — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

frist, sorry, replying so late. and  it happend in some files. On extraction

**Comment by aonez** [comment]
If you reproduce the issue, please share one of those files.

**Comment by IceSnow** [comment]
> If you reproduce the issue, please share one of those files.

Can I give a email? I will provide it to you separately.

**Comment by aonez** [comment]
Sure! Just send it to info [at] keka.io

**Comment by IceSnow** [comment]
> Sure! Just send it to info [at] keka.io

the email has been sent.

**Comment by aonez** [comment]
@IceSnow thanks for the file! I've already fixed the issue for 1.1.19 version. If you've got Keka from the Mac App Store it will be updated soon. If you use the WEB version you can update it right now.

**Comment by IceSnow** [comment]
> @IceSnow thanks for the file! I've already fixed the issue for 1.1.19 version. If you've got Keka from the Mac App Store it will be updated soon. If you use the WEB version you can update it right now.

but i using `Version 1.2.0-dev (3417)`

**Comment by IceSnow** [comment]
> > @IceSnow thanks for the file! I've already fixed the issue for 1.1.19 version. If you've got Keka from the Mac App Store it will be updated soon. If you use the WEB version you can update it right now.
> 
> but i using `Version 1.2.0-dev (3417)`

now, i updated to `Version 1.2.0-dev (3494)`, but it has the same problem. I use the system extraction's tool is normal

**Comment by aonez** [comment]
Check the latest dev build (3542), has this fixed too. If you reproduce the bug there (or in the stable version) please reopen the issue.

Thanks @IceSnow!

**Comment by IceSnow** [comment]
> Check the latest dev build (3542), has this fixed too. If you reproduce the bug there (or in the stable version) please reopen the issue.
> 
> Thanks @IceSnow!

This problem did not occur on  the latest dev build(3575).
