### ISSUE TITLE
 error code 2 using p7zip

### ISSUE THREAD

**Issue by alucent** [aonez/Keka#438]
I want to download the software construct2, which is an .exe file and keka doesn't let me unpack it, I don't know why, please if anyone has a solution I would appreciate it a lot

**Comment by gingerbeardman** [comment]
Not all .exe contain .zip

Even if they do, the zip may be encrypted or special format.

In this case, the .exe does seem to contain zip, but it will not extract using any app I have tried (Unarchiver, unzip, etc)

```
$ file construct2-r269-setup.zip 
construct2-r269-setup.zip: Zip archive data, at least v2.0 to extract
```

```
$ unzip -t construct2-r269-setup.zip 
Archive:  construct2-r269-setup.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of construct2-r269-setup.zip or
        construct2-r269-setup.zip.zip, and cannot find construct2-r269-setup.zip.ZIP, period.
```

**Comment by aonez** [comment]
So it the issue is about the file at [construct2-r269-setup.exe](https://downloads.scirra.com/construct2/construct2-r269-setup.exe), this can't be fixed.
