### ISSUE TITLE
Keka 1.0.9 DMG Corrupt

### ISSUE THREAD

**Issue by ifnull** [aonez/Keka#44]
The DMG will not mount and returns the following system message:

> “Keka-1.0.9.dmg” is damaged and can’t be opened. You should move it to the Trash. 

Multiple attempts were made to download from S3 and Github. The zip from Github seems to work fine.

**Comment by aonez** [comment]
Had a revoked certificate to sign the DMG... Checked it before on a OS X 10.11.6, that eats it anyway.

Resigned again. Thanks for this one too.

**Comment by ifnull** [comment]
👍
