### ISSUE TITLE
Keka hangs when server not available

### ISSUE THREAD

**Issue by gabrielwhite** [aonez/Keka#440]
I last used Keka to do some file operation on an SMB server. 

I changed the name of the server since then.

When I open Keka now, I get an error "NAS - Files not available" and Keka hangs.

I fixed the issue by doing an application reset with CleanMyMac.

**Comment by gabrielwhite** [comment]
I'm using 1.1.17

**Comment by aonez** [comment]
@gabrielwhite thanks for that one!

Most probably Keka created a bookmark to a path where you've done some operations and is trying to resolve this. I'll do some tests.

**Comment by aonez** [comment]
By the way, where do you got that one:

> NAS - Files not available"

It was from Keka or from the OS? Are you using any specific NAS software?

**Comment by gabrielwhite** [comment]
I think it was an OS error, but I can't remember 100% (and I've since fixed the problem, so can't recreate)

**Comment by aonez** [comment]
Did some tests using a SMB shared folder. Can't reproduce the issue. If you reproduce this one again (in case you need to change the name again).

Also let me know if there's any third party software installed that comes with your NAS (in case you're using a NAS). This may be the key.

Thanks @gabrielwhite!
