### ISSUE TITLE
How to extract multiple protected files using same password ?

### ISSUE THREAD

**Issue by angelmic** [aonez/Keka#441]
HI 

Its so easy to use keka on Mac, but I have hundred protected files need to be extracted using same password. How do I do this task without pasted hundred times ?

**Comment by gingerbeardman** [comment]
For now maybe user command line?

Is Apple Script possible using Keka? Just s thought. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by angelmic** [comment]
for now, I just can use script to do that. But I think it should be a feature request.

**Comment by aonez** [comment]
This is a duplicate of #108
