### ISSUE TITLE
Bug in v1.2.0 (3542)

### ISSUE THREAD

**Issue by akrabu** [aonez/Keka#447]
I discovered the solid archive, exclude Mac resource forks, and delete files after compression weren't being respected even though I had them turned on by default and they were checked when I loaded Keka.  I was curious why a 7z archive was larger just because I encrypted it, and then I discovered it was actually because the "exclude Mac resource forks" wasn't being respected.  I then tested for differences after unchecking and rechecking "solid archive" and found discrepancies there as well.

**Comment by aonez** [comment]
Thanks @akrabu! Already spotted and fixed that one! I suppose it's time for a release 😅

**Comment by aonez** [comment]
Fixed version [released](https://github.com/aonez/Keka/releases/tag/v1.2.0-dev.3575)! Thanks again :)
