### ISSUE TITLE
Option to force serialization is missing

### ISSUE THREAD

**Issue by baszero** [aonez/Keka#448]
Many people know it by heart: you want to unzip 100 ZIPs. You select all and open KeKa with it.
What happens is, KeKa tries to unzip 16 ZIPs in parallel. This might be a good option for fast computers, but in many cases it would be useful to force KeKa to not perform any unzipping in parallel.

Please include this option in the preferences! Thanks.

**Comment by aonez** [comment]
This is being developed in https://github.com/aonez/Keka/issues/21. You can already check out the latest beta: https://beta.keka.io

If you check it give any feedback in #21. Thanks!
