### ISSUE TITLE
Beta link 404 from kekaosx.com

### ISSUE THREAD

**Issue by ifnull** [aonez/Keka#45]
The beta link on the homepage of www.kekaosx.com returns a Github 404.

Current link
https://github.com/aonez/Keka/releases/download/v1.1.0-b2/Keka-1.1.0b2r1862.dmg

Correct link
https://github.com/aonez/Keka/releases/download/v1.1.0-beta.2/Keka-1.1.0b2r1862.dmg

**Comment by aonez** [comment]
This has been broken for some time now... Thanks for the tip! Fixed 👍

**Comment by ifnull** [comment]
Thanks for the quick update!
