### ISSUE TITLE
Does not compress now

### ISSUE THREAD

**Issue by tabildskov** [aonez/Keka#450]
Hello - I just tried the Keka-1.2.0-dev.3575 version and installed it on a iMac with OS 10.11.6. The resulting file is about the same size as the folder I was trying to compress. Also, while the compression was going on I noticed in the activity monitor that very little of the CPU was being used. It acts like it is creating a no compression zip file not a normal compression zip file.

**Comment by aonez** [comment]
What type of files where you compressing? Note that images, video and audio is usually already compressed.

While testing for this I found that this dev version crashes on 10.9-10.13, so definitely I need to check backwards compatibility. Even if it crashed, the compression was done properly.
