### ISSUE TITLE
macos10.15不能使用

### ISSUE THREAD

**Issue by wangshiyang** [aonez/Keka#452]
从apple store下载的最新版本
解压zip文件的时候 提示: 错误22-无效的参数

**Comment by aonez** [comment]
Hi @wangshiyang,

Can you reproduce this issue with any file? If that is the case, please:

1. Close Keka
2. [Clean the Keka preferences](https://github.com/aonez/Keka/wiki/Uninstall-Keka#2-delete-the-preferences)
3. Try again

If it still fails, please [enable the verbose log](https://github.com/aonez/Keka/wiki/Console-verbose), repeat the process that generates the error and share the results.

**Comment by wangshiyang** [comment]
@aonez 彻底删除 重新安装后 可以正常使用了 谢谢

**Comment by aonez** [comment]
Thanks @wangshiyang! Enjoy with Keka :)
