### ISSUE TITLE
Lost my file access rights?

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#455]
Today I had to reset file access rights in Keka preferences for seemingly no reason?

![Screen shot 2019-10-14 at 12 23 34](https://user-images.githubusercontent.com/49612/66747865-7901e200-ee7d-11e9-8b9b-cb94620524a7.png)

**Comment by aonez** [comment]
Did you changed the Mac disc name? Or updated the OS?

**Comment by aonez** [comment]
If Keka detects that a bookmark (file access) is no more valid, removes it. In this case, since you have the bookmark for / macOS may break that bookmark for a lot of reasons.

**Comment by gingerbeardman** [comment]
No changes, drive name or OS. 

I recently did a CleanMyMac smart scan which I think could be the culprit.

Will keep an eye on it, but closing.
