### ISSUE TITLE
MacOS' Aliases break on every spanable compression type :(

### ISSUE THREAD

**Issue by DBLjan** [aonez/Keka#46]
I try to backup some things on my mac, and I need a spanable compression format, but every spanable format does break Aliases, no matter if I include or exclude the mac ressources.

I tried ISO and DMG which work fine. Also the OS interne archiver does .zip/unzip thes files flawless.

Any ideas with a workaround to compress some assorted mac-folders in a spanable archive type? 

OSX 10.11.6 and KeKa Version 1.0.9 (1756)

**Comment by DBLjan** [comment]
…I could use a DMG and then slit it up by zip…but that would neglect the intent of not loosing -all- data if one .00zip-file is damaged – the whole DMG will fail to process.

Any other ideas?

**Comment by aonez** [comment]
You're right... The first thing that comes to my mind is using a symlink instead of macOS _Make Alias_:

`ln -s <path> <symlink>`

Those are working as expected, though I don't know if they will fit your needs.

**Comment by aonez** [comment]
Next revision 1.1.0 should work for you. Using tar, or gz, bz2, xz, lz tarballs should keep your aliases intact.
