### ISSUE TITLE
Hidden preference to prevent pause after extraction and before app closes?

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#461]
After extraction there is a wait before Keka closes.

Perhaps this: https://github.com/aonez/Keka/issues/224#issuecomment-400262501
> This is a feature, Keka waits for the notification to close, so in case you click on it it can show in the finder the extraction/compression files. This is a 5 seconds wait.

I find this wait annoying, waiting for my finder window to regain focus so I can work with the extracted files. 

Any chance there can be a hidden pref to disable it? So Keka closes immediately after extraction is finished.

Thanks!

**Comment by aonez** [comment]
@gingerbeardman the 1.2.0 build does not have this 5 seconds fixed wait, but it waits for the extraction/compre sound to play. If no sound is enabled there will be no wait.

Anyway maybe I can try to lose focus once there's no more operations.

**Comment by gingerbeardman** [comment]
I am still using 1.1.20

**Comment by aonez** [comment]
> 1.1.20

Yes, is 1.2.0 that has it changed. The version numbers are so similar right now 😂

**Comment by aonez** [comment]
Can you check this build?

https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-wait-hide.7z

**Comment by gingerbeardman** [comment]
This new build is much better experience for me. Thanks!
