### ISSUE TITLE
Checksum mismatch for Keka-1.0.9.dmg

### ISSUE THREAD

**Issue by gfab23** [aonez/Keka#47]
Hello

There is a mismatch with the MD5 checksum for the Keka-1.0.9.dmg file. On http://www.kekaosx.com/en/ (and also other languages), the following is mention:
```
 Download Keka 1.0.9 (19.2 MB)
Requires Mac OS X 10.7 or newer
MD5: f7cca32cf77a00cff66d127bd84af6b5 
```
But the downloaded file then has a different checksum:
```
 $ openssl md5 Keka-1.0.9.dmg 
MD5(Keka-1.0.9.dmg)= af5659e5e2c92e624f71a3340fa06d28
 $ md5 Keka-1.0.9.dmg 
MD5 (Keka-1.0.9.dmg) = af5659e5e2c92e624f71a3340fa06d28
```
Did something strange happen to the file from the download?

**Comment by aonez** [comment]
Forgot to update them since I've reuploaded them because #44. Updating md5 in a few minutes.

Thanks for spotting that 👍🏼

**Comment by aonez** [comment]
Done!
