### ISSUE TITLE
"Compress with Keka" gives archive with no compression (same size as original)

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#473]
Using "Compress with Keka" service I get a file of the same size as the original. I have tried ZIP and 7Z formats.

If I drop onto Keka window I get a truly compressed file (respecting Keka prefs).

problem: v1.2.0-dev

no problem: 1.1.21

**Comment by aonez** [comment]
Do you have the proper method selected in the Preferences I assume:

![Screen Shot 2019-10-29 at 13 35 00](https://user-images.githubusercontent.com/480163/67767492-f9fdd380-fa50-11e9-985e-775e6f54c7d3.png)

This is strange. If you've told me that the format is not respected, but only the method... Can enable the [verbose mode](https://github.com/aonez/Keka/wiki/Console-verbose) and take a look in the Console.app what arguments the process executes.

**Comment by gingerbeardman** [comment]
![Screen shot 2019-10-29 at 12 57 21](https://user-images.githubusercontent.com/49612/67769277-14817e00-fa4c-11e9-9bdf-0d7c1cecc4fe.png)

![Screen shot 2019-10-29 at 12 58 39](https://user-images.githubusercontent.com/49612/67769278-14817e00-fa4c-11e9-889b-64d085539c3e.png)


https://gist.github.com/gingerbeardman/20f9d7cfe52047c909e37279795f5a90

**Comment by aonez** [comment]
> https://gist.github.com/gingerbeardman/20f9d7cfe52047c909e37279795f5a90

There it says `-mx0` (no compression), but you clearly have "slowest" selected.

What this code returns for you? Must return `5`:

```sh
defaults read com.aone.keka DefaultMethod
```

**Comment by gingerbeardman** [comment]
It returns 3

**Comment by gingerbeardman** [comment]
Are the Services defined in code?

**Comment by aonez** [comment]
> Are the Services defined in code?

Yep, in the latest versions it is just a bridge to the usual compression/extraction call

**Comment by gingerbeardman** [comment]
PS: using Keka v1.2.0-dev

**Comment by gingerbeardman** [comment]
Using 1.1.21 problem is not present

**Comment by aonez** [comment]
> PS: using Keka v1.2.0-dev

Ah! I was checking the stable version 😅

**Comment by gingerbeardman** [comment]
Sorry for not mentioning that sooner.

**Comment by aonez** [comment]
@gingerbeardman check this build: [Keka-1.2.0r3622](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.2.0r3622.7z)

**Comment by gingerbeardman** [comment]
That works! Thanks
