### ISSUE TITLE
Compress button as first responder to enable keyboard

### ISSUE THREAD

**Issue by pSpitzner** [aonez/Keka#475]
I am using keka frequently to compress folders - launched from [alfred](https://www.alfredapp.com/) via `open with...` (or alternatively, via services `compress with keka`). This is a very keyboard-centric workflow.

As shown in the screenshot, per default, the path selection window of keka is not the first responder. Instead, the progress window is frontmost. Therefore, one cannot simply press `enter` to start the compression. A mouse click is required to actiate the window first.

It would be great if we could invert this.

I believe `makeFirstResponder` [(see apple documentation)](https://developer.apple.com/documentation/appkit/nswindow/1419366-makefirstresponder) is what would enable the desired behaviour.

Thanks for looking into it!
Best,
Paul

PS: Would be glad to try myself if you are still willing to share code after the copy-cat issue.

<img width="870" alt="Screenshot 2019-11-01 at 13-27-46" src="https://user-images.githubusercontent.com/12393119/68025446-05e5d180-fcad-11e9-9aeb-f078c2b4c7b6.png">

**Comment by aonez** [comment]
Thanks for the tip @pSpitzner!

> I believe `makeFirstResponder`

In fact this one is creating the issue 😂 it's being called for the tasks window after the save dialog appears.

The fix for one task is very straightforward, coming in 1.1.22. A proper fix for multiple tasks will come in 1.2.0, since it involves more changes.

**Comment by aonez** [comment]
Sorry I meant `makeKeyAndOrderFront` is creating the issue.

**Comment by aonez** [comment]
Fixed build here: [Keka-1.1.22r3389.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.1.22r3389.7z)
