### ISSUE TITLE
Exclude MAC resource files

### ISSUE THREAD

**Issue by 0dayman** [aonez/Keka#476]
Version: 1.1.21 (3378)
System version: 10.14.6 (18g1012)
Problem Description:
Check "exclude MAC resource files (for example,. Ds_store)", but these MAC resource files can still be seen after the windows 10 system decompresses them. What should I do?

**Comment by aonez** [comment]
What format are you compressing in?

Jordi

**Comment by 0dayman** [comment]
zip

**Comment by 0dayman** [comment]
![屏幕快照 2019-11-03 10 53 30](https://user-images.githubusercontent.com/38482781/68082262-729bd000-fe55-11e9-9289-c1435090a79a.png)

**Comment by aonez** [comment]
Keka does not create that _MACOSX folder. Probably you’ve created that file with the contextual menu of Mac.

Jordi

**Comment by aonez** [comment]
https://github.com/aonez/Keka/wiki/Compressing-with-Keka#using-the-context-menu-services

This is how to compress using Keka and the contextual menu of Mac. The default “Compress file” item uses the macOS compressor, not Keka.

Jordi

**Comment by 0dayman** [comment]
Sorry, it is my negligence, thank you.

**Comment by aonez** [comment]
No problem!
