### ISSUE TITLE
Can't compress ISO file

### ISSUE THREAD

**Issue by adamreisnz** [aonez/Keka#478]
It doesn't seem to be possible to compress an existing ISO file with Keka or to add it to a zip file.

Whenever I open the window and select ZIP then try to drag the ISO file to the window, Keka will try to EXTRACT the ISO file, rather than add it to the zip file.

Maybe that's a problem when you try to make the UI too smart...

Can we please have manual options for CREATE archive and select files we want to add, instead of this "smart" drag drop which doesn't always do what we want it to do?

**Comment by gingerbeardman** [comment]
https://github.com/aonez/Keka/wiki/Compressing-with-Keka

- Drag to top of window to extract
- Drag to bottom of window to compress

Hopefully that helps.

**Comment by adamreisnz** [comment]
Lol, yeah sorry but that's just silly. I've since uninstalled the app and went to buy Archiver instead.

Maybe next time consider some more logical and clear UX choices as this fancy drag to top/bottom of window is probably too much for many users.

Context menu wasn't there, it's the first thing I looked for.

**Comment by alvarnell** [comment]
gingerbeardman is just a contributor here, not the developer. 
 
Maybe next time you should wait to see how your suggestion was taken into consideration.

**Comment by gingerbeardman** [comment]
@adamreisnz in all fairness you don't have to dig into the manual, you just have to read what's on the screen as you drag. 

v1.20 looks like this
![Screen shot 2019-11-06 at 09 19 16](https://user-images.githubusercontent.com/49612/68285167-ae61b000-0076-11ea-966b-e0b000337a03.png)

**Comment by gingerbeardman** [comment]
I was just using BetterZip and I got this in the main window, very similar to Keka.

https://imgur.com/a/tYEbfxF
