### ISSUE TITLE
Add Dual Layer DVD discs as split option

### ISSUE THREAD

**Issue by MikeExMachina** [aonez/Keka#479]
DL DVD are missing as a split option.

**Comment by MikeExMachina** [comment]
Well I'm dumb didn't notice BR are on there, but DL DVDs are not. My request was really about DL DVDs and I just assumed DVD was the biggest option.

**Comment by aonez** [comment]
Hi @MikeExMachina! Indeed, DVD deserves more attention.

**Comment by aonez** [comment]
Fixed build here: [Keka-1.1.22r3389.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.1.22r3389.7z)
