### ISSUE TITLE
1.0.9 breaks extraction of password-protected RAR files

### ISSUE THREAD

**Issue by tcobbs** [aonez/Keka#48]
When attempting to extract a password-protected RAR file, version 1.0.9 instead gives the following error message:

Extraction of "<filename>" failed
Error code 255 using "unrar"
Canceled manually

**Comment by aonez** [comment]
Fixing that recursive bug right ahead. Thanks for the feedback @tcobbs!

**Comment by aonez** [comment]
Waiting for MAS review...

**Comment by aonez** [comment]
Released. Sorry for this one.

**Comment by tcobbs** [comment]
Thank you very much for the very quick fix.
