### ISSUE TITLE
Slight typo in "default uncompressor" dialog box

### ISSUE THREAD

**Issue by theodore-s-beers** [aonez/Keka#482]
<img width="360" alt="Screen Shot 2019-11-13 at 09 39 02" src="https://user-images.githubusercontent.com/32523293/68746839-b59a3800-05f9-11ea-9540-870dca61daa7.png">
This is in version 1.1.22. It should read "its" in place of "it's." I know this is a ridiculously minor thing to file, but hey, it can't hurt. Thank you for your work on this great app.

**Comment by aonez** [comment]
Thanks @theodore-s-beers!

**Comment by aonez** [comment]
Was fixed here 9fe300a by @isjamesalive but left unchanged in the code so the string was not matching 😅 fixed for next release!
