### ISSUE TITLE
UNRAR fail on 15 piece divided file

### ISSUE THREAD

**Issue by epiccallingX** [aonez/Keka#489]
I recently bought this software, https://redroomaudio.com/product/palette-symphonic-sketchpad/ and it comes as a 15 piece divided file. none of the files exceed 2.15 gb. the main file will extract, but the files containing the actual samples fail to extract every time. I tried using verbose mode but it didn't help. any suggestions? I am on a deadline, and really need this to work. Thank you for the help!

**Comment by epiccallingX** [comment]
default	06:10:49.273382-0600	Finder	LAUNCHING:0x0-0x13e13e Keka foreground=1 bringForward=1 seed=196 userActivityCount=0
default	06:10:49.280495-0600	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Keka, ready, updating active tracking timer
default	06:10:49.280539-0600	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Keka
default	06:10:49.304126-0600	runningboardd	Resolved pid 15896 to [executable<Keka(502)>:15896]
default	06:10:49.306718-0600	runningboardd	[executable<Keka(502)>:15896] This process will not be managed.
default	06:10:49.306741-0600	runningboardd	Now tracking process: [executable<Keka(502)>:15896]
default	06:10:49.307070-0600	runningboardd	Acquiring assertion targeting executable<Keka(502)> from originator [daemon<com.apple.coreservices.launchservicesd>:133] with description <RBSAssertionDescriptor; foregroundApp:15896; ID: 274-133-842; target: 15896> attributes = {
    <RBSDomainAttribute: 0x7fb36551d220; domain: com.apple.launchservicesd; name: RoleUserInteractiveNonFocal; sourceEnvironment: 0x0>;
}
default	06:10:49.307173-0600	runningboardd	Assertion 274-133-842 (target:executable<Keka(502)>) will be created as active
default	06:10:49.307642-0600	runningboardd	Acquiring assertion targeting executable<Keka(502)> from originator [daemon<com.apple.coreservices.launchservicesd>:133] with description <RBSAssertionDescriptor; foregroundApp:15896; ID: 274-133-843; target: 15896> attributes = {
    <RBSDomainAttribute: 0x7fb36543a890; domain: com.apple.launchservicesd; name: RoleUserInteractiveNonFocal; sourceEnvironment: 0x0>;
}
default	06:10:49.307676-0600	runningboardd	[executable<Keka(502)>:15896] Ignoring jetsam update because this process is not memory-managed
default	06:10:49.307774-0600	runningboardd	[executable<Keka(502)>:15896] Ignoring resume because this process is not lifecycle managed
default	06:10:49.307785-0600	runningboardd	Assertion 274-133-843 (target:executable<Keka(502)>) will be created as active
default	06:10:49.307847-0600	runningboardd	[executable<Keka(502)>:15896] Set darwin role to: UserInteractiveNonFocal
default	06:10:49.307878-0600	runningboardd	Finished acquiring assertion 274-133-842 (target:executable<Keka(502)>)
default	06:10:49.307902-0600	runningboardd	[executable<Keka(502)>:15896] Ignoring GPU update because this process is not GPU managed
default	06:10:49.308725-0600	runningboardd	Finished acquiring assertion 274-133-843 (target:executable<Keka(502)>)
default	06:10:49.308732-0600	runningboardd	Invalidating assertion 274-133-842 (target:executable<Keka(502)>) from originator 133
default	06:10:49.530917-0600	secinitd	Keka[15896]: root path for bundle "<private>" of main executable "<private>"
default	06:10:49.560030-0600	secinitd	Keka[15896]: AppSandbox request successful
default	06:10:49.598433-0600	Keka	FRONTLOGGING: version 1
default	06:10:49.598454-0600	Keka	Registering, pid=15896
default	06:10:49.601463-0600	Keka	CHECKIN: pid=15896
default	06:10:49.621699-0600	launchservicesd	CHECKIN:0x0-0x13e13e 15896 com.aone.keka
default	06:10:49.622476-0600	Keka	CHECKEDIN: pid=15896 asn=0x0-0x13e13e foreground=1
default	06:10:49.625206-0600	lockoutagent	Requesting policy for bundle IDs: (
    "com.aone.keka"
)
default	06:10:49.625144-0600	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Keka
default	06:10:49.626324-0600	lockoutagent	Requested application <private> has policy 0, associated category:DH1005 associated sites:(null) equivalent bundle identifiers:com.aone.keka
default	06:10:49.636636-0600	Keka	Registered, pid=15896 ASN=0x0,0x13e13e
default	06:10:49.636782-0600	Keka	Registered, pid=15896 cgConnectionID=68edf
default	06:10:49.639512-0600	Keka	BringForward: pid=15896 asn=0x0-0x13e13e bringForward=1 foreground=1 uiElement=0 launchedByLS=1 modifiersCount=1 allDisabled=0
default	06:10:49.639566-0600	Keka	BringFrontModifier: pid=15896 asn=0x0-0x13e13e Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
default	06:10:49.639811-0600	Keka	BringForward: pid=15896 asn=0x0-0x13e13e
default	06:10:49.640068-0600	Keka	SetFrontProcess: asn=0x0-0x13e13e options=0
default	06:10:49.641541-0600	runningboardd	Acquiring assertion targeting executable<Keka(502)> from originator [daemon<com.apple.coreservices.launchservicesd>:133] with description <RBSAssertionDescriptor; frontmost:15896; ID: 274-133-844; target: 15896> attributes = {
    <RBSDomainAttribute: 0x7fb365720860; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
}
default	06:10:49.641676-0600	runningboardd	Assertion 274-133-844 (target:executable<Keka(502)>) will be created as active
default	06:10:49.644623-0600	Keka	Current system appearance, (HLTB: 1), (SLS: 0)
default	06:10:49.642388-0600	runningboardd	Finished acquiring assertion 274-133-844 (target:executable<Keka(502)>)
default	06:10:49.646703-0600	runningboardd	[executable<Keka(502)>:15896] Ignoring jetsam update because this process is not memory-managed
default	06:10:49.646732-0600	runningboardd	[executable<Keka(502)>:15896] Set darwin role to: UserInteractiveFocal
default	06:10:49.646750-0600	runningboardd	[executable<Keka(502)>:15896] Ignoring GPU update because this process is not GPU managed
default	06:10:49.647417-0600	Keka	Post-registration system appearance: (HLTB: 1)
default	06:10:49.658353-0600	distnoted	register name: com.apple.xctest.FakeForceTouchDevice object: com.aone.keka token: f4268 pid: 15896
default	06:10:49.665407-0600	Keka	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x60000202a100
 (
    "<NSAquaAppearance: 0x60000202a000>",
    "<NSSystemAppearance: 0x600002029b00>"
)>
default	06:10:49.672235-0600	distnoted	register name: com.apple.nsquiet_safe_quit_give_reason object: com.aone.keka token: f426f pid: 15896
default	06:10:49.688635-0600	Keka	Updating user defaults from 3390...
default	06:10:49.690623-0600	Keka	Dev mode enabled
default	06:10:49.690659-0600	Keka	Dev reader mode enabled
default	06:10:49.690681-0600	Keka	Dev notifications mode enabled
default	06:10:49.690733-0600	Keka	Running on OS X/macOS version 10.15.1 (Build 19B88)
default	06:10:49.690766-0600	Keka	Running sandboxed Keka (WEB) version 1.1.22 (3390)
default	06:10:49.691914-0600	Keka	Used localization: en
default	06:10:49.693989-0600	Keka	Registering for test daemon availability notify post.
default	06:10:49.694137-0600	Keka	notify_get_state check indicated test daemon not ready.
default	06:10:49.742430-0600	Keka	SignalReady: pid=15896 asn=0x0-0x13e13e
default	06:10:49.745771-0600	Keka	SIGNAL: pid=15896 asn=0x0x-0x1302846
default	06:10:49.779577-0600	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier com.aone.keka, type: 0: 0x7f9e96645d40 at /Applications/Keka.app
default	06:10:49.795456-0600	Keka	Adding 1 files
default	06:10:49.795537-0600	Keka	Waiting for more input: 0.250000
default	06:10:49.795677-0600	Keka	Requesting access to all bookmarks...
default	06:10:49.795766-0600	Keka	Bookmarks updated: 1
error	06:10:49.804936-0600	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: com.aone.keka, PID[15896], auid: 502, euid: 502, binary path: '/Applications/Keka.app/Contents/MacOS/Keka'}, REQ:{ID: com.apple.appleeventsd, PID[294], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}
default	06:10:49.805592-0600	Keka	DEPRECATION: SUUpdater is now deprecated. Please use SPUStandardUpdaterController as a nib instantiated replacement, or SPUUpdater.
default	06:10:50.131668-0600	Keka	Format detected: RAR
default	06:10:50.170672-0600	Keka	Binary used: kekaunrar
default	06:10:50.170733-0600	Keka	Arguments: (
    x,
    "-idcd",
    "-x*/__MACOSX",
    "-y",
    "/Users/joshuaangle/Palette/Palette-Symphonic-Sketchpad-SAMPLES.part01.rar",
    "/Users/joshuaangle/Palette/.Keka-C0765362-7DDB-495B-832A-D89AF5163063/"
)
default	06:10:50.194224-0600	Keka	Extraction output: 


Extracting from /Users/joshuaangle/Palette/Palette-Symphonic-Sketchpad-SAMPLES.part01.rar
default	06:10:50.194407-0600	Keka	Extraction output: 

Creating    /Users/joshuaangle/Palette/.Keka-C0765362-7DDB-495B-832A-D89AF5163063  OK
Creating    /Users/joshuaangle/Palette/.Keka-C0765362-7DDB-495B-832A-D89AF5163063/Palette  OK
default	06:10:50.194540-0600	Keka	Extraction output: 

Creating    /Users/joshuaangle/Palette/.Keka-C0765362-7DDB-495B-832A-D89AF5163063/Palette/Samples  OK
Extracting  /Users/joshuaangle/Palette/.Keka-C0765362-7DDB-495B-832A-D89AF5163063/Palette/Samples/Palette Symphonic Sketchpad_001.nkc
default	06:10:50.212271-0600	Keka	Extraction output: 
\^H\^H\^H\^H  0%
default	06:10:50.214081-0600	Keka	Extraction output: 
\^H\^H\^H\^H\^H  OK
default	06:10:50.214584-0600	Keka	Extraction output: 

Extracting  /Users/joshuaangle/Palette/.Keka-C0765362-7DDB-495B-832A-D89AF5163063/Palette/Samples/Palette Symphonic Sketchpad_001.nkx
default	06:10:50.270243-0600	Keka	Extraction output: 
\^H\^H\^H\^H  0%
default	06:10:54.283869-0600	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : Keka
default	06:10:54.283884-0600	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: Keka
default	06:10:54.283910-0600	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: Keka
default	06:10:54.287206-0600	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Contents:(
        {
        BackgroundState = 0;
        BundleID = "com.aone.keka";
        Hide = 0;
        Path = "/Applications/Keka.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/System/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.safari";
        Hide = 0;
        Path = "/Applications/Safari.app";
    }
)
default	06:10:59.709665-0600	Keka	LSExceptions shared instance invalidated for timeout.
default	06:11:21.176254-0600	Keka	done: 1
default	06:11:21.184459-0600	Keka	Notify /Users/joshuaangle/Palette/Palette-Symphonic-Sketchpad-SAMPLES.part01.rar with code 0
default	06:11:21.297890-0600	Keka	Notification didDeliverNotification
default	06:11:21.298012-0600	Keka	{
    code = 0;
    path = "/Users/joshuaangle/Palette/Palette-Symphonic-Sketchpad-SAMPLES.part01.rar";
    type = 3;
}
default	06:11:21.298276-0600	Keka	Notification shouldPresentNotification
default	06:11:21.298366-0600	Keka	:{
    code = 0;
    path = "/Users/joshuaangle/Palette/Palette-Symphonic-Sketchpad-SAMPLES.part01.rar";
    type = 3;
}
default	06:11:21.301134-0600	Keka	GNClastNotificationDate: 2019-11-25 12:11:21 +0000
default	06:11:21.303383-0600	NotificationCenter	Queuing action present for app com.aone.keka.
default	06:11:21.308032-0600	NotificationCenter	Queuing action delivered for app com.aone.keka.
default	06:11:24.406950-0600	Keka	Show: pid=15896 asn=0x0-0x13e13e
default	06:11:24.407238-0600	Keka	Now: 2019-11-25 12:11:24 +0000
default	06:11:24.407291-0600	Keka	Last notificatoin: 2019-11-25 12:11:21 +0000
default	06:11:24.407325-0600	Keka	Time interval: 3.216573
default	06:11:24.407350-0600	Keka	Waiting 1.783427 for notification to quit...
default	06:11:24.424231-0600	runningboardd	Invalidating assertion 274-133-844 (target:executable<Keka(502)>) from originator 133
default	06:11:24.527832-0600	runningboardd	[executable<Keka(502)>:15896] Ignoring jetsam update because this process is not memory-managed
default	06:11:24.527863-0600	runningboardd	[executable<Keka(502)>:15896] Set darwin role to: UserInteractiveNonFocal
default	06:11:24.527883-0600	runningboardd	[executable<Keka(502)>:15896] Ignoring GPU update because this process is not GPU managed
default	06:11:26.192253-0600	Keka	Show: pid=15896 asn=0x0-0x13e13e
default	06:11:26.192593-0600	Keka	Now: 2019-11-25 12:11:26 +0000
default	06:11:26.192645-0600	Keka	Last notificatoin: 2019-11-25 12:11:21 +0000
default	06:11:26.192672-0600	Keka	Time interval: 5.001941
default	06:11:26.192702-0600	Keka	Now: 2019-11-25 12:11:26 +0000
default	06:11:26.192728-0600	Keka	Last notificatoin: 2019-11-25 12:11:21 +0000
default	06:11:26.192751-0600	Keka	Time interval: 5.002068
default	06:11:26.192852-0600	Keka	Stopping access to all bookmarks...
default	06:11:26.195384-0600	NotificationCenter	Queuing action removeAlert for app com.aone.keka.
default	06:11:26.206748-0600	NotificationCenter	Queuing action delivered for app com.aone.keka.
default	06:11:26.208961-0600	runningboardd	[executable<Keka(502)>:15896] Death sentinel fired!
default	06:11:26.218971-0600	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Keka, _appTrackingState = 2
default	06:11:26.218991-0600	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: Keka, quit, updating active tracking timer
default	06:11:26.225759-0600	runningboardd	Invalidating assertion 274-133-843 (target:executable<Keka(502)>) from originator 133
default	06:11:26.404661-0600	runningboardd	Removing process: [executable<Keka(502)>:15896]
default	06:11:26.426568-0600	runningboardd	Removing assertions for terminated process: [executable<Keka(502)>:15896]
default	06:11:31.219865-0600	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      previouslyRunningApps: (
        {
        BackgroundState = 0;
        BundleID = "com.aone.keka";
        Hide = 0;
        Path = "/Applications/Keka.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/System/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.safari";
        Hide = 0;
        Path = "/Applications/Safari.app";
    }
)

**Comment by epiccallingX** [comment]
that's the console info. I know pretty much nada about coding, so I really can't make sense of half of it

**Comment by aonez** [comment]
What error is showing Keka? In the logs you’ve shared I’m seeing “
 Palette-Symphonic-Sketchpad-SAMPLES.part01.rar” was decompressed
successfully.

**Comment by epiccallingX** [comment]
It gives me the File extraction failed with the small text saying it might be corrupt. the files are all the right size though.

**Comment by epiccallingX** [comment]
it creates a file but it contains no samples

**Comment by aonez** [comment]
This might be related to #362. You’ve said you’ve tried multiple times,
though.

**Comment by epiccallingX** [comment]
right

**Comment by aonez** [comment]
Is it possible for you to share the files with me?

**Comment by aonez** [comment]
Can you check all the parted files (but the last one) are the same size?

**Comment by epiccallingX** [comment]
give me a sec

**Comment by epiccallingX** [comment]
Thats right about the file size

**Comment by epiccallingX** [comment]
can I email you the files?

**Comment by aonez** [comment]
> can I email you the files?

Sure! info@keka.io

**Comment by epiccallingX** [comment]
okay

**Comment by epiccallingX** [comment]
it sent with mail-drop

**Comment by epiccallingX** [comment]
did it go through?

**Comment by aonez** [comment]
> did it go through?

Not yet...

Can you try with the Terminal?:

```sh
f='/Users/joshuaangle/Palette'; cd "${f}"; /Applications/Keka.app/Contents/Resources/kekaunrar x "${f}/Palette-Symphonic-Sketchpad-SAMPLES.part01.rar"
```

**Comment by epiccallingX** [comment]
sure thing

**Comment by epiccallingX** [comment]
looks like that's working

**Comment by aonez** [comment]
So it definitely must be #362. The damn sandbox killing the process.

**Comment by epiccallingX** [comment]
it crashed at part 3. should I retry?

**Comment by aonez** [comment]
> it crashed at part 3. should I retry?

If crashed in the Terminal, then definitely there's corruption in the file. Try downloading again the part 3.

**Comment by epiccallingX** [comment]
okay

**Comment by epiccallingX** [comment]
Hey.
Just wanted to say thanks. My software is up and running!! Y’all are awesome!

**Comment by aonez** [comment]
Thanks @epiccallingX! This will be improved in #116, with better error messages :)
