### ISSUE TITLE
4480MB split creates 4.7GB files under Mac OS 10.12.5

### ISSUE THREAD

**Issue by rcosgrove** [aonez/Keka#49]
Keka: v 1.0.9 (1756)
OS: Mac 10.12.5

When I used Keka to create a 7zip archive, using the pre-set 4480MB split option, it created a 4.7GB file that OS X reported as being too large to burn to DVD or disc images.

**Comment by aonez** [comment]
The result file is 4.700.372.992 bytes?

**Comment by aonez** [comment]
**DVD+R** and **DVD+R** are set to this size. I'm seeing that **DVD-** has lees space at 4.700.000.000 and 4.700.307.456. Are you using a **DVD-** device?

I'll adjust the size to **4.700.000.000** so it's compatible with all devices.

**Comment by rcosgrove** [comment]
> The result file is 4.700.372.992 bytes?
Yes, according to Pathfinder

> Are you using a *DVD-* device?
No. I'm using an Apple Superdrive, which uses DVD±RW (±R DL), and "4.7GB"
DVD+R discs.

And I used Burn v 2.5.1 (24) to create the DVDs.

> I'll adjust the size to *4.700.000.000*
Thanks. As a workaround, I split the archive into CD-sized files, and burnt
those to DVDs.

- Richard



--
Richard Cosgrove

**Comment by aonez** [comment]
Meanwhile you can set the split to custom **4.7g**. As soon as I have access to a Mac with superdrive I'll test that issue with [Burn](http://burn-osx.sourceforge.net) (by the way my defecto burner since I own a Mac).

**Comment by aonez** [comment]
I'll set the fixed size to 4698500000 bytes so a 4.7 DVD will have at least 1.5 MB "free".

**Comment by aonez** [comment]
Next revision 1.0.11 will have a quick fix of that. A better implementation will come in 1.1.0 revision.

**Comment by rcosgrove** [comment]
Great. Thank you for working on a fix so quickly.

--
Richard Cosgrove
