### ISSUE TITLE
Creating .zip files broken with Keka 1.1.23

### ISSUE THREAD

**Issue by tiiiecherle** [aonez/Keka#494]
Hey,

first of all thanks for this really nice software and all the work put into it ;)

I'm using the latest macOS version 10.15.1.

We found a bug with the latest version of keka (1.1.23). 

When using the following settings:
- zip
- compression normal
- exclude macOS resource files: yes

creating the .zip file via drag & drop fails with the following error:
Creation of filename.zip failed
error number 2 with p7zip
fatal error

Downgrading to keka 1.1.22 solves this issue.

Thanks for looking into it in advance.

Kind regards and have a nice weekend

**Comment by aonez** [comment]
@tiiiecherle this has been reported multiple times but I'm still unable to reproduce the issue. Can you enable the [verbose mode](https://github.com/aonez/Keka/wiki/Console-verbose), reproduce the issue and let me know what the Console.app says?

To enable the verbose mode:

```sh
defaults write com.aone.keka DevLog true;
defaults write com.aone.keka DevLogReader true;
```

**Comment by aonez** [comment]
Can you please check if any of those fixes the issue:

- https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-LP.7z
- https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-WC.7z

**Comment by sunford** [comment]
Keka-LP.7z helped! But I installed from appstore.

**Comment by aonez** [comment]
@sunford Keka-WC failed for you?

**Comment by tiiiecherle** [comment]
Thanks for the fast response. Keka-LP.7z works but Keka-WC.7z still has the same issue.

**Comment by tiiiecherle** [comment]
do you still need the verbose mode logs? If yes, I have to get back to you tomorrow. Thanks again for the fast help and the great app.

**Comment by sunford** [comment]
> Keka-WC failed

Yes, please upload update to appstore.

**Comment by aonez** [comment]
Already pushed the update to MAS, hopefully they’ll review and approve in a
few hours.

**Comment by tiiiecherle** [comment]
Thanks, it would be nice if you could do a release here, too. I would push it to home-brew-cask then.

**Comment by aonez** [comment]
Both updates are coming

**Comment by aonez** [comment]
@tiiiecherle WEB release is ready. The MAS release is still waiting for Apple to review and approve...

**Comment by aonez** [comment]
@sunford the update just got approved by Apple, should appear in a few minutes in the store.

Thanks again to both of you!

**Comment by tiiiecherle** [comment]
Thanks a lot again. Fixed build is working. Pull request submitted for homebrew-cask a minute ago ;) Have a nice weekend.

In my opinion this issue can be closed ;)

**Comment by sunford** [comment]
Now it works ) thanks!
