### ISSUE TITLE
Some texts are not displayed in the "about" screen

### ISSUE THREAD

**Issue by sigseg5** [aonez/Keka#496]
If you open the About screen, then the text for several categories is not displayed:

- Programmer, designer & maintainer:
- Artwork designer:
- Translations:
- Translations (from 0.1 to 0.1.4.3):
- Occasional testers:
- Donations (most sorted by date):
- Keka uses open source code:
- Keka uses freeware binaries:

<img width="396" alt="image" src="https://user-images.githubusercontent.com/36568961/70380186-041cc700-1959-11ea-8492-0429c093d6e8.png">

macOS Catalina 10.15.1 (19B88)
Keka Version 1.1.24 (3421)

**Comment by aonez** [comment]
Thanks for the tip @sigseg5! Seems that in Catalina `iframe`s are no longer supported in the default about window. Glad already changed that for 1.2.0 :)

Fixing anyway for 1.1.25, since 1.2.0 is not yet ready.
