### ISSUE TITLE
Chrome warning when downloading latest release

### ISSUE THREAD

**Issue by Underdoge** [aonez/Keka#50]
Getting the following security error when trying to download the latest release from [Github](https://github.com/aonez/Keka/releases/download/v1.0.11/Keka-1.0.11.dmg) using Chrome.

[Warning message](http://i.imgur.com/91RqKCi.png)

**Comment by aonez** [comment]
Cannot reproduce this one. Still happens to you?

**Comment by Underdoge** [comment]
Nope, I guess it was just a temporary thing, it works fine now, thanks.
