### ISSUE TITLE
Smart default filename option for new multi-file archives

### ISSUE THREAD

**Issue by Darklocq** [aonez/Keka#501]
I guess it's not completely terrible that Keka produces something like `Compressed file.7z` by default when you create a new multi-file archive.  Various other tools, including the built-in `Apple Archive Utility.app`, do something similar.

However, it would be more helpful if, when all the filenames start with a common character string, to use that in the resulting archive file name.  E.g., when I 7z up a pile of files: 

- `Keka_2019-12-12-070227_Serenity.hang`
- `Keka_2019-12-12-074453_Serenity.cpu_resource.diag`
- `Keka_2019-12-12-074847_Serenity.hang`
- `Keka_2019-12-12-064818_Serenity.hang`
- `Keka_2019-12-12-064226_Serenity.hang`
- `Keka_2019-12-12-064226-1_Serenity.hang`
- `Keka_2019-12-12-064529_Serenity.cpu_resource.diag`

it would be useful to have Keka write out `Keka_2019-12-12-… archive.7z`. Using the Unicode 'Horizontal Ellipsis' (U+2026) character (rather than the three-char `...` string) should be platform-agnostic and use up minimal space.

Also, using "archive" instead of "compressed file" would be more concise and more consistent with various other apps, including Apple's.  That even goes for when none of the files start with the same string, and the output from Keka would thus just be something like `Archive.7z` or `Archive.zip`.  Maybe this bit is a separate feature request, actually; but I don't want to create more tickets than necessary.

**Comment by gingerbeardman** [comment]
Related https://github.com/aonez/Keka/issues/188

**Comment by aonez** [comment]
Thanks for the reminder @gingerbeardman 😅

@Darklocq doing that common string is a cool idea but I think the result won't always be the desired or can be confusing. Not sure about that one.

About changing to `Archive`, maybe I can create a poll in Twitter... Already [done](https://twitter.com/kekaosx/status/1205219053079539712). Right now you can customize the name for all the file, but makes sense to:

- [ ] Customize only the default/fallback name

**Comment by aonez** [comment]
@Darklocq This was in fact a duplicate, sort of, from #236.

Take a look at the latest dev build:
https://github.com/aonez/Keka/releases/tag/v1.2.0-dev.3742

You can set a custom name for compression using placeholders. For this issue, you'll want to use %s that prints the shared name.

Take a look and let me know any thought on #236 😊
