### ISSUE TITLE
Droplets (and command-line one-task variants)

### ISSUE THREAD

**Issue by Darklocq** [aonez/Keka#502]
It would be super-handy to be able to create Keka "droplets" (micro-apps with specific options) for Dock and Finder and command-line use.  E.g., I presently use Keka pretty much entirely as a drop-and-forget app for creating 7Z files at maximum compression, and rely on other tools for all other compress/extract operations. I mostly use The Unarchiver when when I want stuff to just extract without interaction.  I'm testing several replacements for The Archive Browser when I want to view contents and do selective extraction (TAB is abandonware, and actually fails to properly read various very modern implementations of some formats, even ZIP).  For non-interactive compression to other formats than 7Z (mostly ZIP and RAR), I've been using a variety of dedicated tools, but this is annoying. I would rather have a single, consistent app for all of this.

It would be great to be able to use Keka to set up various "Keka lite" apps (presumably compiled AppleScripts that just feed the base Keka.app with some command-line options) that each do a single pre-defined job like "extract what I send to you without interaction", or "open what I send to you for interactive extraction" (even if it's 20 archives, one per window), or "compress what I send to you without interaction", or "open what I send to you for interactive compression, like selecting format and compression level and archive filename and location", etc.

There may already be a way for _über_-geeks to do this via manual scripting (I'm not sure yet how scriptable Keka is, and what command-line options it may support), but an interface _within_ the app for setting these up would be super-handy for creating things like `Keka - quiet 7Z max.app`, `Keka - interactive compress.app`, or whatever the user wants to name them.  Myself, I would probably store these in `/Applications/`, but some people might want them in `~/Library/Application Support/Keka/Droplets/` or where ever.

**Comment by aonez** [comment]
If I get it right, this will be achieved in #292. The Finder extension already implemented in 1.2.0 betas can dynamically modify its menu. So creating a custom operations list in the preferences, selecting compression/extraction options will be the way to do this. 

One problem the Finder extension has is that it does not pass file handling permission to its parent app, so this will be limited to places added to File Access or an open panel should be called to get file permission, which can break the non-interactive option.

**Comment by Darklocq** [comment]
Understood. I've told this app it can write to any drive I have, so it shouldn't be a problem (then again, as I said in other thread, I know jack about macOS's file-save-sandboxing crap, other than I try to defeat any such "be paranoid for the user's sake" stuff the OS is doing when it gets in my way; I have enough layers of security, I don't need the OS holding my hand. >;-)

**Comment by aonez** [comment]
So I'm dropping this issue in favor of #292. Any other idea goes there. Thanks a lot @Darklocq!
