### ISSUE TITLE
files not getting deleted after extraction

### ISSUE THREAD

**Issue by microcreators** [aonez/Keka#503]
hi.
i'm on the latest stable mojave and keka v. 1.1.24
i have an option selected to move files to trash after extraction, but... it never happens. keka has access to few default folders (like Downloads obviously),  but it doesn't seem to make a difference. 
i remember it used to work in the past, but i can't remember when exactly it stopped working.
any tips? thanks.

**Comment by aonez** [comment]
@microcreators what macOS version are you using?

**Comment by microcreators** [comment]
10.14.6, but it's been like that for a while..

-------- Original Message --------

**Comment by aonez** [comment]
Just for double checking, you have that option enabled?

![Screen Shot 2019-12-16 at 15 54 17](https://user-images.githubusercontent.com/480163/70916655-54acb800-201c-11ea-8830-d3fffd89397d.png)

**Comment by aonez** [comment]
@microcreators please try [this build](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-debug.7z) and follow [these steps](https://github.com/aonez/Keka/wiki/Report-an-issue) so I can help you better.

**Comment by microcreators** [comment]
Thanks for the support. Will do today / tomorrow and get back to you.

-------- Original Message --------

**Comment by microcreators** [comment]
Fun fact. All logs I'm getting have only one line:
`2019-12-22 22:40:51.022 Stopping access to all bookmarks...` ???
Sorry for the delay, xmas coming...

**Comment by aonez** [comment]
@microcreators you tried [that build](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-debug.7z) and enabled the "Create a debug session" in the menu as stated [here](https://github.com/aonez/Keka/wiki/Report-an-issue)? That "stopping access to all bookmarks" appears when Keka is closing. Did you reproduced the issue before closing Keka?

**Comment by microcreators** [comment]
come on... :|
https://imgur.com/a/6me6fQE
(yes... "move to bin" is on, file access to Downloads is granted)

**Comment by aonez** [comment]
I’m mostly sure you’re opening that ZIP file with the macOS extractor and
not Keka. Check that Keka is your default handler for ZIP files.

You can try dropping that file to the Keka window or the icon in the dock.

**Comment by microcreators** [comment]
fixed! one of the sys updates must've brought back macos default extractor...
