### ISSUE TITLE
Cannot open dmg installers on Mojave

### ISSUE THREAD

**Issue by andywickett** [aonez/Keka#505]
Hi, I Cannot open dmg installers on Mojave. When I click on a dmg file to install an app Keka takes over and makes them into an archive. Can you help please?

**Comment by aonez** [comment]
Keka does never set itself as the default DMG handler.

You can change the default handler for any file type manually:

https://www.google.es/amp/s/www.macrumors.com/how-to/change-a-files-default-app-in-macos/amp/

**Comment by andywickett** [comment]
Hi 
There is no option for an app installer in the list . Also the installers that it unarchived are corrupt

**Comment by aonez** [comment]
This is the default application that opens DMG images. You've changed it manually? Again, Keka never sets itself as the default for DMG nor ISO images. Also not all DMG can be extracted properly with Keka.

![Screen Shot 2019-12-17 at 10 52 12](https://user-images.githubusercontent.com/480163/70984781-5da09680-20bb-11ea-9b0c-acecfc623006.png)
