### ISSUE TITLE
aks for destination

### ISSUE THREAD

**Issue by meisterleise** [aonez/Keka#506]
**Configuration**
Keka version: [e.g. 1.1.24 (3421)]
macOS version: [e.g. 10.14.6 (18G2022)]

**Describe the bug**
Although it is set to "save next to original file" in the settings, keka asks where to store.

**To Reproduce**
1. select multible zip files
2. double click the files (keka is set as default app)
3. keka asks where to store for each file

**Comment by aonez** [comment]
@meisterleise can you check [this comment](https://github.com/aonez/Keka/issues/325#issuecomment-439838136) and let me know if this helps?

**Comment by aonez** [comment]
> Keka version: [e.g. 1.1.24 (3421)]
> macOS version: [e.g. 10.14.6 (18G2022)]

Is that your current configuration?

**Comment by meisterleise** [comment]
Yes, this is my configuration.
I'll test it and will soon be back...

**Comment by meisterleise** [comment]
Seems to work now. I should have figured out this on my own.
Thank you for helping me.

**Comment by aonez** [comment]
Glad to hear that @meisterleise!
