### ISSUE TITLE
[REQ] Queue multiple ongoing extractions

### ISSUE THREAD

**Issue by lsgd** [aonez/Keka#509]
**Is your feature request related to a problem? Please describe.**
I very often have to extract multiple archives in different folders and double-click on them to let Keka extract them. This will add another item to the Keka window and the extraction starts immediately for all of them. This slows down the overall extraction progress because multiple read/write operations on the disks are ongoing.

What I usually do is: I start the extraction and click the pause button for the new item in the Keka window. Once the current ongoing one is done, I resume the next one.

<img src="https://user-images.githubusercontent.com/820580/71883847-8b678100-3137-11ea-984b-cc4363fc1e8c.png" height="300" />

**Describe the solution you'd like**
I would like to limit the number of simultaneous executed extractions in the preferences.
A checkbox for queueing them all and only actively process one would be sufficient as well.

**Describe alternatives you've considered**
Switching from Keka to another extractor, but I would love to not.

**Comment by gingerbeardman** [comment]
Try `ForceOldQueue` hidden preference.
https://github.com/aonez/Keka/wiki/Hidden-configuration

or the latest Dev build
https://github.com/aonez/Keka/releases

**Comment by aonez** [comment]
@lsgd this has been already developed in the 1.2.0 version, that is not yet ready for a public release, but you can already try and use it as @gingerbeardman noted:

https://github.com/aonez/Keka/releases/tag/v1.2.0-dev.3742

I'm closing this one in favor of #21. Let me know there (or here) if you try the beta and your thought on the queue there :)

**Comment by lsgd** [comment]
Fantastic!
I supported you by buying the app from the AppStore.
I will just wait until it is available there :-)
