### ISSUE TITLE
macOS icon not changing after open with and change all 

### ISSUE THREAD

**Issue by nsby7c** [aonez/Keka#511]
I use VLC on my Macbook for video, but it frustratingly always forces rar files to use the VLC icon in finder. Usually the following fixed this issue and allowed Finder to use Keka as the default file icon.

1. Right click file in Finder
2. Select _Get Info_ 
3. Change default application with _Change All_ option

This would change the default icons on rar files to Keka. However, after a recent update, this does not work anymore. The items will open with Keka, but the icons will not change. While this may seem silly or petty, it is very helpful identifying rar files when quickly scrolling through Finder - which I do often. 

I would really appreciate any fixes to this issue. It is serious enough to make me switch to command line for most of my recent compression related tasks.

Thanks

**Comment by aonez** [comment]
Are you running on macOS 10.15 Catalina?

**Comment by gingerbeardman** [comment]
I am also seeing this on Mojave.

![Screen shot 2020-01-22 at 16 06 20](https://user-images.githubusercontent.com/49612/72911005-45aed900-3d31-11ea-8ba8-808e981950b2.png)

Related to #453 ?

**Comment by aonez** [comment]
@gingerbeardman most probably it is the same as #453, but @nsby7c does not confirm it is on Catalina. Anyhow this isn't a bug in Keka.

**Comment by gingerbeardman** [comment]
I hate modern macOS and its crappy bugs.

![Screen shot 2020-01-26 at 16 14 11](https://user-images.githubusercontent.com/49612/73138115-00531a00-4057-11ea-9c8f-718b4e559b8f.png)

**Comment by aonez** [comment]
@gingerbeardman I'm still working with Mojave just for this icons bug.

**Comment by gingerbeardman** [comment]
I’m still on Mojave too!

**Comment by aliakseikalosha** [comment]
I'm on Monterey and have the same issue 😔
