### ISSUE TITLE
[BUG] Long file names are truncated on MacOS

### ISSUE THREAD

**Issue by patchsmyle** [aonez/Keka#512]
**Configuration**
Keka version: [e.g. 1.1.24 (3421)]
macOS version: [e.g. 10.15.2 (19C57)]

**Describe the bug**
Decompression of a file that is greater than 277 characters, the file name is truncated

**To Reproduce**
1. Download the Oracle Linux 7.7.0.0 Installer DVD
2. Drag the downloaded .ISO file to be decompressed on the local file system
3. Examine the contents of the ISO's /repodata folder.

**Expected behavior**
The files names have a trailing label with a -name-blah.xml or gz.  They have been clipped after the 277th character.  If you look at the TRANS.TBL you will see what is the expected file names.

**Screenshots**

**Additional context**

**Comment by aonez** [comment]
Can you share a link to the specific file?

**Comment by aonez** [comment]
I'm testing with `OracleLinux-R7-U7-Server-x86_64-dvd`.

**Comment by aonez** [comment]
The contents are the same when extracted with Keka or seen with Engrampa.

![Screen Shot 2020-01-23 at 11 15 07](https://user-images.githubusercontent.com/480163/72975895-dc32d700-3dd1-11ea-9171-0cb741c8ac8b.png)
![Screen Shot 2020-01-23 at 11 16 01](https://user-images.githubusercontent.com/480163/72975902-ddfc9a80-3dd1-11ea-95a4-d5e264eac1b5.png)

I don't think there's any truncation, just those are the actual contents.

**Comment by aonez** [comment]
Reopen if you think this is still a bug.
