### ISSUE TITLE
[BUG] Can't extract file / Error code 2 using "p7zip" Fatal error

### ISSUE THREAD

**Issue by EpicRocco11** [aonez/Keka#513]
**Configuration**
Keka version: [e.g. 1.1.24 (3421)]
macOS version: [e.g. 10.13.6 (18G2022)]

**Describe the bug**
Extraction of "[filename].7z.001" failed. Error code 2 using "p7zip"
Fatal error
I've followed some steps on other threads and still can't extract the file.

**To Reproduce**
1. Go to file in downloads
2. Open with Keka
3. Begins extracting file
4. Almost instantly fails and produces error code: Error code 2 using "p7zip"
Fatal error

**Expected behavior**
I presume it would extract the file normally

**Screenshots**
![image](https://user-images.githubusercontent.com/60403275/73294055-f1a66780-41fc-11ea-8c77-bfd6d521d5c2.png)

**Additional context**
I've tried certain methods but it still won't work

**Comment by EpicRocco11** [comment]
No way, I get aonez?! I see him in like every possible thread.

**Comment by EpicRocco11** [comment]
And yes, I'm extracting an .iso file for the Wii emulator Dolphin, please don't judge.

**Comment by aonez** [comment]
Can this file be shared? You can also let me know at info@keka.io

**Comment by EpicRocco11** [comment]
Shall I email to info@keka.io?

**Comment by aonez** [comment]
Maybe for privacy will be better, up to you

**Comment by EpicRocco11** [comment]
Sonic Colors [SNCE8P].7z.001

**Comment by EpicRocco11** [comment]
That didn't work did it...
Lemme try again

**Comment by EpicRocco11** [comment]
Github doesn't support that file type (.7z)

**Comment by EpicRocco11** [comment]
I think I can email it to info@keka.io, ill try that now

**Comment by EpicRocco11** [comment]
The mail is sending, its 1.33GB so its taking time

**Comment by EpicRocco11** [comment]
The email sent a while ago, sorry I forgot to let you know

**Comment by aonez** [comment]
@EpicRocco11 usually parted files consist in more that one part. You just sent 001 part. Don't you have other parts?

**Comment by EpicRocco11** [comment]
Oh, no I don’t have any other parts (not that I knew there were even other parts)

**Comment by aonez** [comment]
@EpicRocco11 the file you've sent is incomplete, that's why it fails. If you have the source (link) where you've downloaded it let me know here or in the mail.

**Comment by EpicRocco11** [comment]
Ok, here is the download link that I used, https://romsmania.cc/roms/nintendo-wii/sonic-colors-273151
As you can see, it never specifies that download was in parts.

**Comment by aonez** [comment]
Look at the comments in that page. That file is broken. You should search another way to get that game.

**Comment by EpicRocco11** [comment]
Ok, I'll let you know if it works on another site
