### ISSUE TITLE
[BUG] Folder with name that includes asterisk (*) won't let Keka compress

### ISSUE THREAD

**Issue by tiagorocha1979** [aonez/Keka#514]
Keka version: 1.1.25 (3432)
macOS version: 10.13.6

I have a folder called _*My Files_
When I tried to compress some files that were inside that folder, it wouldn't work. 
The same files, when outside that folder, are compressed, so there's an issue with folders with an asterisk in their name.
I usually use asterisk to make some folders go up in the list and trick the alphabetical order.

I haven't tried with other symbols, but I thought it would be good to let the developer(s) know about this bug.

**Comment by aonez** [comment]
Thanks @tiagorocha1979! This is a duplicated of #488. I need to check it, but won't be easy to fix.
