### ISSUE TITLE
more unraring of divided files

### ISSUE THREAD

**Issue by epiccallingX** [aonez/Keka#518]
was wondering if I could get the terminal lines for another divided file unrar...

**Comment by aonez** [comment]
@epiccallingX you can [create a debug session](https://github.com/aonez/Keka/wiki/Report-an-issue#debug-session) and [take a look at the logs](https://github.com/aonez/Keka/wiki/Report-an-issue#debug-logs).

I'm working in the 1.2.0 for displaying the console log only. Will be tracked here https://github.com/aonez/Keka/issues/116.
