### ISSUE TITLE
[REQ] Requirements to set Keka as default unarchiver through an MDM (Mobile Device Management)

### ISSUE THREAD

**Issue by luke-carwowo** [aonez/Keka#519]
Is there guidance, or instructions to deploy the "Keka Default App" with an MDM (My use case is JAMF Pro).

Also, what privacy preferences should be used to configure Keka with All Volume Access in Catalina?

**Comment by aonez** [comment]
> Is there guidance, or instructions to deploy the "Keka Default App" with an MDM (My use case is JAMF Pro).

Just be sure that `KekaDefaultApp.app` is not in quarantine. Use this code if needed to remove it:

```sh
xattr -d -r com.apple.quarantine KekaDefaultApp.app
```

You can copy it anywhere and execute it if you want to set Keka as the default app. The application will move itself to the [Application Support folder](https://github.com/aonez/Keka/wiki/Default-application#about-the-helper) whenever it is called directly or through the Keka "Set as default..." button.

> Also, what privacy preferences should be used to configure Keka with All Volume Access in Catalina?

You should add the root `/` to the File Access list in the Keka Preferences. Sadly this needs to be done manually, this is a sandbox limitation. Alternatively you can [un-sandbox Keka](https://github.com/aonez/Keka/issues/123#issuecomment-466965500) yourself, then it will have access to all files. I'm unaware if JAMF or any MDM has any way to workaround this.
