### ISSUE TITLE
Feature request: Save file without original suffix

### ISSUE THREAD

**Issue by Jolopu** [aonez/Keka#522]
I love Keka. It's the best file compressor for Mac. There is only one think I miss: When a file like sound.mp3 is compressed the original suffix is always added to the compressed file like sound.mp3.zip. Every time I compress a file, I have to remove the original suffix manually to get sound.zip. An option to include or exclude the original suffix would be very useful.

Thank you!

**Comment by aonez** [comment]
Thanks for the feedback @Jolopu! This is a duplicate of #305, lets follow there.
