### ISSUE TITLE
[BUG]Error Code:0

### ISSUE THREAD

**Issue by CharlotteFallices** [aonez/Keka#524]
Keka:1.1.24(3421)
macOS:10.15.4(19E250c)

我只是解压了一个在别的电脑上压缩的文件,然后又将它压缩......
然后它就提示我:
<img width="1680" alt="截屏2020-03-10 上午11 26 35" src="https://user-images.githubusercontent.com/47619464/76332312-2db80680-632b-11ea-8835-d044e9a66deb.png">
之后我就关闭了Keka,重试后仍然如此.

------
==
The Issue is under Artistic License 2.0.
That's all.

**Comment by aonez** [comment]
Hi @CharlotteFallices. The message in the screenshot is not from Keka, even if the icon preview has the Keka logo.

What format is the file? You re-compressed it using Keka? Maybe it's a ZIP compressed with an AES password? If so take a look at https://github.com/aonez/Keka/issues/477.

**Comment by CharlotteFallices** [comment]
或许你需要[这个](https://github.com/aonez/Keka/issues/477#issuecomment-597440358),我使用了Keka并且得到了相同的结果

**Comment by aonez** [comment]
@CharlotteFallices it worked as expected, right?

**Comment by CharlotteFallices** [comment]
No............它会像这样:
<img width="1680" src="https://user-images.githubusercontent.com/47619464/76413785-087dd380-63d1-11ea-982c-4939aa746784.png">
我尝试了压缩其中的每一个版本,然后:
<img width="1680" src="https://user-images.githubusercontent.com/47619464/76413833-21868480-63d1-11ea-8781-8d5e8a651323.png">
或许是这个文件夹出现了一些问题?
看起来它不能被任何应用压缩......
但我并不认为它和其他版本有什么较大的区别:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/47619464/76414068-91950a80-63d1-11ea-9b6e-0c24ae23755a.png">
或许它们都不能被编译和运行(笑)

**Comment by aonez** [comment]
But the compression fails? I don't understand. Can you screencast the error?

**Comment by CharlotteFallices** [comment]
等待时间会不断增加,但是进度条却没有变化......在那个点之前会以很快的速度移动
我不太清楚我应该怎样去表达这件事,抱歉

**Comment by aonez** [comment]
Can you do a video of your screen while reproducing the problem? You can use QuickTime for this :)

**Comment by CharlotteFallices** [comment]
视频或许太大了......可以通过邮箱发给您嘛?

**Comment by aonez** [comment]
Sure! Mail it to info@keka.io, or just use a sharing service like Wetransfer, Dropbox or similar.
