### ISSUE TITLE
[BUG] MULTIPLE RAR ARCHIVE WITH PASSWORD ERROR

### ISSUE THREAD

**Issue by ILGUIDE** [aonez/Keka#525]
**Configuration**
Keka version: [e.g. 1.1.26]
macOS version: [e.g. 10.15.3 ]

**Describe the bug**
Can't open a multiple rar archive with password. always report crc error

**Comment by aonez** [comment]
Hi @ILGUIDE! Can you share the file? Here or at info@keka.io. If it has a public link just share the link.

**Comment by aonez** [comment]
@ILGUIDE can you create a [debug session](https://github.com/aonez/Keka/wiki/Report-an-issue#debug-session) and share the log?

**Comment by ILGUIDE** [comment]
i don't what does it mean
