### ISSUE TITLE
Context menu only visible for files not folders

### ISSUE THREAD

**Issue by hoba87** [aonez/Keka#526]
**Configuration**
Keka version: [e.g. 1.1.26 (3449)]
macOS version: [e.g. 10.14.6]

**Describe the bug**
for folders no context menu is enabled

**To Reproduce**
right click on folder

**Expected behavior**
context menu as for files "send to keka", "extract with keka", ...

**Comment by aonez** [comment]
This shouldn't be the case. Maybe they're nested in the "Services" menu?

![Screen Shot 2020-03-20 at 09 44 57](https://user-images.githubusercontent.com/480163/77148356-adfb0c00-6a8f-11ea-898a-5c137d19c922.png)

**Comment by hoba87** [comment]
Ah, yes, that is the case. Sorry for the trouble.
