### ISSUE TITLE
[REQ] Parallel/Serial Extraction

### ISSUE THREAD

**Issue by baszero** [aonez/Keka#528]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Depending on the device where extraction happens, it's faster if extraction would be serialized, means, if I select four archives to be extracted, only one at a time would be processed, the others queued.

**Describe alternatives you've considered**
no alternatives

**Comment by aonez** [comment]
Thanks @baszero! This is already developed in the latests beta versions, if you want to check 😊

This is a duplicate of #21.

**Comment by baszero** [comment]
Why is beta not released yet? I don't want to work with beta versions ;-)

**Comment by aonez** [comment]
It will be released when it's ready :)
