### ISSUE TITLE
[REQ]

### ISSUE THREAD

**Issue by ddklysys** [aonez/Keka#530]
Keka v1.1.26

Feature request: When compressing a file directly, the name of the compressed package is generated without the original file extension.

For example, the current version of Keka, compresses the file "abc.jpg", and the name of the compressed package is "abc.jpg.zip". I hope that the development team can consider allowing the user to choose whether the name of the compressed package is "abc.jpg.zip" or "abc.zip".

Thank you very much.

**Comment by gingerbeardman** [comment]
Already been done, awaiting release, see #305

**Comment by aonez** [comment]
Thanks @ddklysys! As @gingerbeardman pointed you can already test that feature in this build:
https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-hide-extension.7z
