### ISSUE TITLE
Keka error when extracting - Help!

### ISSUE THREAD

**Issue by jjas7** [aonez/Keka#531]
I am getting an error code 2 (fatal error) when trying to extract files. Can you give me the command to extract using terminal?  The files are in a folder called TWWW on my desktop.  Destination can be my desktop too.

![Screen Shot 2020-03-31 at 8 01 59 AM](https://user-images.githubusercontent.com/48271566/78041855-1c5c8b80-7326-11ea-977a-b03bc12dc2cc.png)
![Screen Shot 2020-03-31 at 7 57 31 AM](https://user-images.githubusercontent.com/48271566/78041862-1d8db880-7326-11ea-9281-5f7442e12935.png)

**Comment by aonez** [comment]
Please update Keka: https://www.keka.io

**Comment by aonez** [comment]
You should remove the prefixes of those files so it reads like:

```
TWWW_STEMS.zip.001
TWWW_STEMS.zip.002
...
TWWW_STEMS.zip.011
```

instead of:

```
01 - TWWW_STEMS.zip.001
02 - TWWW_STEMS.zip.002
...
11 - TWWW_STEMS.zip.011
```

**Comment by jjas7** [comment]
That worked.  Thank you so much for the fast reply! I really love Keka.

Jason Johnson
