### ISSUE TITLE
Unable to extract rar files 

### ISSUE THREAD

**Issue by isaeef** [aonez/Keka#532]
**Configuration**
Keka version: [Version 1.0.12 (1786)]
macOS version: [Version 1.0.12 (1786)]

**Describe the bug**
when I try to extract .rar file fails with this error message
Error code 10 using "unrar"
No files matching the mask

**Comment by aonez** [comment]
Can you share the file you're having trouble with?

**Comment by aonez** [comment]
You can also share the log of the error, follow this steps:
https://github.com/aonez/Keka/wiki/Report-an-issue
