### ISSUE TITLE
[REQ] Zstandard support

### ISSUE THREAD

**Issue by daniele-orlando** [aonez/Keka#533]
Keka version: 1.1.26

I would appreciate that Keka had the _Zstandard_ compression/decompression support.

**Comment by aonez** [comment]
Thanks for the support @daniele-orlando! 🎉
It's already implemented in 1.2.0 betas, you can already try it: https://beta.keka.io

I'm closing this one in favor of https://github.com/aonez/Keka/issues/84

**Comment by daniele-orlando** [comment]
Oh great! Thank you very much. ☺️
