### ISSUE TITLE
[BUG] cannot zip up word documents on latest version of MacOS 

### ISSUE THREAD

**Issue by amir-11** [aonez/Keka#534]
**Configuration**
Keka version: [e.g. 1.1.24 (3421)]
macOS version: [e.g. 10.14.6 (18G2022)]

**Describe the bug**
after trying to zip a word docx file, it returns error code 2 and says fatal error, creating a new folder (not a .zip file). does same with .7zip and others too

**Comment by aonez** [comment]
How you’re trying to compress it? It seems like Keka is trying to extract
it, it it created a folder.

**Comment by amir-11** [comment]
I just open keka  and drag all the files in there! Word doc, a folder, and
some pdfs

**Comment by amir-11** [comment]
It’s weirdly not repeating now that I’ve waited 10 mins .. but I can’t use
the app if it will randomly fail ! I don’t know the cause .

**Comment by aonez** [comment]
If you dropped on the Keka window, note its divided in two sections:

https://github.com/aonez/Keka/wiki/Compressing-with-Keka#dont-forget-you-have-a-secondary-option-in-the-keka-window-which-can-be-useful-for-compressing-already-compressed-files

If you still use Keka and need more assistance let me know.

**Comment by amir-11** [comment]
Ohhhh got it! That’s perf I can keep using then thanks :)
