### ISSUE TITLE
Each time you start "Keka", the program window, sinks lower and lower.

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#535]
**Configuration**
Keka version: [Keka v1.1.26 & Keka v1.2.0-dev.3742]
macOS version: [10.15.4 (19E266)]

**Describe the bug**
Each time you start "Keka", the program window, sinks lower and lower.

**Screenshots**

[Bildschirmvideo aufnehmen 2020-04-04 um 17.42.10.avi.zip](https://github.com/aonez/Keka/files/4431838/Bildschirmvideo.aufnehmen.2020-04-04.um.17.42.10.avi.zip)

**Comment by aonez** [comment]
Wow thanks for that one @Oleg-Chashko. It seems to only be reproducible with DMG and ISO formats.

**Comment by Oleg-Chashko** [comment]
I'm sorry, forgot to write this. Yes with DMG and ISO formats.

**Comment by aonez** [comment]
1.1.27 with this fixed coming in a few! Thanks again @Oleg-Chashko!

**Comment by aonez** [comment]
Sadly I'll revert the fix, it's causing more problems in some languages. I'll fix that later.

![Screen Shot 2020-05-01 at 17 15 42](https://user-images.githubusercontent.com/480163/80816226-68257d80-8bcf-11ea-8743-546a02912c7e.png)

**Comment by aonez** [comment]
This is now reproducible with all formats in the latest 1.2.0 build 🤦🏻‍♂️

**Comment by aonez** [comment]
I don't remember right now if this was finally fixed, you've closed because it was fixed?

**Comment by Oleg-Chashko** [comment]
@aonez 
Keka v1.2.0-beta.3
Everything works well for me! But I haven't tested on all language packs.
