### ISSUE TITLE
GUI - Small design flaws.

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#536]
**Configuration**
Keka version: [Keka v1.2.0-dev.3742]
macOS version: [10.15.4 (19E266)]

**Describe the bug**
**1.** Problems with the letters "W, V", possibly with some others.
**2.** The problem with centering vertically in the input windows.
           I have attached examples, but that’s not all. **Other windows have problems.**

**Screenshots**
<img width="377" alt="Bildschirmfoto 2020-04-06 um 09 48 52" src="https://user-images.githubusercontent.com/62497891/78537457-cf7a2880-77ef-11ea-88b6-da6543ad9bac.png">
<img width="377" alt="Bildschirmfoto 2020-04-06 um 09 53 32" src="https://user-images.githubusercontent.com/62497891/78537463-d143ec00-77ef-11ea-9b9f-c99bf976a961.png">
<img width="545" alt="Bildschirmfoto 2020-04-06 um 09 26 52" src="https://user-images.githubusercontent.com/62497891/78537466-d2751900-77ef-11ea-8841-9189d0926c47.png">

**Comment by aonez** [comment]
Not sure what is your point here...

**Comment by Oleg-Chashko** [comment]
> Not sure what is your point here...

No, I do not insist that I am right. Each artist sees this world in his own way. As a basis, I took "Apple-Mail".
<img width="668" alt="Bildschirmfoto 2020-04-06 um 12 50 52" src="https://user-images.githubusercontent.com/62497891/78551694-64881c00-7806-11ea-8294-6204182fb24e.png">

**Comment by gingerbeardman** [comment]
I love your attention to detail @Oleg-Chashko 

@aonez I believe Oleg's point was that the IB layout would benefit from some tightening-up to remove the alignment/cropping issues he has listed.

**Comment by Oleg-Chashko** [comment]
For me, "Keka" is the best archiver on MacOS. But the slightest geometric curvature for me is the "Perfectionist hell".
P.S. Perfectionist Hell - This is when he got to hell, and there the boilers are crooked.

**Comment by aonez** [comment]
> I wanted to ask you why here "Kekas icon"?

This is there since 1.1.0 early versions while playing around developing the format selector. Leaved it there for fun since it's only a line of code.

![Screenshot 2020-06-11 at 08 59 52](https://user-images.githubusercontent.com/480163/84354875-ee1ae800-abc1-11ea-854c-98b52fef6729.png)

**Comment by Oleg-Chashko** [comment]
@aonez
I tried to interact with her, but I didn't understand the meaning.
Now I know, this sacred meaning!

**Comment by Oleg-Chashko** [comment]
@aonez
Will the opportunity, be returned to make, large icons of compression modes?
Please!
![222](https://user-images.githubusercontent.com/62497891/84430949-c318ae80-ac2a-11ea-8b50-8c499db687e2.jpg)

**Comment by aonez** [comment]
> Will the opportunity, be returned to make, large icons of compression modes?

You can still use those icons if you disable the "Unified toolbar" in the preferences. You meant that?

**Comment by Oleg-Chashko** [comment]
> > Will the opportunity, be returned to make, large icons of compression modes?
> 
> You can still use those icons if you disable the "Unified toolbar" in the preferences. You meant that?

Thank you. I did not think that this setting is hidden in the settings of the program.

**Comment by Oleg-Chashko** [comment]
Grammatical errors.
<img width="799" alt="Screenshot 2020-06-12 at 14 51 25" src="https://user-images.githubusercontent.com/62497891/84504655-99a86300-acbc-11ea-9bcd-9909dcbdc092.png">

**Comment by aonez** [comment]
I'm not very good at Russian 😅 What are the grammatical errors in operations and queuing?

**Comment by Oleg-Chashko** [comment]
@aonez 
1. Translated everything in the file (ru.lproj) into Russian, fixed errors with a space and grammar errors of the English language. The Russian language was written without errors, just not enough commas.
2. In other language files (bg.lproj, de.lproj, en-GB.lproj & etc.), white space errors and English grammar errors. Will have to correct you!
3. There is a problem! There is no line with the text in the language files:
<img width="542" alt="Screenshot 2020-06-13 at 13 39 06" src="https://user-images.githubusercontent.com/62497891/84569810-6b448980-ad89-11ea-811b-d716b0332a32.png">
**This problem exists in all language files. Please enter this line in the language files, and it will be possible to change it into different languages. And I will translate into Russian in the file.**

**Comment by Oleg-Chashko** [comment]
This I showed which letters were spelled incorrectly. Errors with English and Russian words. This is already **corrected** text!
<img width="799" alt="84504655-99a86300-acbc-11ea-9bcd-9909dcbdc092" src="https://user-images.githubusercontent.com/62497891/84570289-db084380-ad8c-11ea-93b8-0be1265c266e.png">

**Comment by aonez** [comment]
@Oleg-Chashko thanks a lot! Maybe you can try to clone the repository and create a pull request with your changes. Anyway I'll take a look at your attached file :)

If you find some more issues not related with the main topic "Small design flaws" better create a new issue, since this one is becoming hard to track...

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko thanks a lot! Maybe you can try to clone the repository and create a pull request with your changes. Anyway I'll take a look at your attached file :)
> 
> If you find some more issues not related with the main topic "Small design flaws" better create a new issue, since this one is becoming hard to track...
@aonez 
I just added translation and fixed the language pack. If you want to create a topic, transfer what you need there. And I, with pleasure, will join if you want.

**Comment by aonez** [comment]
Finally found the time to merge your translation update and typo fixes 😅

**Comment by aonez** [comment]
I'm closing this one, reopen if I've missed something. Thanks again @Oleg-Chashko!
