### ISSUE TITLE
Keka suddenly just stopped working

### ISSUE THREAD

**Issue by PsYAuM** [aonez/Keka#537]
**Configuration**
Keka version: 1.1.26 problem started on previous version 1.1.22
macOS version: 10.11.6

Hi
Keka was working fine then suddenly it stopped.
 I went to extract something and this message popped up
" can't show progress time "
I select the destination folder and it just hangs with a time elapsed counter counting infinitely it would appear.
I have updated it and still the same.
Can anyone enlighten me as to what has happened and how to fix it please?
Thank you

**Comment by aonez** [comment]
Hi @PsYAuM!

Please remove the Keka preferences and try again. You can do it by executing the code below in the Terminal.app. It will also save the Keka preferences in a file in your desktop (Keka-config.zip), share that file in this thread if you can, so I can try to reproduce the issue:

```sh
f="$HOME/Library/Containers/com.aone.keka"; zip -qry "$HOME/Desktop/Keka-config.zip" "${f}"; rm -r "${f}"
```

If you don't want to share the file just remove the preferences:

```sh
rm -r "$HOME/Library/Containers/com.aone.keka"
```

Hopefully just removing the preferences fixes the issue, let me know.

**Comment by aonez** [comment]
By the way, this happens with any operation, compression and extraction? And with any file?

**Comment by PsYAuM** [comment]
> By the way, this happens with any operation, compression and extraction? And with any file?

I have only tried with extraction and it's the same with all files including ones it previously extracted without issue.
I removed the preferences and now i get this error message
" Error code 10 using "unrar"
No files matching the mask "
It doesn't proceed past there
I have attached the requested file
thanks for your efforts

[Keka-config.zip](https://github.com/aonez/Keka/files/4439108/Keka-config.zip)

**Comment by aonez** [comment]
Thanks for sharing and sorry for all the trouble @PsYAuM. Just realized you're working with folders starting with an asterisk (*) symbol. Can you try in a volume that does not start with an asterisk?

If it still fails please create a debug session and share the log created while reproducing the issue: https://github.com/aonez/Keka/wiki/Report-an-issue

**Comment by PsYAuM** [comment]
i tried removing astrix and still the same
here is the log file 

[Keka-log-20200406204836559.log](https://github.com/aonez/Keka/files/4439218/Keka-log-20200406204836559.log)

**Comment by aonez** [comment]
Sorry @PsYAuM but that log is incomplete. To get a proper log you need to create a [debug session](https://github.com/aonez/Keka/wiki/Report-an-issue#debug-session), reproduce the issue and then share that log (or all from the log folder).

**Comment by PsYAuM** [comment]
how long does it take to create?

**Comment by aonez** [comment]
It's being written since you create the debug session.

**Comment by PsYAuM** [comment]
[Keka-log-20200406210109814.log](https://github.com/aonez/Keka/files/4439286/Keka-log-20200406210109814.log)

**Comment by PsYAuM** [comment]
[Keka-log-20200406210109814.log](https://github.com/aonez/Keka/files/4439292/Keka-log-20200406210109814.log)

**Comment by aonez** [comment]
The log still partial... 😅

Better enable the debug information and the save option, as shown in this screenshot:
![Screen Shot 2020-04-06 at 17 28 39](https://user-images.githubusercontent.com/480163/78575769-1423b500-782c-11ea-8eb4-6c61d78bae84.png)

Then reproduce the issue and share the logs. Thanks for the patience @PsYAuM :)

**Comment by PsYAuM** [comment]
[Keka-log-20200406210109814.log](https://github.com/aonez/Keka/files/4439357/Keka-log-20200406210109814.log)

**Comment by PsYAuM** [comment]
[Keka-log-20200406210109814.log](https://github.com/aonez/Keka/files/4439365/Keka-log-20200406210109814.log)

**Comment by aonez** [comment]
The process states `No files to extract` for that RAR file.

Can you try extracting this file? It's a ZIP that has inside a RAR that has inside a simple text file.

[test.txt.rar.zip](https://github.com/aonez/Keka/files/4439386/test.txt.rar.zip)

**Comment by aonez** [comment]
If it's a little file (less than ~50MB), maybe you can share it with me at the mail info@keka.io?

**Comment by PsYAuM** [comment]
> The process states `No files to extract` for that RAR file.
> 
> Can you try extracting this file? It's a ZIP that has inside a RAR that has inside a simple text file.
>

Ok working now.
The test zip went to another directory that never had a * before it at any point.
It extracted without issue so i moved a couple of files the same folder and they all worked.
in future i will extract within my download folder.
thanks for your help

**Comment by aonez** [comment]
Glad it works now 😊

**Comment by PsYAuM** [comment]
> Glad it works now 😊

again thank you 🙏
