### ISSUE TITLE
GUI - Window "Preferences" - strange behavior.

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#538]
**Configuration**
Keka version: [Keka v1.2.0-dev.3742]
macOS version: [10.15.4 (19E266)]

**Describe the bug**
When I open the "Preferences", the window opens somewhere in the side and constantly in the same place. Although I put the window in another place.
The normal behavior of the startup window is in the center, and if I put it in another place, it should remember this place where I put it.

Sorry for my bad english.

**I attach the video file:**
[Preferences.avi.zip](https://github.com/aonez/Keka/files/4441016/Preferences.avi.zip)

**Comment by aonez** [comment]
Thanks for that one @Oleg-Chashko!

**Comment by Oleg-Chashko** [comment]
> Thanks for that one @Oleg-Chashko!

I am glad to help!

**Comment by aonez** [comment]
This should be fixed in the latest 1.2.0 build :)
