### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by FrancisJMR** [aonez/Keka#542]
**Configuration**
Keka version: [e.g. 1.1.24 (3421)]
macOS version: [e.g. 10.14.6 (18G2022)]

**Describe the bug**
Creating a .zip archive for 20GB csv file takes over system resources preventing further use of mac pro including UI highly slowed, mouse pointer barely responsive, and freezing.
Working off a 2019 Mac Book Pro with i7 and 8GB memory.

**To Reproduce**
1. Drag and drop 20GB CSV
2. Compress in Zip format
3. Wait and see...
4. No error as compression takes place, but UI is highly unresponsive.

Recommendation: reduce priority of Keka processes and limit RAM memory allocation.

**Expected behavior**
Should not freeze system

**Screenshots**
NA

**Additional context**
NA

**Comment by aonez** [comment]
Thanks for the feedback @FrancisJMR! Can you check the latest [beta](https://beta.keka.io)?

This version has thread limit configuration so you can limit Keka to use 8 or 10 of the total 12 threads from your i7:

![Screen Shot 2020-04-13 at 09 12 59](https://user-images.githubusercontent.com/480163/79100513-fba12680-7d66-11ea-9757-006fddd6a9ef.png)

Let me know if this works for you.

**Comment by FrancisJMR** [comment]
Excellent thank you. Works great! 
I set it to 6 cores and took ~19 mins to compress a 20GB csv as a Zip file.

Thanks for the quick solution.

**Comment by aonez** [comment]
Thanks @FrancisJMR! I'm closing this one in favor of #21 then 😊
