### ISSUE TITLE
[BUG] Services -> Compress Using Keka bring up Extraction menu instead of compression

### ISSUE THREAD

**Issue by BenoitFiset** [aonez/Keka#545]
**Configuration**
Keka version: [1.1.26 (3449)]
macOS version: [10.14.6]

**Describe the bug**
Select a single file or list of files and right-click and select services -> Compress Using Keka
Instead of compression, KeKa tries to extract a file.

If I select select services -> Compress With Keka, compression is done ok.

**To Reproduce**
1. Select file or files in finder
2. right-click and select services -> Compress **Using** Keka
3. Watch it show **Extraction message box** with finder window to select where to extract...
4. See error and wrong behavior

**To see compression work normally but without dialog:**
1. Select file or files in finder
2. right-click and select services -> Compress **With** Keka
3. Watch it show Extraction message box with finder window to select where to extract...
4. See error and wrong behavior

**Expected behavior**
Have Keka compress the files(s) asking how to compress and where in dialog box

**Screenshots**
Attached PDF with screen shots.

[Select Compress Using Keka and Keka tries to Extract.pdf](https://github.com/aonez/Keka/files/4489941/Select.Compress.Using.Keka.and.Keka.tries.to.Extract.pdf)

Thanks,

B.

**Comment by aonez** [comment]
@BenoitFiset I can't reproduce your issue. Note that you have legacy context menu items for Keka installed here:

```sh
/Users/YOUR_USER/Library/Services/
```

Since version 1.1.0 Keka has those services bundled and the legacy ones are no more compatible. Please remove them, try again and let me know if you still have issues.

**Comment by BenoitFiset** [comment]
Hi,

 yep removing the old services in `/Users/YOUR_USER/Library/Services/` did the trick.

**Comment by aonez** [comment]
> It there a way with these new services for Keka to ask for my input of files name which I want to write ? I changed the `Name of new files` option in compression preferences to `Custom name`, but doesn't ask for new file name at each compression request.

You can set "Ask each time" in "Save to location", that way you can personalize the name each time :)

**Comment by BenoitFiset** [comment]
Ah... Ok yes that works... 

maybe rename the option to: `"Ask Each Time - Location and Filename"`
I would of figured it out myself if it was named like this... :)

Thanks.

**Comment by aonez** [comment]
It's not a bad idea, maybe I'll add the option "Ask each time" in the "Name of new files" so there's no confusion.
