### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by michaelvelasquez** [aonez/Keka#546]
**Configuration**
Keka version: Version 1.1.26 (3449)
macOS version: 10.13.6 (17G12034)

**Describe the bug**
I apologize if I'm missing a preference somewhere, but In previous versions of Keka, at least when I was using Mac OS El Capitan, I could drag a mixed group of files and folders onto Keka and when I zipped them, it created a zip file without a new folder enclosing the selected items.

Meaning when I unzip the file, what I see now is a folder with the same name as the zip archive and then the files are inside it. Previously, unzipping gave me all the files separately and not in any folder. 

I'm creating applications for Samsung SSSP (Smart Signage Platform) displays and they require files be zipped to run and the zipped files aren't supposed to be enclosed in any folders but Keka is now doing this by default.
https://docs.appspace.com/appspace/6.1/appspace-app/appspace-app-devices/samsung/samsung-ssp/

Thank you.
-michael

**Comment by aonez** [comment]
Hi Michael! Keka extracts multiple files in a folder, so it creates an
intermediate folder during extraction, but does not create intermediate
folders during compression.

You can check this using the Terminal:

‘’’sh
unzip -v <PATH_TO_FILE>
‘’’

**Comment by aonez** [comment]
Hi Michael! Keka extracts multiple files in a folder, so it creates an
intermediate folder during extraction, but does not create intermediate
folders during compression.

You can check this using the Terminal:

‘’’sh
unzip -v <PATH_TO_FILE>
‘’’
