### ISSUE TITLE
sparkle feed broken for 1.1.27

### ISSUE THREAD

**Issue by core-code** [aonez/Keka#552]
https://www.keka.io/update/keka.xml

it links to 

https://github.com/aonez/Keka/releases/download/v1.1.27/Keka-1.1.27.zip

which does not exist 

(404 Not found)

**Comment by aonez** [comment]
My bad! Created a bad tag. Fixed right away, thanks a lot @core-code.

**Comment by core-code** [comment]
thanks! :)
