### ISSUE TITLE
[BUG]Encrypted and compressed into a 7z file, the password cannot be decrypted normally

### ISSUE THREAD

**Issue by junliepigyao** [aonez/Keka#557]
**Configuration**
Keka version: 1.1.21 (3378)
macOS version: 10.15.4 (19E287)

**To Reproduce**
1. ![image](https://user-images.githubusercontent.com/5100122/82113886-c6379080-978b-11ea-8ede-24cf6220820f.png)
2.![image](https://user-images.githubusercontent.com/5100122/82113904-e5362280-978b-11ea-80c4-4ff8041f7ea1.png)
The password cannot be decompressed, and the password input box keeps popping up

Encrypted and compressed into a 7z file, the password cannot be decrypted normally

**Comment by aonez** [comment]
#477
