### ISSUE TITLE
There was a delay in extracting the file

### ISSUE THREAD

**Issue by samuel072** [aonez/Keka#559]
**Configuration**
Keka version: [e.g. 1.1.29]
macOS version: [e.g. 10.15.4]

**Describe the bug**
After Keka decompresses the files in the download folder, the decompressed folder will appear later. But that doesn't happen on the desktop

**Comment by aonez** [comment]
Hi @samuel072! The function used is the same, so the result should be the same. Note that depending on the extraction size it will appear faster or slower.
