### ISSUE TITLE
[BUG] Can't give access to home folder

### ISSUE THREAD

**Issue by cmer** [aonez/Keka#561]
**Configuration**
Keka version: [1.1.29 (3468)]
macOS version: [10.5.5]

**Describe the bug**
When I try to give home folder access, nothing happens and my home folder is not added to the list. However, the following entries appear in Console:

```
default	13:47:42.858355-0400	Keka	Add bookmarks: (
    "file:///Users/carl/"
)
default	13:47:42.859693-0400	Keka	Bookmark is stale, removing it: /Users/carl
default	13:47:42.860805-0400	Keka	Error retrieving bookmark URL: Error Domain=NSCocoaErrorDomain Code=256 "Couldn't issue sandbox extension for the resolved URL" UserInfo={NSDebugDescription=Couldn't issue sandbox extension for the resolved URL}
default	13:47:42.860835-0400	Keka	Bookmark is stale, removing it: /Users/carl

```

**Comment by aonez** [comment]
Hi @cmer, thanks for the feedback!

It feels like macOS is invalidating that bookmark. Can you try if restarting the Mac helps?

If not, is that Keka from the WEB or the MAS? Are you executing it from the Applications folder?

**Comment by cmer** [comment]
I am using the website version. Oddly enough I am able to add all other user folders, except my own. I am executing from the Applications folder and I have been having this issue for many months. Maybe even over a year.

**Comment by aonez** [comment]
@cmer can you try [resetting the Keka settings](https://github.com/aonez/Keka/wiki/Uninstall-Keka#2-delete-the-preferences)? Also restarting the Mac might help.

Let me know if this fixes the issue. It's a rare one.

**Comment by cmer** [comment]
I did all that but nothing worked. I have a feeling something is messed up with my home folder even though I've never had any issues like this in the past. I also tried repairing permissions.

I went ahead and reinstalled macOS from scratch and sure enough, it works now. Very odd... anyhow, I'm good for now, but thought I'd at least share some details in case it happens to someone else in the future.

**Comment by aonez** [comment]
Glad it works now. A fresh install always comes in handy.
