### ISSUE TITLE
[REQ] please don't unpack to a renamed dir?

### ISSUE THREAD

**Issue by Pomax** [aonez/Keka#565]
When unpacking different archives that all put (different) files in the same dir(s). _please_ do not unpack that to a new directory. If I have a file1.zip that unpacks things to a `./content` dir, and a file2.zip that has _more_ files that go into `./content`, honour the directory structure in the archive. Don't unpack the second file to `./content-2`, that's _not_ what the archives say. Please don't invent new dir names, please obey the archives themselves.

**Comment by aonez** [comment]
@Pomax this will come eventually, just not yet, but for sure eventually. Will keep the issue here #72.

**Comment by Pomax** [comment]
That's a 2 year old issue, for something that is fundamental unpacking behaviour... Can it be bumped to much sooner than "not just yet"? I have literally terabytes of audio software that gets installed off of multi-pack archives that do this, so The Unrachiver and Keka are both non-options... and that's just really strange for a technology that everyone basically agreed the behaviour on back in the early 80's =(

**Comment by aonez** [comment]
Bumped it to 1.3.0, impossible to add it in the current 1.1.x or 1.2.0.
