### ISSUE TITLE
Ask for password when drag and dropping on keka

### ISSUE THREAD

**Issue by AtomicNess123** [aonez/Keka#566]
Hi, I just need to set KEKA on my dock so that whenever I drag and drop a file it will request password creation. Thanks.

**Comment by aonez** [comment]
Sorry @Gahamelas for not responding before. I was hopping to add this for the upcoming 1.2.0 but I'll need to do it later.

Also as an option in the contextual menu will come in #292.

**Comment by Gahamelas** [comment]
Thanks! Never too late :) So as I understand this will be implemented in the next update?

**Comment by aonez** [comment]
Not in the next 1.2.0, I had no time to implement it, but in a future update for sure!

**Comment by Gahamelas** [comment]
Great, thanks and keep up the excellent work!

**Comment by aonez** [comment]
Thanks @Gahamelas! I keep this open until it's implemented 👍🏼

**Comment by aonez** [comment]
This is coming next week, in case you are still interested 😅
