### ISSUE TITLE
[BUG] Keka is not removed from my context menu upon uninstall.

### ISSUE THREAD

**Issue by bmurr** [aonez/Keka#568]
I launched Keka from the mounted image and decided not to use it.

I unmounted the image and Keka is now on my context menu.

This is very bad behaviour, for reasons that should be obvious.

Don't install your app to the user's context menu without asking them, and if you do, provide a way to remove it.

**Comment by aonez** [comment]
Thanks for editing the comments, they were gratuitously insulting.

Keka does not install in the context menu. It just gets registered as a service. This is the default way applications register services and the way provided by Apple.

Remove Keka and relaunch your Finder (or Mac) if needed, and that’s all.
