### ISSUE TITLE
Update Error! (can't be updated due to "read-only" location)

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#572]
**Configuration**
Keka version: Version 1.2.0-dev (3742)
macOS version: 10.14.6 (18G4032)

**Describe the bug**

![Screen shot 2020-06-12 at 11 44 10](https://user-images.githubusercontent.com/49612/84494929-37daff80-aca2-11ea-8efa-0a01c69218c3.png)

**To Reproduce**

?

**Expected behavior**
- should check for update

**Screenshots**
- would not check for update

**Additional context**
Was in /Applications

I had to move out of there and then back in to get it to check for update.

**Comment by gingerbeardman** [comment]
Also, 1.2.0-dev (3742) did not find 1.2.0-dev (3901) in update.

**Comment by aonez** [comment]
> Also, 1.2.0-dev (3742) did not find 1.2.0-dev (3901) in update.

Thanks @gingerbeardman! Totally forgot about it.

About the main issue... our friend the translocation, nothing I can about it really. Maybe you've extracted the ZIP package in Applications? So it has the quarantine applied?

**Comment by gingerbeardman** [comment]
Hmm. Not sure but I've been using that 1.20 build for months. Didn't occur to me that it failing update check. 

Anyway! Cheers

**Comment by lobaev** [comment]
sudo xattr -rd com.apple.quarantine /path_to_application/Keka.app
