### ISSUE TITLE
Keka closing after every kind of operation

### ISSUE THREAD

**Issue by Ja-siek** [aonez/Keka#573]
**Configuration**
Keka version:  1.2.0-dev (3901)
macOS version: OS X El Capitan 10.11.6

**Describe the bug**
As mentioned above - Keka is closing after every operation with a error message popping out.
Of course the "close program after action" function is turned off, the box is not ticked.

**To Reproduce**
Try to compress or decompress any file using Keka
 For instance:
1. Open Keka
2. Right-click on any file You want to compress
3. Choose "Open with..."
4. Choose "Other..."
5. Choose Keka
6. Keka compresses, shows a correct information of the chosen operation. At the same time an error message shows up in a pop-up window, telling You, that Keka must have been suddenly closed.
![kekabug2](https://user-images.githubusercontent.com/65165680/84762674-696a0880-afcb-11ea-8e3a-14e97eaa1642.png)

**Expected behavior**
I would of course expect this not to happen

**Additional context**
Maybe El Capitan is just to old and maybe You'll think that's unimportant. I don't know. I'm new to this world, but still I thought - maybe You'd like to know. Thank Your for such a nice programm anyway ;)
 
Ps. The design of Keka 1.0.4 was much nicer in my opinion ;) I'll probably switch back :p

**Comment by aonez** [comment]
@Ja-siek the newer 1.2.0 will still support 10.11 El Capitan (and 10.10 Yosemite). There's some bug there.

**Comment by aonez** [comment]
> Ps. The design of Keka 1.0.4 was much nicer in my opinion ;) I'll probably switch back :p

You mean about the icons? Or something more? 🧐

**Comment by aonez** [comment]
It's something about the sounds. You can temporarily disable the compression/extraction sound but I'm fishing this one right away.

**Comment by aonez** [comment]
Check this build, should fix the issue: [Keka-SOUNDS-FIX.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-SOUNDS-FIX.7z)

**Comment by Ja-siek** [comment]
Hey, thank You very much! You're right - turning off the sounds absolutely solved the problem!
Concerning the design, I ment of course the icons! The old leather file icons where the best ;)

**Comment by Ja-siek** [comment]
> Check this build, should fix the issue: [Keka-SOUNDS-FIX.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-SOUNDS-FIX.7z)

Works perfectly! Thank You very much! :D

**Comment by aonez** [comment]
> The old leather file icons where the best ;)

Pablo's leather icons are a piece of art, sadly no scalable or retina resolution 😞

**Comment by Ja-siek** [comment]
> > The old leather file icons where the best ;)
> 
> Pablo's leather icons are a piece of art, sadly no scalable or retina resolution 😞

You see... progress as we learned to percieve it... isn't always progress :p
I like my non-retina display... at what good is a retina display, if I have (sorry, but true in comparison) crappy icons :p
