### ISSUE TITLE
[BUG] Aliases not conserved by ZIP or 7z

### ISSUE THREAD

**Issue by willnwhite** [aonez/Keka#575]
**Configuration**
Keka version: 1.1.30 (3477)
macOS version: 10.15.4

**Describe the bug**
When I extract a ZIP or 7z file created with Keka, the alias inside the folder has been turned into a TXT file (I want the alias to be conserved). 
No log file attached as log contains personal information. Issue is readily reproducible.

**To Reproduce**
1. Compress a folder with an alias inside it using 7z or ZIP in Keka.
2. Extract the archive using either Keka or macOS's built-in Archive Utility.

**Additional context**
I need a password on the archive, so I'm using 7z or ZIP in Keka. macOS's Archive Utility does conserve aliases, but it doesn't have a password feature.

**Comment by aonez** [comment]
@willnwhite sorry for the late response. This refers to #90 and has no fix right now. Meanwhile you can TAR your contents and then 7Z/ZIP with password that TAR file.

**Comment by aonez** [comment]
@willnwhite also note that the aliases that break are the ones created with macOS contextual menu. You can safely create them using the Terminal like `ln -s <source> <alias>`, those won't break using `p7zip` and are compatible in other platforms (such as Linux).

**Comment by willnwhite** [comment]
> @willnwhite also note that the aliases that break are the ones created with macOS contextual menu. You can safely create them using the Terminal like `ln -s <source> <alias>`, those won't break using `p7zip` and are compatible in other platforms (such as Linux).

Thanks, that could be useful to me. Yes, I came up with something similar to your suggestion of TAR first then password.
