### ISSUE TITLE
[BUG] Error when extracting and crash after cancelling 

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#576]
**Configuration**
Keka version: 1.2.0-dev
macOS version: 10.14.6 (18G4032)

**Describe the bug**

Error when extracting and crash after cancelling 

**To Reproduce**

1. extract this [FSNotes_4.4.0.zip](https://github.com/aonez/Keka/files/4856637/FSNotes_4.4.0.zip)
1. stop at encoding dialog
1. Cmd+Q to quit
1. Choose "Yes" at "Really want to close Keka?"
1. Choose "Yes" at "Really want to close Keka?" again

**Expected behavior**
- Should extract 

**Screenshots**

![Screen shot 2020-07-01 at 09 29 58](https://user-images.githubusercontent.com/49612/86222255-e675b000-bb7d-11ea-9823-78a1e108d9ae.png)

**Additional context**

Archive utility extracts it just fine.

Crash log: 
[Keka_2020-07-01-093020_matt.crash.zip](https://github.com/aonez/Keka/files/4856659/Keka_2020-07-01-093020_matt.crash.zip)

**Comment by aonez** [comment]
@gingerbeardman reproduced the encoding dialog but no error while extracting or crash. You can consistently reproduce the failed extraction and cancel crash?

**Comment by gingerbeardman** [comment]
No, it's happened only 1 in 3 right now.

**Comment by gingerbeardman** [comment]
Oh, I never choose to extract - I am quitting at the above encoding dialog.

**Comment by gingerbeardman** [comment]
I notice the "Really want to close Keka?" dialog appears twice!

**Comment by aonez** [comment]
> I notice the "Really want to close Keka?" dialog appears twice!

Yep, I'm still trying to fix this one 🤯

**Comment by aonez** [comment]
@gingerbeardman I've created #577 because the encoding issue is present in all Keka versions using the `unar` binary.

I'm leaving this on because I really want to reproduce the crash.

**Comment by gingerbeardman** [comment]
Just a hunch, is it possible I quit and approved during Sparkle update check?

**Comment by gingerbeardman** [comment]
Boom, that's it.

[Keka_2020-07-01-131037_matt.crash.zip](https://github.com/aonez/Keka/files/4857709/Keka_2020-07-01-131037_matt.crash.zip)

To Reproduce
1. Set Sparkle check date in plist to old date
2. Open above zip
3. Quit and confirm quit fairly quickly
4. Crashlog

**Comment by aonez** [comment]
I think I got this one, at least where the possible bad VM read is 🤯

**Comment by aonez** [comment]
I can't still reproduce the bug but with the crash log I think I got the possible offending code. [Here](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.0-dev.r3966.7z) a build with that code fixed, let me know if you still can reproduce it. Thanks a lot @gingerbeardman!
