### ISSUE TITLE
[REQ] Add to option to always create folder when extracting

### ISSUE THREAD

**Issue by Marc66** [aonez/Keka#578]
I use both Keka and The Unarchiver. The main reason I keep using The Unarchiver is because it has an option to always create a folder when extracting.

Keka has 3 options for extraction:
- Always ask
- Next to original file
- Specific folder

The Unarchiver has 2 level options for extraction:
- First level: Same folder as archive / Ask for destination folder
- Second level - Create a new folder for extracted files: Never / Only if multiple files at root level / Always
- Second level - Folder date: Same as archive date / Current date & time
* The folder name is the same as the archive name

Would it be possible for Keka to also have an option to always create a new folder when files are extracted?

Thank you

**Comment by aonez** [comment]
@Marc66 this is already developed in the latest 1.2.0 beta (#135)

Note the "Always extract in a subfolder" item:

![Screenshot 2020-07-02 at 12 08 06](https://user-images.githubusercontent.com/480163/86346111-bfda7680-bc5c-11ea-849b-93a23e55142a.png)
