### ISSUE TITLE
macOS 11.0 Big Sur and Apple silicon support

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#579]
- [x] Apple silicon support: Compiled, untested in Apple silicon hardware 👉 [Keka-v1.2.1-rc](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.1-rc.r4182.7z)
  - [x] LRZIP not working on 10.13 and below
  - [x] Brotli compression not working on 10.12 and below
  - [x] Brotli extraction not working on 10.10
- [x] GUI fixes
- [x] GUI changes
- [ ] Other fixes? -> `1.2.1`

**Comment by JayBrown** [comment]
fyi—just a tangent: Archive Utility on Big Sur now supports expanding ZIP64 (zip files with AES-256 encryption etc.)

**Comment by aonez** [comment]
Thanks for the tip @JayBrown!
