### ISSUE TITLE
Compression queue: process one job at time.

### ISSUE THREAD

**Issue by domomg** [aonez/Keka#58]
Hi,

I'm opening this as a feature request.

More than often, I need to compress several files (tens if not hundreds) into separate archives, using the "archive as single files" option.

I used to use WinRAR on Windows, before switching completely to macOS, and I can remember it had this behaviour by default, when selecting the archive as single files option.

Uncompressed files could be several hundred of megabytes each, so wherever I drop them into Keka, it starts compressing them _all at once_, and this is very taxing both on I/O and particularly CPU and memory.

It would be nice to have an additional checkbox somewhere, to have Keka process one or two jobs in the queue at time, given some compressors (like 7zip) can scale on multiple cores, so it would be a good compromise between speed and resources use.

**Comment by aonez** [comment]
@domomg thanks for your feedback! There's already an issue for this one, let's continue there: #21

**Comment by domomg** [comment]
Sure, many thanks and sorry for the duplicate (should've missed it)
