### ISSUE TITLE
[BUG] password not accepted for P7zip on Mac error 334

### ISSUE THREAD

**Issue by bazh1** [aonez/Keka#580]
**Configuration**
Keka version: [e.g. 1.1.24 (3421)]
macOS version MOJAVE : [e.g. 10.14.6 (18G2022)]

I have to extract a file from a keka zip file downloaded from firefox on to my Mac. Password has been entered correctly but i get an error message: Error code 334 using "p7zip" Bad password, try again
There is no issue with the password having been using it without problems before on windows system. Any solutions? I can't send file due to sensitive nature of document. 

Attach a log file reproducing the issue: https://github.com/aonez/Keka/wiki/Report-an-issue

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aonez** [comment]
Can you attach the process log?

https://github.com/aonez/Keka/wiki/Report-an-issue

**Comment by bazh1** [comment]
[Keka-log-20200710101802988.log](https://github.com/aonez/Keka/files/4902210/Keka-log-20200710101802988.log)

**Comment by bazh1** [comment]
Found solution. sorry to be a bother

**Comment by aonez** [comment]
Thanks @bazh1! Was it a wrong password? Keka worked for you finally?

**Comment by bazh1** [comment]
I was sent the documents again with a different password and it worked. Very impressive when it works. The original password is valid and correctly entered, and another person who has access to the documents using the same password could still access the documents, but I can't get to the bottom of why it didn't work. Worked perfectly well all this year using a windows operating system, and so that is why i assumed it must be something to do with the Mac.

**Comment by aonez** [comment]
Is it possible that you share with me only the password to try to replicate the issue? Knowing in what OS and with what app the original file was compressed will help too. Thanks!
