### ISSUE TITLE
[BUG] Typo in settings dialog

### ISSUE THREAD

**Issue by lsgd** [aonez/Keka#582]
**Configuration**
Keka version: 1.2.0-dev (3901)

**Describe the bug**
Typo: "Ask before quitting with opreations"

**To Reproduce**
1. Go to Settings > General

**Expected behavior**
Rename "opreations" to "operations"

**Screenshots**
![image](https://user-images.githubusercontent.com/820580/87242143-54499380-c42a-11ea-88f3-9d850edbc690.png)

I tried to send a Pull request, but I could not find the text for this text in the code... Can you point me to the file?

**Comment by Oleg-Chashko** [comment]
I pointed out this error in GUI - Small design flaws. #536 
<img width="922" alt="Screenshot 2020-07-12 at 10 33 56" src="https://user-images.githubusercontent.com/62497891/87242279-80b1df80-c42b-11ea-9886-ad2db2a00166.png">

**Comment by aonez** [comment]
Fixed! Thanks @lsgd and @Oleg-Chashko :)
