### ISSUE TITLE
[REQ] Updated icon for Big Sur

### ISSUE THREAD

**Issue by godly-devotion** [aonez/Keka#585]
macOS Big Sur is updating all the system icons with a rounded-rectangle shape and a front-facing perspective. Some 3rd party developers including Adobe are converting their app icons to match up with these system icons as well.

![](https://developer.apple.com/design/human-interface-guidelines/macos/images/mail-photos-preferences-big-sur.png)

![](https://developer.apple.com/design/human-interface-guidelines/macos/images/preview-xcode-text-edit-big-sur.png)

Could we get an updated icon that follows more closely to the rounded-rectangle shape with a front-facing perspective so that the icon style is consistent with others in Big Sur? This will help Keka not to look out of place in the dock and Launchpad.

**Comment by aonez** [comment]
I just can hope they enabled [setAlternateIconName](https://developer.apple.com/documentation/uikit/uiapplication/2806818-setalternateiconname) in macOS.

I suppose iOS square is the new standard... Not in 1.2.0, but probably will need to update it in the near future.

**Comment by aonez** [comment]
Just noticed the new Big Sur apps have both the new and old icon inside. Furthermore if you copy/paste one of this new apps to Catalina or later they show the old icon.

The old icon is both present in `file.icns` form and inside the `Assets.car` file. The new one is only present in the assets file and uses a naming scheme like `<NAME>-1016<SIZE>.png`.

So if we can use this, for sure Keka will have an adapted icon for Big Sur sooner than later.

**Comment by godly-devotion** [comment]
Since Keka is a macOS only app, would it be simpler to have the same icon on all versions? For example PS 2020 just updated its app icon to have the rounded corners for all versions of macOS. I don't think it will hurt to have one icon for all, and would even be beneficial to keep the same icon everywhere in the MAS, website, etc.

**Comment by gottabeleGIT** [comment]
Suggestion for possible new icon: https://github.com/elrumo/macOS_Big_Sur_icons_replacements/blob/master/icons/Keka.icns

**Comment by aonez** [comment]
Nice! He added the website background 😀 I was thinking in having some of the white sheets outside the square, since Apple is doing that kind of thing in Big Sur.

**Comment by aonez** [comment]
Some background color variants...

## Dark green
![icon_128x128](https://user-images.githubusercontent.com/480163/99192758-fbda2800-2774-11eb-8acf-1cf806386fb3.png)

## Turtle green
![icon_128x128](https://user-images.githubusercontent.com/480163/99192759-fe3c8200-2774-11eb-824e-e59c06e8b8f8.png)

## Medium green
![icon_128x128](https://user-images.githubusercontent.com/480163/99192760-009edc00-2775-11eb-8855-bdc32634780e.png)

## Light green
![icon_128x128](https://user-images.githubusercontent.com/480163/99192762-01d00900-2775-11eb-991b-cdb47e938014.png)

**Comment by godly-devotion** [comment]
Personally, I think Medium green has a nice hue to it, not too dark and not too light. Also I think it would help to have more padding within the icon itself to give more breathing room for the bug.

**Comment by aonez** [comment]
@godly-devotion I wanted to let the sheets scape from the square, but I know it's too big of a Keka for that little square...

![Untitled](https://user-images.githubusercontent.com/480163/99193453-3e9dff00-2779-11eb-8098-7870f7d7a3d4.png)

**Comment by godly-devotion** [comment]
@aonez Seeing the icon in context in the dock actually helps me to see why the Keka needs to be a little bit big (for better visibility). In terms of the sheets going outside the icon, I don't have a strong opinion for or against it. 👍🏼

**Comment by fre123ber** [comment]
Hello! Let me say that Keka is a phenomenal piece of software, but I think that the proposed icon is just not good enough. Not only it's completely out of place with the new icons in terms of color palette, simplicity, and skeuomorphism, but it's also a bad job of adjusting an older icon. In truth, because I'm a bit of a nerd (as an artist) what has kept me from using Keka are the icons, and I think that I'm not the only one.
May I suggest on open submission or a selection of designers that could contribute to an open source software? I think that many would create an icon for Keka just for the recognition they could get. There are many designers here [(https://github.com/elrumo/macOS_Big_Sur_icons_replacements)]. Also, I suggest the work of the user "yw4z" on Dribbble.
With proper icons and system integration Keka could become an app that everyone is familiar with and considers essential as a Mac user.
Thank You and keep up the good work!

**Comment by aonez** [comment]
Thanks a lot for your ideas and recommendations @fre123ber! For sure I need to tweak the colors and probably the shadows, will do some more revisions to the icon and then will see...

The one in elrumo repo was already suggested and in fact I’ve followed the idea but need to use the proper designs for each size and resolution.

Maybe I send a message to yw4z, loving his transmission rework!

**Comment by aonez** [comment]
As you may see I'm not in love with the new Big Sur icons style. Just found [this](https://medium.com/@NikxDa/macos-big-sur-has-an-iconography-problem-fe83e116eaf3) that talks about that skeuomorphism 😛

**Comment by gingerbeardman** [comment]
I agree, even with no intention of going to Big Sur, that the icon needs to be better. 

Plus, the green is not very visible for me (I am green/brown colour blind).

**Comment by aonez** [comment]
Another version by @Oleg-Chashko: https://github.com/aonez/Keka/issues/691#issue-750005641

**Comment by godly-devotion** [comment]
@aonez That one is pretty cute too 👍🏼

**Comment by aonez** [comment]
Definitely high quality 🔝

**Comment by Oleg-Chashko** [comment]
Green is hard to see on the dark theme of macOS.
Temporarily did it.
![Keka](https://user-images.githubusercontent.com/62497891/100263703-2040bc00-2f4e-11eb-924b-11fbb4f661eb.png)
<img width="142" alt="Bildschirmfoto 2020-11-25 um 18 47 21" src="https://user-images.githubusercontent.com/62497891/100264117-ad841080-2f4e-11eb-9d5b-214f8faba6e3.png">

[Keka.icns.zip](https://github.com/aonez/Keka/files/5598379/Keka.icns.zip)

**Comment by Oleg-Chashko** [comment]
![Keka 2](https://user-images.githubusercontent.com/62497891/100267177-50d72480-2f53-11eb-8793-a1d9bb9c7a12.png)
<img width="142" alt="Bildschirmfoto 2020-11-25 um 19 22 26" src="https://user-images.githubusercontent.com/62497891/100267361-95fb5680-2f53-11eb-8a7b-27230cdeb08d.png">

[Keka 2.icns.zip](https://github.com/aonez/Keka/files/5598557/Keka.2.icns.zip)

**Comment by Jax0rz** [comment]
I think this version is the best:

<img width="512" alt="icons_approved-1604884518665_Keka_Alt" src="https://user-images.githubusercontent.com/7557357/100357131-35d9e280-302f-11eb-8f2f-9321fc09ed51.png">

You can download it at this [link](https://storage.googleapis.com/download/storage/v1/b/macos-icons.appspot.com/o/icons_approved%2F1604884518665_Keka_Alt.icns?generation=1604884707182326&alt=media)

**Comment by mhalachev** [comment]
How about adding a backlight as if it is coming from the light source behind the crunched sheets? 

![backlight-none](https://user-images.githubusercontent.com/2463597/100455289-1f7f6580-30c7-11eb-9271-6648449b0418.png) ![backlight-red](https://user-images.githubusercontent.com/2463597/100455157-e941e600-30c6-11eb-92aa-7e8fc3777a4e.png) ![backlight-blue](https://user-images.githubusercontent.com/2463597/100455171-f19a2100-30c6-11eb-8a4b-b3cf6ad1a0fc.png) ![backlight-orange](https://user-images.githubusercontent.com/2463597/100455058-b7308400-30c6-11eb-8f98-2dcdc6c05031.png)

This shall improve legibility, especially in small sizes, e. g. in Dock, Launchpad, etc...

**Comment by gingerbeardman** [comment]
That looks great, I like the last one of those best.

**Comment by Marc66** [comment]
> How about adding a backlight as if it is coming from the light source behind the crunched sheets?
> 
> ![backlight-orange](https://user-images.githubusercontent.com/2463597/100455058-b7308400-30c6-11eb-8f98-2dcdc6c05031.png)
> 
I like the orange one very much. There's been some discussion about having a green background. Could you make an icon with a green backlight to see what it looks like. Maybe that would be a good compromise of all previous discussions/suggestions

**Comment by mhalachev** [comment]
Here it is...

![green](https://user-images.githubusercontent.com/2463597/102370889-4514d600-3fc6-11eb-8a58-0882e9354c1c.png)

However, the contrast is low IMHO... How about green on green?

![green-halo](https://user-images.githubusercontent.com/2463597/102373058-7bebeb80-3fc8-11eb-8d33-a91881a0ec6f.png)

Or, a distant one, just to make the shaded bottom noticeable:

![green-light-grad](https://user-images.githubusercontent.com/2463597/102373277-b35a9800-3fc8-11eb-8a93-48bda5d8aaf5.png)

**Comment by Marc66** [comment]
Sorry if I wasn't clear: keep the same brown background but make a green ring

**Comment by mhalachev** [comment]
Apologies, my mistake :)

![green-backlight](https://user-images.githubusercontent.com/2463597/102486489-c70e0900-4071-11eb-8e57-2fe200869deb.png)

![mock-dock](https://user-images.githubusercontent.com/2463597/102486503-cc6b5380-4071-11eb-8847-ac7a64cc9c27.png)

**Comment by Marc66** [comment]
Very nice, thank you

**Comment by Oleg-Chashko** [comment]
Perhaps someone wants to make an icon on their own. I attach a sketch file.
<img width="161" alt="Screenshot 2020-12-22 at 15 00 26" src="https://user-images.githubusercontent.com/62497891/102896314-7843e300-4466-11eb-92b5-75cef3a44640.png">
[Keka - Green.icns.zip](https://github.com/aonez/Keka/files/5730202/Keka.-.Green.icns.zip)
[Keka - Green.sketch.zip](https://github.com/aonez/Keka/files/5730203/Keka.-.Green.sketch.zip)

**Comment by leejongyoung** [comment]
With [iconsur](https://github.com/rikumi/iconsur), you can make icons faster

``` shell
# install iconsur from homebrew
brew install iconsur

# - size: 0.8
# - color: #472E01 (html color)
# update icon
sudo iconsur set /Applications/Keka.app -l -s 0.8 -c 472E01
```
# Result screenshot
<img width="130" alt="Screen Shot 2021-03-22 at 4 11 06 PM" src="https://user-images.githubusercontent.com/76589242/111952922-37bd3980-8b29-11eb-9b28-7084f2b20e0e.png">

**Comment by godly-devotion** [comment]
![image](https://user-images.githubusercontent.com/1341760/113914134-2c197600-97ab-11eb-9070-e905fb47ac15.png)
![image](https://user-images.githubusercontent.com/1341760/113914150-32a7ed80-97ab-11eb-863c-92a11a82dee5.png)

[Keka.icns.zip](https://github.com/aonez/Keka/files/6273685/Keka.icns.zip)

Just to add my 2 cents, I've been using this icon and its been working well enough for me.

**Comment by MaxPower85** [comment]
I'm not a fan of just making icons smaller and putting them on top of a rounded square for Big Sur...  it just makes the details of the icon smaller and they don't stand out much.... 

Something like this would maybe also be an option if icons had to be rounded squares...

![Slice 1](https://user-images.githubusercontent.com/37249460/114175145-f656c780-9939-11eb-8dc9-26db669eb580.png)

I just would't rush with making a rounded square icon, since not even all of Apple's icons are necessarily rounded squares.

**Comment by desmortum** [comment]
More and more apps updating their icons every day. Super excited to see new Keka icon.

**Comment by aonez** [comment]
There's already some work on a fully redesigned icon that will fit Big Sur+ and iOS. Hopefully I can share a sample soon :)

**Comment by desmortum** [comment]
@aonez, any news?

**Comment by aonez** [comment]
No more updates yet from the designer, I'll try to reach out later.

**Comment by desmortum** [comment]
¯\\_(ツ)_/¯

**Comment by aonez** [comment]
Almost done 🙈

![icon_16x16](https://user-images.githubusercontent.com/480163/134486107-c5b5b896-34aa-4d20-a106-ccd75d219f87.png)

**Comment by desmortum** [comment]
@aonez, any news?

**Comment by aonez** [comment]
<img width="690" alt="Screen Shot 2021-11-15 at 17 17 02" src="https://user-images.githubusercontent.com/480163/141816423-2a4af17f-bb81-4e23-b9de-26178fab08d9.png">

Just finishing all changes. It's done :)

**Comment by sbarex** [comment]
The previous icon may not have been in the big sur style but it was prettier and more recognizable in my opinion.
The idea of the task counter is nice

**Comment by desmortum** [comment]
> The previous icon may not have been in the big sur style but it was prettier and more recognizable in my opinion. The idea of the task counter is nice

I think new Icon is good and unique. Sure, there always might be a room for improvement but I think apps should follow new Apple guidelines.

**Comment by Oleg-Chashko** [comment]
The "Keka" icon has a face change, and I was very pleased with that. ❤️
The idea with the task counter is very good. 👍🏻

**Comment by ArchitectNaut** [comment]
I preferred the more aggressive looking face.

**Comment by aonez** [comment]
As with the [previous icon change in 2018](https://github.com/aonez/Keka/issues/281#issuecomment-418708087), I understand not all people will prefer this one. Sadly Apple does not give the proper APIs to enable the use of alternative icons within the app in macOS, which I will happily implement if available.

You can ask Apple to implement this feature (already available on iOS): https://www.apple.com/feedback/macos.html

You can always download an earlier Keka version and apply its icon to the newer version: https://github.com/aonez/Keka/issues/281#issuecomment-418708087
