### ISSUE TITLE
Its not related to keka specifically

### ISSUE THREAD

**Issue by Parthvsquare** [aonez/Keka#587]
I was wondering can I get "Extract using keka" to the main menu panel. Not sure if this it's name. (the panel like thing pops up when you control click/right click) ![Screenshot 2020-07-20 at 1.01.59 AM.png](https://user-images.githubusercontent.com/26404957/87883805-74182300-c9f9-11ea-9ac9-ac0058312457.png)

**Comment by gingerbeardman** [comment]
Two answers:

1. no, not with the version you are using
2. but! the latest "dev" version does it

https://github.com/aonez/Keka/releases

**Comment by Parthvsquare** [comment]
i installed the dev version but, i couldn't find it.Also couldn't find it in the toolbar.

**Comment by gingerbeardman** [comment]
You are looking for the Keka Finder Extension

Please use:

_System Preferences > Extensions > Finder Extensions > Keka Finder Integration_

![Screen shot 2020-07-20 at 13 53 09](https://user-images.githubusercontent.com/49612/87939718-5fd33500-ca90-11ea-89d0-29cd28d7842c.png)

**Comment by aonez** [comment]
Thanks @gingerbeardman! @Parthvsquare hope you've found the Finder extension useful :)
