### ISSUE TITLE
can not create zip file in ~/Movies dir[BUG]

### ISSUE THREAD

**Issue by vacuityv** [aonez/Keka#588]
**Configuration**
Keka version: 1.1.30
macOS version: 10.15.6 (19G73)

**Describe the bug**
when I press the right button and zip a file in ~/Movies, it says: error code 2 use “p7zip”
as a programmer I open the debug and found that the true error was permission denied. but i'm sure I have gaven it enough permission

**Comment by aonez** [comment]
@vacuityv could you attach the [log reproducing the error](https://github.com/aonez/Keka/wiki/Report-an-issue)?
