### ISSUE TITLE
tarball with erroneous extension results in a partial extraction

### ISSUE THREAD

**Issue by vlape** [aonez/Keka#589]
**Configuration**
Keka version: 1.1.30 (3477)
macOS version: 10.15.6 (19G73)

**Describe the bug**
Decompressing file which has multiple directories with .tar extension results in single file. Using MacOs Archive utility provides expected results.
[Keka-log-20200720114933604.log](https://github.com/aonez/Keka/files/4949028/Keka-log-20200720114933604.log)

Attach a log file reproducing the issue: https://github.com/aonez/Keka/wiki/Report-an-issue

**To Reproduce**
1. double click on file. file extracted as single file
2. right click, open with keka.app. file extracted a single file. 
right click, open with Archive Utility.app, file extracted as multiple folders containing data.

**Expected behavior**
extract the files and folders exactly as they were compressed as. 

**Screenshots**
[Screen Recording 2020-07-20 at 11.59.21 AM.mov.gz](https://github.com/aonez/Keka/files/4949064/Screen.Recording.2020-07-20.at.11.59.21.AM.mov.gz)

**Additional context**

**Comment by aonez** [comment]
@vlape this is similar to #311, but in this case the file you're extracting lacks the `.gz` extension. `master_opt.tar` should be `master_opt.tar.gz`, it is indeed a `GZIP`ed `TAR` file. As it lacks the tarball extension Keka extracts the `GZIP` content, that is a `TAR` file, but without extension.

macOS extracts subsequent files so it founds the `TAR` file and extracts it too. I should add this feature to Keka, will be tracked in #337.

Thanks for the feedback!
