### ISSUE TITLE
Error code 2 using "p7zip" Fatal error. on MacOS High Sierra

### ISSUE THREAD

**Issue by lpcsz** [aonez/Keka#594]
**Configuration**
Keka version: [Version 1.1.30 (3477)]
macOS version: [10.13.6 (17G12034) High Sierra]

**Describe the bug**
Each time I am trying to encrypt a ZIP file, I get the following error message: Creation of EXAMPLE failed: Error code 2 using "p7zip" Fatal error. Extraction works as usual though. I tried to look for updates, uninstall/reinstall but nothing seemed to help.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lpcsz** [comment]
Also: No, the file is not broken and it does not exceed 4GB.

**Comment by aonez** [comment]
Please @lpcsz can you [attach the log file](https://github.com/aonez/Keka/wiki/Report-an-issue) after reproducing the issue?
