### ISSUE TITLE
Configuration or Window in advancedWindowPopover.strings?

### ISSUE THREAD

**Issue by VinBoiSoft** [aonez/Keka#596]
In the English version of **advancedWindowPopover.strings** is

https://github.com/aonez/Keka/blob/8e24ac1a8f8efd404177eb0b7b20cb2e71b3c75a/Translations/en.lproj/advancedWindowPopover.strings#L5-L6

Instead in the other languages it is (_see for example_)

https://github.com/aonez/Keka/blob/8e24ac1a8f8efd404177eb0b7b20cb2e71b3c75a/Translations/es.lproj/advancedWindowPopover.strings#L5-L6

In the same file there is both **Configuration** (_Automatically save configuration changes_) and **Window** (_Use as default window_ / _Window name:_)

Which of the two strings is the right one?

Thanks.

**Comment by aonez** [comment]
`Remove this configuration` it is. This feature will not come in time for 1.2.0, so don't worry about it :)
