### ISSUE TITLE
Video to gif

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#60]
Maybe adding the option to convert video to gif... not really a compression, sometimes the gif weights more than the original video... but may be useful for some.

Maybe use gifify or something similar:
https://github.com/vvo/gifify
https://github.com/jclem/gifify

**Comment by Bustycat** [comment]
What video formats would Keka support? Would it simply convert a video to GIF? Or would there be some options?

**Comment by aonez** [comment]
> What video formats would Keka support?

Mostly the supported by [ffmpeg](http://ffmpeg.org)

> Would it simply convert a video to GIF? Or would there be some options?

Sure, it will be some options like number of colors, FPS, speed...

As I'm writing this I'm seeing not point of adding this functionality to Keka... Let's see what the [poll](https://twitter.com/kekaosx/status/896355866928087040) says.

**Comment by aonez** [comment]
Dismissed with a [Twitter pool](https://twitter.com/kekaosx/status/896355866928087040).
