### ISSUE TITLE
[REQ] Language selection in application settings.

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#604]
Please add language selection from the program.
Example:
<img width="390" alt="Screenshot 2020-08-01 at 13 48 04" src="https://user-images.githubusercontent.com/62497891/89108585-1395d680-d43a-11ea-9dab-ef1ea0eda96f.png">

**Comment by aonez** [comment]
I've never seen a need for this since you can set your preferred languages (and its order) in the  Preferences. Only for testing, but then you can:

- Temporarily open Keka in any language like that:

```sh
Applications/Keka.app/Contents/MacOS/Keka -AppleLanguages '(ru)'
```

- Set it permanently like this:

```sh
defaults write com.aone.keka AppleLanguages '("ru")'
```

**Comment by Oleg-Chashko** [comment]
> I've never seen a need for this since you can set your preferred languages (and its order) in the  Preferences.

I know it. Thanks for the answer.
