### ISSUE TITLE
Not extracting or compressing

### ISSUE THREAD

**Issue by tiagorocha1979** [aonez/Keka#606]
If I try to extract files from a simple ZIP file, it works, but I'm trying to extract from a combo of RAR files (so a single file split into many RAR files) and it's stuck, nothing is happening.
I tried extracting the same files using The Unarchiver and it worked.

I also tried creating a multi ZIP file compression, nothing.

Updated the app, no luck...

Mac OSX 10.13.6
Keka 1.1.30 (3477)

**Comment by aonez** [comment]
Can you create a debug session, reproduce the issue and share the log file
here?

https://github.com/aonez/Keka/wiki/Report-an-issue
