### ISSUE TITLE
Conflict with Microsoft OneDrive

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#608]
**Configuration**
Keka version: 1.2.0
macOS version: 11.0.1 Beta (20B5022a)

"Keka Finder Integration" partially breaks, "OneDrive.app" its integration with Finder

<img width="667" alt="Keka Finder Integration" src="https://user-images.githubusercontent.com/62497891/89913607-34a5b680-dbf4-11ea-9384-f48012616d4f.png">
<img width="769" alt="Screenshot 2020-08-11 at 17 02 20" src="https://user-images.githubusercontent.com/62497891/89913871-82222380-dbf4-11ea-9bb9-556424544f27.png">

**Screen Recording:**
[Screen Recording 2020-08-11 at 16.37.28.zip](https://github.com/aonez/Keka/files/5057650/Screen.Recording.2020-08-11.at.16.37.28.zip)

**Comment by aonez** [comment]
That’s odd... I don’t use OneDrive but will try to replicate this tomorrow. Thanks for the feedback @Oleg-Chashko!

**Comment by Oleg-Chashko** [comment]
> That’s odd... I don’t use OneDrive but will try to replicate this tomorrow. Thanks for the feedback @Oleg-Chashko!

"Keka" and "OneDrive" have a common area of the context menu. Perhaps because of this there is a conflict between them?
<img width="301" alt="Screenshot 2020-08-12 at 09 04 24" src="https://user-images.githubusercontent.com/62497891/89987720-c8bc6000-dc7e-11ea-992a-517f8b9645bb.png">

**Comment by Oleg-Chashko** [comment]
Will this bug be resolved?

**Comment by Oleg-Chashko** [comment]
Will this bug be fixed?

**Comment by aonez** [comment]
Sorry @Oleg-Chashko will be checking that one today 😅

**Comment by aonez** [comment]
So it seems the first extension that registers for a directory has priority for those flags. I'll investigate if there's any way to change this behaviour.

**Comment by Oleg-Chashko** [comment]
> So it seems the first extension that registers for a directory has priority for those flags. I'll investigate if there's any way to change this behaviour.

I have a conflict when activating the item: Show Keka actions in Finder`s contextual menu.

<img width="758" alt="Bildschirmfoto 2020-11-23 um 13 33 51" src="https://user-images.githubusercontent.com/62497891/99963321-e925ab80-2d91-11eb-9e61-b610abe80173.png">

_Good luck with solving the problem._

**Comment by aonez** [comment]
So far:

- The first extension that registers a directory owns gets `requestBadgeIdentifierForURL`, even if that extension does not implement that method. Subsequent extensions that register for that directory do not get that call.
- All extensions monitoring a directory receive notifications for `beginObservingDirectoryAtURL` and `endObservingDirectoryAtURL` so the sync actually works on all extensions.

I might be missing something but right now I think coexistence of multiple Finder extensions for the same directories is partially implemented. Would be good if I can simply tell `FIFinderSync` I only want to use `menuForMenuKind` (the contextual menu) and not the other methods so other Finder extensions can use them.

At this point I can only think of a selective sync for the Keka Finder Extension so you use the extension in the directories manually selected. Similar to the File Access list.

In fact it's already partially developed (but not activated) to register the extension only in the File Access items, so I might end this development and enable the option:

![Screenshot 2020-11-23 at 17 00 09](https://user-images.githubusercontent.com/480163/99984581-86daa400-2dad-11eb-8a99-574c433baab8.png)

**Comment by aonez** [comment]
I'm gonna ask Apple if I'm missing something, if not I'll create a feedback report so they know this coexistence of multiple extensions on the same directory is not properly implemented.

**Comment by aonez** [comment]
I will not use the File Access list because as soon as you extract something in the OneDrive folder it will be added to that list and the bug will appear. I'll need to add a new list for the context menu.

**Comment by aonez** [comment]
Should be fixed with the customizable list: [Keka-v1.2.5-r4326.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.5-r4326.7z)

**Comment by Oleg-Chashko** [comment]
> Should be fixed with the customizable list: [Keka-v1.2.5-r4326.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.5-r4326.7z)

@aonez 
Checked there is no more conflict. I like it, Thank you. :)
