### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sharrettn** [aonez/Keka#609]
**Configuration**
Keka version: [e.g. 1.1.24 (3421)]
macOS version: [e.g. 10.14.6 (18G2022)]

**Describe the bug**
Compressing a file and/or set of files to zip file.  Password entered and re-entered.  Users are not prompted for password when extracting the compressed file.

**Expected behavior**
User should be prompted for password.

**Comment by aonez** [comment]
Hi @sharrettn, can you please share a test zip file compressed with password that reproduces this issue? What app are the other end using?

**Comment by sharrettn** [comment]
[Keka Test.zip](https://github.com/aonez/Keka/files/5059772/Keka.Test.zip)

See attached test zip file.  I entered the password below on the Keka screen and received the lock icon.  But was not prompted to enter the password when attempting to extract the zip file.

password = TEST11082020

**Comment by aonez** [comment]
The file is indeed not encrypted. You said you're entering and re-entering the password but just for doble check, are you seeing the keychain closing and the green check when re-entering? This assures that the password does match.

Also note that this password is only effective while Keka is open. If you close Keka that password is no more used.

**Comment by sharrettn** [comment]
yes I'm seeing the keychain closing and green check.   I did then close Keka.  if I have to keep it open in order to ensure the password is enforced, that will be challenging to know how long to keep it open based on recipients receiving/extracting the file.

**Comment by aonez** [comment]
You only need to keep Keka open if you want to compress with that password. Once the file is compressed you can close Keka.

**Comment by sharrettn** [comment]
once the file was compressed with the password, I closed Keka.  I then attempted to extract the file and need the end users to be prompted for the password.  the only way to be prompted for the password during extraction is then to have Keka open.  is this true?  we have clients in different countries and different timezones and in order to ensure they are prompted for the password, then I have to keep Keka open?

**Comment by aonez** [comment]
No, you only need Keka open when compressions. I’ll send you a video
showing how to do it.

**Comment by sharrettn** [comment]
I was not prompted for the password after I closed Keka.

**Comment by aonez** [comment]
I've crated the attached [Test.zip](https://github.com/aonez/Keka/files/5063932/Test.zip) file (password is `1234`) doing so:

![Untitled copy mov](https://user-images.githubusercontent.com/480163/90038180-68044600-dcc5-11ea-8baf-479d50672ce9.gif)

If you're doing the same and still the file is not encrypted, please [create a debug session](https://github.com/aonez/Keka/wiki/Report-an-issue#debug-session), reproduce the issue and attach here the resulting log file.

**Comment by sharrettn** [comment]
I realized that I was entering the password into Keka after I dragged the folder in that I wanted to compress.  Now that I dragged the folder in and entering the password into Keka first, it is working for me now.  Thanks so much for the support!!

**Comment by aonez** [comment]
Nice! Glad to help :)
