### ISSUE TITLE
7-Zip password encrypted files cannot be extracted

### ISSUE THREAD

**Issue by philippedcote** [aonez/Keka#610]
**Configuration**
Keka version: Version 1.1.30 (3477)
macOS version: 10.15.6 (19G73)

**Describe the bug**
When using password protection and the 7-Zip format, the resulting archive cannot be unlocked with the password.

**To Reproduce**
1. Open Keka
2. Set to the 7-Zip format
3. Write down a simple password in the two fields
4. Drag & drop file on window to compress
5. After compression, try to extract the file using the same password

**Expected behavior**
Archive should extract upon entering the correct password.

**Comment by aonez** [comment]
Please check you're not trying to extract that file with the macOS bundled archiver instead of Keka:


https://github.com/aonez/Keka/issues/477
