### ISSUE TITLE
[REQ] Type custom split sizes, or create custom sizes in Preferences

### ISSUE THREAD

**Issue by nighto** [aonez/Keka#611]
**Is your feature request related to a problem? Please describe.**
It'd be great to be able to type the desired split size (for i.e. 2GB for WeTransfer) instead of just picking from a list. Alternatively, an option could be creating custom split sizes in Preferences.

Related to #551.

**Comment by nighto** [comment]
Nevermind, just seen it is indeed possible to type on the select field. Maybe a label giving attention to that could be nice, but for now I'm closing this. Sorry for the noise, and thanks for the awesome work :)

**Comment by aonez** [comment]
Thanks @nighto! That dropdown menu really need some improvement :)
