### ISSUE TITLE
[BUG] Keka keeps prompting asking where I want to extract

### ISSUE THREAD

**Issue by briantully** [aonez/Keka#613]
**Configuration**
Keka version: 1.1.30 (3477)
macOS version: 10.14.6 

**Describe the bug**
Keka is the only extractor that doesn't extract without requiring manual intervention. It keeps asking me where I want to extract the files, even though I have explicitly set the preference to extract to location "next to original file".

It it not possible to just double-click on an archive and have it automatically extract without manual intervention?

**To Reproduce**
1. Go to your folder containing your archive (i.e., file.rar)
2. Double click on the file to have Keka open the file to extract
3. Keka opens, but instead of extracting the file, a Finder window opens with a prompt asking where to extract the file.

**Expected behavior**
With the "extract to loction" preference set to "next to original file" I would expect that Keka would automatically extract the file without manual intervention. Instead it seems as though the extract to location preference "ask each time" is being used, despite the preference explicitly being set to "next to original file"

**Comment by aonez** [comment]
Hi @briantully, this is a limitation of the sandbox Keka is running on. Check this: https://github.com/aonez/Keka/issues/325#issuecomment-439838136

If that does not work for you please reopen the issue and let me know. Cheers!
