### ISSUE TITLE
Error 2 with p7zip

### ISSUE THREAD

**Issue by iDjay** [aonez/Keka#616]
**Configuration**
Keka version: [ 1.1.30 (3477)]
macOS version: [e.g. 10.15.6 (19G2021)]

**Describe the bug**
happens at the end of the unzip process, dmg can't be open afterwards

**To Reproduce**
Download file which can't be opened:
https://we.tl/t-IZ7jbMoDOp

**Expected behavior**
should extract fine

**Screenshots**
<img width="511" alt="Bildschirmfoto 2020-08-28 um 10 16 00" src="https://user-images.githubusercontent.com/4127356/91538050-7e421100-e917-11ea-92b6-7be59ff673b0.png">

**Comment by aonez** [comment]
This file is corrupt. Also it's not a ZIP but a BZIP2. Maybe you can download that file again?

**Comment by iDjay** [comment]
True, for some reason the download was messed up. You can close the issue :)

**Comment by aonez** [comment]
Thanks for the followup @iDjay! Enjoy your day :)
