### ISSUE TITLE
Can I add Chinese interface?

### ISSUE THREAD

**Issue by LisonFan** [aonez/Keka#62]

**Comment by aonez** [comment]
Sure! Do you have experience translating Cocoa projects?

**Comment by maxsky** [comment]
Hey guy, you're robbing me for the job. Hahaha... :)

**Comment by LisonFan** [comment]
@maxsky 😂，之前在用老版本，没有中文，所以来问问能不能支持中文，标题是谷歌翻译的，把意思翻译错了。。。。

**Comment by aonez** [comment]
> 之前在用老版本，没有中文，所以来问问能不能支持中文，标题是谷歌翻译的，把意思翻译错了。。。。

So you meant 简体中文? Or 繁體中文?

**Comment by LisonFan** [comment]
@aonez Simplified Chinese

**Comment by aonez** [comment]
Thanks @LisonFan! Then I close this issue :)

**Comment by maxsky** [comment]
:) , tonight I will add new translated files
