### ISSUE TITLE
Hey, I do not know how to complete translated files to you now

### ISSUE THREAD

**Issue by maxsky** [aonez/Keka#63]
Now all files was .string, but before this I can use XCode project file 'Project.xcodeproj' to translated Keka. So what should I do now?

**Comment by aonez** [comment]
Now you just need to translate the string files. They are all like the Localizable.strings. You can open them with Xcode, I personally use [TextMate](https://macromates.com).

**Comment by maxsky** [comment]
Yes, I tried modified many '.string' files. But I can't found some strings. (Keka version 1.1.0-beta.3) Like:

```
Encrypt filenames
Solid archive
Enable context menu services
Use unified toolbar (resets customizations)
```

**Comment by aonez** [comment]
Just updated with the two missing strings:
https://github.com/aonez/Keka/blob/577364b2e4db895c71ffb7ab566590026360e741/Translations/zh-Hans.lproj/preferences.strings#L260-L264

> Encrypt filenames
> Solid archive

My fault, the references where obsolete. Nothing to change here.
https://github.com/aonez/Keka/blob/4214eff58dadebf8f8ed4b194870ff4e2858126d/Translations/zh-Hans.lproj/advanced.strings#L437-L441
