### ISSUE TITLE
Partial extraction

### ISSUE THREAD

**Issue by HelmyBD2** [aonez/Keka#634]
Feature request to be able to list the archive content in the GUI and extract only the files needed not all files.

**Comment by gingerbeardman** [comment]
Dupe of #100

**Comment by aonez** [comment]
Thanks Matt! @HelmyBD2 Closing in favour of #100.

**Comment by HelmyBD2** [comment]
Thanks for the prompt reply. I see #100 is open since 2017, are there any plans to close it soon?

**Comment by gingerbeardman** [comment]
@HelmyBD2 see the list in #100 for alternatives if you need this feature now.

**Comment by HelmyBD2** [comment]
Thanks, I saw it and actually using ezip for now to open archives and keeping Keka only for compression. 

I am just curious what is your plans to close this point.

**Comment by aonez** [comment]
> I am just curious what is your plans to close this point.

It's coming in 1.3.0. No time yet, but will be the next thing to be developed after 1.2.0 is released.
