### ISSUE TITLE
[BUG] Extracting in the same folder

### ISSUE THREAD

**Issue by Myeauxyoozi** [aonez/Keka#636]
### Configuration
- Keka version: [e.g. 1.1.24 (3421)]
- macOS version: [e.g. 10.15.6 (18G2133)]

### Describe the bug
If I want to extract two or more .rar files that are in the same folder, it will only ever re-extract the first rar you use.
Attach a log file reproducing the issue: https://github.com/aonez/Keka/wiki/Report-an-issue

### To Reproduce
1. Download two .rar files (might occur if you make your own)
2. Make sure they are both in the same folder (i.e. same Finder location)
3. Drag the first .rar into Keka to extract it (choose the same folder as the one the .rar's are in)
4. Once it is finished attempt to extract the other .rar by dragging it into Keka
5. See error

### Expected behavior
It would extract the .rar file you just dragged in.

### Screenshots
Screenshots don't really prove much, it looks the same as if you were extracting the first .rar over and over.

### Additional context
I need to do this in the one folder for about 20 .rar's at a time. I don't want to have to create a new finder folder just to do that.

**Comment by aonez** [comment]
Thanks for the feedback @Myeauxyoozi! I can't reproduce your issue. Can you [enable a debug session](https://github.com/aonez/Keka/wiki/Report-an-issue), reproduce the issue and attach the log file here?

Or point me to the files that are triggering the issue? You can send the link/files via mail to info@keka.io if you prefer.

**Comment by Myeauxyoozi** [comment]
Nevermind closing the issue upon further inspection the multiple .rar files are identical copies of eachother under different names, however when unarchiving them it shows the first files name. Don't know how that happened.

**Comment by aonez** [comment]
@Myeauxyoozi probably that file contains a root folder and that's why the output folder name does not match the compressed file name. Greetings!
