### ISSUE TITLE
Asks each time for file save location even though "Next to original file" is selected [BUG]

### ISSUE THREAD

**Issue by bmvandoren** [aonez/Keka#637]
### Configuration
- Keka version: 1.1.30 (3477)
- macOS version: 10.15.6 (19G2021)

### Describe the bug
My Compression preferences are set so that compressed files are saved 'Next to original file,' however Keka asks me for the file save location each time. When I am compressing 50 individual files, this leads to a lot of annoying clicks. 
I've attached a log file where I compressed a text file and was prompted in this manner.
[Keka-log-20200913204536707.log](https://github.com/aonez/Keka/files/5215500/Keka-log-20200913204536707.log)

### To Reproduce
1. Confirm in Compression preferences that 'Next to original file' is selected under 'Save to location', thus Keka should not prompt when saving a file.
2. Drag a file to Keka.
3. Keka prompts where to save the file location.

### Expected behavior
I expected Keka not to prompt me where to save the file location.

### Screenshots
<img width="484" alt="Screen Shot 2020-09-13 at 8 49 35 PM" src="https://user-images.githubusercontent.com/8866446/93033077-a2ce0680-f602-11ea-9401-ce1b745d528b.png">

**Comment by aonez** [comment]
Take a look at this and let me know if it helps: https://github.com/aonez/Keka/issues/325#issuecomment-439838136

**Comment by bmvandoren** [comment]
Looks like that did it! Thanks. And thank you for all the great work with this software. Perhaps good to add a note in the "Name and location" section on the "Compression" table of the preferences to direct people to the File Access tab. It's confusing to have explicitly indicated not to "Ask each time" and still have it ask.

**Comment by aonez** [comment]
@bmvandoren you're not the first to ask that... Indeed just added this info in the upcoming version:

![Screenshot 2020-09-21 at 13 22 00](https://user-images.githubusercontent.com/480163/93761069-7111fc80-fc0d-11ea-9e59-b1a0a6dd7675.png)

![Screenshot 2020-09-21 at 13 22 39](https://user-images.githubusercontent.com/480163/93761118-8850ea00-fc0d-11ea-85ef-67c9d2e199cf.png)
