### ISSUE TITLE
[BUG] "Show content in Finder after extraction" not working properly

### ISSUE THREAD

**Issue by dstd** [aonez/Keka#639]
### Configuration
- Keka version: 1.1.30 (3477)
- macOS version: 10.15.6

### Describe the bug
I've checked "Show content in Finder after extraction" option. But after extraction Keka shows folder containing compressed file, not the extracted content.

### To Reproduce
1. Turn on "Show content in Finder after extraction"
2. Set "Extract to location" to "Next to original file"
3. All access to the file system is granted, "Move compressed to Trash" is turned off
4. Open `~/Downloads/some.zip`.
5. "Extracting" window shown for a while.
6a. [when extracting started in Finder] Finder got the focus back, keeping `~/Downloads/some.zip` selected.
6b. [when extracting started in a browser] Finder opened, showing `Downloads` folder, without focusing on particular item.

### Expected behavior
6a/6b. Finder got the focus back, with `~/Downloads/some/` folder selected.

### Screenshots
Considering `400613550...302959.zip` as an example:
![F041FFC7-FEDA-46C6-A02F-04CDBCDE1C49](https://user-images.githubusercontent.com/1444844/94451329-eace5b00-01b6-11eb-8883-ea7c932a433b.png)

### Additional context
Same version of Keka on macOS 10.14.6 works as expected.
`open ~/Downloads/some/` from Terminal also works fine – opens Finder with a focus on specified folder.

**Comment by aonez** [comment]
Thanks a lot for the feedback @dstd!

This is indeed improved as you suggest in the latest 1.2.0 betas, coming along Big Sur final release.

You can already try it if you want: https://beta.keka.io

**Comment by dstd** [comment]
o'god, finally it works as expected! thank you!
