### ISSUE TITLE
Large File, RAM Consumption

### ISSUE THREAD

**Issue by simondrummond** [aonez/Keka#651]
I received a large file from a vendor - 22.38GB. I was trying to use Keka, but after two hours and 69GB of RAM consumption I "Force Quit" the process. It was not hung, nor did it appear to finish the process.
It took the default Mac Unarchiver about 90 seconds to finish this file. Approx 95 files, generally two per directory. Nothing larger than 2.1 GB. The data files are maps and images for a Sat Nav application.
macOS Catalina 10.15.6
MB Pro 16, 2019
2.4 8-core i9
32 GB RAM
What other information can I provide to help debug this? OBV the file is a bit large to post here.

**Comment by aonez** [comment]
Thanks for all the feedback @simondrummond!

You can create a [debug session](https://github.com/aonez/Keka/wiki/Report-an-issue) and share with me the log file. Also knowing the maps and images format, if this is a ZIP file and where (what app) was used to compress the file would be ideal to try to replicate the issue.

If you don't have data caps and the file does not contain any confidential information maybe you can still share it with me using a sharing service. You can also send a link to info@keka.io.

**Comment by simondrummond** [comment]
Hello, not sure what happened. I have tried twice now and everything works just fine. OBV a problem on my end, so sorry to bother you.

Regards,
Simon

**Comment by aonez** [comment]
I'm closing this then, reopen if it happens again :)
