### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by slanceley** [aonez/Keka#657]
### Configuration
- Keka version:1.1.30 (3477)
- macOS version: 10.15.7 

### Describe the bug
When I try to compress a Final Cut Pro X Library file, i get this error message:
"The operation couldn't be completed. Undefined error: 0"

### To Reproduce
1. Right click on FCPX Library file eg "Video Edit.fcpbundle"
2. Select 'Compress "Video Edit.fcpbundle"'
3. See error

### Expected behavior
I expected Keka to begin compressing the file (These are often large files as they contain video footage, eg 40GB total size)

<img width="411" alt="Screenshot 2020-10-31 at 12 05 39" src="https://user-images.githubusercontent.com/73743906/97778885-4acb6f00-1b72-11eb-8eca-d3e0e9b9303f.png">

### Additional context
Keka is otherwise working fine, compressing and uncompressing files as expected.

**Comment by aonez** [comment]
That message is not form Keka but the bundled compressor of macOS. Drop the file to the Keka icon or interface and let me know how it goes.

Here you can see how to use Keka from the contextual menu:

https://github.com/aonez/Keka/wiki/Context-Menu

**Comment by slanceley** [comment]
Oh my god aonez... i wish i'd asked you sooner! Four days of trying resolved!

**Comment by aonez** [comment]
Hopefully this is a now it works 😅

**Comment by slanceley** [comment]
Yes, seems to be! Thank you
