### ISSUE TITLE
[BUG]  RAR set with an EXE: not deleting all parts post-extraction

### ISSUE THREAD

**Issue by Sophoria** [aonez/Keka#661]
### Configuration

- Keka version: 1.2
- macOS version: 10.15.7

### Describe the bug

When the option to trash extracted files is on and I extract a set of rar's with an exe as the first part, the exe will be properly trashed afterwards (file.part1.exe), but the remaining parts are not (file.part2.rar, file.part3.rar, etc.).

### To Reproduce

1. Enable 'move compressed files to trash after extraction'
2. Extract a rar set with an exe file as the first part
3. The exe file is trashed but not the remaining parts

### Expected behavior

I expected all remaining parts to go to the trash, as it would if I extracted a set of rar's without an exe (file.part1.rar).

Thanks for your assistance~

**Comment by aonez** [comment]
Fixed for 1.2.1!

**Comment by Sophoria** [comment]
Excellent work, thank you very much!
