### ISSUE TITLE
[REQ] Adding "send to Keka" command again

### ISSUE THREAD

**Issue by ddklysys** [aonez/Keka#664]
Keka V1.2.0 can only add two commands in the Finder menu, "Unzip with Keka" and "Compress with Keka". They are so close that the user need to move the cursor and click commands so carefully. I hope you can consider adding "send to Keka" command again, and let Keka decide whether to unzip or compress.Thank you！

**Comment by aonez** [comment]
Note that the new Finder Extension has the option "Open with Keka" that acts the same as "Send to Keka". This extension has far more options. Anyway I'm reading that "Send to Keka" service.

![Screenshot 2020-11-13 at 16 38 06](https://user-images.githubusercontent.com/480163/99090249-a8c67080-25ce-11eb-86fa-289f75ee1371.png)

**Comment by ddklysys** [comment]
thank you very much !
