### ISSUE TITLE
[BUG]The default format is not work when Keka is not open.

### ISSUE THREAD

**Issue by zhouweiluan** [aonez/Keka#676]
### Configuration
- Keka version: 1.2.3 (4223)
- macOS version: 11.0.1 (20B29)

### Describe the bug
I set the default format to ZIP in the preferences and 7z on the main interface of Keka. When I close Keka and compress the file, it will still be compressed into 7z format, not the default ZIP.
It seems that after closing Keka, the format set in the main interface is still used, not the default format in the preferences.
I remember it was normal in the version a long time ago.

我在偏好设置里把默认格式设置成 ZIP，在Keka主界面上设置成7z，在我关闭Keka后对文件进行压缩时，仍然会压缩成7z格式，并非默认设置的ZIP。
似乎关闭Keka后采用的仍然是主界面设置的格式，并非采用偏好设置里的默认格式。
我记得在好久之前的版本里是正常的。

Sorry, My English is not well, I use the Google translate.

### Screenshots
[屏幕录制2020-11-20 下午5.52.31.zip](https://github.com/aonez/Keka/files/5572716/2020-11-20.5.52.31.zip)

**Comment by aonez** [comment]
Thanks a lot for this one @zhouweiluan! Fixing it right away.
