### ISSUE TITLE
[BUG] Different filename if compress process was canceled.

### ISSUE THREAD

**Issue by psmanek** [aonez/Keka#677]
### Configuration
- Keka version: 1.2.3 (4223)
- macOS version: 10.15.7 (19H15)

### Describe the bug
If you interrupt the compression process, a number is added to the file name when you restart the copy process (without closing the application).

### To Reproduce
1. Compress
2. Cancel
3. Compress again

### Expected behavior
The file name should be the same as originally, if the file has not been saved (compression process complete)

**Comment by aonez** [comment]
Thanks a lot @psmanek! Fixing that one for the next revision 👍🏼
