### ISSUE TITLE
Font color doesn't change on selecting the options in Preferences->File Access 

### ISSUE THREAD

**Issue by hpycndl** [aonez/Keka#681]
### Configuration
- Keka version: [e.g. 1.2.3 (4223)]
- macOS version: [e.g. 11.0.1]

### Describe the bug
I use light mode theme for macos. On File Access tab in Preferences, the location options, when selected, doesn't change color. It gives poor visibility.

### To Reproduce
1. Go to 'Preferences', then 'File Access' tab
2. Click on any one of the locations in the list under _You can also customize the access below_
3. The font color doesn't change to white. Giving bad visibility.

### Expected behavior
The font color must change to white for dark background.

### Screenshots
<img width="490" alt="Screen Shot 2020-11-22 at 11 23 55 AM" src="https://user-images.githubusercontent.com/38640849/99909386-37fe1300-2cb6-11eb-981a-b033442b96bd.png">

**Comment by aonez** [comment]
Thanks @hpycndl for that catch! This color was fixed to `NSColor.textColor` that does not change with Light or Dark modes. Changed to `NSColor.controlTextColor` for next revision :)
