### ISSUE TITLE
Bug when creating your own toolbar in macOS Big Sur

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#685]
### Configuration
- Keka version: 1.2.3 (4223)
- macOS version: 11.0.1 (20B29)

### To Reproduce
1. Disable the checkbox: Use unified toolbar.
<img width="756" alt="0 ok" src="https://user-images.githubusercontent.com/62497891/99976477-c4d2ca80-2da3-11eb-8e6b-611b551e0d61.png">

2. Create my own toolbar.
<img width="616" alt="1 ok" src="https://user-images.githubusercontent.com/62497891/99976669-09f6fc80-2da4-11eb-98d4-fd5958069aa2.png">

3. To save, press the "Done" button.
<img width="616" alt="1 ok" src="https://user-images.githubusercontent.com/62497891/99977257-b0db9880-2da4-11eb-8f58-2f150106e164.png">

4. After rebooting, I see:
<img width="438" alt="2 not ok" src="https://user-images.githubusercontent.com/62497891/99977510-07e16d80-2da5-11eb-8640-af83d4d5430a.png">

### Expected behavior
Should be:
<img width="337" alt="Bildschirmfoto 2020-11-23 um 16 04 04" src="https://user-images.githubusercontent.com/62497891/99977929-948c2b80-2da5-11eb-809c-e7a84f4f5998.png">

**Comment by aonez** [comment]
Fixed for next revision! Thanks a lot @Oleg-Chashko!

**Comment by Oleg-Chashko** [comment]
I checked it works great! You can close the topic. Thank you.

**Comment by aonez** [comment]
Thanks again @Oleg-Chashko!
