### ISSUE TITLE
...Can not open the zip

### ISSUE THREAD

**Issue by babakm2** [aonez/Keka#69]
[it-comes-at-night_farsi_persian-1623094.zip](https://github.com/aonez/Keka/files/1271919/it-comes-at-night_farsi_persian-1623094.zip)
 I have many srt files that the ios Goodreader can unzip that, but Mac Keka not...

**Comment by aonez** [comment]
I've extracted the file `It Comes at Night (2017) BluRay.srt` without a problem...
