### ISSUE TITLE
Bug in toolbar on dark theme in macOS Big Sur

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#690]
**Configuration**

Keka version: 1.2.3 (4223)
macOS version: 11.0.1 (20B29)

On a dark theme in macOS Big Sur, Icon shades bug. I think you forgot to adapt the toolbar to macOS Big Sur.

**To Reproduce**
<img width="369" alt="Bildschirmfoto 2020-11-24 um 20 13 18" src="https://user-images.githubusercontent.com/62497891/100141462-c3cc9680-2e92-11eb-869f-c02e08535b77.png">

**Expected behavior**
Should be:
<img width="369" alt="Bildschirmfoto 2020-11-24 um 20 14 39" src="https://user-images.githubusercontent.com/62497891/100141477-c8914a80-2e92-11eb-9c58-0a8911b5091c.png">

**Comment by Oleg-Chashko** [comment]
The toolbar settings menu is also not adapted to macOS Big Sur.
<img width="371" alt="Bildschirmfoto 2020-11-24 um 20 31 41" src="https://user-images.githubusercontent.com/62497891/100142649-8b2dbc80-2e94-11eb-914d-0b3ea7865377.png">

**Comment by aonez** [comment]
I'm not sure I understand this one. The unified toolbar uses Big Sur style `NSWindowToolbarStyleUnified`.
> On a dark theme in macOS Big Sur, Icon shades bug. I think you forgot to adapt the toolbar to macOS Big Sur.

Also this one, the settings menu is default and automatically generated. I'm seeing the same one in Finder.
> The toolbar settings menu is also not adapted to macOS Big Sur.

Can you share screenshots of what you're seeing and screenshots of some other apps (macOS bundled if possible) that appears different?

**Comment by Oleg-Chashko** [comment]
I'm not sure I understand this one. The unified toolbar uses Big Sur style NSWindowToolbarStyleUnified.

_On a dark theme in macOS Big Sur, Icon shades bug. I think you forgot to adapt the toolbar to macOS Big Sur._

**Now such a problem with all icons.**

**Now icon shade:**
<img width="116" alt="Bildschirmfoto 2020-11-25 um 10 53 29" src="https://user-images.githubusercontent.com/62497891/100212237-66c1f680-2f0d-11eb-9d63-656d2095db95.png">
<img width="116" alt="Bildschirmfoto 2020-11-25 um 11 08 05" src="https://user-images.githubusercontent.com/62497891/100213102-84dc2680-2f0e-11eb-8c94-61c415e1d140.png">

**Should Icon shade be:**
<img width="116" alt="Bildschirmfoto 2020-11-25 um 10 54 31" src="https://user-images.githubusercontent.com/62497891/100211945-0d59c780-2f0d-11eb-8cfb-ebacc98cad6f.png">
<img width="116" alt="Bildschirmfoto 2020-11-25 um 11 06 02" src="https://user-images.githubusercontent.com/62497891/100212930-40e92180-2f0e-11eb-9b49-4a93ab8fdaed.png">

**Comment by Oleg-Chashko** [comment]
_The toolbar settings menu is also not adapted to macOS Big Sur._

Symbols and text - Not ok.
Symbols only - ok.
Only text - Not ok.
[Bildschirmaufnahme 2020-11-25 um 11.15.13.zip](https://github.com/aonez/Keka/files/5596008/Bildschirmaufnahme.2020-11-25.um.11.15.13.zip)

**Comment by aonez** [comment]
Right thanks!

> Now such a problem with all icons.

This one I'm facing since Mojave or Catalina. Not sure how to fix it, probably I should implement the format selector in another way.

About the toolbar menu is curios how it changed from Catalina:

![Screenshot 2020-11-25 at 11 43 28](https://user-images.githubusercontent.com/480163/100217179-73494d80-2f13-11eb-9a03-9d8db1390116.png)

**Comment by Oleg-Chashko** [comment]
Was glad to help!

**Comment by aonez** [comment]
Already added the proper labels to the buttons, this will come in 1.2.4. Only text will change to text and icon... Probably this can be fixed by not using custom views, that also may fix the icons color, but this is probably a more difficult fix, if possible.

![Screenshot 2020-11-25 at 12 07 15](https://user-images.githubusercontent.com/480163/100219831-c96bc000-2f16-11eb-9cfa-fa7c8fdc48d9.png)

**Comment by Oleg-Chashko** [comment]
@aonez 
_Configuration_
Keka version: 1.2.4
macOS version: 11.0.1 (20B29)

Symbols and text - ok.
Symbols only - ok.
Only text - Not ok.

When you select "text only" and click, it switches to "Symbols and text", strange behavior in my opinion.
Better to just remove the "text only".

[Bildschirmaufnahme 2020-11-26 um 11.54.06.zip](https://github.com/aonez/Keka/files/5602433/Bildschirmaufnahme.2020-11-26.um.11.54.06.zip)

**It could be done like this:**
<img width="429" alt="Bildschirmfoto 2020-11-26 um 12 04 15" src="https://user-images.githubusercontent.com/62497891/100343582-d56f8480-2fdf-11eb-97d2-25b16bcc08bb.png">

**Comment by aonez** [comment]
That is quick feedback @Oleg-Chashko! Thanks!!! Yep I've [told you here](https://github.com/aonez/Keka/issues/690#issuecomment-733640161):

> Only text will change to text and icon...

There's no way to change the options of that menu. I can get rid of it entirely but like this at least you have some customization right now.

The final fix for that only text option will be using a different object for the format selector.

**Comment by Oleg-Chashko** [comment]
@aonez 
Got it. Thanks for the quick response.

**Comment by aonez** [comment]
> P.S.: Weird why this only happens on macOS Big Sur dark theme?

The light issue in the icon also appears in Catalina (and I recall Mojave). Dark mode only indeed.

**Comment by Jax0rz** [comment]
I think this version is the best:

<img width="512" alt="icons_approved-1604884518665_Keka_Alt" src="https://user-images.githubusercontent.com/7557357/100357131-35d9e280-302f-11eb-8f2f-9321fc09ed51.png">

You can download it at this [link](https://storage.googleapis.com/download/storage/v1/b/macos-icons.appspot.com/o/icons_approved%2F1604884518665_Keka_Alt.icns?generation=1604884707182326&alt=media)

**Comment by microfx** [comment]
@aonez also everything is brown – could you please change that? It's not looking good... I wish it was blue like every other progress bar – brown is a sh*t*y color doesn't look right to me even after having seen it 200 times 

<img width="236" alt="Bildschirmfoto 2021-02-12 um 23 25 30" src="https://user-images.githubusercontent.com/37987212/107828685-a8827080-6d89-11eb-8ac9-93bc021f7077.png">

**Comment by aonez** [comment]
@microfx this is a feature in Big Sur, but I'm not happy with the result of it. I'll tweak or remove it in the next release.

You can also disable that feature in macOS Preferences, it is the "Rainbow" accent color:

![Screenshot 2021-02-13 at 18 41 53](https://user-images.githubusercontent.com/480163/107856821-26e31f00-6e2b-11eb-982b-e56e0eaf13c2.png)

**Comment by microfx** [comment]
Awesome! Thanks a lot!

**Comment by Oleg-Chashko** [comment]
Hopefully they will fix it in macOS updates. :)
Topic closed.

**Comment by aonez** [comment]
This one I'm not sure, maybe I can fix it. Leaving it open so I can check it in the future.

**Comment by Oleg-Chashko** [comment]
Ok.

**Comment by aonez** [comment]
I'm finally closing this one. As you can see the image color distortion is only applied in the toolbar. I'll fill a bug to Apple but I expect nothing to be made about it.

<img width="667" alt="Screenshot 2023-05-10 at 12 32 10" src="https://github.com/aonez/Keka/assets/480163/d982513c-179a-4f97-98f6-7cefecea70e2">
