### ISSUE TITLE
Update input fields to match Big Sur style

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#692]
Round the edges of input boxes.
Please, if possible.

<img width="371" alt="Bildschirmfoto 2020-11-24 um 20 50 33" src="https://user-images.githubusercontent.com/62497891/100145839-3c365600-2e99-11eb-9dfa-43ba28d02740.png">

<img width="758" alt="Bildschirmfoto 2020-11-24 um 20 55 10" src="https://user-images.githubusercontent.com/62497891/100145861-43f5fa80-2e99-11eb-9961-8b47ea123747.png">

**Example:**
<img width="556" alt="Bildschirmfoto 2020-11-24 um 21 30 53" src="https://user-images.githubusercontent.com/62497891/100147990-68070b00-2e9c-11eb-8691-d68e8f6aeca9.png">

**Comment by aonez** [comment]
Those are all standard objects, I'm not sure it's something I can do. I'll double check tomorrow.

**Comment by Oleg-Chashko** [comment]
> Those are all standard objects, I'm not sure it's something I can do. I'll double check tomorrow.

Thanks for the answer. If you can't delete the topic please.

**Comment by aonez** [comment]
Just double checked. Nothing I can do here. See for example the macOS Sharing settings, there you have text box and tables. Maybe in a Retina display appears different.

![Screenshot 2020-11-25 at 09 53 15](https://user-images.githubusercontent.com/480163/100204785-991b2600-2f04-11eb-942c-9ab7dcb87f5b.png)

**Comment by aonez** [comment]
Thanks anyway for the feedback @Oleg-Chashko! Maybe this one you should tell directly to Apple via the Feedback app.

**Comment by Oleg-Chashko** [comment]
Thank you, @aonez!
