### ISSUE TITLE
Return the English language back to "Split" instead of the Russian language.

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#694]
Please return the English language back to menu "Split" instead of the Russian language.
1. Since this is an unnecessary translation.
2. Since, the line does not fit completely.
3. Since, the information about the number of layers is not very important for the user.
4. Since some words or abbreviations are understandable.

**2. Since, the line does not fit completely.**
<img width="391" alt="Bildschirmfoto 2020-11-25 um 12 38 20" src="https://user-images.githubusercontent.com/62497891/100225926-3edb8e80-2f1f-11eb-9f11-6a9b7165dc55.png">

**It is now:**
<img width="738" alt="ru" src="https://user-images.githubusercontent.com/62497891/100226066-78ac9500-2f1f-11eb-8831-4b5c8cbe3b52.png">

**I would like to return the English language back completely:**
<img width="738" alt="en" src="https://user-images.githubusercontent.com/62497891/100226351-e8228480-2f1f-11eb-8eca-40fadab79537.png">

-------------------------------------------------------------------------------------------------------------------------
P.S.: **This is a joke**, you can translate everything, but you don't have to!
5.6 Гигабайтный Маленький Синий-Луч (2х слойный) -> 15.6 GB Mini Blu-ray (DL)

**Comment by aonez** [comment]
I obviously prefer the English one 2, 3 and for me 4 😂 but I imagine Russian speakers may prefer the Russian wording.

I'm curious what @NickKaramoff may think?

**Comment by Oleg-Chashko** [comment]
_I imagine Russian speakers may prefer the Russian wording._

@aonez 
I am Russian speaking, this is my native Russian language.
Nobody has translated that in Keck's app. I will not see it, I am using German.

**Comment by NickKaramoff** [comment]
Well, I see a lot of improvement but I am strictly against the word "Split" or its Cyrillic counterpart "Сплит"

We can rename presets and remove the layer information or reword the preference name to save on space.

"Split" is a Shyamalan movie, and what we deal  here with is a setting in an application that people will use. And each user should be able to use the app in their respective language, without loan words. I don't expect my mother to understand, what "сплит" means and I don't want to waste time explaining it to her when all that could be done is just a translation

I propose:

- remove layer information (and thus from every language really, because it's quite redundant and useless; size is the main metric
- replace "Разбить на тома" (split into volumes) with "Разбить архив" (split the archive) or simply "Разделить" (split)

**Comment by Oleg-Chashko** [comment]
> Well, I see a lot of improvement but I am strictly against the word "Split" or its Cyrillic counterpart "Сплит"
> 
> We can rename presets and remove the layer information or reword the preference name to save on space.
> 
> "Split" is a Shyamalan movie, and what we deal here with is a setting in an application that people will use. And each user should be able to use the app in their respective language, without loan words. I don't expect my mother to understand, what "сплит" means and I don't want to waste time explaining it to her when all that could be done is just a translation
> 
> I propose:
> 
> * remove layer information (and thus from every language really, because it's quite redundant and useless; size is the main metric
> * replace "Разбить на тома" (split into volumes) with "Разбить архив" (split the archive) or simply "Разделить" (split)

Привет @NickKaramoff 
Вопросов к переводу слова "Split" не было.
Разговор о том, чтобы вернуть Английский в меню "Split".

<img width="738" alt="100226351-e8228480-2f1f-11eb-8eca-40fadab79537" src="https://user-images.githubusercontent.com/62497891/100259001-fd130e00-2f47-11eb-9bf8-b66461e61104.png">

<img width="738" alt="100226066-78ac9500-2f1f-11eb-8831-4b5c8cbe3b52" src="https://user-images.githubusercontent.com/62497891/100258883-d81e9b00-2f47-11eb-9402-31e194f972cc.png">

**Comment by NickKaramoff** [comment]
Oh sorry for misunderstanding!

Then yes, I guess this was not the best idea 😅

**Comment by Oleg-Chashko** [comment]
Thank you for understanding!
Nothing bad, everything is good. :)

**Comment by aonez** [comment]
Since it seems you agree, I've reverted it.
