### ISSUE TITLE
In the toolbar, the selection fields for format icons slid down.

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#699]
In the toolbar, the selection fields for format icons have slid down. 
And should be in **the center**, icons have crawled out of their fields.

<img width="372" alt="Normal" src="https://user-images.githubusercontent.com/62497891/100350322-fdfc7c00-2fe9-11eb-9595-fc88044a8906.png">
<img width="1352" alt="Zoom" src="https://user-images.githubusercontent.com/62497891/100350338-048af380-2fea-11eb-925e-2ef651600ac1.png">

-------------------------------------------------------------------------------------------------------------------
<img width="373" alt="Bildschirmfoto 2020-11-26 um 13 45 35" src="https://user-images.githubusercontent.com/62497891/100352858-e626f700-2fed-11eb-8663-f24e443621b3.png">
<img width="1136" alt="Bildschirmfoto 2020-11-26 um 13 46 43" src="https://user-images.githubusercontent.com/62497891/100352878-ecb56e80-2fed-11eb-920d-272e629962c0.png">

------------------------------------------------------------------------------------------------------------------
_The rounding of the field corners disappears:_
<img width="1138" alt="Bildschirmfoto 2020-11-26 um 13 54 43" src="https://user-images.githubusercontent.com/62497891/100353787-5a15cf00-2fef-11eb-8d47-33a6c8464b79.png">

------------------------------------------------------------------------------------------------------------------
_It should be centered like this:_
<img width="1352" alt="Zoom" src="https://user-images.githubusercontent.com/62497891/100351515-d5758180-2feb-11eb-91c3-59445be25c94.png">

**Comment by aonez** [comment]
You're very right! Probably I need to resize the icons a little for Big Sur.

**Comment by aonez** [comment]
I'll need to create new icons with more alpha space at the top, resize is not an option.

**Comment by Oleg-Chashko** [comment]
> I'll need to create new icons with more alpha space at the top, resize is not an option.

Can also decrease alpha space at the sides?
Toolbar Improvements: Reducing the gaps between icons. #728

**Comment by Oleg-Chashko** [comment]
Maybe remove the labels at the bottom of the icons and embed their icons to reduce the vertical size?
**For Example:**

<img width="636" alt="2021-01-06_17-21-22" src="https://user-images.githubusercontent.com/62497891/103792498-ff3ab300-5043-11eb-97b0-0bbad1073f5a.png">

[Archive.zip](https://github.com/aonez/Keka/files/5776861/Archive.zip)

**Comment by Oleg-Chashko** [comment]
Checked, the icons is displayed ok.

- Keka v.1.2.50 (4808)
- macOS v.12.0.1 (21A559)

Topic closed. Thank you.

<img width="336" alt="Screen Shot 2021-11-25 at 16 49 45" src="https://user-images.githubusercontent.com/62497891/143471827-2f1072f5-d4b1-46ce-a3db-67f7aeceabfe.png">
<img width="336" alt="Screen Shot 2021-11-25 at 16 47 39" src="https://user-images.githubusercontent.com/62497891/143471840-e9d63a9f-62c7-4f50-bf79-0a507cb14491.png">

**Comment by aonez** [comment]
Most probably like #717 was fixed with a macOS update. Glad to hear that :)
