### ISSUE TITLE
UI Checkbox off-center, raised to the top.

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#700]
UI Checkbox off-center, raised to the top.
<img width="616" alt="Zoom" src="https://user-images.githubusercontent.com/62497891/100357126-86801a00-2ff4-11eb-87cc-1cc07f61bbdf.png">
<img width="727" alt="Bildschirmfoto 2020-11-26 um 14 04 42" src="https://user-images.githubusercontent.com/62497891/100357135-8bdd6480-2ff4-11eb-9ace-ea32f22eff95.png">
<img width="727" alt="Bildschirmfoto 2020-11-26 um 14 06 56" src="https://user-images.githubusercontent.com/62497891/100357146-90a21880-2ff4-11eb-877b-8247becdb73e.png">

**Comment by aonez** [comment]
This is a system UI and you probably should report it to Apple via the Feedback app 😉

**Comment by Oleg-Chashko** [comment]
> This is a system UI and you probably should report it to Apple via the Feedback app 😉

@aonez 
Will you tell them?
A rare function not many people use. (Small characters)
Can you remove this setting from the user interface?

<img width="727" alt="Bildschirmfoto 2020-11-26 um 17 30 57" src="https://user-images.githubusercontent.com/62497891/100375461-1bdbd800-300e-11eb-9d34-a30ccc437f0f.png">
