### ISSUE TITLE
Doesn't open of the User Preferences menu.

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#705]
### Configuration
- Keka version: 1.2.4 (4287)
- macOS **bug** Sur version: 11.0.1 (20B29)

Stopped opening of the User Preferences menu.
The settings menu opens only 2 times, it can no longer be opened 3 times.
The video file is attached.
[Bildschirmaufnahme 2020-11-28 um 08.40.28.mp4.zip](https://github.com/aonez/Keka/files/5610237/Bildschirmaufnahme.2020-11-28.um.08.40.28.mp4.zip)

**Comment by aonez** [comment]
Thanks @Oleg-Chashko! I've found this issue before but did not had the time to fix it. It was about removing the love button in the WEB versión, the third time the preferences is opened it crashes to load de NIB file (interface).

**Comment by aonez** [comment]
Fixed in this build: [Keka-v1.2.5-r4304](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.5-r4304.7z)

Next release will have this fixed as well.

**Comment by Oleg-Chashko** [comment]
@aonez 
I checked everything works fine! The topic can be closed. Thank you.
