### ISSUE TITLE
[BUG] Keep source extension

### ISSUE THREAD

**Issue by ddklysys** [aonez/Keka#706]
Keka have added option in the preferences which removes the file extension from the archive name.

eg: test.jpg -> test.zip

but this option doesn't work anymore in the version 1.24？

**Comment by aonez** [comment]
Thanks a lot for the tip @ddklysys! Fixing that one!

**Comment by ddklysys** [comment]
thx~

**Comment by aonez** [comment]
Fixed in this build: [Keka-v1.2.5-r4304](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.5-r4304.7z)

Next release will have this fixed as well.
