### ISSUE TITLE
UI: Button "OK" and "X" is not symmetrical to the password input field.

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#708]
### Configuration
- Keka version: 1.2.4 (4287)
- macOS version: 11.0.1 (20B29)

Button "OK" and "X" is not symmetrical to the password input field.

![Bildschirmfoto 2020-11-29 um 14 50 21](https://user-images.githubusercontent.com/62497891/100545102-79fcfb00-325a-11eb-817f-dc83cfe4d270.png)

**Comment by aonez** [comment]
In no-retina resolution is as centered as it can be... I'll check in the iPad the retina resolution 😅

![Screenshot 2020-11-30 at 09 36 01](https://user-images.githubusercontent.com/480163/100586442-77001a00-32ef-11eb-9ad3-97e233576cbf.png)

**Comment by aonez** [comment]
I don't see it like this either in retina (iPad, at least)

![Screenshot 2020-11-30 at 09 48 27](https://user-images.githubusercontent.com/480163/100587750-4620e480-32f1-11eb-9320-9a926d2e2364.png)

But I suppose this is a result of the Bug Sur change in the UI.

**Comment by Oleg-Chashko** [comment]
@aonez 
For the experiment I switched the scaling, the result is negative. The buttons are displaced.
Do you have "macOS bug Sur" installed?

<img width="758" alt="Ohne Titel" src="https://user-images.githubusercontent.com/62497891/100589412-5cc83b00-32f3-11eb-81cd-c1fe190ca9e2.png">

**Comment by aonez** [comment]
I have Bug Sur in a VM only, but is enough for now:

![Untitled gif](https://user-images.githubusercontent.com/480163/100589489-76698280-32f3-11eb-9fa5-7f84eea08c0b.gif)

I'll have to double check this one. It seems the text field is shorter in height but it is strange because this input is vertically placed with a top constraint, not a bottom one. Also the icon is affected 😕

**Comment by gingerbeardman** [comment]
I saw this in latest beta for Affinity Designer:

> - Fix for a UI issue in Big Sur (the vertical positioning of some checkboxes)

So I think it's definitely a Big Sur thing.

**Comment by aonez** [comment]
This will be fixed in 1.2.7 😊

**Comment by Oleg-Chashko** [comment]
Hi, @aonez 
Happy New year to you.
Good news, when is the release v.1.2.7?

**Comment by aonez** [comment]
Happy new year to you to Oleg! Most probably this Thursday.

**Comment by aonez** [comment]
1.2.7 published! Thanks @Oleg-Chashko!

**Comment by Oleg-Chashko** [comment]
@aonez 
Keka v1.2.7
Button "OK" and "X" is not symmetrical to the password input field.
<img width="938" alt="Screenshot 2021-01-13 at 20 55 21" src="https://user-images.githubusercontent.com/62497891/104503969-13e9ee80-55e2-11eb-8450-ed4543b66181.png">
