### ISSUE TITLE
[BUG] Progress bar colour

### ISSUE THREAD

**Issue by idleberg** [aonez/Keka#710]
### Configuration
- Keka version: 1.2.4 (4287)
- macOS version: 10.14.6 (18G6032)

### Describe the bug
I've noticed a minor detail regarding Keka's progress bar. By default, macOS uses the accent colour specified in the General settings for its progress bars. Keka, however, uses a green one.

### To Reproduce
1. Go to 'System Preferences' and change the *Accent colour* in the *General* settings to anything but green
2. Compress a file using Keka
3. Take notice of the progress bar colour

### Expected behavior
I'd expect the user preferences to be respected

### Screenshots

![image](https://user-images.githubusercontent.com/1504938/100721073-28ba4c00-33bf-11eb-93df-9b180a154ab3.png)

Accent colour is red, progress bar is green

**Comment by aonez** [comment]
Thanks for that one @idleberg, had a friend commenting me about those colours but was unsure how he got them.

Keka 1.2.0 uses custom colours for known formats but it seems it only shows the correct colour when the accent colour is set to blue. If you create an ISO/DMG you'll see your accent colour.

I'll see what can I do with that.

**Comment by aonez** [comment]
Keka will only use custom color when blue accent color is selected. Here a build with that fixed: [Keka-v1.2.5-r4305](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.5-r4305.7z)
