### ISSUE TITLE
Encryption does not work as advertised

### ISSUE THREAD

**Issue by dkanze** [aonez/Keka#711]
I purchased this software as the keka site suggested it would encrypt 7z files using AES256 bit.  It does not.  I would like a refund.

Thanks
Dan

**Comment by aonez** [comment]
Hi @dkanze! You can ask for a refund [through Apple](https://support.apple.com/en-us/HT204084).

Keka does indeed encrypt 7Z files using AES256, not sure why you say it does not. Simply set a password a compress some files.

Let me know if you need some assistance, I will gladly help :)

**Comment by Oleg-Chashko** [comment]
Hi @aonez 
I think he concluded that in the "ZIP" window there is an "AES-256" encryption check-box, and in the "7.ZIP" window there is no "AES-256" encryption check-box.
<img width="441" alt="ZIP" src="https://user-images.githubusercontent.com/62497891/100876367-95107a80-34a7-11eb-812a-8a20b2ef8dde.png">
Maybe create the ability to enable and disable AES-256 encryption in "7.ZIP"?
<img width="441" alt="7zip" src="https://user-images.githubusercontent.com/62497891/100876391-9f327900-34a7-11eb-81c7-692a2bd412e4.png">

**Comment by dkanze** [comment]
Here is what I found.  I was selecting 7z and entering the password then closing the dialog.  I then dropped a file onto the icon and it only compressed the file.  I thought it would encrypt the file.  To encrypt the file I had to leave the dialog window open then, drag the file onto it to get encrypted output.

I am new to MacOS and only used PKWARE-SecureZip in the past which has a different workflow.  SecureZip lets you zip a file by dropping a file on the icon then you can choose to encrypt it.

So now that I understand how keka works, I am ok.

Thank you all for your help.
Dan

**Comment by aonez** [comment]
Glad to hear that Dan! Let me know if you need anything else and enjoy your macOS travel :)

**Comment by aonez** [comment]
@Oleg-Chashko 7Z is always encrypted using 256 so there's no point adding the checkbox. In fact as ZIP with AES256 becomes more and more common (already supported in Big Sur) it will be used by default and that checkbox description will change to something like "Use legacy encryption". Thanks for your feedback as always!

**Comment by Oleg-Chashko** [comment]
I'm glad everything is fine. 
Maybe a little instruction when you first start the application how to use Keka?
It will probably be useful for beginners. With the ability to turn it off for "oldies" in macOS.

**Comment by aonez** [comment]
@Oleg-Chashko the idea is there #562... but usually other things go before that window.
