### ISSUE TITLE
UI bug - When customizing the toolbar

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#717]
### Configuration
- Keka version: 1.2.5 (4333)
- macOS version: 11.0.1 (20B29)

When customizing the toolbar, if you click on the icon, it will move to the right side as a ghostly copy.

<img width="832" alt="Untitled" src="https://user-images.githubusercontent.com/62497891/101778861-bf3fe900-3af4-11eb-8345-1e84b11b974b.png">

[Screen Recording 2020-12-10 at 14.18.47.mov.zip](https://github.com/aonez/Keka/files/5673053/Screen.Recording.2020-12-10.at.14.18.47.mov.zip)

**Comment by aonez** [comment]
This was most probably an issue within macOS. Happy it's solved now :)
