### ISSUE TITLE
[BUG] Keka doesn't delete .r01, r02, etc files after extraction

### ISSUE THREAD

**Issue by realdannys** [aonez/Keka#719]
### Configuration
- Keka version: Version 1.2.5 (4333)
- macOS version: 11.0.1 (20B29)

### Describe the bug
When extracting a multi RAR that is labelled .rar, then .r00, r01, r02 with "moved compressed files to bin after extraction" turned on - the files extract fine but Keka only deletes the .rar file leaving you delete the .r00, .r01, .r02 etc yourself.

### To Reproduce
Extract a RAR file split into the behaviour shown above.

### Expected behavior
Keka should delete all files in the extract archive after extraction.

Here's a video:

[https://vimeo.com/489463664](https://vimeo.com/489463664)

### Additional context
This has happened since I first started using Keka years ago.

**Comment by aonez** [comment]
Thanks again @realdannys!

Working on v1.2.0 but a regression was made probably fixing "Fixed issue when opening SFX-RAR volumes". Fixing for next revision!

**Comment by aonez** [comment]
Fixed in this build: [Keka-v1.2.6-r4342.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.6-r4342.7z)

You can wait for the final release (probably next week) or use that build 😊
