### ISSUE TITLE
[BUG] Unable to modify Keka's toolbar

### ISSUE THREAD

**Issue by whitebear60** [aonez/Keka#720]
### Configuration
- Keka version: 1.2.4 (4287)
- macOS version: 10.10 (14A389)

### Describe the bug
When I try to drag the format to the toolbar it doesn't drag. Log: 
[Keka_2020-12-10-200529556.log](https://github.com/aonez/Keka/files/5674793/Keka_2020-12-10-200529556.log)

### To Reproduce
1. Rightclick the toolbar (with the archive type changing buttons)
2. Click "Customise Toolbar"
3. Try to drag any tool into toolbar

### My system
![My system](https://user-images.githubusercontent.com/42472132/101812099-9aaf3580-3b23-11eb-92df-125bc37f9466.png)

**Comment by aonez** [comment]
@whitebear60 this should be fixed in the latest v1.2.5. Can you update to this version and let me know if it works for you?

**Comment by aonez** [comment]
I'm not able to reproduce your issue. You meant with the old toolbar style, right? Anyway try first with 1.2.5 and let me know.

![Screenshot 2020-12-11 at 10 56 59](https://user-images.githubusercontent.com/480163/101889358-99bbe980-3b9f-11eb-8e46-621ada679c9e.png)

**Comment by whitebear60** [comment]
fixed, thanks
