### ISSUE TITLE
Crash after applying "KekaDefaultApp-1.0.2r8"

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#721]
### Configuration
- Keka version: 1.2.5 (4333)
- macOS version: 11.0.1 (20B29)

[crash.zip](https://github.com/aonez/Keka/files/5675720/crash.zip)
[Screen Recording 2020-12-10 at 22.22.46.mov.zip](https://github.com/aonez/Keka/files/5675722/Screen.Recording.2020-12-10.at.22.22.46.mov.zip)
[KekaDefaultApp-1.0.2r8.zip](https://github.com/aonez/Keka/files/5675723/KekaDefaultApp-1.0.2r8.zip)

**Comment by aonez** [comment]
Bad pointer there! Thanks for the tip @Oleg-Chashko 😉

**Comment by aonez** [comment]
Fixed in this build: [Keka-v1.2.6-r4342.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.6-r4342.7z)

**Comment by Oleg-Chashko** [comment]
@aonez 
Thank you, I checked everything ok.
