### ISSUE TITLE
[BUG] Bad TAR structure since 1.1.15

### ISSUE THREAD

**Issue by naugad** [aonez/Keka#722]
### Configuration
- Keka version: [e.g. 1.2.5 (4333)]
- macOS version: [e.g. 10.15.7 (19H15)]

### Describe the bug
Bug in all new versions with TAR. In version 1.0.7 (1705), TAR works fine. Watch the [video](https://www.screencast.com/t/w3aCARzVLzq9) to understand what this is about. I hope for the earliest possible correction of this error, as I have to use an outdated version of the program.

**Comment by aonez** [comment]
@naugad can you paste the text that the web shows? I don't understand Russian but can translate it if you share the text.

**Comment by aonez** [comment]
Issue introduced by fixing #404.

**Comment by aonez** [comment]
Should be fixed here: [Keka-v1.2.6-r4342.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.6-r4342.7z)

**Comment by naugad** [comment]
Thanks for the prompt solution to the problem. Yes, the hosting provider is currently experiencing a failure, but I checked it in my local environment and it works.
