### ISSUE TITLE
Crash "KekaFinderIntegration" after adding a network drive.

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#724]
### Configuration
- Keka version: 1.2.6 (4342)
- macOS version: 11.0.1 (20B29)

Crash "KekaFinderIntegration" after adding a network drive. Accordingly, the integration in the menu disappears.

<img width="827" alt="Untitled" src="https://user-images.githubusercontent.com/62497891/101916709-9b010c80-3bc7-11eb-997e-2ea89fe37f20.png">

**Crash logs:**
[_KekaFinderIntegration_MacBook-Pro.crash_.zip](https://github.com/aonez/Keka/files/5679747/_KekaFinderIntegration_MacBook-Pro.crash_.zip)

**Comment by Oleg-Chashko** [comment]
@aonez 
These Crash seem to be related to Keka.
But I did not see how it happened and whether they are related exactly to this problem.

[_hdiutil_2020-12-11-161422_MacBook-Pro.crash_.zip](https://github.com/aonez/Keka/files/5680314/_hdiutil_2020-12-11-161422_MacBook-Pro.crash_.zip)

**Comment by aonez** [comment]
Still looking for the first crash.

> These Crash seem to be related to Keka.
> But I did not see how it happened and whether they are related exactly to this problem.

You've created a DMG or ISO with Keka?

**Comment by Oleg-Chashko** [comment]
> Still looking for the first crash.
> 
> > These Crash seem to be related to Keka.
> > But I did not see how it happened and whether they are related exactly to this problem.
> 
> You've created a DMG or ISO with Keka?

Yes, I create DMG, I am now trying to find how I did it. To catch a crash.

**Comment by Oleg-Chashko** [comment]
Yes, if you create DMG and ISO. And if the object of compression does not have its own folder, a crash occurs with the creation of a log.

<img width="405" alt="Gping" src="https://user-images.githubusercontent.com/62497891/101930736-d526da00-3bd8-11eb-9a40-1e04a848b829.png">
<img width="405" alt="3" src="https://user-images.githubusercontent.com/62497891/101930749-d9eb8e00-3bd8-11eb-85b4-a18957609b81.png">

**Comment by aonez** [comment]
Totally different bug but I've checked that you can call a compression from the contextual menu with a non folder. ISO and DMG only accept folders. I'll fix that one too.

**Comment by Oleg-Chashko** [comment]
> Totally different bug but I've checked that you can call a compression from the contextual menu with a non folder. ISO and DMG only accept folders. I'll fix that one too.

I was glad to help.

**Comment by aonez** [comment]
@Oleg-Chashko booth fixed here: [Keka-v1.2.6-r4348.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.6-r4348.7z)

You may need to kill `KekaFinderIntegration` or remove older versions of Keka to be sure the latest version is running.

**Comment by Oleg-Chashko** [comment]
Great works, checked, the topic can be closed.
