### ISSUE TITLE
Toolbar Improvements: Reducing the gaps between icons.

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#728]
Reduce the gaps between icons. And rationally use the free space to fit more icons.

**Currently:**
<img width="404" alt="Screenshot 2020-12-12 at 14 40 22" src="https://user-images.githubusercontent.com/62497891/101987423-45defc80-3c94-11eb-8246-040cf336d661.png">

**For example:**
<img width="448" alt="Screenshot 2020-12-12 at 15 48 52" src="https://user-images.githubusercontent.com/62497891/101987495-a9692a00-3c94-11eb-837b-b38116b05c70.png">

**Comment by aonez** [comment]
Sadly this is the design in Big Sur, nothing I can do in Keka.

**Comment by Oleg-Chashko** [comment]
@aonez 
Please look, here in this application the limitation was somehow bypassed ("Lines", "Grid").
Could it be that they made changing the width dynamically changeable?
![Screen Recording 2021-01-06 at 15 22 15](https://user-images.githubusercontent.com/62497891/103779060-7d428e00-5033-11eb-83ce-104b29227bfb.gif)

**Comment by aonez** [comment]
Can you let me know which app is that one? I did some tests with different sizes and margins and the result is always the same. For example, I've tried with a 24 pixels with padding inside icon, and you can see the result with and without labels:

![Screenshot 2021-01-07 at 15 15 30](https://user-images.githubusercontent.com/480163/103902784-4cc62700-50fb-11eb-8650-df81a1a64c39.png)
![Screenshot 2021-01-07 at 15 15 21](https://user-images.githubusercontent.com/480163/103902783-4c2d9080-50fb-11eb-8f92-4757622b3718.png)

Seeing this results, and knowing that the legacy toolbar (not unified) is not used by most of the users (even if I love it), I might be just use `NSWindowToolbarStylePreference` style instead the currently used (more appropriate but buggy) `NSWindowToolbarStyleExpanded`, at least the icons do not overflow:

![Screenshot 2021-01-07 at 15 14 27](https://user-images.githubusercontent.com/480163/103902609-0ec90300-50fb-11eb-9876-c6b6bf611009.png)

**Comment by aonez** [comment]
Another example, this one has icons with no extra space on left-right. See, the padding is exactly the same:

![Screenshot 2021-01-07 at 15 23 20](https://user-images.githubusercontent.com/480163/103903517-484e3e00-50fc-11eb-8db8-e6a1860cf04c.png)

Clearly in Big Sur that type of toolbar is deprecated.

**Comment by Oleg-Chashko** [comment]
Can you let me know which app is that one?

**Red Lines Tools**
https://red-lines-tools.web.app

P.S.: If you can't do it, then don't do it. These are just my wishlist. Thanks for trying. :)

**Comment by aonez** [comment]
Just checked that one. The thing here is that Red Lines Tools is not updated for Big Sur (11.0 SDK). You can check [Keka 1.1.30](https://legacy.keka.io/mavericks) that was not built with Big Sur support neither and the toolbar is rendered like in Catalina.
