### ISSUE TITLE
Update the download link on the website to the new version of "Keka helper"

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#729]
Update the link on the site, to the new version of "Keka helper"

**Old version:** Download the helper: KekaDefaultApp.v1.0.1-r.7
https://github.com/aonez/Keka/wiki/Default-application

<img width="643" alt="Set Keka as the default application" src="https://user-images.githubusercontent.com/62497891/101991831-88620280-3caf-11eb-8709-956c4a0fdafd.png">

--------------------------------------------------------------------------------------------------------

**New version:** Download the helper: KekaDefaultApp.v1.0.2-r.8
https://www.keka.io/en/

<img width="702" alt="Set Keka as the default extraction application" src="https://user-images.githubusercontent.com/62497891/101991835-9021a700-3caf-11eb-9e9a-d2f88afeb589.png">

P.S.: Sorry for the off-topic. Question: why didn't you build "Keka helper" into the Keka app?
If it's better for the user to embed, it's easier. Basically, the user will not bother with this: (download "unknown what", unzip, install).

**Comment by aonez** [comment]
Thanks for the tip @Oleg-Chashko!

This is needed because:

> Due some limitations in sandboxing Keka can't register itself as the default application without some help. It was discovered here #209.

A sandboxed app cannot register as a default application. The helper is not sandboxed.

**Comment by aonez** [comment]
Fixed in https://github.com/aonez/Keka/wiki/Default-application/ba4e4fad21df78ffac1e97b92b12c5b2b693953f
