### ISSUE TITLE
Add GUI option  to disable notifications

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#73]
Currently, you can disable them via Terminal (or in the [System Preferences...](https://support.apple.com/kb/PH25743?locale=en_US)):

`defaults write com.aone.Keka UseGrowl false`

Made [some wiki](https://github.com/aonez/Keka/wiki/Hidden-configuration#notifications) about this...

**Comment by KoolSafak** [comment]
Great idea!

**Comment by aonez** [comment]
Added in revision 2303
