### ISSUE TITLE
Compress and save to a chosen directory

### ISSUE THREAD

**Issue by RVDIOactive** [aonez/Keka#738]
### Is your feature request related to a problem?
I always have to compress the items and then copy the zip file to the directory I want. This takes so long.

### Describe the solution you'd like
Compress the items and save to a directory I choose.

### Describe alternatives you've considered
Right now, I compress the items, and the copy the compressed file to a new directory.

**Comment by aonez** [comment]
Hi @RVDIOactive!

You can set Keka to always ask where to compress (also for extraction) in the Keka Preferences:

![Screenshot 2020-12-22 at 09 41 14](https://user-images.githubusercontent.com/480163/102868122-13729380-443a-11eb-9c75-632fb21e9eb6.png)

Also you can use the Finder Extension menu "Compress to..." item that will also ask where to compress the file:

![Screenshot 2020-12-22 at 09 41 35](https://user-images.githubusercontent.com/480163/102868181-284f2700-443a-11eb-9fd1-129a62f40475.png)

Are those working for you?

**Comment by aonez** [comment]
Please reopen if you still have this issue.
