### ISSUE TITLE
Split doesn't appear to work

### ISSUE THREAD

**Issue by akrabu** [aonez/Keka#740]
Hello!  I just updated to 1.2.6 this morning.  I was trying to make a split XZ file in the terminal and then wondered how Keka did it, and if using ` xz -e9vfc < yourFile.vdi | split -b 1024m - yourFile.vdi.xz` would be compatible with Keka for decompressing.

So, I took a 10MB file and told Keka to use Xz on "fast" and picked the 1.4MB Floppy option...... and it made a single 6MB xz file instead.  I tried putting in 1MB, 1M, 1m - nothing worked.  Just a heads up!

**Comment by aonez** [comment]
@akrabu it only works when using one source file. If you drop multiple files or a folder it will tarball and not split. It uses `p7zip` with one source file.

I should improve that behaviour...

**Comment by akrabu** [comment]
Hmm funny enough, I was using a single 10MB file when I tried the 1.44MB floppy option, though!

**Comment by aonez** [comment]
Sorry @akrabu forgot about this one! If you want the split to work with only compression formats be sure you have `Always tarball non-archiving formats (like GZ...)` deactivated in Keka's Compression Preferences. Works that way, right?

I surely need to improve the split workflow and UI for only compression formats...

**Comment by omata** [comment]
Hello,

I tried the mentioned workflow by @aonez and I found that **lzip** just doesn't split the files, even if I disable the tar option. So does **lzip** is compatible with split or not?

Regards,
- Oscar

**Comment by aonez** [comment]
@omata you're right. Turns out `PLZIP` (multithreaded) is not compatible with splitting. You can disable it and use single thread `LZIP` instead using:

```
defaults write com.aone.keka UseMultithreadLzip false
```

Remember to restart Keka. This will have a performance impact obviously.

Strange nobody found that, it's being there since mid 2018.

**Comment by aonez** [comment]
This build should have this fixed: [Keka-v1.2.62.r5159](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.62.r5159.7z)
