### ISSUE TITLE
.tar.gz files take two steps to decompress, gz to tar, tar to file contents

### ISSUE THREAD

**Issue by vlape** [aonez/Keka#741]
### Configuration
- Keka version: 1.2.6 (4371)
- macOS version: 11.1 (20C69)

### Describe the bug
Decompressing tar.gz files requires decompressing twice. Once for the .gz, which generated the .tar and again for the .tar to decompress contents

### To Reproduce
extracting any tar.gz file either directly dragging file to Keka app or using context menu

### Expected behavior
expected to fully decompress file, both .gz and .tar

### Screenshots
N/A

### Additional context
N/A
[Keka_2020-12-23-105357216.log](https://github.com/aonez/Keka/files/5736330/Keka_2020-12-23-105357216.log)

**Comment by aonez** [comment]
Can you try with this build:

https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.7-r4381.7z

**Comment by aonez** [comment]
If you create a tarball with Keka and then extract it you also get this result?

**Comment by akrabu** [comment]
I came to report the inverse - thought it might be related, so jumping in on this thread.  When dragging a tar to Keka to be compressed, it tries to tarball the tarball.

![Screen Shot 2020-12-23 at 3 44 44 PM](https://user-images.githubusercontent.com/6868732/103044553-c83dab00-4535-11eb-84f4-548e12258ab2.png)

**Comment by vlape** [comment]
> Can you try with this build:
> 
> https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.7-r4381.7z

This worked

**Comment by gxgani** [comment]
This is started occurring with Version 1.2.54 (4983). The tar balls are generated from openWrt archive functionality.
