### ISSUE TITLE
Want does KekaExternalHelper do? Where should it be installed?

### ISSUE THREAD

**Issue by tjluoma** [aonez/Keka#745]
I can't find any documentation on KekaExternalHelper.

**Comment by aonez** [comment]
There you have it:

https://github.com/aonez/Keka/wiki/Default-application

**Comment by tjluoma** [comment]
I made an edit to that page and added this line:

> Note that "KekaDefaultApp.app" and "KekaExternalHelper.app" are two names for the same program.

so that, in the future, if people search for `KekaExternalHelper` they will hopefully find that page.

**Comment by aonez** [comment]
Thanks a lot @tjluoma, I really forgot to edit the documentation. I’ve moved that info to this section:
https://github.com/aonez/Keka/wiki/Default-application#about-the-helper

In fact, the new version has another utility, it removes the Keka quarantine flag from newly compressed files, that’s why I’ve changed the name. I need to add that feature to extractions before it’s really useful: #405 

Also it should work in the future to communicate with the `RAR` Binary to compress in that format, so really the name change was needed.
