### ISSUE TITLE
[BUG] Error code 2 using "p7zip" Fatal error 

### ISSUE THREAD

**Issue by CupOfDepresso** [aonez/Keka#748]
### Configuration
- Keka version: [e.g. 1.1.24 (3421)]
- macOS version: [e.g. 10.14.6 (18G2022)]

### Describe the bug
Extraction of "[filename].zip" failed
 Error code 2 using "p7zip" Fatal error

### To Reproduce
1. Go to file in downloads
2. Click on file and select open with Keka
3. Starts file extraction
4. Immediately fails extraction and produces error code:  Error code 2 using "p7zip" Fatal error

### Expected behavior
It would extract the file like it normally would

### Screenshots
![Screenshot 2021-01-06 at 14 54 18](https://user-images.githubusercontent.com/77057516/103770944-83367000-502f-11eb-9f09-947d79b891a0.png)

### Additional context
This is happening to 3 files I have and they aren't even said to be 7z files

**Comment by CupOfDepresso** [comment]
Hello, I have tried deleting Keka and re-downloading but it still kept doing the same thing

**Comment by aonez** [comment]
Can you click on the warning icon and share the error log?

**Comment by CupOfDepresso** [comment]
I copied it but it has some of my personal details such as my name and other things, should I rather take a screenshot and cover it up or is there an alternative?

**Comment by CupOfDepresso** [comment]
ERROR: /Users/[my username]/Desktop/female finds#1.zip
/Users/[my username]/Desktop/female finds#1.zip
Open ERROR: Can not open the file as [zip] archive


ERRORS:
Is not archive

1 file, 6529 bytes (7 KiB)

Extracting archive: /Users/[my username]/Desktop/female finds#1.zip

  0%

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

Error code 2

**Comment by CupOfDepresso** [comment]
I was able to remove it, the file is Sims 4 female clothing custom content (explanation for the sus name)

**Comment by aonez** [comment]
It seems the file is not an archive, probably you should download it again. Maybe send me the link of the download to info@keka.io so I can test.

**Comment by CupOfDepresso** [comment]
Ok, I'll try to find it

**Comment by aonez** [comment]
It seems the file is not an archive, probably you should download it again.
Maybe send me the link of the download to info@keka.io so I can test.

**Comment by CupOfDepresso** [comment]
I just sent it, with a different email, but I will also send it on the one I'm signed in with at the moment

**Comment by CupOfDepresso** [comment]
I just re-downloaded them for the 5th time, at first they failed again but I tried again and it worked, not sure what happened but thanks!

**Comment by aonez** [comment]
Downloaded all parts and extracted without issue. Probably your download was being corrupted somehow. Salut!
