### ISSUE TITLE
Crashes with password-protected .zip, .7zip files

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#754]
### Configuration
- Keka version: 1.2.7 (4394)
- macOS version: 11.1 (20C69)

### Crashes
- ["keka7z_2021-01-13-223003_MacBook-Pro.crash".zip](https://github.com/aonez/Keka/files/5813473/keka7z_2021-01-13-223003_MacBook-Pro.crash.zip)

### Screen Recording

https://user-images.githubusercontent.com/62497891/104571473-6adbdc00-5653-11eb-817c-ce271a6b49f4.mov

### Test file
- [Frame Diagram.pdf.zip](https://github.com/aonez/Keka/files/5813501/Frame.Diagram.pdf.zip)

**Comment by aonez** [comment]
Thanks for this one Oleg! Fixing in 1.2.8.

Fixed patch for `p7zip`: [17-tty-128+-pass-lenght.patch.zip](https://github.com/aonez/Keka/files/5814566/17-tty-128%2B-pass-lenght.patch.zip)

**Comment by Oleg-Chashko** [comment]
I want to ask when version 1.2.8 beta will be, as there are 2 bugs which I have not published yet.
And they may be related to #754.

**Comment by aonez** [comment]
No timeline yet, probably in a week or two. Usually it depends on the severity of the possible bugs that need to be fixed.

**Comment by aonez** [comment]
Ah sorry! You meant a beta!

**Comment by Oleg-Chashko** [comment]
> Ah sorry! You meant a beta!

I would not like these 2 errors in the release. Because of this, I ask for a beta with corrected error # 754.

**Comment by aonez** [comment]
Sure! There you have it: [Keka-v1.2.8-r4395](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.8-r4395.7z)

**Comment by aonez** [comment]
Thanks for this one Oleg!
