### ISSUE TITLE
[BUG] Error code 335 when creating TAR

### ISSUE THREAD

**Issue by golflabel** [aonez/Keka#760]
### Configuration
- Keka version: [e.g. 1.1.24 (3421)]
- macOS version: [e.g. 10.14.6 (18G2022)]

### Describe the bug
I'm trying to create a 3GB-spanned TAR. I'm pulling files from an external drive that has plenty of storage space left on it, but I keep getting error code 335 when I try. I've got the MAS sandboxed version of Keka, so I wonder if there is some permissions thing going on? I've given Keka access to everything it's asked for, so I'm not sure that's it. I'll attach the log:
[Keka.log](https://github.com/aonez/Keka/files/5823074/Keka.log)

### To Reproduce
1. Try to create TAR (from roughly 95.31 GB of files)
2. Split to 3 GB chunks
3. See error

### Expected behavior
Successfully create the split TAR archive.

### Screenshots
![ScreenShot 2021-01-15 at 14 44 44@2x](https://user-images.githubusercontent.com/57685083/104782176-05feaf80-5741-11eb-8124-7b0bbb9b9507.png)

**Comment by aonez** [comment]
Sorry for the late response @golflabel. Not sure what is happening there. That error occurs when the binary can't be executed. Please try to restart your Mac or even remove Keka and install it again and let me know if that fixes the issue.

As for the split due a bug it will not work with that format. You can create the TAR file and then split it with another format (GZ or BZIP2 i.e.). Be sure you have "Always tarball non-archiving formats" disabled in the Keka Compression Preferences.
