### ISSUE TITLE
[REQ]Support the new M1 apple silicon architecture

### ISSUE THREAD

**Issue by shaonianruntu** [aonez/Keka#762]

**Comment by aonez** [comment]
It is already supported. Do you have any issue working with a M1?

**Comment by shaonianruntu** [comment]
> It is already supported. Do you have any issue working with a M1?

Sorry, I haven't seen you have a specific statement on the version update instructions of the app store that it has native support for the M1 chip. I think the current version is still translated from intel.
After reading the application style of the system, I saw that it was already a universal version.
This is my mistake. I have a very good experience now and there is no problem. I am really sorry for the delay in your precious time.

**Comment by aonez** [comment]
No problem at all! Enjoy it :)
