### ISSUE TITLE
Unable to extract RAR file on OSX

### ISSUE THREAD

**Issue by jrumbut** [aonez/Keka#763]
I am attempting to extract a RAR file on OSX. I have version 1.2.7.

I drag the file to the window, a 2kb file is created for a moment, then it disappears and nothing else happens.

**Comment by aonez** [comment]
Keka reports it successfully extracted the file? Can you share that file?

**Comment by aonez** [comment]
@hasantahir do you have the same issue? Can you give some feedback?

**Comment by hasantahir** [comment]
I was having the same issue with RAR files in particular. With the update 1.2.9, the issue has been fixed.

**Comment by aonez** [comment]
@hasantahir please reopen the issue if you ever reproduce the issue again. Thanks for the feedback!
