### ISSUE TITLE
Keka Helper hash is incorrect

### ISSUE THREAD

**Issue by tylr-r** [aonez/Keka#767]
### Configuration
- Keka version: KekaExternalHelper-v1.1.1
- macOS version: [11.1]

### Describe the bug
Keka helper zip hash does do not match between the download file and the listed MD5 hash on the website.

### To Reproduce
1. Download the helper zip file on https://www.keka.io/en/
2. Scroll down to "Set Keka as the default extraction application"
3. Click on the download button "Download KekaDefaultApp v1.1.1"
4. Check the MD5 hash and compare it with the one listed under the button.

**Comment by aonez** [comment]
Thanks Tyler! Will update it ASAP

**Comment by aonez** [comment]
Fixed! Thanks again Tyler!
