### ISSUE TITLE
The icon (.zsdt) is missing

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#770]
### Configuration
- Keka version:  1.2.7 (4394)
- macOS version: 11.1 (20C69)

### Describe the bug
Keka did not integrate the archive icon (.zsdt) into macOS. The rest were all integrated.

**Comment by aonez** [comment]
The definition of the format is there and the icons for ZSTD are there, working for me:

![Screenshot 2021-01-25 at 09 49 43](https://user-images.githubusercontent.com/480163/105682552-e3b02300-5ef2-11eb-8dee-98f8dfa860a7.png)

Sadly this must be a remanent of #92. Try restarting or report it to Apple...

I'll update my Big Sur to 11.1 (working on 11.0.1 right now) but I assume the result will be the same.

**Comment by apcamargo** [comment]
I'm having this same issue. Any reason it only happens for `.zst` files?

**Comment by aonez** [comment]
Reproduced this issue today. Probably it's something similar to #453.

**Comment by aonez** [comment]
At the moment I'm only reproducing it on an M1, while in an Intel (same Big Sur version) it does show properly.

**Comment by Oleg-Chashko** [comment]
Intel (Big Sur version) :(
<img width="140" alt="Screen Shot 2021-09-30 at 14 41 34" src="https://user-images.githubusercontent.com/62497891/135457093-2889ef3b-0589-4e39-8980-591115d25e67.png">

**Comment by aonez** [comment]
I've just resolved this issue by recreating all the icon caches:

```sh
sudo rm -rfv /Library/Caches/com.apple.iconservices.store; sudo find /private/var/folders/ \( -name com.apple.dock.iconcache -or -name com.apple.iconservices \) -exec rm -rfv {} \; ; sleep 3; killall Dock; killall Finder
```

**Comment by Oleg-Chashko** [comment]
> I've just resolved this issue by recreating all the icon caches:
> 
> ```shell
> sudo rm -rfv /Library/Caches/com.apple.iconservices.store; sudo find /private/var/folders/ \( -name com.apple.dock.iconcache -or -name com.apple.iconservices \) -exec rm -rfv {} \; ; sleep 3; killall Dock; killall Finder
> ```

Unfortunately, I don't have a positive result. :(
<img width="112" alt="Screen Shot 2021-11-19 at 15 30 28" src="https://user-images.githubusercontent.com/62497891/142639286-eca7f46e-1a1d-4f0d-bd2d-fbd6e9f45a6e.png">

**Comment by aonez** [comment]
Should be fixed with next release.

**Comment by Oleg-Chashko** [comment]
Sorry for the off-topic, tell me when you are planning a version 1.3.0? Thank you for your reply.

**Comment by aonez** [comment]
> Sorry for the off-topic, tell me when you are planning a version 1.3.0? Thank you for your reply.

No timeline yet, I want to first finish the iOS version but 1.2.x.

**Comment by Oleg-Chashko** [comment]
Checked, the icon is displayed. 
- Keka v.1.2.50 (4808)
- macOS v.12.0.1 (21A559)
Topic can be closed. Thank you.

**Comment by aonez** [comment]
Thanks for the feedback @Oleg-Chashko!
