### ISSUE TITLE
Honestly, how do you even use keka7z 

### ISSUE THREAD

**Issue by sn0wyfall** [aonez/Keka#773]
I’ve been trying to search for over an hour to an answer to a simple question, but I’m really annoyed that I can’t find documentation for this anywhere, so apologies in advance if I sound a bit ruffled. Basically, I can't figure out how to use ANY of keka's switches. 

I’m trying to use keka7z to output the contents of an archive to a directory. This is my command:

    /Applications/Keka.app/Contents/Resources/keka7z x archive.zip

But this extracts it to whatever folder I cd into. Let's say I want to extract it into `mydir`. I tried these:

    /Applications/Keka.app/Contents/Resources/keka7z x -o mydir archive.zip
    /Applications/Keka.app/Contents/Resources/keka7z x -o mydir/ archive.zip
    /Applications/Keka.app/Contents/Resources/keka7z x -o {mydir} archive.zip
    /Applications/Keka.app/Contents/Resources/keka7z x -o{/mydir} archive.zip
    /Applications/Keka.app/Contents/Resources/keka7z x archive.zip -o mydir
    /Applications/Keka.app/Contents/Resources/keka7z x archive.zip -o mydir/
    /Applications/Keka.app/Contents/Resources/keka7z x -o mydir -- archive.zip

Seriously, none of these work at all. Could you please tell me what I’m missing? This is honestly driving me nuts... every other command line program I've ever used works with method number 1... what am I doing wrong

**Comment by aonez** [comment]
If I remember correctly is:

```
7z x archive.zip -o"mydir"
```

You can also write it without tie quotes `-omydir`. So it should be with no space.

Note that binaries inside next Keka 1.2.8 version will be sandboxed (as required) and won't be usable from the terminal. I might create a downloadable package containing all those binaries un-sandboxed as a replacement though.

**Comment by sn0wyfall** [comment]
Thanks! This actually works. Is this something I'm supposed to know? I literally wasn't able to find it anywhere. Perhaps some documentation would be cool

**Comment by aonez** [comment]
> Is this something I'm supposed to know?

Not really. Keka is not intended to be used as a Terminal client.

**Comment by sn0wyfall** [comment]
Documentation would be really nice. I wanted to use it because it's the only program that unzipped to a folder with the same name as the original zip file and then deleted the zip file. I searched for quite a while but surprisingly, I didn't find anything except Keka which could do that from the command line. 

The reason I wanted to use it from the command line is because I was trying to unzip about 400 files and the GUI was making my computer/the program lag quite a bit

**Comment by aonez** [comment]
> unzipped to a folder with the same name as the original zip file and then deleted the zip file

This can be done with Keka, I'm not sure if you were able to do it from the GUI or not?

> 400 files and the GUI was making my computer/the program lag quite a bit

This can be interesting to test and improve 😊 Were they very small files?

**Comment by sn0wyfall** [comment]
Yup, I was basically trying to replicate the GUI program but without the overhead of having the GUI running. There are some problems I ran into:

1. With lots of files, sometimes if I opened more and more (e.g. if I keep opening a hundred at a time) eventually the program sometimes froze, and I would have to force quit it
2. Doing anything in the program (e.g. scrolling or trying to cancel individual zips from happening) is basically impossible when it's uncompressing such a large number of files, since the GUI lags a lot. So the only way to stop all the unzipping is by force quitting the app
3. There is a "notification bump" every time a file has been unzipped which gets annoying if you are unzipping hundreds of files 😝 

The files were basically a load of data files for a project I have, and I'd say each zip had around 100 files, each 1+ MB. By the way, here are my settings–the parallel unzipping is probably causing a lot of this lag, but I do it for speed:

![image](https://user-images.githubusercontent.com/24374968/107866592-90215d00-6e40-11eb-960e-1786eadd77c8.png)

(By the way, I have to mention: Keka is probably the best-looking app I have installed on my laptop, its dark mode and color scheme is perfect)

**Comment by MaxPower85** [comment]
@aonez 

About this
> Note that binaries inside next Keka 1.2.8 version will be sandboxed (as required) and won't be usable from the terminal. I might create a downloadable package containing all those binaries un-sandboxed as a replacement though.

I think you probably don't need to make a separate version of Keka for that... you could maybe just compile the original utilities as they originally were (some users maybe don't want to compile them themselves) and put just those utilities in a .zip with some readme file about how to use them for those who want to use them from the Terminal.

**Comment by gingerbeardman** [comment]
But why get those utilities from Keka when it's probably better to get them from their source?

**Comment by aonez** [comment]
Already developed (for next release) some kind of client support to keep using those binaries, with the same sandbox file access limitations that Keka has. That will fulfil the needs of most users, I think. Power-users will build or use brew or similar standalone tools as @gingerbeardman stated.

@MaxPower85 that's not a bad idea. My package idea is mostly this but with an "auto-install" approach. But I think with the client implementation I will not do any of those.

![Screenshot 2021-02-16 at 17 31 53](https://user-images.githubusercontent.com/480163/108092342-e975d000-707c-11eb-9378-62a725c6e955.png)

**Comment by aonez** [comment]
@sn0wyfall I'll try to enhance brutal quick multitasking 😉

**Comment by TheTechRobo** [comment]
> @sn0wyfall I'll try to enhance brutal quick multitasking 😉

Maybe have a feature where you can set up to turn off notifications (if it still doesn't exist - correct me if i'm wrong), and also one where instead of the GUI, it'll hide the window and then will re-show it when all archives are done? That might be nice... thoughts?

**Comment by aonez** [comment]
@TheTechRobo you can disable the notifications in the Keka preferences, "Enable Notification Center integration". As for the no GUI I think can be a good addition. The idea is there since long time ago, don't remember now if there's a ticket for it so here it is https://github.com/aonez/Keka/issues/895

**Comment by SoCuul** [comment]
@aonez I didn't think it was important enough to create a new issue (please let me know if I should), but keka7z remains Intel 64-Bit without having an Apple Silicon variant packed into the binary. Hoping this can be resolved before macOS 28 drops support for intel binaries.

**Comment by aonez** [comment]
@SoCuul version 1.6.6 dropped ARM support for `keka7z` since it is only used as fallback on 10.13 or older (Intel). You can check the changelog https://changelog.keka.io/#v1.6.6. `keka7zz` is the binary to use since it is up to date.
