### ISSUE TITLE
Version 1.2.8 always shows "Really want to close Keka?" when quitting

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#774]
### 👉 As a workaround please disable `Safely end tasks` in `Keka` -> `Help` -> `Debug`
https://github.com/aonez/Keka/issues/774#issuecomment-768252080

### Configuration
- Keka version: 1.2.8 (4430)
- macOS version: 11.1 (20C69)

### Describe the bug
After upgrading from v.1.2.7 to v.1.2.8, when unpacking the archive, the "Really want to close Keka?"
I have not changed the settings. 

### Screenshots
<img width="372" alt="Screen Shot Really want to close Keka?" src="https://user-images.githubusercontent.com/62497891/105989482-7c84a100-60a1-11eb-8a3b-6801060a502f.png">

https://user-images.githubusercontent.com/62497891/105989504-84444580-60a1-11eb-9001-33d849256298.mov

**Comment by gingerbeardman** [comment]
I'm also seeing this.

After normal extraction Keka asks if you really want to close the window.

I guess there is a problem in the new window closing logic @aonez

**Comment by aonez** [comment]
Yep, damn, already working on a fix.

**Comment by aonez** [comment]
Please disable `Safely end tasks` in `Keka` -> `Help` -> `Debug`

![Screenshot 2021-01-27 at 13 25 02](https://user-images.githubusercontent.com/480163/105990639-16991900-60a3-11eb-8f1a-1365dc15dd56.png)

**Comment by aonez** [comment]
> I guess there is a problem in the new window closing logic @aonez

@gingerbeardman It's about "Fixed incomplete operation files not deleted if exiting", not really about the Sparkle issue. I don't know how this one skipped my tests.

**Comment by Oleg-Chashko** [comment]
This problem was described by me in the topic: 
Error and strange behavior of the application when using an incorrect password #758

**Comment by aonez** [comment]
Right @Oleg-Chashko, I though there it was because I was working on the Sparkle issue.

**Comment by aonez** [comment]
Already pushed 1.2.9. Will not wait for the MAS review to be accepted, no sync updated this time.
