### ISSUE TITLE
Trying to extract folder ends in an unfinished task

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#778]
https://user-images.githubusercontent.com/62497891/106148276-284cf000-6179-11eb-90dc-6d00cb884aaf.mov

**Comment by Oleg-Chashko** [comment]
Please pay attention, again this window: 
<img width="268" alt="Screen Shot 2021-01-28 at 15 55 29" src="https://user-images.githubusercontent.com/62497891/106156187-87166780-6181-11eb-921c-a5b1200d40e7.png">

**Comment by aonez** [comment]
This issue was introduced in 1.2.4. Will check later.

**Comment by aonez** [comment]
Fixed in [Keka-1.2.9-r4437.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.2.9-r4437.7z). Thanks for the tip Oleg!
