### ISSUE TITLE
[BUG] Multiple Finder Extensions

### ISSUE THREAD

**Issue by dorjanbenic** [aonez/Keka#783]
### Configuration
- Keka version: 1.2.9 (4434)
- macOS version: 11.2 (20D64)

### Describe the bug
In Activity Monitor there is accumulation of processes called Keka Finder integration. After a while there is 50+ processes.

### To Reproduce
After the time of using Mac open Activity Monitor.

### Expected behavior
I expect a few processes runing called Keka Finder integration on Activity Monitor, not 50+.

### Additional context
https://user-images.githubusercontent.com/39588255/107283046-237f1a80-6a5c-11eb-9efd-8f8e0f339d48.mov

**Comment by aonez** [comment]
Take a look at this: https://github.com/aonez/Keka/issues/734

Maybe you have a lot of Finder windows/tabs open?

**Comment by dorjanbenic** [comment]
Hello,

somehow I managed to forgot to reply to you, I apologize.

> Take a look at this: #734 <https://github.com/aonez/Keka/issues/734>Maybe you have a lot of Finder windows/tabs open?
> 

No, I don't but I work in Finder a lot, so I often open and close windows and have multiple windows open. I find that it is easier to manage multiple windows rather than tabs. I don't use Keka much but every once a while I need it.

I did not notice any issues regarding performance i just noticed bunch of entries on Activity Monitor last time. While writing this mail I just went to check Activity Monitor and I had way less entries, just 27 this time but they may accumulate. Only difference is that I had energy impact recorded on  Activity Monitor.



Regards,
Dorjan Benić

**Comment by aonez** [comment]
@dorjanbenic maybe you use some external disks or even network ones? Try disabling external volume support in Keka - Preferences - Finder Extension. There you can set in what folders Keka’s extension will be loaded. Maybe limit it for example to the Desktop and see if it makes any difference. Try also to restart the Mac or manually kill all those loaded extensions.

Maybe there’s some specifics in your workflow that make those extensions leave and use more resources than normally.

**Comment by dorjanbenic** [comment]
I never used network disks but I did use USB stick a lot when I reported 50+ Keka processes however last uptime is 6 days and I did not use Keka and any external storage and I still have 27 Keka processes. 

If I force quit Finder all processes are still there. I can't quit any of these processes, if I try nothing happens but force quit works fine.


I don't see any access given to a external volume. I will continue to observe situation and report if I find anything.

![Screen Shot 2021-02-17 at 13 13 14](https://user-images.githubusercontent.com/39588255/108202826-fc8eab80-7121-11eb-8676-53068a781b3f.png)

**Comment by gingerbeardman** [comment]
@dorjanbenic you don't need to use Keka, as long as you use Finder with the Keka extension enabled this will happen

**Comment by aonez** [comment]
@dorjanbenic please reopen if you have any other new info 😊

**Comment by davecarlson** [comment]
I see this too - I have no finder windows open (last one was opened over an hour ago), and yet there are 11 Finder Integration processes running
