### ISSUE TITLE
Can't use AES256 encryption with Zip compression

### ISSUE THREAD

**Issue by craigraider** [aonez/Keka#785]
### Configuration
- Keka version: 1.2.10 (4464)
- macOS version: 10.15.7 (19H114)

### Describe the bug
Cannot enable AES256 encryption with Zip [compression
![AES problem with repeat error 2021-02-09 at 9 14 55 AM](https://user-images.githubusercontent.com/78813532/107401518-d2047900-6ab7-11eb-99a6-b56fbbad6ec7.png)
[Keka_2021-02-09-091419499.log](https://github.com/aonez/Keka/files/5953032/Keka_2021-02-09-091419499.log)

Attach a log file reproducing the issue: https://github.com/aonez/Keka/wiki/Report-an-issue

**Comment by aonez** [comment]
@craigraider you should repeat the password in the field below, then the password is accepted and you can enable AES256. Also you can enable this option by default in the Keka Preferences.

Here some tips:
https://github.com/aonez/Keka/wiki/Compressing-with-Keka#password-protected-and-encrypted-files

**Comment by Oleg-Chashko** [comment]
https://user-images.githubusercontent.com/62497891/107403093-018da280-6b05-11eb-8c2f-17cd464e5b61.mov

**Comment by craigraider** [comment]
Thank you. Everything works and makes sense too.
