### ISSUE TITLE
GUI clipping

### ISSUE THREAD

**Issue by Suavatore** [aonez/Keka#79]
The GUI begins to clip when the toolbar is changed from "Icons and Text" to any other option. The clipping is most noticeable when switching amongst the different file menus (7z, zip, Tar, etc...).
<img width="448" alt="screen shot 2017-09-24 at 9 24 10 am" src="https://user-images.githubusercontent.com/13889273/30780403-39046e4c-a10a-11e7-912f-ec30966523b4.png">

**Comment by aonez** [comment]
Can you try with the latest beta: [Keka 1.1.0 beta 3](https://github.com/aonez/Keka/releases/tag/v1.1.0-beta.3)

This must be fixed there. Let me know if you can reproduce this there as well.

**Comment by Suavatore** [comment]
Yep, its fixed in the beta. However, I noticed a different bug in the beta. Dmg and Iso menus have no icons if the toolbar is customised.
<img width="448" alt="screen shot 2017-09-24 at 9 34 05 am" src="https://user-images.githubusercontent.com/13889273/30780464-86bde7f2-a10b-11e7-938f-11e593126f28.png">

**Comment by aonez** [comment]
This also is fixed on revision 2273. I might release beta 4 today 😊

Thanks for all the feedback @Suavatore!
