### ISSUE TITLE
Unable to decompress

### ISSUE THREAD

**Issue by sushiichi48** [aonez/Keka#792]
I tried to unzip 500 GB file but it quit after decompressing 20 hours.

**Comment by gingerbeardman** [comment]
Do you have enough disk space to store the decompressed files?

**Comment by aonez** [comment]
Hi @sushiichi48,

- If Keka crashed please look for the crash log in the Console.app.
- If the process finished with an error please share the [log file](https://github.com/aonez/Keka/wiki/Report-an-issue#debug-session).
- You can see the operation log clicking in the warning signal:
![Screenshot 2021-02-18 at 04 44 57](https://user-images.githubusercontent.com/480163/108302407-356f6480-71a4-11eb-986d-7b981987505c.png)

**Comment by sushiichi48** [comment]
Yes, I do have extra 3T.
What else do you need?

Thank you for helping me.

Sam Okamoto

Sam Okamoto Photography

WWW.samokamoto.com

*contact@samokamoto.com <contact@samokamoto.com>*

*530-414-1226*

**Comment by aonez** [comment]
Please check my comment https://github.com/aonez/Keka/issues/792#issuecomment-781028276

**Comment by sushiichi48** [comment]
Hey there I was waiting to decompress the file but it failed again. This
sign came back with it.

Sam Okamoto

Sam Okamoto Photography

WWW.samokamoto.com

*contact@samokamoto.com <contact@samokamoto.com>*

*530-414-1226*

**Comment by aonez** [comment]
Reopened in #796
