### ISSUE TITLE
decompressing failed  

### ISSUE THREAD

**Issue by sushiichi48** [aonez/Keka#796]
I got a message from one of your supporters, 
I tried to decompressing my 500 GB files of photos and it is failed again. 
message result  said 
<img width="414" alt="Screen Shot 2021-02-18 at 8 02 18 PM" src="https://user-images.githubusercontent.com/78170044/108457911-54afd580-7228-11eb-9d2d-2c997fba82eb.png">

**Comment by aonez** [comment]
@sushiichi48 in order to help I need the extraction log. If you click the warning sign ⚠️ you can see the log and copy/paste it here.

Alternatively follow this steps:

1. Open Keka
2. Create a debug session, as shown in the animation below
    ![](https://github.com/aonez/Keka/raw/master/Wiki/Images/Animated/create-debug-session.gif)
3. Extract the file again and wait until it fails
4. Don't close the error window
5. Open the logs folder as shown in the animation below
    ![](https://github.com/aonez/Keka/raw/master/Wiki/Images/Animated/open-logs-folder.gif)
6. Share the log file here (you can ZIP it)

**Comment by cyclebobTX** [comment]
Having the same issue. Here's the error code: 

OS: Version 11.2.1 (Build 20D74)
Keka: v1.2.11-r4493 (MAS) (Sandboxed) (en)
Binary used: keka7z
Arguments: (
    a,
    "-tzip",
    "-v681574400b",
    "-mx5",
    "-p",
    "/Users/bobk/Desktop/Archive.zip",
    "Balance Sheet Detail.numbers",
    "General Ledger.numbers",
    "Profit and Loss Detail.numbers"
)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,16 CPUs x64)
Modified by aONe for Keka

Scanning the drive:
  0M Scan 


___KEKA___PASSWORD___KEKA___
Verify password (will not be echoed) :
3 files, 2413006 bytes (2357 KiB)

Creating archive: /Users/bobk/Desktop/Archive.zip

Items to compress: 3




ERROR: Can't allocate required memory!

Error code 8

**Comment by sushiichi48** [comment]
Ok, I'll check it out.

Sam Okamoto

Sam Okamoto Photography

WWW.samokamoto.com

*contact@samokamoto.com <contact@samokamoto.com>*

*530-414-1226*

**Comment by sushiichi48** [comment]
Okay, I am sending a log.

Sam Okamoto

Sam Okamoto Photography

WWW.samokamoto.com

*contact@samokamoto.com <contact@samokamoto.com>*

*530-414-1226*

**Comment by sushiichi48** [comment]
I sent you a log report, did I do it right?

Sam Okamoto

Sam Okamoto Photography

WWW.samokamoto.com

*contact@samokamoto.com <contact@samokamoto.com>*

*530-414-1226*

**Comment by aonez** [comment]
Nothing received. Please send it via mail to info@keka.io

**Comment by aonez** [comment]
The file was corrupted.
