### ISSUE TITLE
Can't allocate required memory

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#798]
Having the same issue. Here's the error code: 

OS: Version 11.2.1 (Build 20D74)
Keka: v1.2.11-r4493 (MAS) (Sandboxed) (en)
Binary used: keka7z
Arguments: (
    a,
    "-tzip",
    "-v681574400b",
    "-mx5",
    "-p",
    "/Users/bobk/Desktop/Archive.zip",
    "Balance Sheet Detail.numbers",
    "General Ledger.numbers",
    "Profit and Loss Detail.numbers"
)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,16 CPUs x64)
Modified by aONe for Keka

Scanning the drive:
  0M Scan 

___KEKA___PASSWORD___KEKA___
Verify password (will not be echoed) :
3 files, 2413006 bytes (2357 KiB)

Creating archive: /Users/bobk/Desktop/Archive.zip

Items to compress: 3

ERROR: Can't allocate required memory!

Error code 8

_Originally posted by @cyclebobTX in https://github.com/aonez/Keka/issues/796#issuecomment-782389891_

**Comment by aonez** [comment]
@cyclebobTX your's is a totally different issue than #796 (extraction of 500GB file).

**Comment by aonez** [comment]
@cyclebobTX will be great if you can let me know the size of the Numbers files and also the password you were using in the compression.

Does this happen if you do not split the file or use a simple password?

**Comment by cyclebobTX** [comment]
All told, the files are less than 50 kb. They're super tiny. I've got a 10 digit PW, but I can try it with a simpler password

**Comment by cyclebobTX** [comment]
A simpler password seems to have worked

**Comment by aonez** [comment]
If you can share the password that might help improve Keka. Maybe that password used some character that was causing the issue.
