### ISSUE TITLE
Terminal Command for 7zip archive needed. Please help.

### ISSUE THREAD

**Issue by dirkkuepper** [aonez/Keka#799]
I would like to create a 7zip archive of a folder with many other subfolders and files in it. The finished archive must not be compressed and must not be password protected. What is the appropriate command line in Terminal on macOS Mojave?

**Comment by MaxPower85** [comment]
Here's the manpage for 7z, but 7zip is not meant to be used as a replacement for tar

**Comment by MaxPower85** [comment]
Here's a manpage for 7z, but 7z isn't meant to be used as a replacement for tar
https://manpages.debian.org/stretch/p7zip-full/7z.1.en.html

**Comment by dirkkuepper** [comment]
I don't want to replace tar. I need 7zip for another reason. Just for making an archive without compression, and without password. I found help page. But there is no example inside. Question again: What is the appropriate command line in Terminal on macOS Mojave?

**Comment by aonez** [comment]
@dirkkuepper Max already pointed you to 7z manual page. There you have all the information you are asking for.

As for Keka you can simply set the method to "Store":

![Screenshot 2021-02-22 at 11 41 27](https://user-images.githubusercontent.com/480163/108697486-36392b00-7503-11eb-9302-141a4976ca60.png)

**Comment by dirkkuepper** [comment]
@aonez Thank you. How to do this in Terminal on macOS Mojave? The syntax can not be the same on macOS as it is on Debian in 2016? The path to the binary for example /Applications/Keka.app/Contents/MacOS/keka7z is another one. I want to know what is the command for my job :-)

**Comment by aonez** [comment]
> /Applications/Keka.app/Contents/MacOS/keka7z

Can't be used directly since it is sandboxed. You can check this: https://github.com/aonez/Keka/wiki/Terminal-client

You can use it like this:

```
/Applications/Keka.app/Contents/MacOS/Keka --client 7z a -t7z -mx0 <OUTPUT_7Z_FILE> <INPUT_FILES>
```

You can download `p7zip` (for example via [brew](https://brew.sh) 🍺) and do the same:

```
7z a -t7z -mx0 <OUTPUT_7Z_FILE> <INPUT_FILES>
```
