### ISSUE TITLE
Splitted Rar files are not deleted automatically *.r00, *.r01, *.r02, *.r03

### ISSUE THREAD

**Issue by DasBlatz** [aonez/Keka#8]
Splitted Rar files are not deleted automatically like *.r00, *.r01, *.r02, *.r03,… 
Or did I misconfig something?

the *.rar file is deleted but the rest stays still in the folder

**Comment by aonez** [comment]
Reported before here: http://trac.kekaosx.com/ticket/51
Closing the old ticket in favor of this one.

**Comment by aonez** [comment]
Fixed in 1.1.0 beta: beta.kekaosx.com
