### ISSUE TITLE
Best way to compress big chunk of data

### ISSUE THREAD

**Issue by gooseodyssey** [aonez/Keka#80]
Hi I have a question regarding the "Solid archive" setting. What does that actually do? My needs are: I need to compress a large folder of files in to multiple parts, send over the internet and extract everything at the other end to continue working on the files. Are you able to advise me on the best settings for this? Thank you!

**Comment by aonez** [comment]
Usually you can use the solid option so the result compressed file is lighter. Unless you want to create a backup file (which seems to be not the case), in that case I recommend you to use a tarball (i.e. gz, bz2). You can read more about solid archives here: https://en.wikipedia.org/wiki/Solid_compression

So, if the folder you're compressing does not need Mac metadata to be preserved (tags, for example), just create a 7z, with solid option and parted as you like. It will be the faster way to go :)

**Comment by gooseodyssey** [comment]
Thanks for getting back. The folder I'm sending is about 170GB uncompressed. It contains After Effects files, Photoshop files and large video files mostly. The folder needs to be extracted on a Mac and continued to be worked on. I'm on a PC (so I could compress in Windows) but have access to Macs at this end too, which is why I'm looking at Keka (I figured compressing the folder on a Mac might be more reliable than compressing it on a Windows PC, seeing as it has to be opened on a Mac?). I need to get as much compression as possible within reason, as I'm uploading via the internet.

If I want the parts to be about 16GB each, do I type just "16000" in the Split field?

Thank you!

**Comment by aonez** [comment]
Definitely go for 7z. If you don't mind the process to take longer time set the method to the slowest option, so you can achieve more compression. If time is also important, just keep it to normal.

**Comment by gooseodyssey** [comment]
Thank you! I typed "16000" already, will that work too?

I've set it on "slowest". At a total ball park guess, how long are we talking here? Many hours or many days?!

**Comment by aonez** [comment]
> Thank you! I typed "16000" already, will that work too?

Yes, the default are megas, this will work also.

> I've set it on "slowest". At a total ball park guess, how long are we talking here? Many hours or many days?!

It depends on many factors such as your machine and the disks where you're working on. Take a look at the estimated time once it can be calculated. If it's too slow, just cancel the process and go for normal. Or even go for the fastest option (not the store one) since videos are not compressed.

**Comment by gooseodyssey** [comment]
Thank you so much for your help!

**Comment by aonez** [comment]
Hope it all well ok! Otherwise just let me know 👍🏼

**Comment by gooseodyssey** [comment]
It went really well, thank you so much for your help! Great software!

**Comment by 733amir** [comment]
In 2025 is the answer to the question still 7z?
