### ISSUE TITLE
[REQ] When you will port keka for apple silicon to work natively..?

### ISSUE THREAD

**Issue by Rishi-DK** [aonez/Keka#800]
### Is your feature request related to a problem? Please describe
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

**Comment by aonez** [comment]
It's been supporting ARM M1 since November 2020!

**Comment by aonez** [comment]
@Rishi-DK Are you having any trouble running it natively?

**Comment by Rishi-DK** [comment]
No. But there of lot of glitches and bugs and lags...random shutters while running on M1 while comparing with intel...

**Comment by gingerbeardman** [comment]
Please provide more info. Screen recording of comparison would be excellent.

**Comment by aonez** [comment]
@Rishi-DK I did tested it on a Mac mini M1 with no issues. Can you be more specific?
