### ISSUE TITLE
Make txz great again! ;-)

### ISSUE THREAD

**Issue by nodarkthings** [aonez/Keka#803]
### Is your feature request related to a problem? Please describe
I'm using the Mac version, currently in MacOS 10.11.
I've discovered the xz/txz format thanks to Keka, but for some unknown reason, txz has been replaced by tar.xz after a while.
txz is natively supported by MacOS, which makes it a format of choice. I see that renaming tar.xz files to txz works, so why bother with a double-extension?

### Describe the solution you'd like
Allow the user to choose between txz and tar.xz, preferably in the prefs — or when saving a file.

### Describe alternatives you've considered
• changing the extension to txz when saving a file, but it doesn't work.
• Renaming tar.xz files to txz in the Finder. But that makes an additional boring step.

### Additional context
All the other compression tools I've tried support txz, so why bother with tar.xz if not for compatibility reasons?

**Comment by aonez** [comment]
You can already to that executing this command in the Terminal.app:

```
defaults write com.aone.keka UseLongTarballExtension true
```

Remember to restart Keka. I'm adding an option in 1.2.12 anyway, that option should have been there since 1.2.0 😳

<img width="602" alt="Screenshot 2021-02-23 at 19 04 43" src="https://user-images.githubusercontent.com/480163/108887263-4e47a200-760a-11eb-9d0d-dffa0abb0620.png">

**Comment by nodarkthings** [comment]
Wonderful! Thanks. :-)

**Comment by aonez** [comment]
Sorry it was `false`, not `true`:

```
defaults write com.aone.keka UseLongTarballExtension false
```

**Comment by aonez** [comment]
1.2.12 released with this option in the Preferences 😊

**Comment by nodarkthings** [comment]
Thanks! :-)
