### ISSUE TITLE
Gzip restores original filename by default

### ISSUE THREAD

**Issue by nuomi1** [aonez/Keka#82]
- [x] Add an option to use/ignore the original filename if present

---

macOS 10.12.6

`wget -c https://swscan.apple.com/content/catalogs/others/index-10.13-1.sucatalog.gz`

- Keka 1.1.0-beta.3 (2120): `index-10.13-1.sucatalog.nk11p01su-swupdate002.isu.apple.com.gztmp`
- BetterZip 4.0.1 (1174): `index-10.13-1.sucatalog`
- Archive Utility 10.10 (81): `index-10.13-1.sucatalog`

**Comment by aonez** [comment]
> wget -c https://swscan.apple.com/content/catalogs/others/index-10.13-1.sucatalog.gz

This url points to an xml file, even if it has a gz extension.

**Comment by nuomi1** [comment]
```
file index-10.13-1.sucatalog.gz
index-10.13-1.sucatalog.gz: gzip compressed data, was "index-10.13-1.sucatalog.nk11p01su-swupdate002.isu.apple.com.gzt", last modified: Tue Oct  3 12:20:56 2017, from Unix
```

**Comment by aonez** [comment]
Sorry my mistake, it is indeed a gz. Safari opened it like the xml it contains, that confused me. But it has the magic number 1F8B.

**Comment by aonez** [comment]
Technically this is not wrong, since it's applying the original name of the file. The other apps are just ignoring the original name.

**Comment by aonez** [comment]
Here I've stripped the original filename data, so it just names the content as the gz file:

[index-10.13-1.sucatalog.gz.zip](https://github.com/aonez/Keka/files/1352888/index-10.13-1.sucatalog.gz.zip)

I don't think this is something to be changed. If the package creator included the original name, it must be replicated.

**Comment by aonez** [comment]
I'm seeing at least GNU Gzip always stores the original filename but only uses it if `-N` flag is used, so by default does not restore the original filename.

**Comment by aonez** [comment]
- [ ] Add an option to use/ignore the original filename if present.

**Comment by aonez** [comment]
This will be available using [setting the option](https://github.com/aonez/Keka/wiki/Hidden-configuration#extraction) `IgnoreGZIPName` in next 1.2.0 revision.
