### ISSUE TITLE
[REQ] Placeholder for getting archive name from clipboard

### ISSUE THREAD

**Issue by psychowood** [aonez/Keka#823]
### Describe the solution you'd like
I often find myself in the position of compressing a bunch of files without having the option to move them to a unique folder before archiving, while I have the archive name ready in the clipboard.

### Describe alternatives you've considered
I'm either copy/pasting the name and renaming the archive after creation, or moving ll the files in a new folder that is renamed as the archive before compressing.

### Additional context
It would belong here, as an additional placeholder:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/115389/112821948-9a618880-9087-11eb-8b58-ec4df7d00753.png">

If you believe this could be useful, I could try to provide a PR.

**Comment by aonez** [comment]
Nice idea! Let me check that one.

**Comment by MaxPower85** [comment]
If options to rename anything are added, just make sure that it's only for the names of the archives and that names of folders inside of archives would be unaffected... because, for example, most users probably wouldn't want to end up unintentionally renaming some app that was archived or some other "bundle" that is technically a folder with a special extension.

**Comment by psychowood** [comment]
The rename option is already available, I suppose this won't change that behavior.

**Comment by aonez** [comment]
I forgot about this for 1.2.13 but will come in 1.2.14.

**Comment by aonez** [comment]
Here a build to test:
[Keka-1.2.14.r4542](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.2.14.r4542.7z)

**Comment by psychowood** [comment]
@aonez the new option is working quite well, thanks!

Btw, I'm having a small issue, I'm not sure if it is the expected behaviour, I'm reporting it anyway just to be sure. 

When using a clipboard name with "/" in it, the file gets created in the Desktop folder (ignoring the "create next to original files" preference), and the "/" adds an additional parent folder.

This is my configuration:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/115389/119624995-03584900-be0a-11eb-8e45-35012f2013df.png">

**Comment by aonez** [comment]
@psychowood I'll take a look at it

**Comment by aonez** [comment]
I've fixed this for next release. Thanks a lot for the feedback @psychowood!
