### ISSUE TITLE
[REQ]Can you add password manager to Keka? 

### ISSUE THREAD

**Issue by JOJOforshaun** [aonez/Keka#826]
This is very convenient and can save a lot of time for activities that often need to unpack compressed files of the same or several passwords. I even want Keka to be able to automatically traversal the passwords saved in the password manager when it unpacks the encrypted zip file.

**Comment by gingerbeardman** [comment]
I wonder if Keychain is a good place for such passwords to be stored?

**Comment by aonez** [comment]
@JOJOforshaun this is a dupe of #26, will be tracked there :)
