### ISSUE TITLE
[BUG] Using short tar extension (.tgz) checkbox is unchecked after restart

### ISSUE THREAD

**Issue by schmimps** [aonez/Keka#828]
### Configuration
- Keka version: [1.2.13 (4541)]
- macOS version: [11.2.3]

### Describe the bug
The checkbox for using short extension .tgz instead of .tar.gz doesn't survive to app restart

### To Reproduce
Tested on French translation.
1. Go to Preferences -> Compression -> Check "Use short TAR extensions (.tgz instead of .tar.gz)"
2. Quit Keka
3. Go back to Preferences -> Compression
4. The checkbox is unchecked

### Expected behavior
The checkbox should remain checked even after restart.

### Screenshots
<img width="547" alt="image" src="https://user-images.githubusercontent.com/62472949/114844663-4b338b80-9ddb-11eb-99d7-8248968951ff.png">

### Additional context
Tested on French (Switzerland) locale on two different computers.

**Comment by aonez** [comment]
Thanks for this one @schmimps! Turns out the value was saved in a negate state... Fixed for next release!

Meanwhile you can set it using the Terminal.app (`false` if you want short extensions):

```sh
defaults write com.aone.keka UseLongTarballExtension false
```

**Comment by schmimps** [comment]
You're a king, thanks!
