### ISSUE TITLE
AppleArchive support

### ISSUE THREAD

**Issue by MaxPower85** [aonez/Keka#829]
It seems that Apple has included a command line utility that can create .yaa archives since High Sierra... but there don't seem to be a lot of articles about it online... I tried it on High Sierra and it seems to work well... it's multithreaded, it can use different compression formats (Apple's LZFSE is default, but it can also use LZMA, LZ4, ZLIB or LZVN... or not compress) and it can optionally include extended attributes also.

There doesn't seem to be a way to set a compression level, but you can set a larger block size for better compression.

```
Usage: yaa command <options>

Commands:
    extract                     extract files from an archive
    list                        list the contents of an archive
    convert                     convert an archive into another
    archive                     archive the contents of a directory
    info                        show archive info
    manifest                    alias for 'archive -manifest'
    index                       alias for 'convert -index'
    manifest-to-bom             convert a YAA manifest to BOM
    verify                      verify dir contents against YAA manifest

Options:
   -v                           increase verbosity level to stderr. Default is silent operation
   -h                           show usage and quit
   -t nWorkerThreads            number of threads to run for compression/decompression, default is 8 on this machine
   -wt nWriterThreads           number of writer threads to run, default is nWorkerThreads ('extract' only)

   -d targetDir                 target directory, default is current directory

   -o outFile                   output file, default is stdout
   -a <algorithm>               compression algorithm for archive payload
   -b <size>                    compression block size for archive payload
                                  'archive' default compression: lzfse 4m
                                  'manifest','index','combine' default compression: lzfse 1m
   -i inFile                    input file, default is stdin
   -ioffset inOffset            bytes to skip at the beginning of inFile, default is 0
   -isize inSize                bytes to read from inFile, default -1 = read the entire file
   -iindex inIndex              input index file, must be a YAA index of the input archive

   -ignore-eperm                ignore EPERM errors when setting files attributes
   -include-path-list listFile  file containing a list of paths to include (one per line, empty lines ignored); this option can be specified multiple times
   -exclude-path-list listFile  file containing a list of paths to exclude (one per line, empty lines ignored); this option can be specified multiple times
   -include-path path           include entry prefix PATH; this option can be specified multiple times
   -exclude-path path           exclude entry prefix PATH; this option can be specified multiple times
   -exclude-name name           exclude entry paths matching NAME (exact match of a path component); this option can be specified multiple times
   -include-type <types>        include entries matching <types> and exclude all other types
   -exclude-type <types>        exclude entries matching <types> and include all other types
                                  default is to include all entry types
   -include-field <fields>      exclude <fields> from archive entries; this option can be specified multiple times
   -exclude-field <fields>      include <fields> from archive entries; this option can be specified multiple times
                                  'archive': typ,pat,lnk,dev are always included; default is to include typ,pat,lnk,dev,uid,gid,mod,flg,mtm,dat,duz
                                  'convert': typ,pat are always included; default is to include typ,pat,lnk,dev,uid,gid,mod,flg,mtm,dat,xat,acl,duz
                                  'list': default is to include all fields
   -manifest                    alias for the following options:
                                  -exclude-field dat
                                  -include-field sh1,cks,siz
                                  -a lzfse -b 1m
   -index                       alias for the following options:
                                  -exclude-field all
                                  -include-field idx
                                  -a lzfse -b 1m


Special option values:
<fields>                        comma separated list of fields, from the following list:
                                  typ     type
                                  pat     entry path
                                  lnk     link path
                                  dev     device id
                                  uid     user id
                                  gid     group id
                                  mod     access mode
                                  flg     flags
                                  mtm     modification time
                                  dat     file data
                                  siz     file size
                                  cks     file data POSIX 1003.2-1992 32 bit CRC
                                  sh1     file data SHA1 digest
                                  sh2     file data SHA256 digest
                                  xat     extended attributes
                                  acl     access control list
                                  duz     file disk usage
                                  idx     entry index in input archive
                                  yaf     stored fields (metadata entry)
                                  attr    alias for uid,gid,mod,flg,mtm fields
                                  all     alias for all fields
<types>                         one or more characters representing entry types, from the following list:
                                  b       block special
                                  c       character special
                                  d       directory
                                  f       regular file
                                  h       hard link
                                  l       symbolic link
                                  m       metadata entry (not a filesystem object)
                                  p       fifo
                                  s       socket
<algorithm>                     compression algorithm, from the following list:
                                  lzma    LZMA preset 6 (xz)
                                  lzfse   LZFSE
                                  lz4     raw LZ4 default level
                                  raw     no compression
                                  zlib    raw ZLIB level 5
                                  lzvn    LZVN
<size>                          size in bytes, optional suffixes b,k,m,g are accepted

```

**Comment by gingerbeardman** [comment]
I created an app that manages this, it was headless and used the progress circle on the filename. I sent it to @aonez privately some years ago now. 

Since then he has implemented the progress circle on filename, somewhat headless operation, but still no support for .yaa archive format

I think .yaa performance benefits will be even more pronounced on M1. 

So, my point is, I'd like this too.

**Comment by gingerbeardman** [comment]
On thing I wanted to look into, buy never did, was the possibility of using yaa in zip mode to create zips and then replace the header with a zip compatible header. So yaa could be used to make zips. Just an idea.

**Comment by gingerbeardman** [comment]
Any plans @aonez ?

**Comment by aonez** [comment]
Let me check that one again @gingerbeardman

**Comment by aonez** [comment]
I'm doing a quick test and can definitely be implemented. I'm unable to archive/extract metadata, not even stating this:

```
-include-field xat -include-field attr -include-field yaf
```

Were any of you able to do this?

**Comment by aonez** [comment]
> So `yaa` has been renamed `aa`, at least in the latest Big Sur, and the man page clarifies that the name stands for Apple Archive.

Yes, they keept a `yaa` alias. Also there's some documentation now and API's to use the format:
https://developer.apple.com/documentation/applearchive

I've looked at the extensions and it used to be `yaa` and now [it should be](https://developer.apple.com/documentation/accelerate/compressing_file_system_directories) `aar` standing for Apple ARchive, I imagine. In Big Sur both extensions are recognized and the bundled archiver extracts them.

> aa archive -include-field xat,attr,yaf -d temp -o test.aa

This still does not work for me...

```sh
aone@aONe-M1 ~ % xattr aaa/test.png 
com.apple.FinderInfo
com.apple.lastuseddate#PS
com.apple.macl
com.apple.metadata:_kMDItemUserTags
com.apple.metadata:kMDItemIsScreenCapture
com.apple.metadata:kMDItemScreenCaptureGlobalRect
com.apple.metadata:kMDItemScreenCaptureType

```

```sh
aone@aONe-M1 ~ % xattr aaa_/test.png 
com.apple.macl
aone@aONe-M1 ~ % 
```

**Comment by aonez** [comment]
Here a test release:

https://d.keka.io/test/Keka-1.2.19-dev.r4698

It has full extraction support (not encrypted files). Compression does not yet have any option but works too, with the default settings.

I've seen there's encryption support in Monterey, will investigate more on that one.

**Comment by gingerbeardman** [comment]
See #687 

What is remaining to do for Apple Archive?

**Comment by aonez** [comment]
I'll will add support for AAR on iOS next and that will be the foundation of the enhanced support for macOS (compress multiple files. I need to create a custom compressor to not rely on `aa`/`yea`.

The idea is to make it compatible with pipes so the contents can be tarballed.

**Comment by VaslD** [comment]
> <img alt="Screen shot 2021-10-26 at 11 05 25" width="260" src="https://user-images.githubusercontent.com/49612/138857060-ff92c361-ce2d-4d1a-b9f1-3851ea3d6d6a.png">
> 
> Do you still have the shell script that I sent you ages ago?
> 
> I have workaround for this issue.

According to Apple's documentation this is no longer the case using AppleArchive framework. See [Compressing and Saving a String to the File System](https://developer.apple.com/documentation/accelerate/compressing_and_saving_a_string_to_the_file_system) (which differs from [Compressing Single Files](https://developer.apple.com/documentation/accelerate/compressing_single_files) by wrapping the compression stream in an encoder stream just like when compressing a directory, but with a manual header to provide filesystem information instead of raw file data to the archive).

The example only shows when input is `Data` (`some ContigousBytes`), in case of file-on-disk you can call `ArchiveHeader.init(keySet:directory:path:flags:)` (https://developer.apple.com/documentation/applearchive/archiveheader/3589205-init) to copy original filesystem information and make the process less manual.

I made a snippet to do what `aa` does with AppleArchive's Swift API: https://gist.github.com/VaslD/1eaee19546112b04052cfda22a3cb05d. Single file is compressed as-is without additional parent folder.
