### ISSUE TITLE
[BUG] From report alert

### ISSUE THREAD

**Issue by bil9000** [aonez/Keka#835]
Your comments here
Random error I found whie zipping csvs. 

---

NSWindow drag regions should only be invalidated on the Main Thread!

**Comment by aonez** [comment]
Thanks for sharing @bil9000! Do you remember what Keka windows you had opened? Or what were you doing it the alert moment?

**Comment by bil9000** [comment]
Hi there, to the best of my recollection I had the Keka zip window open with a password for encryption open, AES 256 selected along with the option to delete files after compression.  I'll try to grab a screenshot if I can replicate it.  It was a pretty standard operation for the software that I do all the time. (The software is great by the way. Thank you for building this.)

**Comment by aonez** [comment]
Thanks again @bil9000. I'm unable to reproduce, hopefully some more info can be shared in the future to fix this one. At least is no more a crash.

> The software is great by the way. Thank you for building this.

Thanks a lot 😄

**Comment by aonez** [comment]
#860
> I was trying to extract the multi files but then Keka found an issue, Please Fix it!

**Comment by vitorgalvao** [comment]
See the two attached ZIP files. I can reliably reproduce the error if I open both at once (select both and press <kbd>⌘</kbd><kbd>O</kbd>).

Keka 1.2.16 (4617)
macOS 11.5 (20G71)
M1 MacBook Air

[OSS_5.0_VST3_MAC.zip](https://github.com/aonez/Keka/files/6947354/OSS_5.0_VST3_MAC.zip)
[OSS_5.0_AU_MAC.zip](https://github.com/aonez/Keka/files/6947356/OSS_5.0_AU_MAC.zip)

**Comment by aonez** [comment]
Thanks @vitorgalvao! Turns out it was an async call to `[NSWorkspace.sharedWorkspace activateFileViewerSelectingURLs]`, when showing the extraction contents. Just calling it in the main thread solves the issue.

Test build: https://d.keka.io/test/Keka-v1.2.17-r4626
