### ISSUE TITLE
[REQ] Option to exclude/ignore .DS_Store and ._* files

### ISSUE THREAD

**Issue by XStylus** [aonez/Keka#839]
This is a bit of an edge case, but...

Background info:
- We have a NAS device that is configured to silently reject .DS_Store and ._* files. They are unnecessary and cause clutter and confusion on our NAS device which is used by multiple workstations across different OSes. 
- Sometimes, a ZIP file will (for whatever reason) contain .DS_Store or ._* files in addition to the desired content.

Problem: 
- When Keka is commanded to extract the contents of a ZIP file to a NAS in the above configuration, it will run into a "Permission Denied" error (as it should) when trying to extract the .DS_Store and ._* files. However, rather than continuing and extracting the desired content (at which point it _wouldn't_ get a "Permission Denied" error), it gives up completely and throws an "Error Code 2".

Solution request:
- Keka should exclude (or at least give a user-configurable option to exclude) .DS_Store and ._* files when extracting.

Here's the error log we receive when extracting:

```
OS: Version 10.15.7 (Build 19H524)
Keka: v1.2.13-r4541 (MAS) (Sandboxed) (en)
Format detected: ZIP
Binary used: kekaunar
Arguments: (
    "-q",
    "-r",
    "-K",
    "-nq",
    "-o",
    "/Volumes/USER_videotech_10.0.1.11_VIDEO - Troy's Dumpster/Temp/TPN/Test/_FINAL WORK FILES The Promised Neverland 01-12 and Extras.kextraction/Operation",
    "/Volumes/USER_videotech_10.0.1.11_VIDEO - Troy's Dumpster/Temp/TPN/_FINAL WORK FILES The Promised Neverland 01-12 and Extras.zip"
)
  
_FINAL WORK FILES The Promised Neverland 01-12/.DS_Store  (6148 B)... Failed! (Opening file failed)

  
_FINAL WORK FILES The Promised Neverland 01-12/.DS_Store  (0 B, rsrc)... Failed! (Opening file failed)

Extraction to directory "/Volumes/USER_videotech_10.0.1.11_VIDEO - Troy's Dumpster/Temp/TPN/Test/_FINAL WORK FILES The Promised Neverland 01-12 and Extras.kextraction/Operation" failed (2 files failed.)

OS: Version 10.15.7 (Build 19H524)
Keka: v1.2.13-r4541 (MAS) (Sandboxed) (en)
Format detected: ZIP
Binary used: keka7z
Arguments: (
    x,
    "/Volumes/USER_videotech_10.0.1.11_VIDEO - Troy's Dumpster/Temp/TPN/_FINAL WORK FILES The Promised Neverland 01-12 and Extras.zip",
    "-o/Volumes/USER_videotech_10.0.1.11_VIDEO - Troy's Dumpster/Temp/TPN/Test/_FINAL WORK FILES The Promised Neverland 01-12 and Extras.kextraction/Operation",
    "-aou",
    "-xr!__MACOSX"
)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,20 CPUs x64)
Modified by aONe for Keka

Scanning the drive for archives:
  0M Scan /Volumes/USER_videotech_10.0.1.11_VIDEO - Troy's Dumpster/Temp/TPN/

1 file, 113130 bytes (111 KiB)

Extracting archive: /Volumes/USER_videotech_10.0.1.11_VIDEO - Troy's Dumpster/Temp/TPN/_FINAL WORK FILES The Promised Neverland 01-12 and Extras.zip

--
Path = /Volumes/USER_videotech_10.0.1.11_VIDEO - Troy's Dumpster/Temp/TPN/_FINAL WORK FILES The Promised Neverland 01-12 and Extras.zip
Type = zip
Physical Size = 113130

  0%
ERROR: Can not open output file : Permission denied : /Volumes/USER_videotech_10.0.1.11_VIDEO - Troy's Dumpster/Temp/TPN/Test/_FINAL WORK FILES The Promised Neverland 01-12 and Extras.kextraction/Operation/_FINAL WORK FILES The Promised Neverland 01-12/.DS_Store


  2% 1


Sub items Errors: 1

Archives with Errors: 1

Sub items Errors: 1

Error code 2
```

**Comment by aonez** [comment]
Added an option to "Exclude Mac resource forks" in `Preferences` -> `Extraction`.

Check this build: https://d.keka.io/test/Keka-1.2.14.r4558

Should work, let me know it it still fails with some format.

**Comment by Blinks44** [comment]
> Added an option to "Exclude Mac resource forks" in `Preferences` -> `Extraction`.
> 
> Check this build: https://d.keka.io/test/Keka-1.2.14.r4558
> 
> Should work, let me know it it still fails with some format.

Is it possible to do this for development folders: node_modules, vendor etc.
Maybe list in settings where we can define names to exclude from archive?

**Comment by aonez** [comment]
yep @Blinks44! This should come in 1.3.0, will follow the development of the feature in your ticket #324 :)

**Comment by XStylus** [comment]
The function doesn't seem to persist between instances.

If I enable "Exclude Mac resource forks" and then quit Keka and then re-open Keka, the "Exclude Mac resource forks" is no longer enabled.

**Comment by aonez** [comment]
If you want the option to persist enable it on Keka -> Preferences. Let
me know if you still have issues with it.
