### ISSUE TITLE
[BUG]M1 Silicon Mac mini Unable to run KekaExternalHelper

### ISSUE THREAD

**Issue by andysocial21** [aonez/Keka#842]
M1 Silicon Mac mini Unable to run KekaExternalHelper

### Configuration
- Keka version:  1.2.13 (4541)
- macOS version: 11.2 Silicon Mac mini

### Describe the bug
Unable to run KekaExternalHelper message - no such app found with Find any File
Attach a log file reproducing the issue: https://github.com/aonez/Keka/wiki/Report-an-issue

**Comment by aonez** [comment]
Works for me on 11.2 with M1. If you click on "Set Keka as the default uncompressor" does it not work?

Here more info about the helper: https://github.com/aonez/Keka/wiki/Default-application#about-the-helper

It's auto installed in:

```
/Users/[YOUR_USERNAME]/Library/Containers/com.aone.keka/Data/Library/Application Support/Keka/
```

Maybe that's why you're not finding it.

**Comment by andysocial21** [comment]
Sorted - downloaded Helper !
Thanks

**Comment by aonez** [comment]
Nice!
