### ISSUE TITLE
[BUG] No way to make a password protected compression

### ISSUE THREAD

**Issue by flyonearth** [aonez/Keka#846]
Everything is in the tittle... I have set the pref windows with the password... But it doesn't apply
Big thanks !

### Configuration
- Keka version: [e.g. 1.1.24 (3421)]
- macOS version: [e.g. 10.14.6 (18G2022)]

### Describe the bug
Attach a log file reproducing the issue: https://github.com/aonez/Keka/wiki/Report-an-issue

**Comment by gingerbeardman** [comment]
It works.

Please describe the steps you are taking to 1) set the password 2) compress using Keka.

**Comment by flyonearth** [comment]
Big thanks for your answer Matt (;o)))

Here is more precisely what I do :

Launch Keka
A window appears, on which I can set the password : I repeat it and the image lock gets locked
I keep that window open when I move a directory on the keka icon -> That dir is compressed
AND YES it works that way : it asks me the password to decompress

BUT if I close the window where I have set the password
And I move the directory to the keka icon, it is compressed without password : it decompress without asking anything
And the password is lost : nothing appears it I open again that window

That means the password is lost as soon as I close the window…
Such behavior might be OK for some people… But not at all for me
I want the password to be always active, and saved across restart, and when I want to compress, keka should ask me which of 3 items I want  :
* password compress with the recorded password
* password compress with a new password
* No password

The way it works presently is to me everything but user friendly !   I have tried many times, and lost time before discovering the right way when writhing that mail.
 
Anyhow, big thanks for that very nice app, regarding all its other features

Jean Christophe



Le 8 mai 2021 à 13:20, Matt Sephton ***@***.***> a écrit :


It works.

Please describe the steps you are taking to 1) set the password 2) compress using Keka.

**Comment by gingerbeardman** [comment]
OK, now I understand. The title of the issue does not accurately describe what you are referring to. :)

Currently with Keka, password cannot be permanently set. So this would be a feature request.

**Comment by aonez** [comment]
@flyonearth as @gingerbeardman said you should set the password anytime you want to compress some files. This will be enhanced, follow this issue to know when it's implemented: #26
