### ISSUE TITLE
[BUG] Delete file(s) post compression fails with external storage

### ISSUE THREAD

**Issue by AFitch07** [aonez/Keka#847]
### Configuration
- Keka version: [1.2.13 (4541)]
- macOS version: [11.2.3 (20D91)]

### Describe the bug

From the log:  ”...couldn’t be moved to the trash because the volume “Filing Cabinet” doesn’t have one."

[Keka_2021-05-08-110128408.log](https://github.com/aonez/Keka/files/6446156/Keka_2021-05-08-110128408.log)

So, to clarify, the files do not get deleted when compressing on external storage.  It deletes files natively when everything is on the Mac only.  

I use a Synology NAS and it very much has it's own trash/recycle system.  The same CMD+BACKSPACE functions just the same when browsing NAS shares.  

### To Reproduce
1. Open Keka app
2. Check "Delete file(s) after compression"
3. Drag files (to be compressed) over app
4. Files that were compressed, do not get deleted

### Expected behavior
I expected the files I just compressed to be deleted, per the check box option that I selected.  This did not occur.

### Screenshots
Current settings when issue occurs in screenshot:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/77162853/117545465-80eb1f00-afeb-11eb-8b54-855bb9da06b6.png">

### Additional context

If there is anything else needed, let me know.

**Comment by AFitch07** [comment]
Synology uses a folder in the root of each share called "#recycle" for it's trash bin.

If my share is "Filing Cabinet" and I have a directory inside that share called "TestFolder" and a file inside called "MyFile.txt" then I go to delete the file "MyFile.txt" it will appear in the "#recycle" folder in the root of the "Filing Cabinet" share in the same folder path before it was deleted. 

### Example of structure **BEFORE** deletion of "MyFile.txt" file: 
- **Filing Cabinet**   
    - **#recycle** 
    - **SomeFolder**
    - **TestFolder**   
         - **SubFolder1**   
              - **MyFile.txt**   
    - **AnotherFolder**



### Example of structure **AFTER** deletion of only the "MyFile.txt" file: 
- **Filing Cabinet**   
    - **#recycle**
         - **TestFolder**   
              - **SubFolder1**   
              - **MyFile.txt**    
    - **SomeFolder**
    - **TestFolder**   
         - **SubFolder1**   
    - **AnotherFolder**

**Comment by aonez** [comment]
@AFitch07 and how you’ve deleted that “MyFile.txt”? With cmd+backspace via Finder? If so, did Finder told you that “[the file will be deleted immediately](https://community.synology.com/enu/forum/1/post/124664)”?

**Comment by AFitch07** [comment]
> @AFitch07 and how you’ve deleted that “MyFile.txt”? With cmd+backspace via Finder? If so, did Finder told you that “[the file will be deleted immediately](https://community.synology.com/enu/forum/1/post/124664)”?

Yes, while using Finder to browse my external NAS, I use CMD + BACKSPACE to delete a file.  This does show that exact message you stated above (similar to if you use CMD + OPTION + BACKSPACE on Mac native files)

<img width="372" alt="image" src="https://user-images.githubusercontent.com/77162853/117561013-83d02900-b058-11eb-9cea-75813e5db7be.png">

**Comment by aonez** [comment]
@AFitch07 please check this build: https://d.keka.io/test/Keka-1.2.15.r4564

If that one fixes the issue for you, let me know and simply replace your current Keka.app with it until an official release comes :)

**Comment by AFitch07** [comment]
> @AFitch07 please check this build: https://d.keka.io/test/Keka-1.2.15.r4564
> 
> If that one fixes the issue for you, let me know and simply replace your current Keka.app with it until an official release comes :)


Sorry it took a bit to test and reply.

I have tried to zip a few files on the Synology NAS with the setting checked to delete after compression.  I compressed with 7Z and ZIP to test. 

The files remain - they do not get deleted...

**Comment by aonez** [comment]
Can you check the log file?

**Comment by AFitch07** [comment]
@aonez 
[Keka_2021-05-20-110154001.log](https://github.com/aonez/Keka/files/6517301/Keka_2021-05-20-110154001.log)

**Comment by aonez** [comment]
My bad! Please check this build: https://d.keka.io/test/Keka-1.2.15.r4576

It should fix the issue, if not please share the log again, as it will output the correct error code.

**Comment by AFitch07** [comment]
All seems well.  Log is attached for your reference.  I didn't see any warnings/errors within it.  
Thank you for adding this in; much appreciated!

[Keka_2021-05-27-131935879.log](https://github.com/aonez/Keka/files/6556023/Keka_2021-05-27-131935879.log)
