### ISSUE TITLE
[REQ] KEKA website - PL 

### ISSUE THREAD

**Issue by ClusterByte-x** [aonez/Keka#849]
Hello!

I'm sending minor linguistic corrections to the website translation. In the place of the quote there is the original with the corrected phrase below it.

> Jeśli kupisz program Keka w App Store wsprzesz autora i rozwój projektu. 
> Aplikacja jest taka sama, jak wersja z tej witryny. Jest jedna aktualizowana za pośrednictwem w App Store.

Kupując program Keka w App Store wspierasz autora oraz rozwój projektu.
Aplikacja jest taka sama jak z witryny i różni się jedynie kosztem i aktualizacjami przez App Store.

> Jeśli przepadasz za zakupami w App Store 
> , możesz wesprzeć projekt również za pomocą PayPal.

Jeżeli nie przepadasz za zakupami w App Store,
możesz wesprzeć projekt również za pomocą PayPala.

> Nie musisz nawet programu, aby skompresować plik. Wystarczy, że będzie przypięty w Dock'u. 
> Aby skompresować pliki, wystarczy je przeciągnąć na ikonę lub okno programu.

Nie musisz nawet uruchamiać programu, by skompresować swoje pliki. Wystarczy, że Keka będzie przypięta w Dock'u, gdzie wystarczy przeciągnąć na nią ikonkę lub okno programu.

> Udostępniaj bezpiecznie dzięki plikom zaszyfrowanym.

Udostępniaj bezpiecznie dane dzięki zaszyfrowanym plikom. 

> Set Keka as the default extraction application
> Keka needs a helper  to set itself as the default application.
> Simply download and extract it, move it to the desktop and then open it.

Ustaw Keka jako domyślną aplikację do wypakowania skompresowanych plików 

W tym celu potrzebujesz zainstalować **program pomocniczy**, aby móc ustawić Keka jako domyślną aplikację.
Po prostu pobierz i rozpakuj plik, przenieść na pulpit i otwórz.

**Comment by aonez** [comment]
Thanks @ClusterByte-x! What do you think @lboratynski?

**Comment by lboratynski** [comment]
Fine. I updated the translation using @ClusterByte-x suggestions. I am open to any suggestions. Don't hesitate to call me @aonez! 👍

**Comment by aonez** [comment]
Merged in https://github.com/aonez/Keka/pull/851. Thanks again!
