### ISSUE TITLE
[BUG] Adding Password Protection to Files on Mac Partially Works in Windows

### ISSUE THREAD

**Issue by wkhan69** [aonez/Keka#854]
### Configuration
- Keka version: [e.g. 1.1.24 (3421)]
- macOS version: [e.g. 10.14.6 (18G2022)]

### Describe the bug
When you create a password-protected .zip archive in Mac, it works fine.  You cannot open the archive with other compression/decompression utilities (that I've tried), without the password.  You cannot even look at the filenames within the archive in the Mac without the password.  However, when you take the same archive in a windows environment, you can see everything with any zip utility, even all the sub-folder and filenames.  Note: when you create a password-protected .zip archive in windows using 7-zip, you can't see anything inside the archive without the password, whether you try in windows or Mac.

### To Reproduce

1. In your Mac, choose a folder to archive that has several subfolders and files within each subfolder.  
2. Create a .zip archive of the main folder using Keko, with password protection.  
3. Copy the archive to a windows 10 PC
4. Open the archive using 7-zip or any other archive-extractor

### Expected behavior
-With 7-zip in windows, without entering the password, it SHOULD NOT allow you to navigate or view inside the archive and see all the folders & files.  The issue is that you can see the filename and folder structure without entering a password.
-You shouldn't be able to extract the files without the password, which is working correctly

**Comment by aonez** [comment]
Take a look at https://github.com/aonez/Keka/issues/592#issuecomment-662084612
