### ISSUE TITLE
Split compression fails on Dropbox folder

### ISSUE THREAD

**Issue by JingleDjango** [aonez/Keka#859]
I'm unable to generate multi-part archives of this directory. I'm using the same disk for source/destination. 700GB+ free on the disk. The log posted below concerns TAR files but I've tried ZIP, 7zip and GZIP as well. Generating a single-part archive seems to work but I need to part out the archive for delivery via web. Could this be a permissions issue? Is there something else I'm missing?

7zip doesn't fail with an error. Instead I get a notification indicating the archive is ready but the destination folder is empty.

![Screen Shot 2021-06-11 at 14 20 42](https://user-images.githubusercontent.com/12893739/121732413-3f550480-cac0-11eb-809d-35aa97d00ca7.png)

![Screen Shot 2021-06-11 at 14 11 12](https://user-images.githubusercontent.com/12893739/121731473-fd778e80-cabe-11eb-830c-5b60795a7442.png)

`OS: Version 10.14.6 (Build 18G87)
Keka: v1.2.14-r4561 (WEB) (Sandboxed) (en)
Binary used: kekatar
Arguments: (
    "-Kcf",
    "/Volumes/Work/Dropbox/Projects/REDACTED/EditSessionArchive20200611.tar",
    "--no-mac-metadata",
    "--no-xattrs",
    "--exclude=.DS_Store",
    "--exclude=.localized",
    "--exclude=._*",
    "--exclude=.FBC*",
    "--exclude=.Spotlight-V100",
    "--exclude=.Trash",
    "--exclude=.Trashes",
    "--exclude=.background",
    "--exclude=.TemporaryItems",
    "--exclude=.fseventsd",
    "--exclude=.com.apple.timemachine.*",
    "--exclude=.VolumeIcon.icns",
    "-C",
    "/Volumes/Work/Dropbox/Projects/REDACTED/",
    EditSessionArchive20200611
)
kekatar: Failed to open '/Volumes/Work/Dropbox/Projects_Active/REDACTED/EditSessionArchive20200611.tar'

Error code 1`

I understand that I could split/cat a single large archive but I'm trying to avoid sending a shell illiterate client to the terminal. Much less stressful for them if I can say to download keka and double-click.

**Comment by aonez** [comment]
Could you try compressing that folder with a destination outside the
Dropbox folder? For example in the root of your Work volume.

**Comment by JingleDjango** [comment]
Thanks for your reply. I was able to create a split archive in the root of that volume. Before doing so I manually granted access to that volume in the keka prefs but I didn't check whether it was in the access list already before doing that so it may be irrelevant.

**Comment by aonez** [comment]
Probably the Dropbox app is messing with the newly created file in a way Keka can't continue the process. I might do some more research about this issue.

Thanks a lot for the feedback @JingleDjango!

**Comment by JingleDjango** [comment]
@aonez Thanks for the great free tool and for your attention.
