### ISSUE TITLE
b4 hangs during delete package

### ISSUE THREAD

**Issue by DasBlatz** [aonez/Keka#88]
seemed that the b4 can’t delete the packages anymore? 

![bildschirmfoto 2017-10-18 um 12 18 14](https://user-images.githubusercontent.com/398669/31713559-eaa32d9e-b3fe-11e7-8a49-f675d5a372e6.png)

and I need to force close the app to get the progress bar away
![bildschirmfoto 2017-10-18 um 12 18 56](https://user-images.githubusercontent.com/398669/31713564-ed68a63a-b3fe-11e7-8c59-7a658b880575.png)

**Comment by aonez** [comment]
Good catch! There's in fact a bug here...

**Comment by aonez** [comment]
Already fixed. Will publish a new beta later today or tomorrow morning with this fix 🤓
