### ISSUE TITLE
[BUG]endless extracting time wo result

### ISSUE THREAD

**Issue by AliBengali21** [aonez/Keka#884]
### Configuration
- Keka version: [e.g. 1.1.15 (4583)]
- macOS version: [e.g. 10.15.7 (18G2022)]

### Describe the bug
I try to extract .zip-files. The extraction starts, but wo any development.
[Keka_2021-06-30-094138551.log](https://github.com/aonez/Keka/files/6739015/Keka_2021-06-30-094138551.log)

### Expected behavior
I wanted to receive a 300GB-Folder with many photographs

**Comment by aonez** [comment]
The log states that the operation was cancelled.

Does the operation start and then you cancel it? Note that a 300GB file will take some time to extract. There's no progress bar or time estimation?

**Comment by AliBengali21** [comment]
I cancelled after 10 minutes wo any progress in the progress bar. No time estimation either, only the amount of time spent extracting is shown. I will try being more patient with the extracting, but after which timespan do you think the progress bar should show some progress?

**Comment by aonez** [comment]
I depends on your configuration, for an extraction is depends a lot on your destination disk (SSD or HDD). You can check the Activity Monitor, filter it with "Keka" and see if it's doing work there.

A 300GB file extraction with a slow disk (HDD) could take hours. 1% of the progress could be more than half an hour... Try extracting it to a different disk (if you have multiple) and to the one that has the best write speed.

Let me know how it goes.

**Comment by AliBengali21** [comment]
Shame on me! I did not expect anything to happen, but after 4h it was completely extracted. Although after 1h there still was no progression in the bar visible. 
Sorry for being so impatient and thank you for your excellent work!!!

**Comment by aonez** [comment]
Glad it helped 😊
