### ISSUE TITLE
When there is an error while compressing, original files should not be sent to the Bin

### ISSUE THREAD

**Issue by victor** [aonez/Keka#885]
I encountered a disk full error when compressing some folders, with the option to move the original files to the Bin after compression. This option should only be honored on successful compression, to avoid data loss and an easier retry.

One could argue that the files in the Bin are not lost and the can be recovered easily, but that is not entirely true: there may be many similarly named files in the bin and finding the correct ones may prove complicated. Also, one of the first things one can do irreflexively (meaning, I did it) is to empty the Bin, to gain disk space. Doing this ensures there's no trace of the original source files to retry compression after gaining some disk space

**Comment by aonez** [comment]
It's set to only remove files if the operation works properly. I'll test if a disk full error bypasses somehow this.

**Comment by aonez** [comment]
@victor what format and setting were you using?

**Comment by victor** [comment]
Format was 7z, with slow, max compression.

**Comment by aonez** [comment]
I've detected the issue, fixed for next revision, coming in a few. Thanks a lot @victor!

**Comment by victor** [comment]
glad to be of service 

Enviat des del meu iPhone

**Comment by aonez** [comment]
@victor, as a followup:

This should be fixed in the upcoming 1.2.16. Test build: [Keka-1.2.16.r4608.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.2.16.r4608.7z)

There was an issue detecting the error codes that has been reported in various ways (#891 #883 #885). Thanks a lot for the feedback!
