### ISSUE TITLE
[BUG] Keka fails to report broken multipart rar extraction

### ISSUE THREAD

**Issue by ImreLovasz** [aonez/Keka#891]
### Configuration
- Keka version: 1.2.15 (4583)
- macOS version: 11.4 (20F71)

### Describe the bug
Keka reports successful extraction, even though it failed to extract all the files, and it logs the checksum error in the log:

> \nExtracting  *.mp3     41%",
>     "\n*.mp3 - checksum error",
>     "\nCorrupt header is found",
>     "\n"
> )

### To Reproduce
This is happening to large, multipart rar archives

### Expected behavior
Report the found error(s) instead of reporting successfull extraction

### Additional context
Tested with cli rar, and the downloaded file is broken indeed.

**Comment by aonez** [comment]
@ImreLovasz is it possible to share those file to test? Here or at info@keka.io.

Thanks!

**Comment by ImreLovasz** [comment]
Hi,
The CRC checksum error introduced during downloading (probably a server issue, or something like that - re-downloading the file fixed it), and the files are pretty huge (like 4 GB), so it's quite hard to reproduce this issue.
To make it even more elusive, it's not happening all the time, as a matter of fact, Keka usually reports broken files just fine, in my experience.

Cheers,
Imre

**Comment by aonez** [comment]
This should be fixed in the upcoming 1.2.16. Test build: [Keka-1.2.16.r4608.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.2.16.r4608.7z)

There was an issue detecting the error codes that has been reported in various ways (#891 #883 #885). Thanks a lot for the feedback!

**Comment by ImreLovasz** [comment]
Thank you!
