### ISSUE TITLE
All Keka CLI utils fail with "Illegal Instruction: 4" and no gui extraction works

### ISSUE THREAD

**Issue by MisterC925** [aonez/Keka#893]
Helping an fellow employee.  They have a 2020 Macbook Pro (4 port model) with MacOS 11.4.  We installed Keka 1.2.15 and it failed with error on GUI extractions so I dug deeper and all of the CLI utils give either a "illegal hardware instruction  /Applications/Keka.app/Contents/MacOS/keka7z" when run as a user or "Illegal Instruction: 4" when run as root.

Any suggestions?

Thanks!

**Comment by aonez** [comment]
Since all binaries inside Keka are sandboxed, you can’t run them directly.

You can run them like this:

https://github.com/aonez/Keka/wiki/Terminal-client

What errors where they getting using the GUI?

**Comment by MisterC925** [comment]
Thanks I wasn't aware of that.  The error when running is an error 2 on p7zip.

I downloaded p7zz separately and it was unable to fully process the archive in question so it may just be too big and/or corrupted.   I'll try again with the sandbox method and let you know how it goes, either way.

Thanks
