### ISSUE TITLE
[BUG]errorcode 2 use“p7zip” error

### ISSUE THREAD

**Issue by AaronWing** [aonez/Keka#894]
OS: version11.2.3（version20D91）
Keka: v1.2.15-r4583 (WEB) (Sandboxed) (zh-Hans)
Format detected: Unknown
Binary used: keka7z
Arguments: (
    x,
    "/s/git.zip",
    "-o/Users/s/git.kextraction/Operation",
    "-aou",
    "-xr!__MACOSX"
)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,12 CPUs x64)
Modified by aONe for Keka

Scanning the drive for archives:
  0M Scan /Users/s/

1 file, 4649269894 bytes (4434 MiB)

Extracting archive: /Users/git.zip
  0% Open
ERROR: /Users/git.zip

  0%
/Users/git.zip
Open ERROR: Can not open the file as [zip] archive

ERRORS:
Is not archive

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

Error code 2

**Comment by aonez** [comment]
Hi @AaronWing! Seems from the log that the file is not a ZIP file. Can you check with the bundled macOS extraction tool?

**Comment by yemane10** [comment]
Hello, i am also getting the same error message. i am trying to extract a multi tar file in the same folder where the tar files exist. 

thanks 

OS: Version 10.14.6 (Build 18G103)
Keka: v1.2.16-r4617 (MAS) (Sandboxed) (en)
Format detected: Unknown
Binary used: keka7z
Arguments: (
    x,
    "/Users/mac/Downloads/Spitfire Audio Olafur Arnalds Stratus/Spitfire Audio Olafur Arnalds Stratus.tar.001",
    "-o/Users/mac/Downloads/Spitfire Audio Olafur Arnalds Stratus/Spitfire Audio Olafur Arnalds Stratus.tar.kextraction/Operation",
    "-aou",
    "-xr!__MACOSX"
)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,12 CPUs x64)
Modified by aONe for Keka

Scanning the drive for archives:
  0M Scan /Users/mac/Downloads/Spitfire Audio Olafur Arnalds Stratus/

ERROR: 

No more files
/Users/mac/Downloads/Spitfire Audio Olafur Arnalds Stratus/Spitfire Audio Olafur Arnalds Stratus.tar.001



System ERROR:
Unknown error: -2147024872

Error code 2
