### ISSUE TITLE
keka version 1.2.15, MAC High Sierra.  Got an error 2 message when extracting US_pacific_osm-topo-v33.7z[BUG]

### ISSUE THREAD

**Issue by iahawkeyes** [aonez/Keka#899]
### Configuration
- Keka version: [e.g. 1.1.24 (3421)]
- macOS version: [e.g. 10.14.6 (18G2022)]

### Describe the bug
Attach a log file reproducing the issue: https://github.com/aonez/Keka/wiki/Report-an-issue

**Comment by aonez** [comment]
Can you share the link to that file?

**Comment by iahawkeyes** [comment]
Sure. Thanks.

https://www.gmaptool.eu/en/content/usa-osm-topo-routable <https://www.gmaptool.eu/en/content/usa-osm-topo-routable>

Here are the 7z files I’m trying to extract as downloaded to my Mac.

**Comment by iahawkeyes** [comment]
And here is the error description.

OS: Version 10.13.6 (Build 17G65)
Keka: v1.2.15-r4583 (MAS) (Sandboxed) (en)
Format detected: Unknown
Binary used: keka7z
Arguments: (
    x,
    "/Users/garygeil/Desktop/USA OSM Topo Routable/US_Pacific_OSM_Topo_v33.7z",
    "-o/Users/garygeil/Desktop/USA OSM Topo Routable/US_Pacific_OSM_Topo_v33.kextraction/Operation",
    "-aou",
    "-xr!__MACOSX"
)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)
Modified by aONe for Keka

Scanning the drive for archives:
  0M Scan /Users/garygeil/Desktop/USA OSM Topo Routable/

1 file, 0 bytes

Extracting archive: /Users/garygeil/Desktop/USA OSM Topo Routable/US_Pacific_OSM_Topo_v33.7z

ERROR: /Users/garygeil/Desktop/USA OSM Topo Routable/US_Pacific_OSM_Topo_v33.7z

  0%
Can not open the file as archive



Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

Error code 2


Gary Geil
Sales Engineer
O: 949-361-0212

**Comment by aonez** [comment]
@iahawkeyes I'm having no issue extracting the files. Note that this is a multi part file:

- USA_OSM_Topo_v33.7z.001
- USA_OSM_Topo_v33.7z.002
- USA_OSM_Topo_v33.7z.003
- USA_OSM_Topo_v33.7z.004
- USA_OSM_Topo_v33.7z.005

You need all five parts to be able to extract the contents.

<img width="853" alt="Screen Shot 2021-07-16 at 11 09 51" src="https://user-images.githubusercontent.com/480163/125923609-8356d0a4-78bd-4f58-a8a6-c097bd7e66cb.png">

I'm not sure if you downloaded only one part and removed the 00X extension?
