### ISSUE TITLE
Unexpected end of archive[RESOLVED]

### ISSUE THREAD

**Issue by routineCode** [aonez/Keka#908]
I'm unable to extract a multi-part archive. I've tried several things, including granting Keka access to home/desktop/downloads and putting the files in those locations before extracting. I always get the same "unexpected end of archive" error, shown in the error log below.

Thanks for any help

OS: Version 11.5.1 (Build 20G80)
Keka: v1.2.16-r4617 (WEB) (Sandboxed) (en-GB)
Format detected: ZIP (7Z)
Binary used: keka7z

ERRORS:
Unexpected end of archive

**Comment by routineCode** [comment]
I found the problem: I thought there were only 3 parts to the archive, but there were 4.

I suggest a more helpful error message, providing if possible, the number of parts that should be in the archive.

**Comment by aonez** [comment]
Thanks for the feedback @routineCode, indeed more volume info should be displayed.
