### ISSUE TITLE
Error code 10 using "unrar" No files matching the mask

### ISSUE THREAD

**Issue by MaverickStout** [aonez/Keka#91]
Please help me extract this file!

https://drive.google.com/open?id=0B4Vj_7DqobcNQi1yejI2RHFCUU0

Password = AUDIOSTRIKE

**Comment by MaverickStout** [comment]
P.S: I'm using Mac OSX 10.10.5

**Comment by aonez** [comment]
Wether the file is corrupt or most probably the password is incorrect. Are you sure this is the right password?
