### ISSUE TITLE
Default Compression Path cleared if unfound

### ISSUE THREAD

**Issue by Obatics** [aonez/Keka#914]
### Is your feature request related to a problem? Please describe
I set the default destination for Compression to a server. The server may not always be available. The default needs to be set each time it's not found.

### Describe the solution you'd like
Go to "Ask" when path not available but should return to setting when path is available again

**Comment by aonez** [comment]
Totally agree with that one. Already fixed it for the upcoming 1.2.17 version, here you can test it:

https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.17-r4628.7z

**Comment by aonez** [comment]
Fixed in 1.2.17 release
