### ISSUE TITLE
[REQ] add Quick Look preview for archive files

### ISSUE THREAD

**Issue by sbarex** [aonez/Keka#915]
It would be fantastic to be able to view the list of files (path, attributes, size) contained in an archive through the macOS Quick Look window.

**Comment by aonez** [comment]
This one needs #100 first. No timeline yet.

**Comment by Rorschach111** [comment]
_I found a[ plugin](https://findergg.com/) is very useful for all the quicklook needs._ from [Jax0rz](https://github.com/Jax0rz). Maybe you'll find this useful.

**Comment by aonez** [comment]
Nice one
