### ISSUE TITLE
Support for .wpress archive — Wordpress Backup made with All-in-One WP Migration

### ISSUE THREAD

**Issue by porg** [aonez/Keka#919]
## Foreword
- There's a .wpress decompressing tool for Mac/Windows/Linux: https://traktor.wp-migration.com
- It also provides the source code: https://github.com/servmask/Qtraktor

## Feature Request
Would be cool if Keka as my favorite Mac archiving app could:
- Add decompression support
- Add support to also decompress automatically if wrapped in another archive, i.e. `backup.wpress.7z`
  - Because the .wpress is
    - a) uncompressed,
    - b) has some null-character-padding,
    - c) maybe also additionaly metadata/revision info etc,
  - which in total makes it even significantly larger than the uncompressed folder! See here:
 
<img width="828" alt="wPress Archive" src="https://user-images.githubusercontent.com/737143/136596150-9072b395-40a5-4dd2-824f-a32d11a8fa07.png">

**Comment by aonez** [comment]
@porg are you abre to provide an example` .wpress` backup file?

**Comment by aonez** [comment]
Missing the format icon yet, but here a build that supports `wpress` extraction: https://d.keka.io/test/Keka-v1.2.19-r4664



> * Add support to also decompress automatically if wrapped in another archive

This one will eventually be implemented in https://github.com/aonez/Keka/issues/337, but no timeline for it.

**Comment by aonez** [comment]
The icon will be made using the current Keka style, plain icon with the extension on bottom. I could use that blue from the ServMask icon :)

By the way I was unable to use the `time` information in the `.wpress`. It's informed for every entry in a format I did not quickly recognized and all implementations I've seen (Traktor included) just ignore that information. Maybe you could let me know the modification date of "package.json" (in the server) so I can do some more tests knowing the actual data. Any other included file will do too, just "package.json" is the first one in the backup.

**Comment by porg** [comment]
## Icon is two-fold here
- On the one side the icon you may use in-app
- and on the other side what icon the Finder (and other integrations of icon via API such as in window titles) shows for a certain file type (Uniform Type Identifier).

## Please help me clarify
- AFAIR on macOS certain general public filetypes (i.e. RTF, JPG, MP4) get their Finder file type icons from the OS. And then apps themselves can provide icons for file-types in their manifest, which Finder then utilizes, if the app is set as the default or specific file handler.
- At first glance Traktor.app does not look like a native macOS app, but rather as if an app-wrapper built by some cross platform app builder. With indications like i.e. in this my request servmask/Qtraktor#1 
- Ofc if would be better if Qtraktor as the official .wpress decompressing app would offer the proper manifest+icons, but I doubt this to happen quickly.
- So if the author agrees, could you include Finder file-type icons and also the string how the Finder refers to this file type? So instead of generically being called "Keka Document" could it be shown as "Wordpress All-in-One Backup" ?

**Comment by porg** [comment]
1. Even better as the tinting-color of your Keka-file-icon-template is the only type specific hint we don't have to ask for copyright-permission at all. Yes the blue from ServMask should work. Its hue should be somewhere inbetween BZIP2 and ZSTD, hopefully still distinguishable enough.
2. So this icon will be used both in-app (destination format chooser) and for its Finder file type representation then?
- If so please name it "Wordpress All-in-One Backup" in the manifest.
3. If we have compiled and tested another version, would you like me to communicate to ServMask?

**Comment by aonez** [comment]
The ones below are grey on plugin blue and ServMask logo's blue on blue.

This one is grey on WordPress blue:

<img width="537" alt="Screen Shot 2021-10-13 at 21 20 12" src="https://user-images.githubusercontent.com/480163/137199144-539aabf8-609d-44f1-be39-23739cdadcca.png">

**Comment by porg** [comment]
Great, let's take this one.

**Comment by porg** [comment]
Yes, ok, take that one!

**Comment by aonez** [comment]
Here the latest build:
https://d.keka.io/test/Keka-1.2.19-dev.r4698

**Comment by porg** [comment]
✅ **Closing**: This feature was included in release 1.2.50 (4808)
