### ISSUE TITLE
[BUG] - macOS Monterey - corrputed external disks icons in finder

### ISSUE THREAD

**Issue by kapitainsky** [aonez/Keka#938]
### Configuration
- Keka version:  1.2.18 (4662)
- macOS version: 12.0.1

### Describe the bug
When  Finder extension "Keka finder integration" is enabled external disks icons are corrupted.

![pk13sz7apfz51](https://user-images.githubusercontent.com/15635386/139635256-5e1c0ef7-31d8-4d43-b8da-26cfe97452c6.jpeg)

see Backup and Data icons - instead of disk icon it is some generic one.

### To Reproduce
1. Enable "Keka finder integration" in system preferences -> extensions

<img width="780" alt="Screenshot 2021-11-01 at 07 19 23" src="https://user-images.githubusercontent.com/15635386/139635697-b398e19f-531c-4fba-a121-603949f37091.png">

2. Relaunch finder e.g. go to force quit from apple menu, select finder and relaunch

When extension is disabled icons are not corrupted.

**Comment by aonez** [comment]
Take a look at this: https://github.com/aonez/Keka/issues/667

It's an issue in macOS, introduced in Big Sur and still present in Monterey as it seems. Please report to Apple if you want they to fix it.

**Comment by aonez** [comment]
I'm closing this one in favor of #667. Thanks for reporting @kapitainsky!
