### ISSUE TITLE
Error code 2 using "p7zip" Fatal Error

### ISSUE THREAD

**Issue by hmcw25** [aonez/Keka#956]
Hi i am trying to extract a 5.4 MB file with Keko. 

It keeps saying the error:  Error code 2 using "p7zip" Fatal Error

Can anyone help me.

**Comment by aonez** [comment]
Can you check the log of the extraction in the warning symbol, once it failed, and paste it here.

Also if it's not a private file just share it here or at info@keka.io.

**Comment by hmcw25** [comment]
OS: Version 10.13.6 (Build 17G14042)
Keka: v1.2.18-r4662 (MAS) (Sandboxed) (en-GB)
Format detected: RAR Legacy
Binary used: kekaunrar
Arguments: (
    x,
    "-idcd",
    "-kb",
    "-x*/__MACOSX",
    "-y",
    "/Users/hannahmills/Downloads/WickHunterBinance 2/WickHunter.Binance 2.exe",
    "/Users/hannahmills/Downloads/WickHunterBinance 2/WickHunter.Binance 2.kextraction/Operation/"
)

/Users/hannahmills/Downloads/WickHunterBinance 2/WickHunter.Binance 2.exe is not RAR archive

No files to extract

OS: Version 10.13.6 (Build 17G14042)
Keka: v1.2.18-r4662 (MAS) (Sandboxed) (en-GB)
Format detected: RAR Legacy
Binary used: keka7z
Arguments: (
    x,
    "/Users/hannahmills/Downloads/WickHunterBinance 2/WickHunter.Binance 2.exe",
    "-o/Users/hannahmills/Downloads/WickHunterBinance 2/WickHunter.Binance 2.kextraction/Operation",
    "-aou",
    "-xr!__MACOSX"
)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)
Modified by aONe for Keka

Scanning the drive for archives:
  0M Scan /Users/hannahmills/Downloads/WickHunterBinance 2/

1 file, 5553681 bytes (5424 KiB)

Extracting archive: /Users/hannahmills/Downloads/WickHunterBinance 2/WickHunter.Binance 2.exe
  0% Open
ERROR: /Users/hannahmills/Downloads/WickHunterBinance 2/WickHunter.Binance 2.exe


Can not open the file as archive


 98%

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

Error code 2

**Comment by aonez** [comment]
It's seems that the file is broken. If you've downloaded it try downloading it again.

**Comment by aonez** [comment]
Any luck?

**Comment by desmortum** [comment]
7z files work like a charm for me, even with huge files, maximum compression and password.

**Comment by rkleps** [comment]
I've used Keka for several months with no problem. I'm zipping ~200Mb files regularly, but today I get the p7zip error for several similar files. I trashed that Keka and downloaded a new copy and got the same error. Below is copy of the error code.
>>>>>>
OS: Version 11.3.1 (Build 20E241)
Keka: v1.2.18-r4662 (MAS) (Sandboxed) (en)
Binary used: keka7z
Arguments: (
    a,
    "-tzip",
    "-mx5",
    "-xr!.DS_Store",
    "-xr!.localized",
    "-xr!._*",
    "-xr!.FBC*",
    "-xr!.Spotlight-V100",
    "-xr!.Trash",
    "-xr!.Trashes",
    "-xr!.background",
    "-xr!.TemporaryItems",
    "-xr!.fseventsd",
    "-xr!.com.apple.timemachine.*",
    "-xr!.VolumeIcon.icns",
    "/Volumes/RAW WELLS/Wells MF 5 diet raw+mzML 211014/MFS/MS1134.mzML.zip",
    "/Volumes/RAW WELLS/Wells MF 5 diet raw+mzML 211014/MFS/MS1134.mzML"
)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs LE)
Modified by aONe for Keka

Scanning the drive:
  0M Scan
1 file, 269457771 bytes (257 MiB)

Creating archive: /Volumes/RAW WELLS/Wells MF 5 diet raw+mzML 211014/MFS/MS1134.mzML.zip

Items to compress: 1

  0%



System ERROR:
E_FAIL

Error code 2
>>>>>>>

Please email me at rkleps@yahoo.com

**Comment by aonez** [comment]
Does the problem occur if you use TAR or ZSTD formats instead of ZIP?
Different error logs?

If you can share any of those files with me it will be helpful to test.

**Comment by rkleps** [comment]
I just tried the new Keka on data files that worked fine earlier today and it failed.
AM testing now tar and zstd

**Comment by aonez** [comment]
Also try restarting the Mac, sometimes the sandbox system gets annoying.

**Comment by rkleps** [comment]
Both failed. Errors below

>>>>>>>>>>>>>>>>> using TAR format below

OS: Version 11.3.1 (Build 20E241)
Keka: v1.2.18-r4662 (MAS) (Sandboxed) (en)
Binary used: kekatar
Arguments: (
    "-Kcf",
    "/Volumes/RAW WELLS/Wells MF 5 diet raw+mzML 211014/MFM/FM1166.mzML.tar",
    "--no-mac-metadata",
    "--no-xattrs",
    "--exclude=.DS_Store",
    "--exclude=.localized",
    "--exclude=._*",
    "--exclude=.FBC*",
    "--exclude=.Spotlight-V100",
    "--exclude=.Trash",
    "--exclude=.Trashes",
    "--exclude=.background",
    "--exclude=.TemporaryItems",
    "--exclude=.fseventsd",
    "--exclude=.com.apple.timemachine.*",
    "--exclude=.VolumeIcon.icns",
    "-C",
    "/Volumes/RAW WELLS/Wells MF 5 diet raw+mzML 211014/MFM/",
    "FM1166.mzML"
)
kekatar: Write error

Error code 1

>>>>>>>>>>using ZSTD below
OS: Version 11.3.1 (Build 20E241)
Keka: v1.2.18-r4662 (MAS) (Sandboxed) (en)
Binary used: kekatar
Arguments: (
    "--use-compress-program",
    "\"/Applications/Keka.app/Contents/MacOS/kekazstd\" -4 -T8",
    "-Kcf",
    "/Volumes/RAW WELLS/Wells MF 5 diet raw+mzML 211014/MFM/FM1166.mzML.tar.zst",
    "--no-mac-metadata",
    "--no-xattrs",
    "--exclude=.DS_Store",
    "--exclude=.localized",
    "--exclude=._*",
    "--exclude=.FBC*",
    "--exclude=.Spotlight-V100",
    "--exclude=.Trash",
    "--exclude=.Trashes",
    "--exclude=.background",
    "--exclude=.TemporaryItems",
    "--exclude=.fseventsd",
    "--exclude=.com.apple.timemachine.*",
    "--exclude=.VolumeIcon.icns",
    "-C",
    "/Volumes/RAW WELLS/Wells MF 5 diet raw+mzML 211014/MFM/",
    "FM1166.mzML"
)
kekatar: 
Can't write to program: "/Applications/Keka.app/Contents/MacOS/kekazstd" -4 -T8

zstd: error 25 : Write error : Broken pipe (cannot write compressed block) 

Error code 1

**Comment by rkleps** [comment]
will try MAC  restart

**Comment by rkleps** [comment]
MAC restarted. Keka set to ZIP. Tried compressions > error below.

OS: Version 11.3.1 (Build 20E241)
Keka: v1.2.18-r4662 (MAS) (Sandboxed) (en)
Binary used: keka7z
Arguments: (
    a,
    "-tzip",
    "-mx5",
    "-xr!.DS_Store",
    "-xr!.localized",
    "-xr!._*",
    "-xr!.FBC*",
    "-xr!.Spotlight-V100",
    "-xr!.Trash",
    "-xr!.Trashes",
    "-xr!.background",
    "-xr!.TemporaryItems",
    "-xr!.fseventsd",
    "-xr!.com.apple.timemachine.*",
    "-xr!.VolumeIcon.icns",
    "/Volumes/RAW WELLS/Wells MF 5 diet raw+mzML 211014/MFM/FM1166.mzML.zip",
    "/Volumes/RAW WELLS/Wells MF 5 diet raw+mzML 211014/MFM/FM1166.mzML"
)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs LE)
Modified by aONe for Keka

Scanning the drive:
  0M Scan
1 file, 269952750 bytes (258 MiB)

Creating archive: /Volumes/RAW WELLS/Wells MF 5 diet raw+mzML 211014/MFM/FM1166.mzML.zip

Items to compress: 1

  0%



System ERROR:
E_FAIL

Error code 2

**Comment by aonez** [comment]
Can you check compressing the file in another disk? The probably the issue is with that external disk.

**Comment by rkleps** [comment]
Will test other disk now

**Comment by rkleps** [comment]
VERY interesting!

Tried 80Mb data file on main disk   worked ok

Copied file that failed from thumbdrive to main disk and it worked fine.

Do you have possible explanation?

**Comment by aonez** [comment]
What format has that external drive? Has write access? Can you create a folder on it?

**Comment by rkleps** [comment]
VERY VERY STUPID of me.

I filled the thumb drive. There was no room for the zipped file on the thumb drive.

I zipped the 200Mb file and STORED it on main disk with no problem.

Sorry about that. I really appreciate the fast replies.

Rob

**Comment by aonez** [comment]
No problem Rob! Have a nice weekend 😉

**Comment by rkleps** [comment]
I will now.
Thanks.
Rob

    On Friday, November 19, 2021, 11:59:33 AM CST, aONe ***@***.***> wrote:  
 
 


No problem Rob! Have a nice weekend 😉
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mnohai-mdsol** [comment]
I'm getting the same issue while trying to zip up 200+ folders. However, if I put the 200+ folders in a single folder, I can zip that single folder without issue. I'm using Zip compression, however, issue also occurs for 7Zip. GZip works okay.
```
OS: Version 10.15.7 (Build 19H1419)
Keka: v1.2.50-r4808 (WEB) (Sandboxed) (en)
Binary used: keka7z
Arguments: (
    a,
    "-tzip",
    "-mx5",
    "/Users/mnohai/Downloads/uploads/3 of 3/Archive.zip",
    "@FT_MCC-261190",
    "@FT_MCC-265263",
    "@FT_MCC-267263",
    "@FT_MCC-271428",
    "@FT_MCC-274896_MCC-274884",
    "@FT_MCC-276241",
    "@FT_MCC-276336",
    "@FT_MCC-277054",
    "@FT_MCC-279842",
    "@FT_MCC-283244",
    "@FT_MCC-285360",
    "@FT_MCC-290423",
    "@FT_MCC-305215",
    "@FT_MCC-310253",
    "@FT_MCC-312187_Rave",
    "@FT_MCC-312206",
    "@FT_MCC-312746_CustomFunctionsMigration.feature",
    "@FT_MCC-314597",
    "@FT_MCC-314597_TSDV",
    "@FT_MCC-314846",
    "@FT_MCC-314849",
    "@FT_MCC-314970",
    "@FT_MCC-315284",
    "@FT_MCC-334489",
    "@FT_MCC-334490",
    "@FT_MCC-334491_MCC-334492",
    "@FT_MCC-335576",
    "@FT_MCC-335713",
    "@FT_MCC-339303",
    "@FT_MCC-340319",
    "@FT_MCC-340320",
    "@FT_MCC-342197",
    "@FT_MCC-342682",
    "@FT_MCC-345168",
    "@FT_MCC-346043",
    "@FT_MCC-347122",
    "@FT_MCC-347122-Courier_1_1",
    "@FT_MCC-347122-Courier_1_2",
    "@FT_MCC-347122-Courier_2_1",
    "@FT_MCC-347122-Courier_2_2",
    "@FT_MCC-347122-Helvetica_1_1",
    "@FT_MCC-347122-Helvetica_1_2",
    "@FT_MCC-347122-Helvetica_2_1",
    "@FT_MCC-347122-Helvetica_2_2",
    "@FT_MCC-347122-HelveticaEmbedded_1_1",
    "@FT_MCC-347122-HelveticaEmbedded_1_2",
    "@FT_MCC-347122-HelveticaEmbedded_2_1",
    "@FT_MCC-347122-HelveticaEmbedded_2_2",
    "@FT_MCC-347122-TimesRoman_1_1",
    "@FT_MCC-347122-TimesRoman_1_2",
    "@FT_MCC-347122-TimesRoman_2_1",
    "@FT_MCC-347122-TimesRoman_2_2",
    "@FT_MCC-350318",
    "@FT_MCC-354690",
    "@FT_MCC-354691",
    "@FT_MCC-359126",
    "@FT_MCC-360647",
    "@FT_MCC-364805",
    "@FT_MCC-366118",
    "@FT_MCC-370460",
    "@FT_MCC-372243",
    "@FT_MCC-372905",
    "@FT_MCC-373115",
    "@FT_MCC-378258",
    "@FT_MCC-379684",
    "@FT_MCC-385822",
    "@FT_MCC-387672",
    "@FT_MCC-392431",
    "@FT_MCC-392733",
    "@FT_MCC-398568",
    "@FT_MCC-404143",
    "@FT_MCC-404450",
    "@FT_MCC-404580",
    "@FT_MCC-406232_MCC-427178",
    "@FT_MCC-407018",
    "@FT_MCC-410575",
    "@FT_MCC-417345",
    "@FT_MCC-419774",
    "@FT_MCC-427884_RaveBlockingArchitect",
    "@FT_MCC-427884_RaveBlockingCentralLabs",
    "@FT_MCC-427884_RaveBlockingConfig",
    "@FT_MCC-427884_RaveBlockingELearning",
    "@FT_MCC-427884_RaveBlockingLogin",
    "@FT_MCC-427884_RaveBlockingMisc",
    "@FT_MCC-427932",
    "@FT_MCC-434148",
    "@FT_MCC-437986-RemoraOnly",
    "@FT_MCC-439566",
    "@FT_MCC-439647",
    "@FT_MCC-442032",
    "@FT_MCC-442290",
    "@FT_MCC-443372",
    "@FT_MCC-444538",
    "@FT_MCC-445923",
    "@FT_MCC-447960",
    "@FT_MCC-448785",
    "@FT_MCC-450519",
    "@FT_MCC-453367",
    "@FT_MCC-454080",
    "@FT_MCC-454400",
    "@FT_MCC-454418-Remora",
    "@FT_MCC-457305",
    "@FT_MCC-458172",
    "@FT_MCC-462958",
    "@FT_MCC-470415",
    "@FT_MCC-470430",
    "@FT_MCC-472730",
    "@FT_MCC-482867",
    "@FT_MCC-489852",
    "@FT_MCC-490427",
    "@FT_MCC-492387",
    "@FT_MCC-498018",
    "@FT_MCC-499555",
    "@FT_MCC-499558",
    "@FT_MCC-506962",
    "@FT_MCC-506963",
    "@FT_MCC-509789",
    "@FT_MCC-516043_MCC-516058_MCC-516164",
    "@FT_MCC-519110",
    "@FT_MCC-523037_MCC-463788",
    "@FT_MCC-523211",
    "@FT_MCC-525142",
    "@FT_MCC-531311",
    "@FT_MCC-533144",
    "@FT_MCC-543167",
    "@FT_MCC-548678",
    "@FT_MCC-551545",
    "@FT_MCC-554471",
    "@FT_MCC-560861",
    "@FT_MCC-581992",
    "@FT_MCC-588829",
    "@FT_MCC-603599",
    "@FT_MCC-605945",
    "@FT_MCC-610807",
    "@FT_MCC-613791",
    "@FT_MCC-622685",
    "@FT_MCC-622902",
    "@FT_MCC-647573",
    "@FT_MCC-653323",
    "@FT_MCC-655630",
    "@FT_MCC-657551",
    "@FT_MCC-657554_ProjectIsClassicInitialValueFalse",
    "@FT_MCC-657554_ProjectIsClassicInitialValueTrue",
    "@FT_MCC-657555",
    "@FT_MCC-657556_MCC-657549_MCC-658028",
    "@FT_MCC-662994",
    "@FT_MCC-665342",
    "@FT_MCC-669377",
    "@FT_MCC-670111",
    "@FT_MCC-674165",
    "@FT_MCC-683092",
    "@FT_MCC-683560",
    "@FT_MCC-689885",
    "@FT_MCC-692227_MCC-729194",
    "@FT_MCC-692904",
    "@FT_MCC-692905",
    "@FT_MCC-692906",
    "@FT_MCC-692916",
    "@FT_MCC-711965",
    "@FT_MCC-714007",
    "@FT_MCC-715121",
    "@FT_MCC-721194",
    "@FT_MCC-722897",
    "@FT_MCC-723030_MCC-727797",
    "@FT_MCC-723487",
    "@FT_MCC-729229",
    "@FT_MCC-732082",
    "@FT_MCC-742762",
    "@FT_MCC-744844",
    "@FT_MCC-749903",
    "@FT_MCC-750631",
    "@FT_MCC-751994",
    "@FT_MCC-752477",
    "@FT_MCC-752866",
    "@FT_MCC-764204",
    "@FT_MCC-767087",
    "@FT_MCC-768459_MCC-780941_Remora",
    "@FT_MCC-772845",
    "@FT_MCC-777943_MCC-798410",
    "@FT_MCC-781519",
    "@FT_MCC-784967",
    "@FT_MCC-793708",
    "@FT_MCC-800803",
    "@FT_MCC-804085",
    "@FT_MCC-814438",
    "@FT_QueryRefiringLogic_LogForm_MultiFldEC",
    "@FT_Status_Rollups_EDC_Roll_Update_Verification",
    "@FT_Status_Rollups_User_EDC_Roll_Update_Verification",
    "@FT_US10241_DT12797",
    "@FT_US10246_DT13300",
    "@FT_US11101_DT9700",
    "@FT_US11306_DT13637",
    "@FT_US12994_DT10991",
    "@FT_US12996_AM2_DT13997",
    "@FT_US12996_AM2_DT13997StandardField",
    "@FT_US12999_DT13977",
    "@FT_US13020_AM2_DT13504",
    "@FT_US17446",
    "@FT_US17701_DT13437",
    "@FT_US17743_DT12513",
    "@FT_US18087_DT14073",
    "@FT_US18531_AM2_DT13626",
    "@FT_US18689",
    "@FT_US18745_DT11148_AddEvents",
    "@FT_US18784_DT14321",
    "@FT_US18812",
    "@FT_US19017",
    "@FT_US19302_DT14205",
    "@FT_US19695",
    "@FT_US19877",
    "index.html",
    QColumbo
)


Command Line Error:
Cannot find listfile
FT_MCC-261190


7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)
Modified by aONe for Keka


Error code 7
```

**Comment by aonez** [comment]
Thanks for this one @mnohai-mdsol, the cause are the `@` symbol. I'm gonna try to fix this one for the next release.

**Comment by aonez** [comment]
@mnohai-mdsol this build should have this issue fixed:
https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.2.51-dev.r.4815.7z

**Comment by mnohai-mdsol** [comment]
> @mnohai-mdsol this build should have this issue fixed: https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.2.51-dev.r.4815.7z

Works great, thanks for the fix!
