### ISSUE TITLE
Functions are not available in the "Finder Extension" tab: Show in Finder and Delete

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#974]
### Configuration
- Keka version: 1.2.18 (4662)
- macOS version: 12.0.1 (21A559)

### Describe the bug
Functions are not available in the "Finder Extension" tab: Show in Finder and Delete.

### Screenshots
https://user-images.githubusercontent.com/62497891/142235661-7ff913fd-99b0-4acb-8138-4707600267d8.mov

**Comment by aonez** [comment]
Thanks @Oleg-Chashko! Fixed it for the next release.

**Comment by aonez** [comment]
Still fails the delete option. Not sure why.

**Comment by aonez** [comment]
Properly fixed it for next revision. Made sure both list behave the same.
