### ISSUE TITLE
[BUG] Finder Extension Keka icon not updated

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#980]
Version 1.2.50 has the new square Keka icon, but it is not updated in the Finder Extension. Will be updated on next release.

**Comment by Oleg-Chashko** [comment]
And "KekaExternalHelper" updated icon.

**Comment by aonez** [comment]
Oh right!

**Comment by Oleg-Chashko** [comment]
Please pay attention to this:

https://user-images.githubusercontent.com/62497891/143041163-7bdcb9b9-a414-4d0c-a3ab-5f575a4a1a69.mov


https://user-images.githubusercontent.com/62497891/143041186-1cc8ebeb-e336-4b9c-8957-d1d839deec57.mov

**Comment by aonez** [comment]
Oleg remove all other versions of Keka you have so the system uses the new ones. That icon in the notification was not even released with Keka 😅

**Comment by Oleg-Chashko** [comment]
_Remove all other versions of Keka you have so the system uses the new ones._ 0_o 

- I always install only one version of the app.

<img width="961" alt="Screen Shot 2021-11-23 at 16 54 19" src="https://user-images.githubusercontent.com/62497891/143058534-f255c775-bc1a-4802-aa89-0d2330918819.png">

**Comment by aonez** [comment]
The icon from the notification is this one: https://github.com/aonez/Keka/issues/585#issuecomment-733859244

Check if you have that one applied anywhere else. Maybe restarting the Mac can help updating the icons cache.

If you do this:

```
touch ~/Desktop/test.kextraction
```

Does it show the old icon? Note it's also not present at `Keka.app`. Instead it has the new one:

```
/Applications/Keka.app/Contents/Resources/Keka-Extraction-Package.icns
```

**Comment by Oleg-Chashko** [comment]
- Restarting the Mac helped refresh the cache.
The result:
<img width="374" alt="Screen Shot 2021-11-23 at 17 15 37" src="https://user-images.githubusercontent.com/62497891/143063496-4634c77e-b2bb-4150-812e-951375e5726f.png">

- If you do this:
_touch ~/Desktop/test.kextraction_
The result:
<img width="106" alt="Screen Shot 2021-11-23 at 17 27 24" src="https://user-images.githubusercontent.com/62497891/143063969-d5df9892-ca5d-46ca-bcd5-11834bd8c253.png">

- Does it show the old icon? Note it's also not present at Keka.app. Instead it has the new one:
_/Applications/Keka.app/Contents/Resources/Keka-Extraction-Package.icns_
The result:
<img width="724" alt="Screen Shot 2021-11-23 at 17 29 23" src="https://user-images.githubusercontent.com/62497891/143064293-db93b246-222e-4983-8664-d38cf59868c4.png">

---

The old icon remained when unpacking:

<img width="106" alt="Screen Shot 2021-11-23 at 17 32 31" src="https://user-images.githubusercontent.com/62497891/143065143-8b57c2b1-5039-471c-9632-d7112fef4883.png">

**Comment by Oleg-Chashko** [comment]
Removing Keka and installing did not bring a positive result.
<img width="106" alt="143065143-8b57c2b1-5039-471c-9632-d7112fef4883" src="https://user-images.githubusercontent.com/62497891/143068663-afdda2d5-b358-45d5-b343-35023540a521.png">

**Comment by Oleg-Chashko** [comment]
- 1 Uninstalled Keka.
- 2 Removed the rest of the application.

/private/var/folders/g9/t6l5fknj43q1p39qkpckk0z40000gn/C/com.aone.keka
/private/var/folders/g9/t6l5fknj43q1p39qkpckk0z40000gn/C/com.aone.keka.KekaFinderIntegration
/private/var/folders/g9/t6l5fknj43q1p39qkpckk0z40000gn/C/com.aone.keka/com.aone.keka
/private/var/folders/g9/t6l5fknj43q1p39qkpckk0z40000gn/T/com.aone.keka
/private/var/folders/g9/t6l5fknj43q1p39qkpckk0z40000gn/T/com.aone.keka.KekaFinderIntegration
/Users/elenachashko/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.aone.keka.sfl2
/Users/elenachashko/Library/Caches/com.aone.keka
/Users/elenachashko/Library/Containers/com.aone.keka
/Users/elenachashko/Library/Containers/com.aone.keka.KekaFinderIntegration
/Users/elenachashko/Library/Containers/com.aone.keka.KekaFinderIntegration/Data/Library/Application Scripts/com.aone.keka.KekaFinderIntegration
/Users/elenachashko/Library/Containers/com.aone.keka/Data/Library/Application Scripts/com.aone.keka
/Users/elenachashko/Library/Containers/com.aone.keka/Data/Library/Application Support/Keka
/Users/elenachashko/Library/Containers/com.aone.keka/Data/Library/Application Support/Keka/KekaDefaultApp.app
/Users/elenachashko/Library/Containers/com.aone.keka/Data/Library/Application Support/Keka/KekaExternalHelper.app
/Users/elenachashko/Library/Containers/com.aone.keka/Data/Library/Application Support/Keka/KekaExternalHelper.app/Contents/MacOS/KekaExternalHelper
/Users/elenachashko/Library/Containers/com.aone.keka/Data/Library/Application Support/Keka/KekaExternalHelper.app/Contents/Resources/Keka-Extension.icns
/Users/elenachashko/Library/Containers/com.aone.keka/Data/Library/Caches/com.aone.keka
/Users/elenachashko/Library/Containers/com.aone.keka/Data/Library/HTTPStorages/com.aone.keka
/Users/elenachashko/Library/Containers/com.aone.keka/Data/Library/Preferences/com.aone.keka.plist
/Users/elenachashko/Library/Containers/org.sparkle-project.Downloader/Data/Library/Caches/com.aone.keka
/Users/elenachashko/Library/Containers/org.sparkle-project.Downloader/Data/Library/Caches/com.aone.keka/org.sparkle-project.Sparkle/PersistentDownloads/SYXYdPxZB/Keka 4808
/Users/elenachashko/Library/Containers/org.sparkle-project.Downloader/Data/Library/Caches/com.aone.keka/org.sparkle-project.Sparkle/PersistentDownloads/zrJF3Ny3I/Keka 4808
/Users/elenachashko/Library/Group Containers/4FG648TM2A.group.com.aone.keka
/Users/elenachashko/Library/Group Containers/4FG648TM2A.group.com.aone.keka/Library/Application Scripts/4FG648TM2A.group.com.aone.keka
/Users/elenachashko/Library/Group Containers/4FG648TM2A.group.com.aone.keka/Library/Preferences/4FG648TM2A.group.com.aone.keka.plist
/Users/elenachashko/Library/Preferences/com.aone.keka.plist

- 3 Rebooted the Mac.
- 4 Installed Keka.
- 5 Result is the old icon when unpacking.

Do you have any suggestions for further action? :)

**Comment by aonez** [comment]
This that code:

https://github.com/aonez/Keka/issues/770#issuecomment-974016306

**Comment by Oleg-Chashko** [comment]
@aonez 

Clearing the cache through the terminal helped.

sudo rm -rfv /Library/Caches/com.apple.iconservices.store; sudo find /private/var/folders/ \( -name com.apple.dock.iconcache -or -name com.apple.iconservices \) -exec rm -rfv {} \; ; sleep 3; killall Dock; killall Finder

[Log_Terminal.zip](https://github.com/aonez/Keka/files/7589966/Log_Terminal.zip)

**Comment by aonez** [comment]
I don’t understand why sometimes it’s that hard 🙃

**Comment by Oleg-Chashko** [comment]
All's Well That Ends Well! :)

**Comment by DarkStiller** [comment]
I don't see the problem. The new icon is ugly as sin.
Maybe an option to the old one will be nice.

**Comment by aonez** [comment]
@Oleg-Chashko the helper is already updated: https://www.keka.io/defaultapp

**Comment by gingerbeardman** [comment]
@DarkStiller see https://github.com/aonez/Keka/issues/988
