### ISSUE TITLE
Not able to update app

### ISSUE THREAD

**Issue by seveneleven-711** [aonez/Keka#981]
### Configuration
- Keka version: [1.2.50]
- macOS version: [11.6.1]

### Describe the bug
It is not possible to receive app updates via "check for updates"

### To Reproduce
1. Go to file
2. Click on 'check for updates'
3. See error

### Expected behavior
update check

### Screenshots
![Bildschirmfoto 2021-11-23 um 12 05 30](https://user-images.githubusercontent.com/94903240/143013801-c6223c58-7a55-4a69-a81f-9e27740185b8.png)

### Additional context
also happened with older Version 1.2.18.

**Comment by aonez** [comment]
Checking

**Comment by aonez** [comment]
Should be fixed now. Thanks a lot for the tip @seveneleven-711 🔝
