### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dujialun** [aonez/Keka#989]
### Configuration
- Keka version: [e.g. 1.2.50 (4808)]
- macOS version: [e.g. 11.6 (20G165)]

### Describe the bug
I created an ISO including multiple files and directories. When I mount it on CentOS in VirtualBox, I found the file name is wrong, the first character case is incorrect and the dot in the file name is missing.

**Comment by gingerbeardman** [comment]
Screenshot please

**Comment by aonez** [comment]
> Screenshot please

@dujialun that would be helpful, or a sample ISO that reproduces the issue too.
