### ISSUE TITLE
[BUG] Extraction takes a long time (sometimes doesn't complete)

### ISSUE THREAD

**Issue by nrutman** [aonez/Keka#992]
### Configuration
- Keka version: 1.2.50 (4808)
- macOS version: 12.0.1 (21A559)

### Describe the bug
When extracting files, Keka regularly takes 10-20 seconds to complete. On one occasion, it never completed (I just cancelled after about 3 minutes). These aren't large archives. The standard Archive Utility extracts these files in a second or two. Log file is attached.

[Keka_2021-12-08-133014026.log](https://github.com/aonez/Keka/files/7678223/Keka_2021-12-08-133014026.log)

### To Reproduce
1. Download a zip file (the file used in this log was Fantastical, which I downloaded from [their website](https://flexibits.com/fantastical/download))
2. Double-click the archive, which fires up Keka for extraction

### Expected behavior
I expect it to extract the files within a few seconds

### Screenshots
The extraction modal appears, but says it should be 5 seconds and just hangs until I cancel the operation or until it finally finishes.

### Additional context
I've used Keka on other machines with zero problems. On this one (an M1Pro) I've consistently had this issue.

**Comment by aonez** [comment]
I’ll check it later, but reading the log maybe disabling the quarantine application (Keka - Preferences - Extraction) can be a workaround.

**Comment by aonez** [comment]
I can't reproduce the issue, neither with the file downloaded for Safari or Firefox as in your log. Please try disabling "Inherit quarantine from downloaded files", it should work fast for you.

I'm not really sure what is happening here for you, there should be some external reason. Maybe restarting the Mac helps.

![image](https://user-images.githubusercontent.com/480163/145415672-7a0a6679-a97a-4114-93e8-605903571944.png)

**Comment by aonez** [comment]
Also taking a look at the `Console.app` filtered by "Keka" may help.

**Comment by berezovskyi** [comment]
Experiencing the same issue on macOS 11.6.1 (20G224) and Keka Version 1.2.50 (4808). The "Inherit quarantine from downloaded files" workaround works for me.

**Comment by berezovskyi** [comment]
I think it’s still an issue

**Comment by aonez** [comment]
@berezovskyi can you replicate the issue and share the Keka log and check the Console.app for some extra logs?

**Comment by berezovskyi** [comment]
Cannot reproduce any more, sorry. Happy holidays and thank you for your work!

**Comment by berezovskyi** [comment]
[Keka_2021-12-22-190335373.log](https://github.com/aonez/Keka/files/7764434/Keka_2021-12-22-190335373.log)

also attaching the system log around that time:

[relevant_system.log](https://github.com/aonez/Keka/files/7764449/relevant_system.log)

to be clear, Docker is not running:

> docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

The download was made with Safari, so I assume the Chrome log message is not relevant.

**Comment by aonez** [comment]
@berezovskyi thank you so much for the feedback. Sadly I'm not seeing any valuable information in the `system.log`.

I've just prepared two builds with extra logging to try to at least see where the hang starts. If you could try them and report the logs it would be very helpful.

https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.2.51-dev.r4843.7z

Maybe you can quit `com.docker.helper` in your test, in case it's affecting somehow (even if only the logs).

Also are you (and @nrutman) running on Intel or  Silicon? Not sure it will be of any difference.
